    'cloud-engineer': {
      title: 'Cloud Engineer',
      slug: 'cloud-engineer',
      industry: 'Technology',
      roleDescription: `Cloud Engineers at IBM build and manage the hybrid cloud infrastructure that powers digital transformation for the world\'s largest enterprises. Working across IBM Cloud, Red Hat OpenShift, and multi-cloud environments, you\'ll design resilient architectures, automate deployments, and ensure the reliability of systems serving Fortune 500 clients in regulated industries like finance and healthcare. IBM\'s unique position as both a cloud provider and the world\'s largest Red Hat services partner means Cloud Engineers work at the intersection of cutting-edge open-source technology and enterprise requirements. The role spans infrastructure as code, Kubernetes orchestration, networking, security, and observability. IBM\'s consulting heritage means Cloud Engineers often work directly with clients on cloud migrations, modernization projects, and hybrid cloud strategies. The team emphasizes both technical excellence and business understanding—knowing why clients need specific architectures is as important as how to build them.`,
      responsibilities: [
        'Design and implement hybrid cloud architectures on IBM Cloud and Red Hat OpenShift',
        'Automate infrastructure provisioning using Terraform and Ansible',
        'Build and manage Kubernetes clusters for enterprise workloads',
        'Implement CI/CD pipelines and GitOps workflows',
        'Ensure compliance and security for regulated industry deployments',
        'Monitor system performance and implement reliability improvements',
        'Support client cloud migration and modernization projects',
        'Write infrastructure as code following IBM standards',
        'Collaborate with development teams on cloud-native applications'
      ],
      growthOpportunities: [
        'Progress from Cloud Engineer to Senior, Staff, and Principal levels',
        'Earn certifications across IBM, Red Hat, AWS, and Azure',
        'Specialize in Kubernetes, security, networking, or automation',
        'Transition into cloud architecture or technical leadership',
        'Move into IBM Consulting for client-facing cloud strategy',
        'Lead cloud Centers of Excellence for specific industries',
        'Build expertise in hybrid and multi-cloud architectures',
        'Contribute to open-source projects in the cloud ecosystem'
      ],
      interviewProcess: [
        { stage: 'Application Review', description: 'Resume screening for cloud and infrastructure experience' },
        { stage: 'Technical Assessment', description: 'Online assessment covering cloud concepts and Linux fundamentals' },
        { stage: 'Technical Phone Screen', description: '45-minute interview on cloud architecture and troubleshooting' },
        { stage: 'Technical Deep Dive', description: '60-minute interview on Kubernetes, networking, and automation' },
        { stage: 'System Design', description: 'Interview designing a cloud architecture for a client scenario' },
        { stage: 'HR Interview', description: 'Discussion of career goals and cultural fit' }
      ],
      technicalQuestions: [
        'How would you design a highly available Kubernetes cluster?',
        'Explain the differences between containers and virtual machines.',
        'How do you implement infrastructure as code at scale?',
        'Describe your approach to cloud cost optimization.',
        'How would you secure a multi-tenant cloud environment?',
        'Explain Kubernetes networking and service mesh concepts.',
        'How do you handle disaster recovery in hybrid cloud?',
        'Describe your experience with GitOps and continuous deployment.',
        'How would you migrate a legacy application to containers?',
        'Explain your approach to cloud monitoring and observability.',
        'How do you ensure compliance in regulated cloud environments?',
        'Describe your experience with Terraform or other IaC tools.',
        'How would you design a multi-cloud architecture?',
        'Explain the Red Hat OpenShift platform and its benefits.',
        'How do you handle secrets management in cloud environments?',
        'Describe your approach to cloud capacity planning.'
      ],
      behavioralQuestions: [
        'Tell me about a complex cloud migration you led.',
        'Describe a time you resolved a critical production issue.',
        'How have you balanced automation with manual oversight?',
        'Tell me about a time you worked with a challenging client.',
        'Describe your experience with cloud security incidents.',
        'How have you handled competing priorities from multiple teams?',
        'Tell me about a time you improved system reliability significantly.',
        'Describe how you stay current with cloud technologies.',
        'How have you mentored others in cloud practices?',
        'Tell me about a time you had to learn a new technology quickly.',
        'Describe your experience documenting cloud architectures.',
        'How have you handled disagreements about technical approaches?',
        'Tell me about a cost optimization success story.',
        'Describe your experience with 24/7 on-call support.'
      ],
      whatTheyLookFor: [
        'Strong Linux and infrastructure fundamentals',
        'Experience with Kubernetes and container orchestration',
        'Familiarity with IBM Cloud, AWS, Azure, or GCP',
        'Infrastructure as code skills (Terraform, Ansible)',
        'Understanding of networking and security concepts',
        'Experience with CI/CD and automation tools',
        'Client-facing communication skills',
        'Certifications in cloud platforms (valued but not required)',
        'Problem-solving and troubleshooting abilities',
        'Understanding of enterprise compliance requirements'
      ],
      interviewTips: [
        'Research IBM Cloud and Red Hat OpenShift before interviewing',
        'Be ready to discuss Kubernetes architecture in depth',
        'Prepare examples of cloud architectures you\'ve designed',
        'Show understanding of hybrid cloud concepts',
        'Demonstrate infrastructure as code proficiency',
        'Be ready to troubleshoot a scenario live',
        'Show experience with enterprise and compliance requirements',
        'Prepare examples of working with clients or stakeholders',
        'Highlight relevant certifications',
        'Demonstrate understanding of cost optimization',
        'Show familiarity with monitoring and observability tools',
        'Be ready to discuss multi-cloud strategies',
        'Prepare questions about IBM\'s cloud strategy and culture',
        'Show continuous learning mindset for cloud technologies'
      ],
      salary: {
        min: 100000,
        max: 180000,
        average: 140000
      },
      compensation: [
        'Competitive base salary ($100K-$180K based on level)',
        'Annual performance bonus (10-20% of base)',
        'Restricted Stock Units (RSUs)',
        '5% automatic retirement benefit contribution',
        'Comprehensive health benefits',
        'Certification reimbursement and training budget',
        'Employee stock purchase plan',
        'Generous PTO policy',
        'On-call compensation where applicable',
        'Global mobility opportunities'
      ],
      dayInLife: {
        intro: 'A typical day as a Cloud Engineer at IBM balances infrastructure work, automation, and client collaboration.',
        schedule: [
          '9:00 AM - Review infrastructure alerts and overnight changes',
          '9:30 AM - Team standup with cloud engineering colleagues',
          '10:00 AM - Work on Terraform modules for client deployment',
          '11:00 AM - Client call to discuss migration strategy',
          '12:00 PM - Lunch break',
          '1:00 PM - Troubleshoot Kubernetes cluster issue',
          '2:30 PM - Code review for infrastructure changes',
          '3:30 PM - Update documentation and runbooks',
          '4:30 PM - Collaborate with development team on deployment',
          '5:30 PM - Wrap up and handoff to global team if needed'
        ],
        closing: 'Cloud Engineering at IBM means building the infrastructure that powers enterprise digital transformation, with opportunities to work on cutting-edge hybrid cloud technology.'
      },
      similarRoles: ['Senior Cloud Engineer at IBM', 'Cloud Architect at IBM', 'DevOps Engineer at IBM', 'Site Reliability Engineer at IBM', 'Platform Engineer at IBM']
    },

    'security-engineer': {
      title: 'Security Engineer',
      slug: 'security-engineer',
      industry: 'Technology',
      roleDescription: `Security Engineers at IBM protect enterprise systems and data for some of the world\'s most security-conscious organizations—financial institutions, government agencies, and healthcare providers. Working across IBM\'s security portfolio including QRadar SIEM, Guardium data protection, and enterprise security services, you\'ll detect threats, build defensive systems, and ensure compliance with regulations like PCI-DSS, HIPAA, and SOC 2. IBM\'s security practice combines decades of enterprise security expertise with cutting-edge research from IBM X-Force, the company\'s threat intelligence team. Security Engineers work at the intersection of technology and business risk: understanding not just how to implement controls but why they matter to clients. The role spans application security, infrastructure security, identity management, and security operations. IBM\'s global presence means you\'ll work on security challenges across regulated industries worldwide, often collaborating with IBM Consulting teams on security assessments and implementations.`,
      responsibilities: [
        'Design and implement security architectures for enterprise clients',
        'Monitor and respond to security incidents using IBM QRadar and other tools',
        'Conduct vulnerability assessments and penetration testing',
        'Implement identity and access management solutions',
        'Ensure compliance with regulatory frameworks (PCI-DSS, HIPAA, SOC 2)',
        'Build security automation and orchestration workflows',
        'Collaborate with IBM X-Force on threat intelligence',
        'Create security policies and documentation',
        'Train and advise clients on security best practices'
      ],
      growthOpportunities: [
        'Progress from Security Engineer to Senior, Staff, and Principal levels',
        'Earn security certifications (CISSP, OSCP, CEH, etc.)',
        'Specialize in threat intelligence, pen testing, or cloud security',
        'Join IBM X-Force for threat research',
        'Move into security architecture or CISO advisory roles',
        'Lead security Centers of Excellence for industries',
        'Transition into IBM Consulting for strategic security advisory',
        'Contribute to security research and publications'
      ],
      interviewProcess: [
        { stage: 'Application Review', description: 'Resume screening for security experience and certifications' },
        { stage: 'Technical Assessment', description: 'Online assessment covering security concepts and scenarios' },
        { stage: 'Technical Phone Screen', description: '45-minute interview on security fundamentals and experience' },
        { stage: 'Security Deep Dive', description: '60-minute interview on technical security skills' },
        { stage: 'Scenario Interview', description: 'Walk through security incident response or architecture design' },
        { stage: 'HR Interview', description: 'Discussion of career goals and cultural fit' }
      ],
      technicalQuestions: [
        'How would you design a security architecture for a financial institution?',
        'Explain your approach to threat modeling.',
        'How do you detect and respond to a potential data breach?',
        'Describe your experience with SIEM platforms like QRadar.',
        'How would you secure a hybrid cloud environment?',
        'Explain the OWASP Top 10 and how you address each.',
        'How do you implement zero trust architecture?',
        'Describe your approach to identity and access management.',
        'How would you conduct a security assessment for a client?',
        'Explain techniques for detecting lateral movement in a network.',
        'How do you ensure compliance with PCI-DSS requirements?',
        'Describe your experience with security automation.',
        'How would you respond to a ransomware incident?',
        'Explain your approach to secure code review.',
        'How do you prioritize vulnerabilities for remediation?',
        'Describe your experience with penetration testing methodologies.'
      ],
      behavioralQuestions: [
        'Tell me about a security incident you handled.',
        'Describe how you\'ve communicated security risks to non-technical stakeholders.',
        'How have you balanced security with business needs?',
        'Tell me about a time you identified a critical vulnerability.',
        'Describe your experience working with compliance auditors.',
        'How have you stayed current with evolving threats?',
        'Tell me about a time you improved security processes.',
        'Describe a challenging client security engagement.',
        'How have you handled disagreement about security priorities?',
        'Tell me about a time you trained others on security.',
        'Describe your experience with security tool implementation.',
        'How have you handled high-pressure security situations?',
        'Tell me about a security project you\'re proud of.',
        'Describe how you\'ve built security culture in an organization.'
      ],
      whatTheyLookFor: [
        'Strong foundation in security concepts and frameworks',
        'Experience with enterprise security tools and platforms',
        'Understanding of compliance requirements in regulated industries',
        'Incident response and threat detection skills',
        'Security certifications (CISSP, CEH, etc.) valued',
        'Clear communication for technical and business audiences',
        'Experience with cloud security',
        'Programming/scripting skills for automation',
        'Understanding of network and application security',
        'Client-facing and advisory capabilities'
      ],
      interviewTips: [
        'Research IBM\'s security portfolio (QRadar, Guardium, X-Force)',
        'Be ready to walk through incident response scenarios',
        'Prepare examples of security architectures you\'ve designed',
        'Show understanding of enterprise compliance frameworks',
        'Demonstrate threat intelligence and detection skills',
        'Highlight relevant certifications',
        'Prepare to discuss both technical and advisory work',
        'Show experience with regulated industries if applicable',
        'Be ready to discuss security automation approaches',
        'Prepare examples of communicating risk to leadership',
        'Show continuous learning about emerging threats',
        'Demonstrate understanding of cloud security challenges',
        'Prepare questions about IBM\'s security practice',
        'Show balance of technical depth and business understanding'
      ],
      salary: {
        min: 110000,
        max: 190000,
        average: 150000
      },
      compensation: [
        'Competitive base salary ($110K-$190K based on level)',
        'Annual performance bonus (10-20% of base)',
        'Restricted Stock Units (RSUs)',
        '5% automatic retirement benefit contribution',
        'Comprehensive health benefits',
        'Certification reimbursement',
        'Employee stock purchase plan',
        'Generous PTO policy',
        'Conference attendance support',
        'On-call compensation where applicable'
      ],
      dayInLife: {
        intro: 'A typical day as a Security Engineer at IBM balances defensive operations, client advisory, and security improvements.',
        schedule: [
          '8:30 AM - Review overnight security alerts and threat intelligence',
          '9:00 AM - Team standup with security operations colleagues',
          '9:30 AM - Investigate potential security incident',
          '11:00 AM - Client call to discuss security assessment findings',
          '12:00 PM - Lunch break',
          '1:00 PM - Work on security automation script',
          '2:30 PM - Vulnerability assessment review',
          '3:30 PM - Security architecture review for new project',
          '4:30 PM - Update security documentation and policies',
          '5:30 PM - Wrap up and handoff to global SOC if needed'
        ],
        closing: 'Security Engineering at IBM means protecting the world\'s most critical organizations, with opportunities to work on cutting-edge threat detection and enterprise security.'
      },
      similarRoles: ['Senior Security Engineer at IBM', 'Security Architect at IBM', 'Threat Intelligence Analyst at IBM', 'Penetration Tester at IBM', 'Security Consultant at IBM']
    },

    'consultant': {
      title: 'Consultant',
      slug: 'consultant',
      industry: 'Technology',
      roleDescription: `Consultants at IBM Consulting help the world\'s largest organizations transform their businesses through technology strategy, implementation, and change management. Working at the intersection of business and technology, you\'ll advise C-suite executives, design transformation roadmaps, and lead implementation projects that span cloud adoption, AI integration, and digital operations. IBM Consulting is one of the world\'s largest professional services organizations, with expertise spanning strategy, experience design, technology, and operations. Consultants work across industries—financial services, healthcare, manufacturing, and more—bringing deep domain expertise to client challenges. The role combines analytical rigor with client relationship skills: you\'ll structure complex problems, develop recommendations, and guide clients through change. IBM\'s unique position as both a consulting firm and technology company means consultants have access to cutting-edge platforms like watsonx AI and Red Hat OpenShift to deliver solutions.`,
      responsibilities: [
        'Advise clients on digital transformation and technology strategy',
        'Lead workstreams on complex implementation projects',
        'Develop business cases and transformation roadmaps',
        'Conduct interviews and workshops with client stakeholders',
        'Analyze data and synthesize insights into recommendations',
        'Create presentations and deliverables for client leadership',
        'Manage project timelines, risks, and stakeholder relationships',
        'Collaborate with IBM technology teams on solution design',
        'Build and maintain client relationships for ongoing engagements'
      ],
      growthOpportunities: [
        'Progress through Consultant, Senior Consultant, Managing Consultant, and Partner',
        'Specialize in strategy, technology, operations, or experience',
        'Develop deep industry expertise in finance, healthcare, etc.',
        'Move into practice leadership or offering development',
        'Transition into client partner or account leadership roles',
        'Build expertise in AI, cloud, or emerging technologies',
        'Lead large transformation programs',
        'Contribute to thought leadership and publications'
      ],
      interviewProcess: [
        { stage: 'Application Review', description: 'Resume screening for consulting and analytical experience' },
        { stage: 'Recruiter Screen', description: '30-minute conversation about background and interests' },
        { stage: 'Case Interview', description: '45-minute structured problem-solving case' },
        { stage: 'Behavioral Interview', description: '45-minute interview on leadership and client situations' },
        { stage: 'Partner Interview', description: 'Final round with practice leadership' }
      ],
      technicalQuestions: [
        'How would you structure a digital transformation strategy for a retailer?',
        'Describe your approach to building a business case for technology investment.',
        'How do you assess an organization\'s cloud readiness?',
        'Explain how you would design a change management approach.',
        'How do you prioritize initiatives in a transformation portfolio?',
        'Describe your experience with Agile implementation methodologies.',
        'How would you measure the success of a transformation program?',
        'Explain your approach to stakeholder management.',
        'How do you handle scope creep on client projects?',
        'Describe your experience with data analysis and visualization.',
        'How would you advise a client on AI adoption?',
        'Explain your approach to risk management in consulting projects.',
        'How do you ensure knowledge transfer to client teams?',
        'Describe your experience with process improvement methodologies.',
        'How would you structure a recommendation for C-suite presentation?',
        'Explain your approach to creating project timelines and milestones.'
      ],
      behavioralQuestions: [
        'Tell me about a time you led a successful client engagement.',
        'Describe a situation where you had to influence without authority.',
        'How have you handled difficult client stakeholders?',
        'Tell me about a time you had to deliver bad news to a client.',
        'Describe your experience managing project teams.',
        'How have you built trust with client executives?',
        'Tell me about a time you solved an ambiguous problem.',
        'Describe how you\'ve handled competing priorities on a project.',
        'How have you dealt with team conflict?',
        'Tell me about a time you went above and beyond for a client.',
        'Describe your experience with change management.',
        'How have you managed your own professional development?',
        'Tell me about a project that didn\'t go as planned.',
        'Describe how you\'ve mentored or developed others.'
      ],
      whatTheyLookFor: [
        'Strong analytical and problem-solving skills',
        'Excellent communication and presentation abilities',
        'Client relationship and stakeholder management experience',
        'Understanding of business and technology trends',
        'Leadership and team collaboration skills',
        'Industry expertise or specialization',
        'Structured thinking and attention to detail',
        'Adaptability and learning agility',
        'Project management experience',
        'Intellectual curiosity and drive'
      ],
      interviewTips: [
        'Prepare for case interviews—practice structured problem-solving',
        'Research IBM Consulting\'s industries and service offerings',
        'Have clear examples of client impact and leadership',
        'Show understanding of digital transformation trends',
        'Demonstrate structured thinking in case interviews',
        'Prepare to discuss why consulting and why IBM',
        'Show client empathy and relationship skills',
        'Be ready to discuss industry expertise if applicable',
        'Prepare examples of working with senior stakeholders',
        'Show business acumen alongside technical understanding',
        'Demonstrate adaptability and learning from challenges',
        'Prepare thoughtful questions about the practice',
        'Show enthusiasm for the consulting lifestyle',
        'Highlight any IBM technology exposure or interest'
      ],
      salary: {
        min: 90000,
        max: 180000,
        average: 130000
      },
      compensation: [
        'Competitive base salary ($90K-$180K based on level)',
        'Annual performance bonus (15-30% of base)',
        'Restricted Stock Units (RSUs) at senior levels',
        '5% automatic retirement benefit contribution',
        'Comprehensive health benefits',
        'Travel expense coverage',
        'Professional development budget',
        'Generous PTO policy',
        'Parental leave benefits',
        'Career coaching and mentorship programs'
      ],
      dayInLife: {
        intro: 'A typical day as a Consultant at IBM Consulting varies based on project phase and client needs.',
        schedule: [
          '8:00 AM - Travel to client site or remote work setup',
          '8:30 AM - Review project status and prepare for meetings',
          '9:00 AM - Client stakeholder workshop facilitation',
          '11:00 AM - Analyze interview findings and data',
          '12:00 PM - Lunch with client team',
          '1:00 PM - Team working session on deliverable',
          '3:00 PM - Internal project team sync',
          '4:00 PM - Continue analysis and deliverable creation',
          '5:30 PM - Client project status update',
          '6:00 PM - Prepare for tomorrow\'s meetings'
        ],
        closing: 'Consulting at IBM means helping the world\'s largest organizations transform, with variety across projects and industries and clear career progression.'
      },
      similarRoles: ['Senior Consultant at IBM', 'Managing Consultant at IBM', 'Strategy Consultant at IBM', 'Technology Consultant at IBM', 'Associate Partner at IBM']
    },

    'solutions-architect': {
      title: 'Solutions Architect',
      slug: 'solutions-architect',
      industry: 'Technology',
      roleDescription: `Solutions Architects at IBM design the technical foundations for enterprise digital transformation, translating complex business requirements into architectures spanning hybrid cloud, AI, security, and enterprise applications. Working at the intersection of technical depth and client advisory, you\'ll create solution blueprints that integrate IBM technologies—watsonx AI, Red Hat OpenShift, IBM Cloud—with client systems and third-party platforms. IBM Solutions Architects are technical leaders who guide clients through strategic technology decisions: cloud migrations, application modernization, AI adoption, and infrastructure transformation. The role requires both broad technology understanding and the ability to dive deep into specific domains. IBM\'s consulting heritage means Solutions Architects work closely with both clients and IBM Consulting teams, ensuring technical solutions align with business objectives. You\'ll create architecture documents, present to technical and business stakeholders, and guide implementation teams.`,
      responsibilities: [
        'Design end-to-end technical architectures for enterprise clients',
        'Translate business requirements into technical solutions',
        'Lead architecture reviews and technical governance',
        'Create solution blueprints integrating IBM and client technologies',
        'Present technical solutions to client executives and IT leadership',
        'Guide implementation teams on architecture standards',
        'Evaluate and recommend technology platforms and tools',
        'Ensure solutions meet security, compliance, and scalability requirements',
        'Collaborate with IBM product teams on customer requirements'
      ],
      growthOpportunities: [
        'Progress from Solutions Architect to Senior, Principal, and Distinguished levels',
        'Specialize in cloud, AI, security, or industry-specific architecture',
        'Move into technical leadership or Chief Architect roles',
        'Lead architecture practices for industries or regions',
        'Transition into IBM Consulting as technical advisor',
        'Contribute to IBM reference architectures and patterns',
        'Build expertise across IBM and competitor technologies',
        'Present at industry conferences and publish thought leadership'
      ],
      interviewProcess: [
        { stage: 'Application Review', description: 'Resume screening for architecture and enterprise experience' },
        { stage: 'Technical Phone Screen', description: '45-minute interview on architecture experience and approach' },
        { stage: 'Architecture Design Interview', description: '60-minute interview designing a solution for a client scenario' },
        { stage: 'Technical Deep Dive', description: 'Deep dive into specific technology areas' },
        { stage: 'Client Scenario Interview', description: 'Interview on presenting and defending technical recommendations' },
        { stage: 'Leadership Interview', description: 'Final round with architecture leadership' }
      ],
      technicalQuestions: [
        'How would you design a hybrid cloud architecture for a bank?',
        'Explain your approach to application modernization.',
        'How do you evaluate build vs. buy decisions for clients?',
        'Describe your experience with microservices architecture patterns.',
        'How would you integrate AI capabilities into existing enterprise systems?',
        'Explain your approach to ensuring security in solution design.',
        'How do you address scalability requirements in architecture?',
        'Describe your experience with Red Hat OpenShift or Kubernetes.',
        'How would you design a data architecture for analytics and AI?',
        'Explain your approach to API design and integration patterns.',
        'How do you handle non-functional requirements in design?',
        'Describe your experience with event-driven architecture.',
        'How would you approach a legacy system migration?',
        'Explain your approach to disaster recovery architecture.',
        'How do you ensure architectural governance across teams?',
        'Describe your experience with enterprise integration patterns.'
      ],
      behavioralQuestions: [
        'Tell me about a complex architecture you designed.',
        'Describe a time you had to defend a technical recommendation.',
        'How have you communicated technical concepts to business leaders?',
        'Tell me about a time your architecture approach changed mid-project.',
        'Describe your experience working with implementation teams.',
        'How have you handled disagreement on architecture decisions?',
        'Tell me about a time you had to learn a new technology for a project.',
        'Describe how you stay current with technology trends.',
        'How have you balanced ideal architecture with practical constraints?',
        'Tell me about a challenging client technical engagement.',
        'Describe your experience with architecture documentation.',
        'How have you mentored others on architecture practices?',
        'Tell me about a time you identified a significant technical risk.',
        'Describe how you\'ve influenced technology standards in an organization.'
      ],
      whatTheyLookFor: [
        'Broad technology knowledge across cloud, AI, security, and applications',
        'Experience designing enterprise-scale architectures',
        'Strong communication for technical and business audiences',
        'Understanding of IBM and competitor technology platforms',
        'Client-facing advisory and presentation skills',
        'Experience with regulated industry requirements',
        'Architecture patterns and best practices knowledge',
        'Balance of strategic thinking and technical depth',
        'Collaboration skills for working with delivery teams',
        'Continuous learning orientation for new technologies'
      ],
      interviewTips: [
        'Research IBM\'s technology portfolio deeply—watsonx, Red Hat, Cloud',
        'Prepare to whiteboard an architecture for a complex scenario',
        'Show breadth across cloud, integration, security, and data',
        'Demonstrate experience with enterprise clients',
        'Be ready to discuss architecture tradeoffs and decisions',
        'Prepare examples of presenting to executives',
        'Show understanding of compliance and security requirements',
        'Highlight industry expertise if applicable',
        'Be ready to discuss both IBM and competitor technologies',
        'Prepare examples of guiding implementation teams',
        'Show how you stay current with technology trends',
        'Demonstrate structured approach to architecture',
        'Prepare questions about IBM\'s architecture community',
        'Show balance of technical depth and business understanding'
      ],
      salary: {
        min: 140000,
        max: 220000,
        average: 180000
      },
      compensation: [
        'Competitive base salary ($140K-$220K based on level)',
        'Annual performance bonus (15-25% of base)',
        'Restricted Stock Units (RSUs)',
        '5% automatic retirement benefit contribution',
        'Comprehensive health benefits',
        'Certification reimbursement',
        'Conference and training budget',
        'Employee stock purchase plan',
        'Generous PTO policy',
        'Global mobility opportunities'
      ],
      dayInLife: {
        intro: 'A typical day as a Solutions Architect at IBM balances design work, client engagement, and technical leadership.',
        schedule: [
          '8:30 AM - Review architecture documents and prepare for meetings',
          '9:00 AM - Client architecture workshop',
          '11:00 AM - Design session for hybrid cloud solution',
          '12:00 PM - Lunch with client technical team',
          '1:00 PM - Internal architecture review board',
          '2:30 PM - Create solution blueprint documentation',
          '4:00 PM - Call with implementation team on architecture guidance',
          '5:00 PM - Research new technology for upcoming proposal',
          '5:30 PM - Prepare presentation for tomorrow\'s client meeting'
        ],
        closing: 'Solutions Architecture at IBM means designing the technical foundations for enterprise transformation, with variety across industries and technologies.'
      },
      similarRoles: ['Senior Solutions Architect at IBM', 'Principal Architect at IBM', 'Cloud Architect at IBM', 'Enterprise Architect at IBM', 'Technical Architect at IBM']
    }