    'machine-learning-engineer': {
      title: 'Machine Learning Engineer',
      slug: 'machine-learning-engineer',
      industry: 'Technology',
      roleDescription: `Machine Learning Engineers at Stripe build the AI systems that protect billions of dollars in transactions and power intelligent financial products. Working at the intersection of ML research and production engineering, you'll develop models for fraud detection, risk assessment, merchant underwriting, and revenue optimization that must perform with extreme precision—false positives hurt legitimate businesses while false negatives enable fraud. Stripe's ML team operates with unusual autonomy: engineers own models end-to-end from research through production deployment, monitoring, and iteration. The technical challenges are unique to fintech: you'll work with highly imbalanced datasets, adversarial actors constantly probing for weaknesses, and strict latency requirements where models must make decisions in milliseconds. Stripe's written culture means you'll document your approaches thoroughly, contributing to a knowledge base that compounds team effectiveness. The company's focus on developer experience extends to ML infrastructure—Stripe has invested heavily in internal tools that accelerate model development and deployment. You'll collaborate with product teams to build ML features that differentiate Stripe's offerings, working in Python, Scala, and proprietary ML frameworks.`,
      responsibilities: [
        'Build and deploy fraud detection models protecting billions in transactions',
        'Develop ML systems for merchant risk assessment and underwriting',
        'Create real-time prediction systems with strict latency requirements',
        'Design features and pipelines for financial ML models',
        'Own models end-to-end from research through production and monitoring',
        'Combat adversarial actors constantly testing system weaknesses',
        'Collaborate with product teams to build ML-powered features',
        'Write detailed documentation for models and approaches',
        'Contribute to Stripe\'s internal ML platform and tooling'
      ],
      growthOpportunities: [
        'Progress from ML Engineer to Senior, Staff, and Principal ML Engineer',
        'Specialize in fraud, risk, or revenue optimization domains',
        'Lead ML initiatives across multiple product areas',
        'Transition into ML management while maintaining technical depth',
        'Publish research at top ML conferences',
        'Shape Stripe\'s ML platform and infrastructure strategy',
        'Build expertise in adversarial ML and financial AI',
        'Mentor junior engineers on ML best practices'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '30-minute conversation about background, ML experience, and interest in Stripe' },
        { stage: 'Technical Phone Screen', description: '60-minute interview covering ML fundamentals and practical problem-solving' },
        { stage: 'Onsite - ML Design', description: '60-minute interview designing an ML system for a Stripe-relevant problem' },
        { stage: 'Onsite - Coding', description: '60-minute practical coding interview implementing ML algorithms' },
        { stage: 'Onsite - Cross-functional', description: '60-minute interview on collaboration, communication, and working with product teams' },
        { stage: 'Hiring Committee Review', description: 'Panel review of all feedback to make final hiring decision' }
      ],
      technicalQuestions: [
        'How would you design a fraud detection system for card-not-present transactions?',
        'Explain how you would handle extreme class imbalance in fraud detection.',
        'How do you evaluate ML models when false positives and false negatives have different costs?',
        'Describe approaches to detecting adversarial attacks on ML models.',
        'How would you design a real-time feature pipeline for payment fraud?',
        'Explain the tradeoffs between model accuracy and latency in production.',
        'How do you handle concept drift in financial ML models?',
        'Describe how you would build a merchant risk scoring system.',
        'How would you design A/B testing for ML models in production?',
        'Explain techniques for making ML models interpretable for compliance.',
        'How do you ensure model fairness across different merchant segments?',
        'Describe your approach to feature engineering for financial data.',
        'How would you detect and prevent model degradation in production?',
        'Explain how you would handle PII in ML training pipelines.',
        'How do you approach hyperparameter tuning at scale?',
        'Describe techniques for ensemble methods in fraud detection.'
      ],
      behavioralQuestions: [
        'Tell me about a time you deployed an ML model that had unexpected behavior in production.',
        'Describe a situation where you had to balance model accuracy with business constraints.',
        'How have you communicated ML concepts to non-technical stakeholders?',
        'Tell me about a time you identified a data quality issue affecting model performance.',
        'Describe your experience working with adversarial or noisy data.',
        'How have you handled disagreement about model design decisions?',
        'Tell me about a time you had to make tradeoffs between model complexity and maintainability.',
        'Describe a situation where you improved an ML system significantly.',
        'How have you approached knowledge sharing with your team?',
        'Tell me about a time you had to debug a production ML issue quickly.',
        'Describe your experience with compliance or regulatory requirements in ML.',
        'How have you prioritized multiple ML projects with competing deadlines?',
        'Tell me about a time you learned from an ML project failure.',
        'Describe how you\'ve mentored others in ML best practices.'
      ],
      whatTheyLookFor: [
        'Strong foundations in ML algorithms and statistical methods',
        'Experience deploying and maintaining production ML systems',
        'Understanding of adversarial ML and robustness',
        'Ability to work with extreme class imbalance',
        'Experience with real-time prediction systems',
        'Strong software engineering skills beyond ML',
        'Clear written and verbal communication',
        'Understanding of ML ethics and fairness',
        'Experience with A/B testing and experimentation',
        'Ability to translate business problems into ML solutions'
      ],
      interviewTips: [
        'Stripe values practical ML skills over theoretical knowledge—focus on real-world applications',
        'Be prepared to discuss production ML challenges like latency, monitoring, and drift',
        'Understand fraud detection challenges: class imbalance, adversarial actors, false positive costs',
        'Practice designing ML systems with clear metrics and evaluation strategies',
        'Prepare to write clear documentation for your ML approaches',
        'Show understanding of when not to use ML (simpler solutions often work)',
        'Discuss experience with ML infrastructure and tooling',
        'Be ready to explain model decisions for compliance and interpretability',
        'Research Stripe\'s ML blog posts and published papers',
        'Demonstrate end-to-end ownership mindset from research to production',
        'Prepare examples of debugging production ML issues',
        'Show how you balance technical excellence with business impact',
        'Understand financial industry constraints on ML systems',
        'Be ready to discuss ML ethics and fairness considerations'
      ],
      salary: {
        min: 200000,
        max: 350000,
        average: 275000
      },
      compensation: [
        'Highly competitive base salary ($200K-$350K+ based on level)',
        'Significant equity grants with annual refreshers',
        'Annual performance bonuses',
        '$1,000/month remote work stipend',
        'Comprehensive health, dental, and vision insurance',
        '401(k) with company match',
        'Generous parental leave',
        'Unlimited PTO with encouraged minimums',
        'Learning and development budget',
        'Home office setup allowance'
      ],
      dayInLife: {
        intro: 'A typical day as a Machine Learning Engineer at Stripe balances model development, production monitoring, and collaboration.',
        schedule: [
          '9:00 AM - Review overnight model performance metrics and alerts',
          '9:30 AM - Check for fraud pattern changes requiring model updates',
          '10:00 AM - Deep work on new model development or feature engineering',
          '12:00 PM - Lunch break',
          '1:00 PM - ML team sync to discuss ongoing projects and blockers',
          '1:30 PM - Continue model work or run experiments',
          '3:00 PM - Write RFC or documentation for model approach',
          '4:00 PM - Code review for ML PRs',
          '4:30 PM - Collaborate with product team on ML feature requirements',
          '5:30 PM - Wrap up with experiment monitoring'
        ],
        closing: 'Machine Learning at Stripe means building AI systems that protect millions of businesses, with the satisfaction of seeing your models prevent fraud in real-time.'
      },
      similarRoles: ['Senior ML Engineer at Stripe', 'Staff ML Engineer at Stripe', 'Research Scientist at Stripe', 'Risk ML Engineer at Stripe', 'Applied Scientist at Stripe']
    },

    'infrastructure-engineer': {
      title: 'Infrastructure Engineer',
      slug: 'infrastructure-engineer',
      industry: 'Technology',
      roleDescription: `Infrastructure Engineers at Stripe build and maintain the foundational systems that power global payment processing for millions of businesses. Working on one of the most critical infrastructure stacks in fintech, you'll design systems that must achieve extreme reliability—every second of downtime directly impacts businesses and their customers. Stripe's infrastructure handles hundreds of billions of dollars annually, requiring sophisticated approaches to distributed systems, data consistency, disaster recovery, and performance optimization. The technical challenges span database architecture, networking, container orchestration, observability, and security infrastructure. Stripe's engineering culture values written communication: major technical decisions go through detailed RFCs, and engineers document their systems thoroughly. You'll work primarily in Ruby, Go, and Java, building internal platforms that accelerate product development while maintaining the reliability standards financial infrastructure demands. The team practices end-to-end ownership—you'll design, build, deploy, and operate your systems, participating in on-call rotations. Stripe's infrastructure work directly enables the company's mission to increase the GDP of the internet.`,
      responsibilities: [
        'Design and build highly available distributed systems for payment processing',
        'Develop internal platforms and tools used by all Stripe engineers',
        'Create database infrastructure handling petabytes of financial data',
        'Build networking and service mesh infrastructure for global operations',
        'Implement observability systems for monitoring, alerting, and debugging',
        'Design disaster recovery and business continuity systems',
        'Optimize system performance and efficiency at scale',
        'Write RFCs and documentation for infrastructure decisions',
        'Participate in on-call rotations for critical systems'
      ],
      growthOpportunities: [
        'Progress from Infrastructure Engineer to Senior, Staff, and Principal levels',
        'Specialize in databases, networking, compute, or observability',
        'Lead infrastructure initiatives with company-wide impact',
        'Transition into infrastructure management',
        'Contribute to open-source infrastructure projects',
        'Shape Stripe\'s multi-cloud and global expansion strategy',
        'Build expertise in financial systems reliability',
        'Present at industry conferences on infrastructure challenges'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '30-minute conversation about background and infrastructure experience' },
        { stage: 'Technical Phone Screen', description: '60-minute systems design and coding interview' },
        { stage: 'Onsite - Systems Design', description: '60-minute interview designing distributed infrastructure systems' },
        { stage: 'Onsite - Coding', description: '60-minute practical coding interview focusing on infrastructure problems' },
        { stage: 'Onsite - Debugging', description: '60-minute interview debugging production-like scenarios' },
        { stage: 'Hiring Committee Review', description: 'Panel review of all feedback to make final decision' }
      ],
      technicalQuestions: [
        'How would you design a globally distributed database for payment data?',
        'Explain approaches to achieving high availability in payment systems.',
        'How do you handle data consistency in distributed transactions?',
        'Describe your approach to capacity planning for high-growth systems.',
        'How would you design a service mesh for microservices communication?',
        'Explain strategies for zero-downtime deployments.',
        'How do you approach disaster recovery for financial systems?',
        'Describe how you would build an observability platform.',
        'How would you design rate limiting for API infrastructure?',
        'Explain approaches to database sharding and replication.',
        'How do you handle secret management in infrastructure?',
        'Describe your approach to infrastructure as code.',
        'How would you design a CI/CD pipeline for infrastructure changes?',
        'Explain techniques for debugging distributed systems.',
        'How do you approach cost optimization in cloud infrastructure?',
        'Describe your experience with container orchestration at scale.'
      ],
      behavioralQuestions: [
        'Tell me about a time you designed a system that needed extreme reliability.',
        'Describe a production incident you handled and what you learned.',
        'How have you approached making infrastructure changes safely?',
        'Tell me about a time you improved system performance significantly.',
        'Describe your experience with on-call and incident response.',
        'How have you communicated technical decisions to stakeholders?',
        'Tell me about a time you had to balance reliability with development velocity.',
        'Describe a situation where you debugged a complex distributed systems issue.',
        'How have you approached documentation and knowledge sharing?',
        'Tell me about a time you influenced infrastructure direction across teams.',
        'Describe your experience with capacity planning challenges.',
        'How have you handled competing priorities in infrastructure work?',
        'Tell me about a time you learned from an infrastructure failure.',
        'Describe how you\'ve mentored others in systems thinking.'
      ],
      whatTheyLookFor: [
        'Deep expertise in distributed systems design',
        'Experience building highly available, fault-tolerant systems',
        'Strong programming skills in systems languages',
        'Understanding of database internals and consistency models',
        'Experience with cloud infrastructure at scale',
        'Strong debugging and troubleshooting skills',
        'Clear written and verbal communication',
        'Understanding of security best practices',
        'Experience with observability and monitoring',
        'Ability to make pragmatic tradeoffs under constraints'
      ],
      interviewTips: [
        'Stripe values practical systems experience—be ready with concrete examples',
        'Practice designing systems with explicit reliability requirements',
        'Understand CAP theorem and consistency tradeoffs deeply',
        'Be prepared to discuss specific numbers: latencies, throughput, error rates',
        'Show experience with production operations and incident response',
        'Prepare to write clear technical documentation',
        'Discuss experience with both build and operate responsibilities',
        'Research Stripe\'s infrastructure blog posts',
        'Be ready to explain complex systems simply',
        'Demonstrate ownership mindset for infrastructure',
        'Prepare examples of debugging distributed systems issues',
        'Show understanding of security requirements for financial data',
        'Understand financial industry reliability requirements',
        'Be ready to discuss cost vs. reliability tradeoffs'
      ],
      salary: {
        min: 190000,
        max: 340000,
        average: 265000
      },
      compensation: [
        'Highly competitive base salary ($190K-$340K+ based on level)',
        'Significant equity grants with annual refreshers',
        'Annual performance bonuses',
        '$1,000/month remote work stipend',
        'Comprehensive health, dental, and vision insurance',
        '401(k) with company match',
        'Generous parental leave',
        'Unlimited PTO with encouraged minimums',
        'Learning and development budget',
        'Home office setup allowance'
      ],
      dayInLife: {
        intro: 'A typical day as an Infrastructure Engineer at Stripe involves system design, operational work, and cross-team collaboration.',
        schedule: [
          '9:00 AM - Review infrastructure metrics and overnight alerts',
          '9:30 AM - Check deployment pipeline status and rollout progress',
          '10:00 AM - Deep work on infrastructure project or system design',
          '12:00 PM - Lunch break',
          '1:00 PM - Infrastructure team sync',
          '1:30 PM - Continue project work or write RFC documentation',
          '3:00 PM - Review infrastructure PRs from teammates',
          '4:00 PM - Collaborate with product teams on infrastructure needs',
          '4:30 PM - Address any production issues or improvements',
          '5:30 PM - Wrap up and update project documentation'
        ],
        closing: 'Infrastructure Engineering at Stripe means building the foundation that enables global commerce, with direct impact on the reliability of payments for millions of businesses.'
      },
      similarRoles: ['Senior Infrastructure Engineer at Stripe', 'Staff Infrastructure Engineer at Stripe', 'Site Reliability Engineer at Stripe', 'Platform Engineer at Stripe', 'Database Engineer at Stripe']
    },

    'security-engineer': {
      title: 'Security Engineer',
      slug: 'security-engineer',
      industry: 'Technology',
      roleDescription: `Security Engineers at Stripe protect the financial infrastructure that processes hundreds of billions of dollars annually, defending against sophisticated attackers targeting one of the most valuable systems on the internet. Working at the intersection of security and fintech, you'll tackle unique challenges: protecting payment card data under PCI-DSS, preventing account takeovers, securing APIs used by millions of developers, and building fraud-resistant systems. Stripe's security team operates proactively—you'll design secure systems from the start rather than bolting on security later. The work spans application security, infrastructure security, detection and response, and security tooling. Stripe's culture of written communication means security decisions are documented thoroughly through threat models, security design reviews, and incident postmortems. You'll collaborate with engineering teams across the company, building security into every layer of Stripe's stack. The team values both defensive depth and practical security that enables product velocity. Security Engineers at Stripe own their projects end-to-end, from identifying risks through implementing solutions and measuring their effectiveness.`,
      responsibilities: [
        'Conduct security design reviews for new products and features',
        'Build security tooling and infrastructure for the engineering org',
        'Develop detection and response capabilities for security threats',
        'Perform penetration testing and vulnerability assessments',
        'Design and implement authentication and authorization systems',
        'Ensure compliance with PCI-DSS and other financial regulations',
        'Create security training and awareness programs',
        'Investigate and respond to security incidents',
        'Write detailed threat models and security documentation'
      ],
      growthOpportunities: [
        'Progress from Security Engineer to Senior, Staff, and Principal levels',
        'Specialize in application security, infrastructure security, or detection/response',
        'Lead security initiatives across the company',
        'Transition into security management',
        'Contribute to security research and disclosures',
        'Shape Stripe\'s security strategy and roadmap',
        'Build expertise in financial security regulations',
        'Present at security conferences'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '30-minute conversation about background and security experience' },
        { stage: 'Technical Phone Screen', description: '60-minute security-focused technical interview' },
        { stage: 'Onsite - Security Design', description: '60-minute interview designing secure systems' },
        { stage: 'Onsite - Technical Deep Dive', description: '60-minute interview on security engineering skills' },
        { stage: 'Onsite - Collaboration', description: '60-minute interview on working with engineering teams' },
        { stage: 'Hiring Committee Review', description: 'Panel review of all feedback to make final decision' }
      ],
      technicalQuestions: [
        'How would you design authentication for a payments API?',
        'Explain your approach to threat modeling a new feature.',
        'How do you secure sensitive data at rest and in transit?',
        'Describe your approach to API security at scale.',
        'How would you design a secrets management system?',
        'Explain techniques for preventing and detecting account takeover.',
        'How do you approach security for third-party integrations?',
        'Describe your experience with PCI-DSS compliance.',
        'How would you build a security detection and alerting pipeline?',
        'Explain approaches to securing microservices communication.',
        'How do you handle vulnerability management at scale?',
        'Describe your approach to secure code review.',
        'How would you design a fraud detection system from a security perspective?',
        'Explain techniques for securing customer data access.',
        'How do you approach security incident response?',
        'Describe your experience with cloud security architecture.'
      ],
      behavioralQuestions: [
        'Tell me about a time you identified a critical security vulnerability.',
        'Describe how you\'ve influenced security practices across an organization.',
        'How have you balanced security requirements with product velocity?',
        'Tell me about a security incident you handled.',
        'Describe your experience working with engineering teams on security.',
        'How have you communicated security risks to non-technical stakeholders?',
        'Tell me about a time you designed security into a system from the start.',
        'Describe a situation where you had to make security tradeoffs.',
        'How have you approached security awareness and training?',
        'Tell me about a time you improved detection capabilities.',
        'Describe your experience with compliance and audits.',
        'How have you prioritized security work across competing demands?',
        'Tell me about a time you learned from a security failure.',
        'Describe how you\'ve mentored others in security practices.'
      ],
      whatTheyLookFor: [
        'Deep expertise in application and infrastructure security',
        'Experience with security engineering, not just assessment',
        'Understanding of financial industry security requirements',
        'Strong programming and automation skills',
        'Experience with security tooling and infrastructure',
        'Ability to communicate security concepts clearly',
        'Understanding of attack patterns and threat actors',
        'Experience with detection and incident response',
        'Ability to balance security with usability',
        'Strong written communication for threat models and documentation'
      ],
      interviewTips: [
        'Stripe values security engineers who can build, not just break',
        'Be prepared to discuss security design decisions and tradeoffs',
        'Understand financial security requirements: PCI-DSS, data protection',
        'Show experience with practical security at scale',
        'Prepare to discuss both offensive and defensive security skills',
        'Practice threat modeling exercises',
        'Research Stripe\'s security blog posts and bug bounty program',
        'Be ready to explain security concepts to non-security engineers',
        'Demonstrate understanding of the developer experience in security',
        'Prepare examples of influencing security culture',
        'Show experience with security automation and tooling',
        'Understand the balance between security and velocity',
        'Be ready to discuss incident response experiences',
        'Prepare to write clear security documentation'
      ],
      salary: {
        min: 200000,
        max: 360000,
        average: 280000
      },
      compensation: [
        'Highly competitive base salary ($200K-$360K+ based on level)',
        'Significant equity grants with annual refreshers',
        'Annual performance bonuses',
        '$1,000/month remote work stipend',
        'Comprehensive health, dental, and vision insurance',
        '401(k) with company match',
        'Generous parental leave',
        'Unlimited PTO with encouraged minimums',
        'Learning and development budget',
        'Conference attendance and training support'
      ],
      dayInLife: {
        intro: 'A typical day as a Security Engineer at Stripe balances proactive security work with reactive response and collaboration.',
        schedule: [
          '9:00 AM - Review security alerts and overnight findings',
          '9:30 AM - Triage new vulnerability reports from bug bounty',
          '10:00 AM - Security design review for upcoming product feature',
          '11:00 AM - Work on security tooling or detection engineering',
          '12:00 PM - Lunch break',
          '1:00 PM - Security team sync',
          '1:30 PM - Continue security engineering project',
          '3:00 PM - Code review with security focus for a product team',
          '4:00 PM - Write threat model documentation',
          '5:00 PM - Review security metrics and coverage',
          '5:30 PM - Wrap up and handle any urgent issues'
        ],
        closing: 'Security Engineering at Stripe means protecting the financial infrastructure that millions of businesses depend on, with direct impact on trust in the global payments ecosystem.'
      },
      similarRoles: ['Senior Security Engineer at Stripe', 'Staff Security Engineer at Stripe', 'Security Researcher at Stripe', 'Detection Engineer at Stripe', 'AppSec Engineer at Stripe']
    },

    'solutions-architect': {
      title: 'Solutions Architect',
      slug: 'solutions-architect',
      industry: 'Technology',
      roleDescription: `Solutions Architects at Stripe bridge the gap between complex technical products and enterprise customer needs, designing payment integrations that power some of the world's largest businesses. Working at the intersection of technical depth and customer relationships, you'll architect solutions for sophisticated use cases: multi-currency payment flows, complex subscription models, marketplace payments, and custom fraud rules. Stripe's Solutions Architects are technical experts first—you'll write code, review integrations, and dive deep into API design. The role requires understanding not just Stripe's products but the broader payments ecosystem: card networks, banking rails, regulatory requirements, and competitive landscape. You'll work directly with enterprise customers like Amazon, Google, and Fortune 500 companies, translating their business requirements into technical architectures. Stripe's written culture extends to solutions work: you'll create detailed technical proposals, integration guides, and architecture documents. The team values both technical excellence and customer empathy—understanding what customers need even when they can't articulate it.`,
      responsibilities: [
        'Design payment architectures for enterprise customers with complex requirements',
        'Write code and build proof-of-concept integrations demonstrating Stripe capabilities',
        'Create detailed technical proposals and integration documentation',
        'Review customer code and provide integration guidance',
        'Collaborate with product teams to advocate for customer needs',
        'Develop reusable integration patterns and best practices',
        'Present technical solutions to customer engineering teams',
        'Support sales teams with technical expertise during complex deals',
        'Train customers on Stripe products and integration approaches'
      ],
      growthOpportunities: [
        'Progress to Senior, Staff, and Principal Solutions Architect levels',
        'Specialize in verticals like marketplaces, SaaS, or financial services',
        'Transition into product management or engineering',
        'Lead Solutions Architecture for regions or customer segments',
        'Contribute to Stripe\'s public documentation and developer resources',
        'Shape product roadmap through customer insights',
        'Build expertise in payments industry and regulations',
        'Mentor junior Solutions Architects'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '30-minute conversation about background and interest in Solutions Architecture' },
        { stage: 'Technical Phone Screen', description: '60-minute technical interview on API design and integration patterns' },
        { stage: 'Onsite - Technical Design', description: '60-minute interview designing a payment integration architecture' },
        { stage: 'Onsite - Coding', description: '60-minute practical coding interview building an integration' },
        { stage: 'Onsite - Customer Scenario', description: '60-minute role-play handling a customer technical challenge' },
        { stage: 'Hiring Committee Review', description: 'Panel review of all feedback to make final decision' }
      ],
      technicalQuestions: [
        'How would you design a payment integration for a global marketplace?',
        'Explain approaches to handling multi-currency payments.',
        'How do you architect subscription billing with complex pricing?',
        'Describe your approach to payment security and PCI compliance for customers.',
        'How would you design a retry strategy for failed payments?',
        'Explain webhook reliability patterns for payment integrations.',
        'How do you approach idempotency in payment systems?',
        'Describe techniques for optimizing payment authorization rates.',
        'How would you design dispute handling workflows?',
        'Explain approaches to payment reconciliation at scale.',
        'How do you handle customer data for compliance requirements?',
        'Describe your experience with payment gateway integrations.',
        'How would you architect a solution for instant payouts?',
        'Explain techniques for A/B testing payment flows.',
        'How do you approach debugging payment integration issues?',
        'Describe considerations for mobile payment integration.'
      ],
      behavioralQuestions: [
        'Tell me about a time you designed a solution for a complex customer requirement.',
        'Describe how you\'ve explained technical concepts to non-technical stakeholders.',
        'How have you handled a situation where the customer\'s ask exceeded product capabilities?',
        'Tell me about a time you advocated for product changes based on customer feedback.',
        'Describe your experience building relationships with technical decision makers.',
        'How have you balanced customer requests with product vision?',
        'Tell me about a time you debugged a complex integration issue.',
        'Describe a situation where you had to say no to a customer.',
        'How have you approached knowledge sharing and documentation?',
        'Tell me about a time you turned a frustrated customer into a champion.',
        'Describe your experience with enterprise sales cycles.',
        'How have you prioritized across multiple customer engagements?',
        'Tell me about a time you learned a new technical domain quickly.',
        'Describe how you\'ve influenced product roadmap decisions.'
      ],
      whatTheyLookFor: [
        'Strong technical skills including ability to write code',
        'Deep understanding of API design and integration patterns',
        'Experience with payments or fintech industry',
        'Excellent communication skills for technical and business audiences',
        'Ability to understand customer needs and translate to solutions',
        'Experience with enterprise customer relationships',
        'Strong written communication for proposals and documentation',
        'Problem-solving skills for complex integration challenges',
        'Customer empathy and service orientation',
        'Ability to influence product direction through customer insights'
      ],
      interviewTips: [
        'Stripe Solutions Architects are technical first—be ready to code',
        'Understand Stripe\'s product suite deeply before interviewing',
        'Prepare to discuss payment industry concepts: rails, networks, compliance',
        'Practice designing payment integrations with clear tradeoffs',
        'Be ready to role-play customer scenarios',
        'Show ability to communicate technical concepts at multiple levels',
        'Prepare examples of advocating for customers internally',
        'Research Stripe\'s enterprise customers and their use cases',
        'Demonstrate curiosity about customer problems',
        'Show experience with both building and explaining solutions',
        'Prepare to discuss how you handle scope and expectations',
        'Understand webhook reliability and idempotency deeply',
        'Be ready to whiteboard integration architectures',
        'Show how you balance technical purity with pragmatism'
      ],
      salary: {
        min: 180000,
        max: 320000,
        average: 250000
      },
      compensation: [
        'Highly competitive base salary ($180K-$320K+ based on level)',
        'Significant equity grants with annual refreshers',
        'Annual performance bonuses tied to customer success',
        '$1,000/month remote work stipend',
        'Comprehensive health, dental, and vision insurance',
        '401(k) with company match',
        'Generous parental leave',
        'Unlimited PTO with encouraged minimums',
        'Travel budget for customer meetings',
        'Learning and development budget'
      ],
      dayInLife: {
        intro: 'A typical day as a Solutions Architect at Stripe balances customer engagement, technical work, and cross-functional collaboration.',
        schedule: [
          '9:00 AM - Review customer requests and prioritize for the day',
          '9:30 AM - Customer call: architecture review for marketplace integration',
          '10:30 AM - Write technical proposal for enterprise customer',
          '12:00 PM - Lunch with product team discussing customer feedback',
          '1:00 PM - Build proof-of-concept for complex use case',
          '2:30 PM - Customer call: troubleshooting integration issue',
          '3:30 PM - Collaborate with sales on technical qualification',
          '4:30 PM - Code review for customer integration patterns',
          '5:00 PM - Update internal documentation with learnings',
          '5:30 PM - Wrap up and prep for tomorrow\'s customer meetings'
        ],
        closing: 'Solutions Architecture at Stripe means helping the world\'s most innovative companies build on payments infrastructure, combining deep technical skills with customer impact.'
      },
      similarRoles: ['Senior Solutions Architect at Stripe', 'Staff Solutions Architect at Stripe', 'Implementation Engineer at Stripe', 'Technical Account Manager at Stripe', 'Partner Engineer at Stripe']
    }