    'software-engineer': {
      title: 'Software Engineer',
      slug: 'software-engineer',
      industry: 'Technology',
      roleDescription: `Software Engineers at Cisco build the software that powers the world\'s networking infrastructure—from enterprise routers and switches to cloud security platforms and collaboration tools like Webex. Working at a company that connects over 85% of internet traffic, you\'ll develop software for networking devices, security products, cloud management platforms like Meraki, and communication solutions used by millions. Cisco\'s engineering culture spans embedded systems programming in C/C++ to modern cloud-native development in Python, Go, and Java. The interview process focuses on data structures, algorithms, and computer networking fundamentals—understanding how networks operate is essential for many roles. Engineers work in a "Conscious Culture" that emphasizes inclusion, collaboration, and work-life balance. With Cisco\'s expansion into security (following the Splunk acquisition), cloud networking, and AI-powered solutions, software engineers have opportunities to work on diverse technical challenges across the networking industry.`,
      responsibilities: [
        'Develop software for networking devices, security products, or cloud platforms',
        'Build features for Webex, Meraki, or enterprise networking products',
        'Write efficient code in C/C++, Python, Go, or Java',
        'Implement networking protocols and distributed systems',
        'Collaborate with hardware teams on embedded software',
        'Participate in code reviews and maintain high quality standards',
        'Debug complex networking and distributed systems issues',
        'Contribute to CI/CD pipelines and automation',
        'Work with cross-functional teams across global locations'
      ],
      growthOpportunities: [
        'Progress through Software Engineer levels to Distinguished Engineer',
        'Specialize in networking, security, collaboration, or cloud',
        'Transition into technical leadership or architecture roles',
        'Move into product management or technical marketing',
        'Lead development for new products or platforms',
        'Build expertise in emerging areas like AI networking',
        'Contribute to open-source projects and industry standards',
        'Access Cisco\'s extensive learning and certification programs'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '45-minute phone conversation about background and interests' },
        { stage: 'Online Assessment', description: 'Coding assessment with DSA problems and networking MCQs' },
        { stage: 'Technical Phone Screen', description: '60-minute interview covering coding and CS fundamentals' },
        { stage: 'Onsite Technical Rounds', description: '4-5 one-hour interviews on coding, system design, and networking' },
        { stage: 'Behavioral Interview', description: 'Discussion of teamwork, values alignment, and past experiences' }
      ],
      technicalQuestions: [
        'Implement a function to find the shortest path in a graph.',
        'Explain how TCP ensures reliable data delivery.',
        'Design a distributed caching system for network devices.',
        'How does ARP work and what problems can arise?',
        'Implement a trie data structure for IP routing.',
        'Explain the differences between TCP and UDP.',
        'Design a load balancer for high-traffic applications.',
        'How do you debug a network connectivity issue?',
        'Implement a thread-safe producer-consumer queue.',
        'Explain how OSPF routing protocol works.',
        'Design a system for real-time video conferencing.',
        'How do firewalls and packet filtering work?',
        'Implement a rate limiter for API endpoints.',
        'Explain the OSI model and how protocols map to layers.',
        'Design a network monitoring and alerting system.',
        'How do you optimize network packet processing?'
      ],
      behavioralQuestions: [
        'Tell me about a challenging technical problem you solved.',
        'Describe a time you worked effectively with a remote team.',
        'How have you handled disagreements with colleagues?',
        'Tell me about a project where you had to learn new technology quickly.',
        'Describe your experience with code reviews.',
        'How do you prioritize when facing multiple deadlines?',
        'Tell me about a time you improved a process or system.',
        'Describe how you stay current with technology trends.',
        'How have you mentored or helped junior engineers?',
        'Tell me about a project that didn\'t go as planned.',
        'Describe your experience working in diverse teams.',
        'How do you handle ambiguous requirements?',
        'Tell me about a time you went above and beyond.',
        'Describe your approach to debugging complex issues.'
      ],
      whatTheyLookFor: [
        'Strong foundation in data structures and algorithms',
        'Understanding of computer networking concepts',
        'Proficiency in C/C++, Python, Java, or Go',
        'Experience with distributed systems or embedded software',
        'Problem-solving skills for complex technical challenges',
        'Collaboration skills for global team environments',
        'Understanding of software development lifecycle',
        'Knowledge of networking protocols valued',
        'Clear communication across technical levels',
        'Alignment with Cisco\'s Conscious Culture values'
      ],
      interviewTips: [
        'Review computer networking fundamentals—Cisco emphasizes this',
        'Practice DSA problems, especially graph algorithms',
        'Understand TCP/IP, routing, and network protocols',
        'Be prepared for questions on your resume and projects',
        'Research Cisco\'s product portfolio: Webex, Meraki, security',
        'Show understanding of distributed systems concepts',
        'Prepare examples of collaboration and teamwork',
        'Review system design for networking scenarios',
        'Show enthusiasm for Cisco\'s mission and products',
        'Be ready to discuss experience with embedded or network software',
        'Prepare for MCQs on networking and OS concepts',
        'Use STAR method for behavioral questions',
        'Research Cisco\'s Conscious Culture and values',
        'Highlight any networking certifications (CCNA, etc.)'
      ],
      salary: {
        min: 100000,
        max: 200000,
        average: 150000
      },
      compensation: [
        'Competitive base salary ($100K-$200K based on level)',
        'Annual performance bonus (target varies by level)',
        'Restricted Stock Units (RSUs)',
        '401(k) with company match',
        'Employee Stock Purchase Plan',
        'Comprehensive health, dental, and vision insurance',
        'Generous PTO and flexible work arrangements',
        'Tuition reimbursement',
        'Wellness programs and gym subsidies',
        'Remote work options for many roles'
      ],
      dayInLife: {
        intro: 'A typical day as a Software Engineer at Cisco combines development work, collaboration, and continuous learning.',
        schedule: [
          '9:00 AM - Review overnight build results and team updates',
          '9:30 AM - Team standup with colleagues across time zones',
          '10:00 AM - Deep work on feature development',
          '12:00 PM - Lunch break',
          '1:00 PM - Code review session with team',
          '2:00 PM - Cross-functional meeting with QA or product',
          '3:00 PM - Continue development or debugging',
          '4:30 PM - Technical discussion or design review',
          '5:30 PM - Document progress and plan tomorrow'
        ],
        closing: 'Software Engineering at Cisco means building the technology that connects the world, with work-life balance and opportunities across networking, security, and collaboration.'
      },
      similarRoles: ['Senior Software Engineer at Cisco', 'Principal Engineer at Cisco', 'Network Software Engineer at Cisco', 'Cloud Software Engineer at Cisco', 'Embedded Software Engineer at Cisco']
    },

    'product-manager': {
      title: 'Product Manager',
      slug: 'product-manager',
      industry: 'Technology',
      roleDescription: `Product Managers at Cisco shape the strategy and execution of products that power the world\'s networking infrastructure—from enterprise routers and switches to Webex collaboration, Meraki cloud networking, and security solutions. Working at the intersection of technology and business, you\'ll define product vision, prioritize features, and drive go-to-market strategies for products used by organizations worldwide. Cisco\'s PM role spans hardware and software products: you\'ll work with engineering teams on networking devices, cloud platforms, and software applications. The company\'s B2B focus means PMs work closely with enterprise customers, channel partners, and field teams to understand complex networking requirements. With Cisco\'s expansion into security, collaboration, and AI-powered networking, product managers have opportunities to shape products across diverse technology domains.`,
      responsibilities: [
        'Define product strategy and roadmaps for networking or software products',
        'Gather and prioritize requirements from customers and market analysis',
        'Work with engineering teams to translate requirements into specifications',
        'Drive product launches and go-to-market strategies',
        'Collaborate with sales and marketing on positioning and enablement',
        'Analyze competitive landscape and market trends',
        'Present product strategies to executives and customers',
        'Manage product lifecycle from concept through end-of-life',
        'Build business cases for new product investments'
      ],
      growthOpportunities: [
        'Progress from Product Manager to Senior PM, Director, and VP',
        'Lead product lines for networking, security, or collaboration',
        'Move into general management or business unit leadership',
        'Transition into technical marketing or solutions architecture',
        'Build expertise in specific markets: enterprise, SMB, service provider',
        'Lead product management for acquisitions',
        'Move into corporate strategy or business development',
        'Build external presence as industry thought leader'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '30-minute conversation about background and interests' },
        { stage: 'Hiring Manager Interview', description: '45-minute discussion of PM experience and approach' },
        { stage: 'Product Case Study', description: '60-minute interview presenting solution to product challenge' },
        { stage: 'Cross-functional Interviews', description: 'Conversations with engineering, marketing, and sales' },
        { stage: 'Executive Interview', description: 'Final round with senior product leadership' }
      ],
      technicalQuestions: [
        'How would you prioritize features for an enterprise networking product?',
        'Explain your approach to building a product roadmap.',
        'How do you measure success for B2B networking products?',
        'Describe your experience with hardware product development.',
        'How would you differentiate Cisco products against competitors?',
        'Explain your approach to gathering enterprise customer feedback.',
        'How do you balance innovation with customer support for existing products?',
        'Describe your experience with pricing for enterprise products.',
        'How would you approach the cloud networking market opportunity?',
        'Explain your process for making build vs. buy decisions.',
        'How do you work with channel partners in product planning?',
        'Describe your experience with product launches.',
        'How would you approach subscription vs. perpetual licensing?',
        'Explain your approach to competitive analysis.',
        'How do you work with engineering on technical trade-offs?',
        'Describe your experience with enterprise sales cycles.'
      ],
      behavioralQuestions: [
        'Tell me about a product you launched and its market impact.',
        'Describe a time you had to make a difficult prioritization decision.',
        'How have you handled disagreement with engineering teams?',
        'Tell me about a time you pivoted product strategy based on data.',
        'Describe your experience working with enterprise customers.',
        'How have you navigated organizational complexity?',
        'Tell me about a product decision you\'d make differently.',
        'Describe how you stay current with technology trends.',
        'How have you built relationships across functions?',
        'Tell me about a time you influenced without direct authority.',
        'Describe your experience with data-driven decision making.',
        'How have you balanced customer requests with product vision?',
        'Tell me about a competitive win you drove.',
        'Describe how you handle pressure and tight timelines.'
      ],
      whatTheyLookFor: [
        'Experience with B2B or enterprise product management',
        'Technical depth to work with networking engineering teams',
        'Understanding of networking industry and competitive landscape',
        'Strong analytical and strategic thinking skills',
        'Customer empathy and market understanding',
        'Experience with channel partners and enterprise sales',
        'Excellent communication across technical and business audiences',
        'Data-driven decision making',
        'Cross-functional collaboration skills',
        'MBA or technical degree often preferred'
      ],
      interviewTips: [
        'Understand Cisco\'s product portfolio and competitive position',
        'Be prepared to discuss B2B and enterprise product challenges',
        'Show technical depth—Cisco PMs need to understand networking',
        'Prepare a case study on networking or enterprise product strategy',
        'Research Cisco\'s security acquisition strategy (Splunk, etc.)',
        'Demonstrate understanding of channel partner dynamics',
        'Show experience with enterprise customer relationships',
        'Be ready to discuss subscription business model evolution',
        'Prepare examples of data-driven product decisions',
        'Show knowledge of networking trends: cloud, security, AI',
        'Demonstrate ability to simplify complex technical concepts',
        'Prepare questions about Cisco\'s product culture',
        'Show enthusiasm for networking and connectivity',
        'Highlight any networking or enterprise experience'
      ],
      salary: {
        min: 130000,
        max: 220000,
        average: 175000
      },
      compensation: [
        'Competitive base salary ($130K-$220K based on level)',
        'Annual performance bonus (15-25% of base)',
        'Restricted Stock Units (RSUs)',
        '401(k) with company match',
        'Employee Stock Purchase Plan',
        'Comprehensive health benefits',
        'Generous PTO and flexible work',
        'Professional development support',
        'Tuition reimbursement',
        'Remote work flexibility'
      ],
      dayInLife: {
        intro: 'A typical day as a Product Manager at Cisco balances strategy, customer engagement, and cross-functional collaboration.',
        schedule: [
          '8:30 AM - Review market reports and competitive updates',
          '9:00 AM - Engineering sync on product requirements',
          '10:00 AM - Customer call discussing product needs',
          '11:00 AM - Product strategy meeting with leadership',
          '12:00 PM - Lunch with marketing team',
          '1:00 PM - Competitive analysis and positioning work',
          '2:30 PM - Cross-functional review for upcoming launch',
          '4:00 PM - Work on business case for new initiative',
          '5:30 PM - Respond to stakeholder requests and plan tomorrow'
        ],
        closing: 'Product Management at Cisco means shaping products that connect the world, with direct impact on how organizations communicate and operate.'
      },
      similarRoles: ['Senior Product Manager at Cisco', 'Director of Product Management at Cisco', 'Technical Product Manager at Cisco', 'Product Line Manager at Cisco', 'Cloud Product Manager at Cisco']
    },

    'engineering-manager': {
      title: 'Engineering Manager',
      slug: 'engineering-manager',
      industry: 'Technology',
      roleDescription: `Engineering Managers at Cisco lead teams building the software and systems that power global networking infrastructure—from enterprise switches and routers to Webex collaboration tools and Meraki cloud platforms. With responsibility for both technical excellence and people development, EMs at Cisco navigate diverse technical domains including embedded systems, cloud services, security platforms, and communication applications. Cisco\'s management culture emphasizes its "Conscious Culture" values: inclusion, collaboration, and respect. The company consistently ranks among the best places to work, with 96% of employees rating it positively. Engineering Managers work across global teams, coordinating with colleagues in the U.S., India, and other locations. With Cisco\'s continued expansion into security and cloud networking, EMs have opportunities to build and lead teams in high-growth areas.`,
      responsibilities: [
        'Lead and develop engineering teams of 5-15 engineers',
        'Drive technical strategy and architecture decisions',
        'Manage hiring, performance reviews, and career development',
        'Collaborate with product management on roadmap and priorities',
        'Ensure quality and timely delivery of software releases',
        'Foster Cisco\'s Conscious Culture values within the team',
        'Build cross-site relationships for global team coordination',
        'Balance technical debt management with feature development',
        'Drive continuous improvement in engineering practices'
      ],
      growthOpportunities: [
        'Progress from Engineering Manager to Senior EM, Director, and VP',
        'Lead larger organizations or multiple product areas',
        'Move into Distinguished Engineer technical track',
        'Take on cross-site or global team leadership',
        'Lead engineering for acquisitions or new initiatives',
        'Transition into product management or architecture',
        'Build expertise across Cisco\'s product portfolio',
        'Take on executive leadership roles'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '30-minute conversation about leadership experience' },
        { stage: 'Hiring Manager Interview', description: '60-minute discussion of management philosophy and experience' },
        { stage: 'Technical Interview', description: '60-minute assessment of technical depth and decision-making' },
        { stage: 'Leadership Panel', description: 'Interviews with peer managers and senior leadership' },
        { stage: 'Behavioral Interview', description: 'Deep dive on people management and cultural fit' }
      ],
      technicalQuestions: [
        'How do you approach technical decision-making with your team?',
        'Describe your experience with networking or distributed systems.',
        'How do you balance technical debt with feature development?',
        'Explain your approach to code quality and engineering standards.',
        'How do you handle production issues and on-call responsibilities?',
        'Describe your experience with global team coordination.',
        'How do you stay technically current while managing?',
        'Explain your approach to system architecture decisions.',
        'How do you evaluate build vs. buy decisions?',
        'Describe your experience with CI/CD and DevOps practices.',
        'How do you approach security in software development?',
        'Explain your experience with agile methodologies.',
        'How do you handle technical disagreements on your team?',
        'Describe your approach to release management.',
        'How do you balance innovation with stability?',
        'Explain your experience with cloud-native development.'
      ],
      behavioralQuestions: [
        'Tell me about a time you had to deliver difficult feedback.',
        'Describe how you\'ve built a high-performing team.',
        'How have you handled underperforming team members?',
        'Tell me about a project that didn\'t meet expectations.',
        'Describe your experience managing through organizational change.',
        'How do you balance hands-on work with management?',
        'Tell me about a time you made a difficult resource decision.',
        'Describe how you\'ve built cross-functional relationships.',
        'How have you managed teams across multiple locations?',
        'Tell me about a time you advocated for your team.',
        'Describe your approach to promoting diversity and inclusion.',
        'How have you fostered innovation on your teams?',
        'Tell me about a time you had to rapidly scale a team.',
        'Describe how you handle conflict between team members.'
      ],
      whatTheyLookFor: [
        'Strong technical background in software or networking',
        'Proven track record of developing and leading teams',
        'Experience with global team coordination',
        'Alignment with Cisco\'s Conscious Culture values',
        'Excellent communication across all levels',
        'Balance of technical depth and management breadth',
        'Experience with agile development practices',
        'Understanding of networking industry',
        'Ability to drive results through influence',
        'Commitment to diversity and inclusion'
      ],
      interviewTips: [
        'Demonstrate both technical depth and people leadership',
        'Prepare examples of developing team members',
        'Show experience with global or remote teams',
        'Research Cisco\'s Conscious Culture and values',
        'Be ready to discuss technical architecture decisions',
        'Show understanding of Cisco\'s organization',
        'Demonstrate experience with performance management',
        'Prepare examples of building inclusive teams',
        'Show how you balance innovation with delivery',
        'Research Cisco\'s Great Place to Work recognition',
        'Be ready to discuss metrics for team success',
        'Prepare questions about Cisco\'s engineering culture',
        'Show experience with hiring diverse teams',
        'Demonstrate continuous learning mindset'
      ],
      salary: {
        min: 160000,
        max: 280000,
        average: 210000
      },
      compensation: [
        'Competitive base salary ($160K-$280K based on level)',
        'Annual performance bonus (20-35% of base)',
        'Restricted Stock Units (RSUs)',
        '401(k) with company match',
        'Employee Stock Purchase Plan',
        'Comprehensive health benefits',
        'Generous PTO and flexible work',
        'Executive development programs',
        'Tuition reimbursement',
        'Remote work flexibility'
      ],
      dayInLife: {
        intro: 'A typical day as an Engineering Manager at Cisco balances people leadership, technical guidance, and cross-functional collaboration.',
        schedule: [
          '8:30 AM - Review team status and overnight issues',
          '9:00 AM - Team standup with engineers',
          '9:30 AM - 1:1 with team member on career development',
          '10:30 AM - Architecture review for new feature',
          '11:30 AM - Cross-site sync with partner team in India',
          '12:00 PM - Lunch',
          '1:00 PM - Product and engineering leadership meeting',
          '2:00 PM - Technical deep-dive or code review',
          '3:30 PM - Interview candidate for open position',
          '4:30 PM - Address team issues and blockers',
          '5:30 PM - Wrap up and plan tomorrow'
        ],
        closing: 'Engineering Management at Cisco means leading teams that build critical networking infrastructure, with strong emphasis on culture and work-life balance.'
      },
      similarRoles: ['Senior Engineering Manager at Cisco', 'Director of Engineering at Cisco', 'Software Development Manager at Cisco', 'Cloud Engineering Manager at Cisco', 'Security Engineering Manager at Cisco']
    },

    'data-scientist': {
      title: 'Data Scientist',
      slug: 'data-scientist',
      industry: 'Technology',
      roleDescription: `Data Scientists at Cisco apply machine learning and analytics to optimize networking products, improve customer experiences, and drive business insights across the world\'s largest networking company. Working with data from billions of network devices, you\'ll build models for network anomaly detection, predictive maintenance, customer analytics, and AI-powered networking features. Cisco\'s data science teams work across the company—from enhancing Meraki\'s cloud management with ML to building intelligent features in Webex to analyzing customer behavior for product improvement. The role combines traditional data science with domain expertise in networking: understanding how network telemetry translates to predictive models, or how customer usage patterns inform product decisions. With Cisco\'s expansion into AI-powered networking and security analytics (including the Splunk acquisition), data scientists have opportunities to work on cutting-edge applications.`,
      responsibilities: [
        'Develop machine learning models for network analytics and optimization',
        'Build predictive models for customer behavior and product usage',
        'Create anomaly detection systems for network security',
        'Analyze large-scale network telemetry data',
        'Collaborate with product teams on AI-powered features',
        'Develop dashboards and visualizations for business insights',
        'Work with engineering to productionize ML models',
        'Present findings and recommendations to stakeholders',
        'Research and implement state-of-the-art ML techniques'
      ],
      growthOpportunities: [
        'Progress from Data Scientist to Senior, Principal, and Distinguished',
        'Specialize in network ML, customer analytics, or security',
        'Transition into AI/ML engineering or research',
        'Lead data science for specific product areas',
        'Build expertise in network analytics and telemetry',
        'Move into product management for AI products',
        'Contribute to Cisco\'s AI strategy',
        'Publish research and present at conferences'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '30-minute conversation about background and interests' },
        { stage: 'Technical Assessment', description: 'Take-home or online assessment on ML and statistics' },
        { stage: 'Technical Phone Screen', description: '60-minute interview on ML fundamentals and coding' },
        { stage: 'Onsite Presentation', description: 'Present a past data science project' },
        { stage: 'Technical Deep Dive', description: 'Interview on ML algorithms and implementation' },
        { stage: 'Behavioral Interview', description: 'Discussion of teamwork and communication' }
      ],
      technicalQuestions: [
        'How would you design an anomaly detection system for network traffic?',
        'Explain your approach to time series forecasting.',
        'How do you handle class imbalance in security classification?',
        'Describe techniques for analyzing network telemetry at scale.',
        'How do you evaluate and compare ML models?',
        'Explain the bias-variance tradeoff.',
        'How would you build a customer churn prediction model?',
        'Describe your experience with deep learning architectures.',
        'How do you handle missing data in network datasets?',
        'Explain techniques for feature engineering with log data.',
        'How do you ensure ML models perform well in production?',
        'Describe your approach to A/B testing ML models.',
        'How would you approach NLP for network log analysis?',
        'Explain techniques for dimensionality reduction.',
        'How do you make ML models interpretable for stakeholders?',
        'Describe your experience with distributed computing for ML.'
      ],
      behavioralQuestions: [
        'Tell me about a data science project that had significant impact.',
        'Describe a time you communicated findings to non-technical stakeholders.',
        'How have you handled situations where data quality was poor?',
        'Tell me about a time your model didn\'t perform as expected.',
        'Describe your experience working with product teams.',
        'How have you prioritized between multiple data science projects?',
        'Tell me about a time you had to learn a new domain quickly.',
        'Describe how you\'ve worked with engineering on productionization.',
        'How have you handled disagreement about modeling approaches?',
        'Tell me about a project where you were creative with limited data.',
        'Describe your experience with real-time analytics.',
        'How have you balanced accuracy with interpretability?',
        'Tell me about a time you identified an opportunity through data.',
        'Describe how you stay current with ML research.'
      ],
      whatTheyLookFor: [
        'Strong foundation in statistics and machine learning',
        'Proficiency in Python and data science libraries',
        'Experience with production ML systems',
        'Ability to communicate to diverse audiences',
        'Network or security analytics experience valued',
        'Strong problem-solving and analytical skills',
        'Experience with time series and streaming data',
        'Familiarity with big data technologies',
        'Understanding of ML ethics and fairness',
        'Collaborative mindset for cross-functional work'
      ],
      interviewTips: [
        'Prepare to discuss the full ML lifecycle',
        'Review statistics fundamentals thoroughly',
        'Be ready to present a past data science project',
        'Research Cisco\'s AI and ML initiatives',
        'Show interest in network analytics and telemetry',
        'Demonstrate experience with production ML systems',
        'Prepare examples of business impact',
        'Be ready to code—Python and SQL expected',
        'Show understanding of scale challenges',
        'Research Cisco\'s Splunk acquisition',
        'Demonstrate collaborative mindset',
        'Prepare questions about Cisco\'s data science team',
        'Show experience with time series data',
        'Highlight any networking or security domain experience'
      ],
      salary: {
        min: 120000,
        max: 200000,
        average: 160000
      },
      compensation: [
        'Competitive base salary ($120K-$200K based on level)',
        'Annual performance bonus (15-25% of base)',
        'Restricted Stock Units (RSUs)',
        '401(k) with company match',
        'Employee Stock Purchase Plan',
        'Comprehensive health benefits',
        'Conference and training budget',
        'Generous PTO and flexibility',
        'Tuition reimbursement',
        'Remote work options'
      ],
      dayInLife: {
        intro: 'A typical day as a Data Scientist at Cisco balances model development, collaboration, and delivering business insights.',
        schedule: [
          '9:00 AM - Review model performance and experiment results',
          '9:30 AM - Team standup with data science colleagues',
          '10:00 AM - Deep work on model development',
          '12:00 PM - Lunch',
          '1:00 PM - Present findings to product team',
          '2:30 PM - Collaborate with engineering on model deployment',
          '4:00 PM - Research new techniques and review papers',
          '5:00 PM - Document findings and plan experiments',
          '5:30 PM - Wrap up and respond to stakeholder questions'
        ],
        closing: 'Data Science at Cisco means applying ML to optimize the world\'s networking infrastructure, with opportunities to work on AI-powered features used by millions.'
      },
      similarRoles: ['Senior Data Scientist at Cisco', 'Principal Data Scientist at Cisco', 'ML Engineer at Cisco', 'AI Research Scientist at Cisco', 'Analytics Lead at Cisco']
    }