    'machine-learning-engineer': {
      title: 'Machine Learning Engineer',
      slug: 'machine-learning-engineer',
      industry: 'Technology',
      roleDescription: `Machine Learning Engineers at Lyft build the intelligent systems that power real-time transportation for millions of riders and drivers. Working with one of the richest mobility datasets in technology, you'll develop ML models for dynamic pricing, demand forecasting, driver positioning, ETA prediction, fraud detection, and personalized recommendations. Unlike pure research roles, MLEs at Lyft focus on production systems—building models that serve millions of predictions per minute with strict latency requirements. The role bridges data science and engineering, requiring both ML expertise and strong software engineering skills. You'll work on unique challenges: models must adapt to real-time market conditions, handle the cold-start problem in new cities, and balance optimization for riders and drivers simultaneously. Lyft's ML infrastructure is sophisticated, with internal platforms for feature stores, model training, and online serving. Teams collaborate closely with Data Scientists who develop experimental models and Software Engineers who integrate ML into products.`,
      responsibilities: [
        'Design and deploy machine learning models for pricing, matching, and demand forecasting',
        'Build robust ML pipelines handling feature engineering, training, and serving at scale',
        'Develop real-time prediction systems meeting strict latency requirements',
        'Partner with Data Scientists to translate experimental models into production',
        'Build and maintain ML infrastructure including feature stores and model serving',
        'Conduct A/B tests measuring model impact on marketplace metrics',
        'Optimize models for latency, cost, and accuracy trade-offs',
        'Collaborate with Product teams to identify ML opportunities',
        'Stay current with ML research and evaluate applicability to Lyft problems'
      ],
      growthOpportunities: [
        'Progress through IC levels to Staff and Principal ML Engineer',
        'Specialize in areas like real-time systems, NLP, computer vision, or forecasting',
        'Transition into ML Platform engineering building core infrastructure',
        'Move into Research Scientist roles for more exploratory work',
        'Lead ML architecture decisions across multiple product areas',
        'Build and lead ML teams as an Engineering Manager',
        'Contribute to open source and industry ML standards'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial call covering ML experience, background, and interest in Lyft' },
        { stage: 'Technical Phone Screen', description: '60-minute interview covering ML fundamentals, coding, and system design' },
        { stage: 'Onsite - ML Depth', description: 'Deep dive into ML algorithms, model selection, and feature engineering' },
        { stage: 'Onsite - Coding', description: 'Algorithmic coding interview testing implementation skills' },
        { stage: 'Onsite - ML System Design', description: 'Design end-to-end ML system for rideshare-relevant problem' },
        { stage: 'Onsite - Behavioral', description: 'Assessment of collaboration, communication, and values alignment' },
        { stage: 'Team Matching', description: 'Discussions with potential teams to find right fit' }
      ],
      technicalQuestions: [
        'Design a real-time pricing model that responds to supply and demand',
        'How would you build a demand forecasting system for different cities?',
        'Explain your approach to the cold-start problem for new markets',
        'Design a fraud detection system for fake rides and payment fraud',
        'How would you build a driver positioning recommendation system?',
        'Describe techniques for handling class imbalance in churn prediction',
        'How would you design an ETA prediction model accounting for traffic?',
        'Explain your approach to feature engineering for marketplace ML',
        'How would you detect and handle concept drift in pricing models?',
        'Design an ML pipeline for real-time predictions at scale',
        'How would you approach multi-objective optimization in matching?',
        'Explain techniques for interpretable ML in pricing decisions',
        'How would you build a personalized ride recommendation system?',
        'Describe your approach to online learning for real-time adaptation',
        'How would you design A/B testing for ML model changes?',
        'Explain strategies for reducing model serving latency'
      ],
      behavioralQuestions: [
        'Tell me about an ML model you deployed that had significant business impact',
        'Describe a time you chose a simpler model over a more complex one',
        'How have you communicated ML limitations to non-technical stakeholders?',
        'Tell me about an ML project that failed and what you learned',
        'Describe how you balance model accuracy with serving latency',
        'How have you collaborated with data scientists on production ML?',
        'Tell me about debugging a challenging ML issue in production',
        'Describe how you approach feature engineering for a new problem',
        'How have you handled disagreements about model approaches?',
        'Tell me about improving an existing ML system significantly',
        'Describe your approach to monitoring models in production',
        'How have you mentored others in ML best practices?',
        'Tell me about working with engineers to integrate ML into products',
        'Describe handling a situation where model performance degraded'
      ],
      whatTheyLookFor: [
        'Strong ML fundamentals with production deployment experience',
        'Excellent software engineering skills for robust ML systems',
        'Experience with real-time prediction and low-latency serving',
        'Pragmatic approach choosing the right technique for the problem',
        'Strong communication explaining ML to diverse audiences',
        'Collaborative mindset with Data Science, Product, and Engineering',
        'Understanding of marketplace dynamics and network effects',
        'Experience with ML infrastructure at scale',
        'Growth mindset with continuous learning orientation',
        'Alignment with Lyft\'s mission and values'
      ],
      interviewTips: [
        'Review Lyft\'s engineering blog for ML posts on pricing and marketplace',
        'Practice ML system design with focus on production requirements',
        'Be ready to discuss latency vs accuracy trade-offs',
        'Prepare examples of deployed models with business impact',
        'Understand rideshare-specific ML challenges (real-time, two-sided)',
        'Practice coding ML implementations in Python',
        'Be ready to explain feature engineering strategies',
        'Prepare questions about ML infrastructure and team structure',
        'Show genuine interest in transportation ML problems',
        'Be ready to discuss model monitoring and production issues',
        'Review recommendation system and time-series forecasting fundamentals',
        'Prepare to discuss when simpler models beat complex ones',
        'Show how you balance innovation with shipping pragmatism',
        'Be authentic about both successes and failures'
      ],
      salary: { min: 160000, max: 280000 },
      compensation: [
        'Highly competitive base salary with significant equity (RSUs)',
        'Annual refresher grants based on performance',
        'Lyft Pink membership (unlimited Lyft rides)',
        'Comprehensive health, dental, and vision coverage',
        'Flexible PTO policy',
        '401(k) with company match',
        'Conference attendance and ML learning budget',
        'Access to compute resources for experimentation',
        'Parental leave',
        'Home office stipend'
      ],
      dayInLife: {
        intro: 'A day as an ML Engineer at Lyft combines deep technical work with collaborative product partnership on real-time systems.',
        schedule: [
          '9:00 AM - Review model performance dashboards and overnight metrics',
          '9:30 AM - Team standup discussing ML projects and blockers',
          '10:00 AM - Deep work on feature engineering for new pricing model',
          '12:00 PM - Lunch with ML colleagues discussing recent papers',
          '1:00 PM - Meeting with PM on ML approach for new product feature',
          '2:00 PM - Code review for teammate\'s model training pipeline',
          '3:00 PM - A/B test analysis meeting with Data Science partners',
          '4:00 PM - Debug model serving latency issue with platform team',
          '5:00 PM - Write design doc for upcoming ML system improvement',
          '5:30 PM - Wrap up with experiment monitoring check'
        ],
        closing: 'ML Engineering at Lyft means building systems that directly improve transportation for millions while working on unique real-time marketplace challenges.'
      },
      similarRoles: ['Senior ML Engineer at Lyft', 'Staff ML Engineer at Lyft', 'Data Scientist at Lyft', 'ML Platform Engineer at Lyft', 'Research Scientist at Lyft']
    },

    'operations-manager': {
      title: 'Operations Manager',
      slug: 'operations-manager',
      industry: 'Technology',
      roleDescription: `Operations Managers at Lyft ensure the transportation marketplace runs smoothly in cities across the country, balancing rider availability with driver supply to create reliable experiences. This role bridges technology and on-the-ground execution, managing the complex operational challenges of a real-time marketplace. You'll work on driver supply management, market performance optimization, local partnerships, and incident response—ensuring that when someone opens the Lyft app, there's a driver available nearby. Operations at Lyft requires analytical thinking combined with practical problem-solving; you'll use data to identify issues and develop solutions that work in the real world. The role involves managing local market dynamics, which vary significantly—airport regulations, event traffic, commute patterns, and weather all affect how the marketplace performs. Operations partners closely with Product, Data Science, and Marketing to translate operational insights into platform improvements and localized strategies.`,
      responsibilities: [
        'Manage market performance ensuring strong supply-demand balance',
        'Develop and execute driver acquisition and retention strategies',
        'Analyze marketplace data to identify opportunities and issues',
        'Build and manage relationships with local partners and stakeholders',
        'Lead operational response for special events and high-demand periods',
        'Collaborate with Product on operational tools and improvements',
        'Execute localized marketing and driver incentive programs',
        'Handle escalations and incident response for market issues',
        'Report on market performance and develop improvement plans'
      ],
      growthOpportunities: [
        'Progress to Senior Operations Manager overseeing multiple markets',
        'Advance to Regional Operations Director',
        'Move into General Management with P&L responsibility',
        'Transition to Product Management with operational expertise',
        'Lead new market launches and expansion',
        'Move into corporate strategy or business development',
        'Build and lead operations teams'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial discussion of operations background and interest in Lyft' },
        { stage: 'Hiring Manager Interview', description: 'Deep dive into operations experience, analytical skills, and problem-solving' },
        { stage: 'Case Study', description: 'Operational case analyzing market performance and developing solutions' },
        { stage: 'Analytical Assessment', description: 'Data analysis exercise testing Excel/SQL skills and business thinking' },
        { stage: 'Cross-functional Interview', description: 'Assessment of partnership skills with Product, Marketing, and Data teams' },
        { stage: 'Behavioral Interview', description: 'Leadership examples and values alignment assessment' },
        { stage: 'Leadership Interview', description: 'Final round with senior operations leader' }
      ],
      technicalQuestions: [
        'How would you diagnose and address consistently high wait times in a market?',
        'Design a driver incentive program for a supply-constrained market',
        'How would you prepare operations for a major sporting event?',
        'Walk me through how you\'d analyze marketplace health metrics',
        'How would you approach launching Lyft in a new city?',
        'Design an operational playbook for weather-related demand spikes',
        'How would you improve driver retention in a competitive market?',
        'Walk me through analyzing driver supply patterns to optimize incentives',
        'How would you balance rider pricing with driver earnings?',
        'Design a system for managing airport pickup operations',
        'How would you measure the success of an operational improvement?',
        'Walk me through troubleshooting a sudden drop in driver online rates',
        'How would you approach partnering with local government on regulations?',
        'Design a process for handling high-volume event traffic',
        'How would you prioritize operational improvements with limited resources?',
        'Walk me through capacity planning for a market expansion'
      ],
      behavioralQuestions: [
        'Tell me about an operational improvement you led with measurable impact',
        'Describe handling a crisis or urgent operational issue',
        'How have you used data to change an operational strategy?',
        'Tell me about managing competing priorities in operations',
        'Describe building relationships with external stakeholders',
        'How have you worked with product teams to improve operations?',
        'Tell me about a difficult decision balancing driver and rider needs',
        'Describe leading a team through operational change',
        'How have you approached operations in unfamiliar markets?',
        'Tell me about an initiative that didn\'t work and what you learned',
        'Describe collaborating with marketing on driver acquisition',
        'How have you handled pushback from stakeholders?',
        'Tell me about improving team processes or efficiency',
        'Describe managing operations during a major event or surge'
      ],
      whatTheyLookFor: [
        'Strong analytical skills with ability to use data for decision-making',
        'Operational experience in fast-paced, complex environments',
        'Problem-solving ability for ambiguous, real-world challenges',
        'Cross-functional collaboration with Product, Marketing, and Data',
        'Communication skills for stakeholder management',
        'Strategic thinking balancing short-term execution with long-term goals',
        'Comfort with ambiguity and changing conditions',
        'Passion for transportation and community impact',
        'Leadership ability to drive results through others',
        'Alignment with Lyft\'s values and mission'
      ],
      interviewTips: [
        'Prepare examples of operational improvements with quantified impact',
        'Be ready to work through market analysis problems analytically',
        'Understand Lyft\'s marketplace dynamics and two-sided challenges',
        'Research local market conditions and competitive landscape',
        'Prepare to discuss handling ambiguity and changing priorities',
        'Show how you use data while acknowledging real-world constraints',
        'Be ready to discuss stakeholder management experiences',
        'Prepare questions about team structure and growth opportunities',
        'Show genuine interest in transportation and cities',
        'Be ready to discuss both successes and failures with learnings',
        'Understand driver and rider perspectives on the marketplace',
        'Prepare examples of cross-functional collaboration',
        'Practice case study frameworks for operational problems',
        'Research Lyft\'s recent operational initiatives and challenges'
      ],
      salary: { min: 90000, max: 150000 },
      compensation: [
        'Competitive base salary',
        'Equity grants (RSUs)',
        'Annual performance bonuses',
        'Lyft Pink membership (unlimited Lyft rides)',
        'Comprehensive health, dental, and vision insurance',
        'Flexible PTO policy',
        '401(k) with company match',
        'Professional development budget',
        'Parental leave',
        'Phone and connectivity stipend'
      ],
      dayInLife: {
        intro: 'A day as an Operations Manager at Lyft balances data analysis with on-the-ground problem-solving and stakeholder management.',
        schedule: [
          '8:00 AM - Review overnight market performance and any issues',
          '8:30 AM - Check driver supply levels and adjust incentives if needed',
          '9:00 AM - Team standup covering market priorities and active issues',
          '9:30 AM - Analyze weekly marketplace data and identify trends',
          '11:00 AM - Call with airport authority on pickup zone improvements',
          '12:00 PM - Lunch with local driver partner for feedback gathering',
          '1:00 PM - Cross-functional meeting with Product on operational tools',
          '2:00 PM - Prepare operations plan for upcoming major event',
          '3:30 PM - Driver incentive program review with Marketing',
          '4:30 PM - Update market performance report for leadership',
          '5:00 PM - Review next day\'s expected demand and supply positioning',
          '5:30 PM - Wrap up with quick check on evening market conditions'
        ],
        closing: 'Operations at Lyft means ensuring millions of rides happen smoothly every day, bridging data-driven decisions with real-world execution in communities.'
      },
      similarRoles: ['Senior Operations Manager at Lyft', 'Regional Operations Manager at Lyft', 'Market Manager at Lyft', 'Driver Operations Manager at Lyft', 'City Manager at Lyft']
    },

    'marketing-manager': {
      title: 'Marketing Manager',
      slug: 'marketing-manager',
      industry: 'Technology',
      roleDescription: `Marketing Managers at Lyft drive growth and brand awareness for one of the most recognized names in transportation. Working across channels including digital, brand, partnerships, and local activation, you'll develop campaigns that acquire riders, retain existing users, and build Lyft's reputation as the friendlier alternative in rideshare. Lyft's marketing is distinctive—emphasizing community impact, driver welfare, and the human connections that happen in cars. The role requires balancing brand building with performance marketing, national campaigns with local relevance, and rider acquisition with driver recruitment. Marketing partners closely with Product on feature launches, Operations on local campaigns, and Data Science on measurement and optimization. Lyft's two-sided marketplace means marketing must speak to both riders and drivers, often with different messages and channels. The company values marketers who combine creative thinking with analytical rigor, building campaigns that resonate emotionally while delivering measurable results.`,
      responsibilities: [
        'Develop and execute marketing campaigns driving rider acquisition and engagement',
        'Manage multi-channel programs across digital, social, partnerships, and events',
        'Analyze campaign performance and optimize for ROI and growth metrics',
        'Partner with Creative on campaign concepts and content development',
        'Collaborate with Product Marketing on feature launches and adoption',
        'Develop localized marketing strategies for different markets',
        'Manage agency relationships and external partners',
        'Build brand awareness while driving performance goals',
        'Coordinate with Driver Marketing on two-sided campaigns'
      ],
      growthOpportunities: [
        'Progress to Senior Marketing Manager and Director roles',
        'Specialize in brand, performance, partnerships, or driver marketing',
        'Move into Head of Marketing for regions or verticals',
        'Transition to Product Marketing or Growth PM roles',
        'Lead marketing for new products or market expansion',
        'Build and lead marketing teams',
        'Shape company marketing strategy at executive level'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial discussion of marketing experience and interest in Lyft' },
        { stage: 'Hiring Manager Interview', description: 'Deep dive into marketing philosophy, campaigns, and team fit' },
        { stage: 'Case Study', description: 'Marketing strategy exercise for Lyft-relevant challenge' },
        { stage: 'Cross-functional Interview', description: 'Assessment of collaboration with Product, Operations, and Creative' },
        { stage: 'Presentation Round', description: 'Present past campaign demonstrating strategy and results' },
        { stage: 'Behavioral Interview', description: 'Values alignment and leadership assessment' },
        { stage: 'Leadership Interview', description: 'Final round with senior marketing leader' }
      ],
      technicalQuestions: [
        'How would you design a campaign to acquire riders in a new market?',
        'Walk me through your approach to marketing attribution',
        'How would you balance brand marketing with performance goals?',
        'Design a campaign targeting riders who\'ve churned',
        'How would you approach marketing during a competitive promotional period?',
        'Walk me through optimizing a campaign based on performance data',
        'How would you market a new Lyft product feature?',
        'Design a loyalty program marketing strategy',
        'How would you approach localized marketing for different cities?',
        'Walk me through your media mix optimization approach',
        'How would you market Lyft\'s differentiated brand values?',
        'Design a co-marketing campaign with a partner brand',
        'How would you measure brand awareness lift from a campaign?',
        'Walk me through A/B testing for marketing campaigns',
        'How would you balance rider and driver marketing messages?',
        'Design a marketing response to competitor promotions'
      ],
      behavioralQuestions: [
        'Tell me about a campaign you led that exceeded goals',
        'Describe pivoting a campaign strategy based on performance',
        'How have you balanced creative vision with data-driven decisions?',
        'Tell me about marketing to an audience different from yourself',
        'Describe building relationships with creative partners',
        'How have you handled budget constraints while driving growth?',
        'Tell me about a campaign that underperformed and what you learned',
        'Describe collaborating with product teams on launches',
        'How have you approached competitive marketing situations?',
        'Tell me about leading through ambiguity in marketing strategy',
        'Describe managing agency relationships effectively',
        'How have you built brand while driving performance?',
        'Tell me about adapting national campaigns for local markets',
        'Describe influencing stakeholders on marketing strategy'
      ],
      whatTheyLookFor: [
        'Strong marketing track record with measurable campaign success',
        'Balance of creative thinking and analytical optimization',
        'Brand sensibility aligned with Lyft\'s values',
        'Multi-channel expertise across digital, social, and traditional',
        'Strategic thinking connecting marketing to business outcomes',
        'Local market sensitivity for relevant campaigns',
        'Collaboration skills with Product, Operations, and Creative',
        'Alignment with Lyft\'s mission and community values',
        'Comfort with fast-paced, changing environments',
        'Passion for transportation and mobility'
      ],
      interviewTips: [
        'Study Lyft\'s recent marketing campaigns and brand positioning',
        'Prepare campaign examples with clear metrics and learnings',
        'Be ready to discuss both brand and performance marketing',
        'Research Lyft\'s competitive differentiation vs Uber',
        'Show understanding of two-sided marketplace marketing',
        'Prepare questions about marketing culture and team structure',
        'Be ready to present creative ideas with strategic rationale',
        'Understand Lyft\'s brand values (community, friendliness, drivers)',
        'Show genuine passion for Lyft\'s mission',
        'Prepare to discuss marketing measurement and attribution',
        'Be authentic about both successes and failures',
        'Show how you balance data with creative intuition',
        'Research local market conditions and competitive dynamics',
        'Practice case study frameworks for marketing problems'
      ],
      salary: { min: 110000, max: 190000 },
      compensation: [
        'Competitive base salary with equity (RSUs)',
        'Annual performance bonuses',
        'Lyft Pink membership (unlimited Lyft rides)',
        'Comprehensive health, dental, and vision insurance',
        'Flexible PTO policy',
        '401(k) with company match',
        'Marketing conference and professional development budget',
        'Parental leave',
        'Home office stipend',
        'Creative tools and software access'
      ],
      dayInLife: {
        intro: 'A day as a Marketing Manager at Lyft balances strategic planning with campaign execution and cross-functional collaboration.',
        schedule: [
          '9:00 AM - Review overnight campaign performance dashboards',
          '9:30 AM - Team standup on active campaigns and priorities',
          '10:00 AM - Creative review meeting on new campaign concepts',
          '11:00 AM - Partner with Analytics on campaign optimization',
          '12:00 PM - Lunch with colleagues from Product Marketing',
          '1:00 PM - Agency call reviewing upcoming production',
          '2:00 PM - Strategy session on Q4 campaign planning',
          '3:00 PM - Cross-functional sync with Operations on local campaigns',
          '4:00 PM - Budget review and reallocation based on performance',
          '5:00 PM - Social listening and competitive monitoring',
          '5:30 PM - Wrap up with campaign status updates'
        ],
        closing: 'Marketing at Lyft means building campaigns that grow ridership while reinforcing the brand values that differentiate Lyft in the market.'
      },
      similarRoles: ['Senior Marketing Manager at Lyft', 'Brand Marketing Manager at Lyft', 'Growth Marketing Manager at Lyft', 'Driver Marketing Manager at Lyft', 'Product Marketing Manager at Lyft']
    },

    'ux-designer': {
      title: 'UX Designer',
      slug: 'ux-designer',
      industry: 'Technology',
      roleDescription: `UX Designers at Lyft create the experiences that help millions of riders get where they're going and drivers earn a living. Working on one of the most used mobile apps in transportation, you'll design for complex real-time scenarios—from requesting a ride to tracking your driver to navigating as a driver. Lyft's design culture emphasizes user empathy for both sides of the marketplace, inclusive design that works for diverse users, and the craft details that make experiences feel polished. Designers work in cross-functional teams with Product Managers and Engineers, having significant ownership over their product areas. The challenge is unique: designing for users in motion, with divided attention, in varied contexts from daily commutes to late-night rides home. Lyft's design system ensures consistency across rider and driver apps while allowing for context-appropriate innovation. The company's commitment to making transportation accessible means designers must consider users with disabilities, seniors, and those in underserved communities.`,
      responsibilities: [
        'Design intuitive user experiences for rider and driver mobile apps',
        'Conduct user research including interviews, usability testing, and ride-alongs',
        'Create wireframes, prototypes, and high-fidelity designs using Figma',
        'Partner with PM and Engineering to ship features that improve the marketplace',
        'Contribute to and evolve Lyft\'s design system',
        'Design for accessibility across diverse user needs and abilities',
        'Present design work and incorporate stakeholder feedback',
        'Collaborate with researchers to develop deep user empathy',
        'Mentor junior designers and contribute to design culture'
      ],
      growthOpportunities: [
        'Progress through IC levels to Senior, Staff, and Principal Designer',
        'Specialize in areas like motion design, design systems, or research',
        'Transition into Design Management leading design teams',
        'Move into Product Management leveraging design foundation',
        'Lead design for major new product initiatives',
        'Shape company design direction and strategy',
        'Represent Lyft at industry conferences and events'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial conversation about design background and portfolio' },
        { stage: 'Hiring Manager Call', description: 'Deep discussion of design philosophy and team fit' },
        { stage: 'Portfolio Review', description: 'Detailed walkthrough of past work focusing on process and outcomes' },
        { stage: 'Design Exercise', description: 'Take-home or whiteboard exercise solving transportation design problem' },
        { stage: 'Onsite - Craft Review', description: 'Assessment of design skills, attention to detail, and systems thinking' },
        { stage: 'Onsite - Cross-functional', description: 'Interviews with PM and Engineering assessing collaboration' },
        { stage: 'Onsite - Behavioral', description: 'Values alignment and culture fit assessment' }
      ],
      technicalQuestions: [
        'Walk me through your design process from research to launch',
        'How would you redesign the Lyft ride request experience?',
        'Design a feature to help drivers navigate to pickup locations more easily',
        'How do you approach designing for users in motion with divided attention?',
        'Show how you\'ve used data to inform design decisions',
        'How would you design the first-time rider experience?',
        'Describe your approach to mobile design for diverse contexts',
        'How do you balance consistency with innovation in a design system?',
        'Design an experience for scheduling rides in advance',
        'How would you approach accessibility in the Lyft app?',
        'Show how you collaborate with engineers during implementation',
        'How would you design for users with disabilities?',
        'Design a feature to help riders compare ride options',
        'How do you handle feedback that challenges your design direction?',
        'Show how you prototype and test ideas quickly',
        'How would you design for both rider and driver apps with shared patterns?'
      ],
      behavioralQuestions: [
        'Tell me about a design you\'re most proud of and why',
        'Describe advocating for users when business wanted different direction',
        'How have you designed for users very different from yourself?',
        'Tell me about design feedback that changed your approach',
        'Describe collaborating with engineering on complex implementation',
        'How have you balanced design quality with shipping quickly?',
        'Tell me about a design that didn\'t work as expected',
        'Describe how you\'ve built inclusive design culture',
        'How have you mentored or helped grow other designers?',
        'Tell me about navigating ambiguity in a design project',
        'Describe building trust with cross-functional partners',
        'How have you approached designing for accessibility?',
        'Tell me about handling conflicting stakeholder feedback',
        'Describe your most challenging design problem and how you solved it'
      ],
      whatTheyLookFor: [
        'Strong portfolio demonstrating end-to-end product design',
        'Deep user empathy for diverse audiences including riders and drivers',
        'Excellent collaboration with PM, Engineering, and Research',
        'Clear communication presenting design rationale',
        'Design system thinking balancing consistency with innovation',
        'Mobile design expertise for complex, real-time experiences',
        'Commitment to accessibility and inclusive design',
        'Growth mindset open to feedback and iteration',
        'Alignment with Lyft\'s mission and values',
        'Craft excellence with attention to detail'
      ],
      interviewTips: [
        'Prepare a portfolio that tells stories of process, not just finals',
        'Use Lyft as a rider and driver if possible to understand both perspectives',
        'Practice presenting designs with clear rationale',
        'Be ready to discuss designing for mobile and real-time contexts',
        'Show how you collaborate with PM and Engineering',
        'Prepare for design exercises with structured approach',
        'Research Lyft\'s design culture and recent product changes',
        'Be ready to discuss accessibility and inclusive design',
        'Show genuine passion for transportation and mobility',
        'Prepare thoughtful questions about design team and culture',
        'Be authentic—Lyft values genuine fit',
        'Practice articulating trade-offs in design decisions',
        'Show how you use research and data alongside intuition',
        'Be ready to discuss failures and what you learned'
      ],
      salary: { min: 120000, max: 210000 },
      compensation: [
        'Competitive base salary with equity (RSUs)',
        'Annual performance bonuses',
        'Lyft Pink membership (unlimited Lyft rides)',
        'Comprehensive health, dental, and vision insurance',
        'Flexible PTO policy',
        '401(k) with company match',
        'Design conference and learning budget',
        'Latest hardware and design tools',
        'Parental leave',
        'Home office stipend'
      ],
      dayInLife: {
        intro: 'A day as a UX Designer at Lyft blends creative exploration with user research and collaborative refinement.',
        schedule: [
          '9:00 AM - Review user feedback and research findings',
          '9:30 AM - Team standup with PM and Engineering on sprint progress',
          '10:00 AM - Deep design work on new feature concepts in Figma',
          '12:00 PM - Lunch with design teammates sharing inspiration',
          '1:00 PM - User testing session observing riders request rides',
          '2:30 PM - Design critique with broader design team',
          '3:30 PM - Sync with engineer on implementation details',
          '4:30 PM - Prototype new interaction for testing',
          '5:00 PM - Document design decisions and update specs',
          '5:30 PM - Wrap up reviewing tomorrow\'s priorities'
        ],
        closing: 'Design at Lyft means creating experiences that help people move through their lives, from daily commutes to nights out, with craft and care.'
      },
      similarRoles: ['Senior UX Designer at Lyft', 'Product Designer at Lyft', 'Design Lead at Lyft', 'Visual Designer at Lyft', 'UX Researcher at Lyft']
    }
