    'software-engineer': {
      title: 'Software Engineer',
      slug: 'software-engineer',
      industry: 'Technology',
      roleDescription: `Software Engineers at Intel develop the software that powers the world\'s computing infrastructure—from firmware and drivers that enable processors to function, to AI frameworks that accelerate machine learning workloads, to cloud orchestration tools for data centers. Working at the intersection of hardware and software, you\'ll optimize code for Intel\'s latest processor architectures, build tools used by millions of developers, and contribute to performance-critical systems where every cycle matters. Intel\'s software organization spans compiler development, graphics drivers, AI toolkits (OpenVINO), virtualization, and operating system enablement across Linux and Windows. The interview process focuses on algorithms, data structures, and system design, with strong emphasis on C/C++ proficiency given Intel\'s low-level software work. Engineers work in a culture that values technical depth, innovation, and risk-taking—Intel encourages trying novel approaches. With the company\'s renewed focus on foundry services and AI chips, software engineers have opportunities to shape next-generation computing platforms.`,
      responsibilities: [
        'Develop firmware, drivers, and system software for Intel processors',
        'Optimize software performance for Intel hardware architectures',
        'Build AI and machine learning frameworks and toolkits',
        'Create development tools and compilers for Intel platforms',
        'Enable operating systems and hypervisors on new silicon',
        'Write low-level code in C/C++ and assembly',
        'Collaborate with hardware teams on co-design and optimization',
        'Debug complex system-level issues across hardware and software',
        'Contribute to open-source projects and community standards'
      ],
      growthOpportunities: [
        'Progress from Software Engineer to Senior, Principal, and Fellow',
        'Specialize in compilers, graphics, AI, or systems software',
        'Transition into technical leadership or architecture roles',
        'Move into hardware engineering or product development',
        'Lead software enablement for new processor generations',
        'Contribute to industry standards and open-source leadership',
        'Build expertise across the full computing stack',
        'Access sabbatical program after 7 years'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '30-45 minute conversation about background and compensation expectations' },
        { stage: 'Technical Phone Screen', description: '60-minute virtual interview with coding problems using IDE' },
        { stage: 'On-Site Technical Rounds', description: 'Multiple 1-hour interviews covering algorithms, system design, and domain knowledge' },
        { stage: 'Behavioral Interview', description: 'Discussion of past experiences, teamwork, and cultural fit' },
        { stage: 'Hiring Manager Interview', description: 'Final conversation about role expectations and team fit' }
      ],
      technicalQuestions: [
        'Implement a function to reverse a linked list iteratively and recursively.',
        'How would you optimize memory access patterns for cache efficiency?',
        'Explain the differences between user space and kernel space.',
        'Design a thread-safe producer-consumer queue.',
        'How do you debug a performance regression in a large codebase?',
        'Explain how virtual memory and paging work.',
        'Implement a basic memory allocator.',
        'How would you profile and optimize code for SIMD instructions?',
        'Explain the boot process from power-on to OS loading.',
        'Design a device driver for a simple hardware peripheral.',
        'How do you handle race conditions in multithreaded code?',
        'Explain cache coherency protocols in multiprocessor systems.',
        'Implement a LRU cache with O(1) operations.',
        'How would you debug a system crash or hang?',
        'Explain interrupt handling and context switching.',
        'Design a scalable logging system for a distributed application.'
      ],
      behavioralQuestions: [
        'Tell me about a challenging technical problem you solved.',
        'Describe a time you had to learn new technology quickly.',
        'How have you handled disagreements with team members?',
        'Tell me about a project where you optimized performance significantly.',
        'Describe your experience working with hardware teams.',
        'How do you prioritize when facing multiple deadlines?',
        'Tell me about a time you took a risk on a new approach.',
        'Describe how you stay current with technology trends.',
        'How have you mentored or helped junior engineers?',
        'Tell me about a project that didn\'t go as planned.',
        'Describe your experience with code reviews.',
        'How do you handle ambiguous requirements?',
        'Tell me about a time you improved a process or tool.',
        'Describe your experience debugging complex systems.'
      ],
      whatTheyLookFor: [
        'Strong proficiency in C/C++ and systems programming',
        'Understanding of computer architecture and hardware concepts',
        'Experience with low-level software development',
        'Problem-solving skills for complex technical challenges',
        'Knowledge of operating systems internals',
        'Performance optimization and profiling experience',
        'Collaboration skills for hardware-software co-design',
        'Understanding of parallel programming and threading',
        'Python proficiency for scripting and automation',
        'Innovation mindset and willingness to take risks'
      ],
      interviewTips: [
        'Brush up on C/C++ fundamentals—Intel emphasizes low-level skills',
        'Practice LeetCode problems focusing on systems-oriented questions',
        'Understand computer architecture: caches, pipelining, memory hierarchy',
        'Be prepared to discuss hardware-software interaction',
        'Research Intel\'s current products and strategic direction',
        'Show understanding of performance optimization techniques',
        'Prepare to explain your thought process while coding',
        'Review operating systems concepts thoroughly',
        'Be ready to discuss open-source contributions if applicable',
        'Show enthusiasm for Intel\'s mission and technology',
        'Prepare examples of debugging complex issues',
        'Understand Intel\'s foundry and AI strategies',
        'Be patient—Intel\'s response times can be slow',
        'Highlight any experience with embedded or firmware development'
      ],
      salary: {
        min: 100000,
        max: 200000,
        average: 145000
      },
      compensation: [
        'Competitive base salary ($100K-$200K based on level and location)',
        'Annual performance bonus',
        'Restricted Stock Units (RSUs) with 3-year vesting',
        '7% 401(k) match (2024)',
        'Employee Stock Purchase Plan with 15% discount',
        'Comprehensive health, dental, and vision insurance',
        '$40K fertility benefits',
        '12 weeks parental leave plus 4 weeks part-time at full pay',
        '4-week sabbatical after 7 years',
        'Tuition reimbursement and professional development'
      ],
      dayInLife: {
        intro: 'A typical day as a Software Engineer at Intel combines deep technical work with collaboration across hardware and software teams.',
        schedule: [
          '9:00 AM - Review overnight build results and test failures',
          '9:30 AM - Team standup discussing sprint progress',
          '10:00 AM - Deep work on driver development or optimization',
          '12:00 PM - Lunch break',
          '1:00 PM - Code review session with team',
          '2:00 PM - Cross-functional meeting with hardware engineers',
          '3:00 PM - Continue development work or debugging',
          '4:30 PM - Performance profiling and analysis',
          '5:30 PM - Update documentation and plan tomorrow'
        ],
        closing: 'Software Engineering at Intel means working at the intersection of hardware and software, building the foundational code that powers billions of devices worldwide.'
      },
      similarRoles: ['Senior Software Engineer at Intel', 'Principal Engineer at Intel', 'Systems Software Engineer at Intel', 'Firmware Engineer at Intel', 'Graphics Software Engineer at Intel']
    },

    'product-manager': {
      title: 'Product Manager',
      slug: 'product-manager',
      industry: 'Technology',
      roleDescription: `Product Managers at Intel shape the strategy and execution of products that power the world\'s computing—from processors and graphics chips to AI accelerators and foundry services. Working at the intersection of engineering, business, and market strategy, you\'ll define product requirements, drive roadmaps, and launch technologies that serve billions of users. Intel\'s PM role is uniquely technical given the company\'s hardware focus: you\'ll work closely with silicon engineers, understand processor architectures, and translate complex technical capabilities into market-winning products. The role spans Intel\'s diverse portfolio including client computing (Core processors), data center (Xeon), AI products (Gaudi accelerators), and Intel Foundry Services. PMs at Intel navigate long development cycles typical of hardware—products planned years in advance—while adapting to rapidly evolving market demands. With Intel\'s strategic transformation including the foundry business and AI focus, product managers have opportunities to shape the company\'s next chapter.`,
      responsibilities: [
        'Define product strategy and roadmaps for processor or platform products',
        'Gather and prioritize requirements from customers and market analysis',
        'Work with engineering teams to translate requirements into specifications',
        'Drive product launches and go-to-market strategies',
        'Analyze competitive landscape and market trends',
        'Present product strategies to executives and customers',
        'Collaborate with sales and marketing on positioning',
        'Manage product lifecycle from concept through end-of-life',
        'Build business cases for new product investments'
      ],
      growthOpportunities: [
        'Progress from Product Manager to Senior PM, Director, and VP',
        'Lead product lines or business segments',
        'Move into general management or business unit leadership',
        'Transition into technical marketing or solutions architecture',
        'Build expertise in specific markets: AI, data center, client',
        'Lead Intel Foundry Services customer engagements',
        'Move into corporate strategy or business development',
        'Build external presence as industry thought leader'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '30-minute conversation about background and interests' },
        { stage: 'Hiring Manager Interview', description: '45-minute discussion of PM experience and approach' },
        { stage: 'Technical Interview', description: '60-minute interview on technical understanding and product skills' },
        { stage: 'Case Study', description: 'Present product strategy for a given market scenario' },
        { stage: 'Cross-functional Interviews', description: 'Conversations with engineering, marketing, and sales' },
        { stage: 'Executive Interview', description: 'Final round with senior product leadership' }
      ],
      technicalQuestions: [
        'How would you prioritize features for a new processor generation?',
        'Explain your approach to building a product roadmap.',
        'How do you balance performance, power, and cost in product decisions?',
        'Describe your experience with hardware product development cycles.',
        'How would you differentiate Intel products against AMD or ARM competitors?',
        'Explain your approach to gathering technical requirements.',
        'How do you measure success for a processor product?',
        'Describe your experience with pricing strategy for technical products.',
        'How would you approach the AI accelerator market opportunity?',
        'Explain your process for making build vs. buy vs. partner decisions.',
        'How do you handle long development cycles with changing market needs?',
        'Describe your experience with semiconductor industry dynamics.',
        'How would you position Intel Foundry Services to customers?',
        'Explain your approach to competitive analysis.',
        'How do you work with engineering on technical trade-offs?',
        'Describe your experience launching technical products.'
      ],
      behavioralQuestions: [
        'Tell me about a product you launched and its market impact.',
        'Describe a time you had to make a difficult trade-off decision.',
        'How have you handled disagreement with engineering teams?',
        'Tell me about a time you pivoted product strategy based on new data.',
        'Describe your experience working with enterprise customers.',
        'How have you navigated organizational complexity?',
        'Tell me about a product decision you\'d make differently in hindsight.',
        'Describe how you stay current with technology trends.',
        'How have you built relationships across functions?',
        'Tell me about a time you influenced without direct authority.',
        'Describe your experience with data-driven decision making.',
        'How have you balanced customer requests with product vision?',
        'Tell me about a competitive win you drove.',
        'Describe how you handle pressure and tight timelines.'
      ],
      whatTheyLookFor: [
        'Technical depth to work with hardware engineering teams',
        'Experience with product management in technical industries',
        'Understanding of semiconductor or hardware product development',
        'Strong analytical and strategic thinking skills',
        'Excellent communication across technical and business audiences',
        'Customer empathy and market understanding',
        'Experience with long product development cycles',
        'Ability to make decisions with incomplete information',
        'Cross-functional collaboration skills',
        'MBA or technical degree often preferred'
      ],
      interviewTips: [
        'Understand Intel\'s product portfolio and competitive position',
        'Be prepared to discuss semiconductor industry dynamics',
        'Show technical depth—Intel PMs need to speak with engineers',
        'Prepare a case study on processor or hardware product strategy',
        'Research Intel\'s foundry strategy and AI initiatives',
        'Demonstrate understanding of long hardware development cycles',
        'Show experience with B2B and enterprise customers',
        'Be ready to discuss competitive positioning vs AMD and ARM',
        'Prepare examples of data-driven product decisions',
        'Show knowledge of processor architecture concepts',
        'Demonstrate ability to simplify complex technical concepts',
        'Prepare questions about Intel\'s strategic transformation',
        'Show enthusiasm for Intel\'s mission and technology leadership',
        'Highlight any hardware or semiconductor experience'
      ],
      salary: {
        min: 130000,
        max: 220000,
        average: 175000
      },
      compensation: [
        'Competitive base salary ($130K-$220K based on level)',
        'Annual performance bonus (15-25% of base)',
        'Restricted Stock Units (RSUs)',
        '7% 401(k) match',
        'Employee Stock Purchase Plan with 15% discount',
        'Comprehensive health benefits',
        'Generous PTO and sabbatical program',
        'Parental leave benefits',
        'Professional development support',
        'Global mobility opportunities'
      ],
      dayInLife: {
        intro: 'A typical day as a Product Manager at Intel balances strategy, customer engagement, and cross-functional collaboration.',
        schedule: [
          '8:30 AM - Review market reports and competitive updates',
          '9:00 AM - Engineering sync on product requirements',
          '10:00 AM - Customer call discussing product roadmap',
          '11:00 AM - Product strategy meeting with leadership',
          '12:00 PM - Lunch with marketing team',
          '1:00 PM - Competitive analysis and positioning work',
          '2:30 PM - Cross-functional review for upcoming launch',
          '4:00 PM - Work on business case for new initiative',
          '5:30 PM - Respond to stakeholder requests and plan tomorrow'
        ],
        closing: 'Product Management at Intel means shaping the products that power the world\'s computing, with deep technical engagement and strategic impact.'
      },
      similarRoles: ['Senior Product Manager at Intel', 'Director of Product Management at Intel', 'Technical Product Manager at Intel', 'Platform Product Manager at Intel', 'AI Product Manager at Intel']
    },

    'engineering-manager': {
      title: 'Engineering Manager',
      slug: 'engineering-manager',
      industry: 'Technology',
      roleDescription: `Engineering Managers at Intel lead teams building the software and systems that enable the world\'s processors, accelerators, and computing platforms. With responsibility for both technical excellence and people development, EMs at Intel navigate the unique challenges of hardware-software co-design, long product cycles, and cross-site collaboration. Intel\'s management culture values technical depth—managers are expected to understand the architecture and systems their teams build. The role spans diverse domains: firmware, drivers, AI frameworks, compilers, and platform software. EMs work closely with hardware engineering teams, coordinating software enablement for new silicon generations. Intel invests in management development through leadership programs and promotes from within. With the company\'s strategic transformation around foundry and AI, engineering managers have opportunities to shape new organizations and build teams in high-growth areas.`,
      responsibilities: [
        'Lead and develop engineering teams of 5-15 software engineers',
        'Drive technical strategy and architecture decisions',
        'Manage hiring, performance reviews, and career development',
        'Coordinate with product management on roadmap and priorities',
        'Ensure quality and timely delivery of software releases',
        'Collaborate with hardware teams on co-design and enablement',
        'Build cross-site relationships for global team coordination',
        'Manage technical debt and engineering investments',
        'Foster a culture of innovation and technical excellence'
      ],
      growthOpportunities: [
        'Progress from Engineering Manager to Senior EM, Director, and VP',
        'Lead larger organizations or multiple product areas',
        'Move into Principal or Fellow technical track',
        'Take on cross-site or global team leadership',
        'Lead engineering for new business areas like foundry',
        'Transition into product management or architecture',
        'Build expertise across hardware and software',
        'Take on executive leadership roles'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '30-minute conversation about leadership experience' },
        { stage: 'Hiring Manager Interview', description: '60-minute discussion of management philosophy and experience' },
        { stage: 'Technical Interview', description: '60-minute assessment of technical depth and architecture skills' },
        { stage: 'Leadership Panel', description: 'Interviews with peer managers and senior leadership' },
        { stage: 'Behavioral Interview', description: 'Deep dive on people management and cultural fit' }
      ],
      technicalQuestions: [
        'How do you approach technical decision-making with your team?',
        'Describe your experience with hardware-software co-design.',
        'How do you balance technical debt with feature development?',
        'Explain your approach to code quality and engineering standards.',
        'How do you handle performance issues in software releases?',
        'Describe your experience with firmware or driver development.',
        'How do you stay technically current while managing?',
        'Explain your approach to system architecture decisions.',
        'How do you coordinate software enablement for new hardware?',
        'Describe your experience with release management.',
        'How do you evaluate build vs. buy decisions?',
        'Explain your experience with CI/CD and automation.',
        'How do you approach security in software development?',
        'Describe your experience with cross-site team coordination.',
        'How do you handle technical disagreements on your team?',
        'Explain your approach to on-call and incident management.'
      ],
      behavioralQuestions: [
        'Tell me about a time you had to deliver difficult feedback.',
        'Describe how you\'ve built a high-performing team.',
        'How have you handled underperforming team members?',
        'Tell me about a project that didn\'t meet expectations.',
        'Describe your experience managing through organizational change.',
        'How do you balance individual contributor work with management?',
        'Tell me about a time you had to make a difficult resource decision.',
        'Describe how you\'ve built cross-functional relationships.',
        'How have you managed teams across multiple locations?',
        'Tell me about a time you advocated for your team.',
        'Describe your approach to succession planning.',
        'How have you fostered innovation on your teams?',
        'Tell me about a time you had to rapidly hire or grow a team.',
        'Describe how you handle conflict between team members.'
      ],
      whatTheyLookFor: [
        'Strong technical background in software or systems engineering',
        'Proven track record of developing and leading teams',
        'Experience with hardware-software interface',
        'Excellent communication across technical levels',
        'Cross-site and global team leadership experience',
        'Balance of technical depth and management breadth',
        'Experience with long product development cycles',
        'Understanding of semiconductor industry dynamics',
        'Ability to drive results through influence',
        'Commitment to diversity and team development'
      ],
      interviewTips: [
        'Demonstrate both technical depth and people leadership',
        'Prepare examples of developing team members',
        'Show experience with hardware-software collaboration',
        'Be ready to discuss managing across time zones and sites',
        'Prepare for technical architecture discussions',
        'Show understanding of Intel\'s organizational structure',
        'Demonstrate experience with performance management',
        'Prepare examples of navigating organizational change',
        'Show how you balance innovation with delivery',
        'Research Intel\'s engineering culture and values',
        'Be ready to discuss metrics for team success',
        'Prepare questions about Intel\'s transformation',
        'Show experience with hiring and building diverse teams',
        'Demonstrate continuous learning mindset'
      ],
      salary: {
        min: 160000,
        max: 280000,
        average: 210000
      },
      compensation: [
        'Competitive base salary ($160K-$280K based on level)',
        'Annual performance bonus (20-35% of base)',
        'Restricted Stock Units (RSUs)',
        '7% 401(k) match',
        'Employee Stock Purchase Plan',
        'Comprehensive health benefits',
        'Sabbatical program after 7 years',
        'Executive development programs',
        'Parental leave benefits',
        'Global mobility opportunities'
      ],
      dayInLife: {
        intro: 'A typical day as an Engineering Manager at Intel balances people leadership, technical guidance, and cross-functional coordination.',
        schedule: [
          '8:30 AM - Review team status and overnight issues',
          '9:00 AM - Team standup with engineers',
          '9:30 AM - 1:1 with team member on career development',
          '10:30 AM - Architecture review for new feature',
          '11:30 AM - Cross-site sync with partner team',
          '12:00 PM - Lunch',
          '1:00 PM - Product and engineering leadership meeting',
          '2:00 PM - Technical deep-dive or code review',
          '3:30 PM - Hardware-software coordination meeting',
          '4:30 PM - Interview candidate for open position',
          '5:30 PM - Wrap up and plan tomorrow'
        ],
        closing: 'Engineering Management at Intel means leading teams that build foundational computing technology, with opportunities to develop people and drive technical excellence.'
      },
      similarRoles: ['Senior Engineering Manager at Intel', 'Director of Engineering at Intel', 'Software Development Manager at Intel', 'Firmware Engineering Manager at Intel', 'Platform Engineering Manager at Intel']
    },

    'data-scientist': {
      title: 'Data Scientist',
      slug: 'data-scientist',
      industry: 'Technology',
      roleDescription: `Data Scientists at Intel apply machine learning and analytics to optimize the world\'s most complex manufacturing processes and drive product innovation. Working at a company that produces billions of transistors on every chip, you\'ll tackle unique challenges: predicting silicon yield, optimizing fabrication processes, analyzing performance data from processors, and building AI models that run efficiently on Intel hardware. Intel\'s data science teams work across the company—from manufacturing and supply chain optimization to product analytics and AI product development. The role combines traditional data science with domain expertise in semiconductors: understanding how data from fabs translates to process improvements, or how workload analysis informs next-generation processor design. Intel also develops AI tools like OpenVINO for external developers, giving data scientists opportunities to build products used by the AI community worldwide.`,
      responsibilities: [
        'Develop machine learning models for manufacturing process optimization',
        'Analyze silicon yield data to identify improvement opportunities',
        'Build predictive models for supply chain and demand forecasting',
        'Create analytics solutions for product performance analysis',
        'Optimize AI models for efficient inference on Intel hardware',
        'Collaborate with fab engineers on process control improvements',
        'Develop dashboards and visualizations for business insights',
        'Contribute to Intel\'s AI tools and frameworks',
        'Present findings and recommendations to technical leadership'
      ],
      growthOpportunities: [
        'Progress from Data Scientist to Senior, Principal, and Fellow',
        'Specialize in manufacturing, product, or AI domains',
        'Transition into AI/ML engineering or research',
        'Lead data science for specific business units',
        'Build expertise in semiconductor process optimization',
        'Move into product management for AI products',
        'Contribute to Intel\'s AI strategy and tools',
        'Publish research and present at industry conferences'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '30-minute conversation about background and interests' },
        { stage: 'Technical Assessment', description: 'Take-home or online assessment covering ML and statistics' },
        { stage: 'Technical Phone Screen', description: '60-minute interview on ML fundamentals and problem-solving' },
        { stage: 'On-Site Presentations', description: 'Present a past project and solve a case study' },
        { stage: 'Technical Deep Dive', description: 'Interview on ML algorithms, statistics, and implementation' },
        { stage: 'Behavioral Interview', description: 'Discussion of teamwork, communication, and cultural fit' }
      ],
      technicalQuestions: [
        'Explain your approach to a time series forecasting problem.',
        'How would you detect anomalies in manufacturing process data?',
        'Describe techniques for handling imbalanced datasets.',
        'How do you optimize ML models for inference performance?',
        'Explain the bias-variance tradeoff and its implications.',
        'How would you approach a yield prediction problem in semiconductor manufacturing?',
        'Describe your experience with deep learning architectures.',
        'How do you handle missing data in real-world datasets?',
        'Explain techniques for feature engineering with sensor data.',
        'How do you evaluate and compare ML models?',
        'Describe your approach to model interpretability.',
        'How would you design an A/B test for a process change?',
        'Explain techniques for dimensionality reduction.',
        'How do you ensure ML models remain performant in production?',
        'Describe your experience with distributed computing for ML.',
        'How would you approach natural language processing for technical documents?'
      ],
      behavioralQuestions: [
        'Tell me about a data science project that had significant business impact.',
        'Describe a time you communicated complex findings to non-technical stakeholders.',
        'How have you handled situations where data quality was poor?',
        'Tell me about a time your model didn\'t perform as expected.',
        'Describe your experience working with domain experts.',
        'How have you prioritized between multiple data science projects?',
        'Tell me about a time you had to learn a new domain quickly.',
        'Describe how you\'ve worked with engineering teams to productionize models.',
        'How have you handled disagreement about modeling approaches?',
        'Tell me about a project where you had to be creative with limited data.',
        'Describe your experience with real-time or streaming analytics.',
        'How have you balanced model accuracy with interpretability?',
        'Tell me about a time you identified an opportunity through data analysis.',
        'Describe how you stay current with ML research and techniques.'
      ],
      whatTheyLookFor: [
        'Strong foundation in statistics and machine learning',
        'Proficiency in Python and data science libraries',
        'Experience with production ML systems',
        'Ability to communicate findings to diverse audiences',
        'Manufacturing or industrial analytics experience valued',
        'Understanding of model optimization for performance',
        'Strong problem-solving and analytical skills',
        'Experience with time series and sensor data',
        'Familiarity with deep learning frameworks',
        'Domain curiosity about semiconductors and hardware'
      ],
      interviewTips: [
        'Prepare to discuss the full ML lifecycle from problem framing to deployment',
        'Review statistics fundamentals thoroughly',
        'Be ready to present a past data science project clearly',
        'Research Intel\'s AI tools like OpenVINO',
        'Show interest in manufacturing and process optimization',
        'Demonstrate experience with production ML systems',
        'Prepare examples of business impact from your work',
        'Be ready to code—Python and SQL proficiency expected',
        'Show understanding of model optimization for hardware',
        'Research Intel\'s AI product strategy',
        'Demonstrate collaborative mindset',
        'Prepare questions about Intel\'s data science team',
        'Show experience with time series or sensor data if applicable',
        'Highlight any hardware or manufacturing domain experience'
      ],
      salary: {
        min: 110000,
        max: 190000,
        average: 150000
      },
      compensation: [
        'Competitive base salary ($110K-$190K based on level)',
        'Annual performance bonus (10-20% of base)',
        'Restricted Stock Units (RSUs)',
        '7% 401(k) match',
        'Employee Stock Purchase Plan',
        'Comprehensive health benefits',
        'Conference and training budget',
        'Sabbatical program after 7 years',
        'Parental leave benefits',
        'Professional development support'
      ],
      dayInLife: {
        intro: 'A typical day as a Data Scientist at Intel balances model development, collaboration with domain experts, and delivering business insights.',
        schedule: [
          '9:00 AM - Review model performance and experiment results',
          '9:30 AM - Team standup with data science colleagues',
          '10:00 AM - Deep work on model development or feature engineering',
          '12:00 PM - Lunch with fab engineering team',
          '1:00 PM - Present analysis findings to manufacturing leadership',
          '2:30 PM - Collaborate with MLOps on model deployment',
          '4:00 PM - Research new techniques and review papers',
          '5:00 PM - Document findings and plan next experiments',
          '5:30 PM - Wrap up and respond to stakeholder questions'
        ],
        closing: 'Data Science at Intel means applying ML to optimize the world\'s most complex manufacturing and product development, with opportunities to build AI tools used by developers worldwide.'
      },
      similarRoles: ['Senior Data Scientist at Intel', 'Principal Data Scientist at Intel', 'ML Engineer at Intel', 'AI Research Scientist at Intel', 'Analytics Lead at Intel']
    }