    'software-engineer': {
      title: 'Software Engineer',
      slug: 'software-engineer',
      industry: 'Technology',
      roleDescription: `Software Engineers at Stripe build the financial infrastructure that powers millions of businesses worldwide, from startups to Fortune 500 companies. Working on one of the most critical systems in the internet economy, you'll tackle challenges spanning payment processing, fraud detection, financial compliance, and developer APIs that handle hundreds of billions of dollars annually. Stripe's engineering culture is defined by rigor, clarity, and written communication—engineers write detailed RFCs, conduct thorough code reviews, and make decisions through well-reasoned documents rather than meetings. The company believes in end-to-end ownership: engineers own their projects completely, from design through deployment and on-call support. Stripe's interview process is unique—no LeetCode grinding, instead focusing on practical problems similar to real work. Engineers work primarily in Ruby, Java, and Scala, building systems where reliability isn't optional—every millisecond of downtime directly impacts businesses and their customers. The company's mission to increase the GDP of the internet attracts engineers who want their work to have massive economic impact.`,
      responsibilities: [
        'Design and build scalable payment processing systems handling billions in transactions',
        'Develop APIs that millions of developers use to build businesses',
        'Build fraud detection and risk systems protecting merchants and cardholders',
        'Create financial products for invoicing, billing, subscriptions, and treasury',
        'Write detailed technical documents and RFCs for major decisions',
        'Own services end-to-end including design, deployment, monitoring, and on-call',
        'Participate in thorough code reviews maintaining Stripe\'s high bar',
        'Collaborate with product, design, and business teams on complex financial products',
        'Ensure reliability and security for systems processing sensitive financial data'
      ],
      growthOpportunities: [
        'Progress through IC levels from L2 to Staff (L5) and Principal (L6+) Engineer',
        'Transition into engineering management while maintaining technical depth',
        'Specialize in areas like payments, infrastructure, ML, or security',
        'Lead cross-team technical initiatives with company-wide impact',
        'Contribute to Stripe\'s technical blog and open-source projects',
        'Shape technical strategy through the RFC process',
        'Build expertise in financial systems and regulatory compliance',
        'Work on new products from zero to launch'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '30-minute conversation about background, experience, and interest in Stripe' },
        { stage: 'Technical Phone Screen', description: '60-minute practical coding interview focusing on real-world problems, not LeetCode' },
        { stage: 'Onsite - Coding Interview', description: '60-minute interview building features similar to Stripe\'s actual work' },
        { stage: 'Onsite - Bug Bash', description: '60-minute debugging session working through real codebases to find and fix issues' },
        { stage: 'Onsite - System Design', description: '60-minute design of payment or financial systems at scale' },
        { stage: 'Onsite - Integration', description: '45-minute session building with APIs similar to Stripe\'s developer experience' },
        { stage: 'Onsite - Manager/Cultural', description: '45-minute behavioral interview assessing rigor, ownership, and cultural fit' }
      ],
      technicalQuestions: [
        'Design a payment processing system that handles millions of transactions daily',
        'How would you build an idempotent API for payment retries?',
        'Design a fraud detection system that balances false positives with catching fraud',
        'How would you implement a subscription billing system with complex pricing?',
        'Design a ledger system for tracking money movement across accounts',
        'How would you build a webhook delivery system with guaranteed delivery?',
        'Design an API versioning strategy for breaking changes',
        'How would you implement rate limiting that\'s fair to all customers?',
        'Design a system for handling multi-currency transactions',
        'How would you build a reconciliation system for payments?',
        'Design a dispute/chargeback handling system',
        'How would you implement PCI compliance in a payment system?',
        'Design a real-time risk scoring system for transactions',
        'How would you build a developer dashboard showing API usage?',
        'Design a system for handling payment method tokenization',
        'How would you implement graceful degradation when payment processors fail?'
      ],
      behavioralQuestions: [
        'Tell me about a system you built that required extreme reliability',
        'Describe a time you wrote a technical document that influenced a major decision',
        'How have you handled on-call incidents for critical systems?',
        'Tell me about debugging a complex distributed systems issue',
        'Describe your experience with code review—giving and receiving',
        'How have you balanced moving fast with maintaining quality?',
        'Tell me about owning a project end-to-end',
        'Describe working on systems where failure directly impacts customers financially',
        'How have you approached learning a new codebase or domain?',
        'Tell me about a time you pushed back on a technical decision',
        'Describe simplifying a complex system or process',
        'How have you communicated technical trade-offs to non-technical stakeholders?',
        'Tell me about building for scale before you had the traffic',
        'Describe mentoring other engineers or elevating team practices'
      ],
      whatTheyLookFor: [
        'Strong fundamentals in systems and distributed computing',
        'Experience building reliable, scalable systems',
        'Clear written and verbal communication',
        'End-to-end ownership mentality',
        'Rigor in code quality and technical decisions',
        'Ability to navigate ambiguity and make decisions',
        'Curiosity about financial systems and payments',
        'Collaborative approach with high standards',
        'Growth mindset with desire to learn continuously',
        'Comfort with Ruby, Java, or Scala (or ability to learn)'
      ],
      interviewTips: [
        'Prepare for practical coding, not LeetCode—Stripe values real-world skills',
        'Practice debugging unfamiliar codebases for the Bug Bash round',
        'Study payment systems, idempotency, and financial concepts',
        'Be ready to discuss how you\'d design reliable systems',
        'Prepare to write clearly—Stripe values written communication',
        'Research Stripe\'s products and API documentation',
        'Practice system design with payment/financial focus',
        'Be ready to discuss end-to-end ownership experiences',
        'Understand Stripe\'s mission to increase GDP of the internet',
        'Prepare questions about engineering culture and RFC process',
        'Review Stripe\'s engineering blog for technical insights',
        'Be authentic about both successes and failures',
        'Practice explaining complex technical concepts clearly',
        'Show curiosity about financial infrastructure'
      ],
      salary: { min: 170000, max: 300000 },
      compensation: [
        'Highly competitive base salary',
        'Significant equity grants (RSUs or options)',
        'Annual refresher grants and bonuses',
        'Comprehensive health, dental, and vision insurance',
        'Generous parental leave',
        'Flexible PTO policy',
        '401(k) with company match',
        'Wellness and mental health benefits',
        'Learning and development budget',
        'Home office stipend',
        'Commuter benefits'
      ],
      dayInLife: {
        intro: 'A day as a Software Engineer at Stripe combines deep technical work with written communication and high-ownership collaboration.',
        schedule: [
          '9:00 AM - Review overnight alerts and on-call handoff notes',
          '9:30 AM - Read and comment on RFC for new payment feature',
          '10:30 AM - Deep coding block on API improvements',
          '12:00 PM - Team lunch discussing technical challenges',
          '1:00 PM - Code review session with detailed feedback',
          '2:30 PM - Design discussion for fraud detection improvements',
          '3:30 PM - Write technical document for upcoming project',
          '4:30 PM - Pairing session on complex debugging',
          '5:30 PM - Review dashboards and prepare for tomorrow'
        ],
        closing: 'Engineering at Stripe means building infrastructure that millions of businesses depend on, with a culture that values rigor, ownership, and clear thinking.'
      },
      similarRoles: ['Senior Software Engineer at Stripe', 'Staff Engineer at Stripe', 'Infrastructure Engineer at Stripe', 'Backend Engineer at Stripe', 'Platform Engineer at Stripe']
    },

    'product-manager': {
      title: 'Product Manager',
      slug: 'product-manager',
      industry: 'Technology',
      roleDescription: `Product Managers at Stripe shape the financial infrastructure that powers millions of businesses worldwide. Working on products that process hundreds of billions of dollars annually, you'll define strategy and execution for payments, billing, fraud prevention, financial services, and developer tools. Stripe's PM culture is uniquely rigorous—decisions are made through written documents, data analysis, and clear reasoning rather than opinions or politics. PMs are expected to develop deep technical understanding and work closely with engineering as equals. The company's developer-focused DNA means PMs must think about API design, developer experience, and technical trade-offs alongside business metrics. You'll work on products ranging from core payments to emerging areas like embedded finance, crypto, and climate. Stripe's mission to increase the GDP of the internet means PM decisions have outsized impact on the global economy, enabling businesses that might not otherwise exist.`,
      responsibilities: [
        'Define product vision and strategy for payment and financial products',
        'Write detailed product specifications and requirements documents',
        'Partner with engineering to build reliable, scalable financial systems',
        'Analyze data to inform product decisions and measure impact',
        'Design developer experiences including APIs, documentation, and dashboards',
        'Navigate complex regulatory requirements across global markets',
        'Collaborate with sales, support, and business teams on go-to-market',
        'Conduct user research with businesses of all sizes',
        'Drive product launches with cross-functional coordination'
      ],
      growthOpportunities: [
        'Progress from PM to Senior PM to Product Lead roles',
        'Advance to Director and VP of Product',
        'Specialize in areas like payments, developer tools, or financial services',
        'Lead new product areas from zero to one',
        'Build and manage PM teams',
        'Shape company strategy at executive level',
        'Develop deep expertise in financial systems and regulations',
        'Work on emerging areas like embedded finance and crypto'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '30-minute conversation about PM experience and interest in Stripe' },
        { stage: 'Hiring Manager Interview', description: '45-minute deep dive into PM philosophy and past product work' },
        { stage: 'Product Design Case', description: '60-minute case designing a payment or financial product' },
        { stage: 'Analytical Interview', description: '60-minute case testing data analysis and metrics thinking' },
        { stage: 'Technical Interview', description: '45-minute discussion assessing technical depth and API thinking' },
        { stage: 'Cross-functional Interview', description: '45-minute sessions with engineering, design, and business partners' },
        { stage: 'Written Exercise', description: 'Take-home or onsite writing exercise demonstrating clear thinking' }
      ],
      technicalQuestions: [
        'Design a new payment method integration for Stripe',
        'How would you approach building a fraud prevention product for merchants?',
        'Define success metrics for Stripe\'s subscription billing product',
        'Design an embedded finance product for platforms',
        'How would you prioritize features for Stripe\'s developer dashboard?',
        'Design a product for international expansion to a new region',
        'How would you approach pricing for a new Stripe product?',
        'Design an API for a complex financial workflow',
        'How would you measure the success of Stripe\'s documentation?',
        'Design a product to help businesses with revenue recognition',
        'How would you approach building for enterprise vs. startup customers?',
        'Design a compliance product for regulated industries',
        'How would you handle a major API breaking change?',
        'Design a product for dispute management',
        'How would you approach building Stripe\'s mobile SDKs?',
        'Design a product strategy for emerging markets'
      ],
      behavioralQuestions: [
        'Tell me about a product you launched and its impact',
        'Describe making a difficult prioritization decision with data',
        'How have you worked with engineering on technical trade-offs?',
        'Tell me about a product that failed and what you learned',
        'Describe navigating regulatory or compliance requirements',
        'How have you approached building developer-focused products?',
        'Tell me about influencing without authority',
        'Describe writing a document that changed a product direction',
        'How have you balanced different customer segments?',
        'Tell me about learning a complex domain quickly',
        'Describe handling competing stakeholder priorities',
        'How have you approached product launches?',
        'Tell me about a time you pushed back on leadership',
        'Describe building products for global markets'
      ],
      whatTheyLookFor: [
        'Strong analytical and data-driven thinking',
        'Technical depth and ability to partner with engineering',
        'Excellent written communication',
        'Experience with developer or B2B products',
        'Strategic thinking with execution ability',
        'Curiosity about financial systems',
        'Rigor in decision-making',
        'User empathy across business sizes',
        'Comfort with ambiguity and complexity',
        'Collaborative approach with high standards'
      ],
      interviewTips: [
        'Prepare to write clearly—Stripe values written communication',
        'Study Stripe\'s products and API documentation thoroughly',
        'Practice product cases with payment/financial context',
        'Be ready to discuss technical trade-offs and API design',
        'Research payment industry trends and regulations',
        'Prepare metrics frameworks for financial products',
        'Understand Stripe\'s mission and customer segments',
        'Be ready for a writing exercise',
        'Show curiosity about financial infrastructure',
        'Prepare examples of developer-focused product work',
        'Practice articulating complex decisions clearly',
        'Research Stripe\'s blog and press for product insights',
        'Be authentic about both successes and failures',
        'Prepare thoughtful questions about PM culture'
      ],
      salary: { min: 180000, max: 320000 },
      compensation: [
        'Highly competitive base salary',
        'Significant equity grants',
        'Annual refresher grants and bonuses',
        'Comprehensive health, dental, and vision insurance',
        'Generous parental leave',
        'Flexible PTO policy',
        '401(k) with company match',
        'Wellness and mental health benefits',
        'Learning and development budget',
        'Home office stipend'
      ],
      dayInLife: {
        intro: 'A day as a Product Manager at Stripe balances strategic thinking with detailed execution on financial products.',
        schedule: [
          '9:00 AM - Review metrics dashboards and overnight data',
          '9:30 AM - Write product spec for upcoming feature',
          '11:00 AM - Engineering sync on technical approach',
          '12:00 PM - Lunch with design partner discussing UX',
          '1:00 PM - Customer call with enterprise merchant',
          '2:00 PM - Data analysis for pricing experiment',
          '3:00 PM - Cross-functional review of launch plan',
          '4:00 PM - Document review and feedback session',
          '5:00 PM - Stakeholder update on product progress',
          '5:30 PM - Wrap up with planning for tomorrow'
        ],
        closing: 'Product management at Stripe means building financial infrastructure that enables millions of businesses, with a culture that values rigorous thinking and clear communication.'
      },
      similarRoles: ['Senior Product Manager at Stripe', 'Product Lead at Stripe', 'Group Product Manager at Stripe', 'Technical PM at Stripe', 'Platform PM at Stripe']
    },

    'engineering-manager': {
      title: 'Engineering Manager',
      slug: 'engineering-manager',
      industry: 'Technology',
      roleDescription: `Engineering Managers at Stripe lead teams building the financial infrastructure that powers millions of businesses. The EM role at Stripe is deeply technical—managers are expected to maintain credibility through code review, architectural guidance, and hands-on problem-solving alongside people leadership. Stripe's written culture extends to management: EMs write detailed performance reviews, project proposals, and technical documents. Teams own their domains end-to-end, and EMs are responsible for both delivery excellence and engineer development. The company's high bar for quality means EMs must balance moving fast with maintaining reliability for systems processing billions in transactions. You'll work with engineers in Ruby, Java, and Scala, building payment systems, developer tools, and financial products. Stripe's mission to increase the GDP of the internet attracts EMs who want their teams' work to have massive economic impact.`,
      responsibilities: [
        'Lead, mentor, and grow a team of 5-8 engineers',
        'Maintain technical credibility through code review and architectural guidance',
        'Partner with Product and Design on roadmap and prioritization',
        'Write detailed performance reviews and development plans',
        'Drive hiring for your team with Stripe\'s high bar',
        'Own team delivery including reliability and on-call',
        'Contribute to engineering-wide initiatives and culture',
        'Navigate cross-team dependencies and technical decisions',
        'Foster an environment of rigor, ownership, and continuous learning'
      ],
      growthOpportunities: [
        'Progress to Senior EM managing multiple teams',
        'Advance to Director of Engineering',
        'Move into VP of Engineering with executive scope',
        'Transition back to IC path at Staff+ level',
        'Lead new engineering organizations',
        'Drive company-wide technical initiatives',
        'Shape engineering culture and practices',
        'Build expertise in financial systems leadership'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial discussion of management experience and interest in Stripe' },
        { stage: 'Hiring Manager Interview', description: 'Deep dive into leadership philosophy and technical background' },
        { stage: 'Technical Assessment', description: 'System design or code review demonstrating technical depth' },
        { stage: 'People Leadership Interview', description: 'Scenarios on coaching, feedback, and team development' },
        { stage: 'Cross-functional Interview', description: 'Assessment of partnership with Product and stakeholders' },
        { stage: 'Written Exercise', description: 'Writing sample demonstrating clear communication' },
        { stage: 'Executive Interview', description: 'Final round with senior engineering leader' }
      ],
      technicalQuestions: [
        'How do you balance technical debt with feature development?',
        'Describe your approach to code review as a manager',
        'How do you maintain technical credibility while managing?',
        'Walk me through a system your team owns and key decisions',
        'How do you approach architecture decisions with your team?',
        'Describe your philosophy on on-call and operational excellence',
        'How do you handle disagreements on technical approach?',
        'What\'s your approach to incident response and post-mortems?',
        'How do you evaluate engineers\' technical growth?',
        'Describe your process for technical hiring decisions',
        'How do you balance autonomy with alignment across teams?',
        'What\'s your approach to reliability in critical systems?',
        'How do you drive engineering standards?',
        'Describe handling a major production incident',
        'How do you approach capacity planning?',
        'What role does documentation play in your teams?'
      ],
      behavioralQuestions: [
        'Tell me about developing an engineer from junior to senior',
        'Describe giving difficult feedback that led to improvement',
        'How have you handled an underperformer?',
        'Tell me about a difficult termination decision',
        'Describe building team culture remotely',
        'How have you navigated competing priorities from leadership?',
        'Tell me about partnering with Product on roadmap',
        'Describe handling team disagreements',
        'How have you grown as a leader?',
        'Tell me about inheriting a struggling team',
        'Describe your approach to written communication',
        'How have you built diverse, inclusive teams?',
        'Tell me about a project that failed',
        'Describe leading through organizational change'
      ],
      whatTheyLookFor: [
        'Strong people leadership with technical credibility',
        'Experience building reliable systems at scale',
        'Excellent written communication',
        'High standards for team and code quality',
        'Track record developing engineers',
        'Cross-functional partnership abilities',
        'Strategic thinking about team building',
        'Ownership mentality for team outcomes',
        'Cultural fit with rigor and clarity values',
        'Growth mindset for continuous improvement'
      ],
      interviewTips: [
        'Prepare to demonstrate technical depth—Stripe EMs stay technical',
        'Practice writing clearly for the writing exercise',
        'Have concrete examples of developing engineers',
        'Be ready to discuss difficult management situations',
        'Research Stripe\'s engineering culture and RFC process',
        'Prepare questions about EM role and growth',
        'Show how you balance people and technical leadership',
        'Be authentic about management philosophy',
        'Prepare examples of handling reliability and incidents',
        'Understand Stripe\'s written culture deeply',
        'Show curiosity about financial systems',
        'Be ready to discuss cross-functional collaboration',
        'Practice discussing complex decisions clearly',
        'Prepare examples of building high-performing teams'
      ],
      salary: { min: 220000, max: 380000 },
      compensation: [
        'Highly competitive base salary',
        'Significant equity grants',
        'Annual refresher grants and bonuses',
        'Comprehensive health, dental, and vision insurance',
        'Generous parental leave',
        'Flexible PTO with managers modeling balance',
        '401(k) with company match',
        'Leadership development programs',
        'Executive coaching access',
        'Home office stipend'
      ],
      dayInLife: {
        intro: 'A day as an Engineering Manager at Stripe balances people leadership with technical engagement and written communication.',
        schedule: [
          '9:00 AM - Review team dashboards and on-call status',
          '9:30 AM - 1:1 with engineer on career growth',
          '10:00 AM - Code review staying connected to technical work',
          '10:30 AM - Team standup on project progress',
          '11:00 AM - Write performance review',
          '12:00 PM - Lunch with new team member',
          '1:00 PM - Cross-team technical design review',
          '2:00 PM - Hiring debrief calibrating on candidates',
          '3:00 PM - Product sync on quarterly planning',
          '4:00 PM - 1:1 coaching conversation',
          '5:00 PM - Review RFCs and technical documents',
          '5:30 PM - Prepare for tomorrow'
        ],
        closing: 'Engineering management at Stripe means building teams that create financial infrastructure for millions of businesses, with a culture that values rigor, ownership, and clear thinking.'
      },
      similarRoles: ['Senior Engineering Manager at Stripe', 'Engineering Director at Stripe', 'Staff Engineer at Stripe', 'Technical Program Manager at Stripe']
    },

    'data-scientist': {
      title: 'Data Scientist',
      slug: 'data-scientist',
      industry: 'Technology',
      roleDescription: `Data Scientists at Stripe build the models and analytics that power financial decision-making for millions of businesses. Working with one of the richest financial datasets in technology—payment transactions, fraud signals, business behaviors, and economic indicators—you'll tackle challenges spanning fraud detection, credit risk, pricing optimization, and business intelligence. Stripe's DS culture emphasizes rigor and production impact: models must work reliably at scale for systems processing hundreds of billions of dollars. Data Scientists partner closely with engineering to deploy models, with product to inform decisions, and with business teams on strategy. The company's written culture extends to DS—analyses and recommendations are documented thoroughly. You'll work on problems ranging from real-time fraud scoring to long-term economic modeling, all contributing to Stripe's mission of increasing the GDP of the internet.`,
      responsibilities: [
        'Build machine learning models for fraud detection, risk, and pricing',
        'Conduct analysis informing product and business decisions',
        'Partner with engineering to deploy models in production',
        'Design experiments and analyze A/B tests',
        'Develop metrics frameworks measuring product success',
        'Write detailed documents communicating findings and recommendations',
        'Collaborate with product teams on data-informed roadmaps',
        'Build analytics infrastructure and dashboards',
        'Research new approaches to financial ML problems'
      ],
      growthOpportunities: [
        'Progress through IC levels to Staff and Principal Data Scientist',
        'Specialize in fraud, risk, pricing, or analytics',
        'Transition into Data Science management',
        'Move into Product Management with DS expertise',
        'Lead cross-functional data initiatives',
        'Shape data strategy at company level',
        'Contribute to research and publications',
        'Build expertise in financial ML systems'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial conversation about DS background and interest in Stripe' },
        { stage: 'Technical Phone Screen', description: '60-minute interview on statistics, ML, and analytical thinking' },
        { stage: 'Onsite - ML Deep Dive', description: '60-minute assessment of ML expertise and model building' },
        { stage: 'Onsite - Analytical Case', description: '60-minute case testing business analysis and problem-solving' },
        { stage: 'Onsite - Coding', description: '45-minute SQL and Python coding assessment' },
        { stage: 'Onsite - Behavioral', description: '45-minute interview on collaboration and communication' },
        { stage: 'Writing Exercise', description: 'Document analysis findings clearly and concisely' }
      ],
      technicalQuestions: [
        'Design a fraud detection model for real-time transaction scoring',
        'How would you approach credit risk modeling for Stripe Capital?',
        'Build a model to predict merchant churn',
        'How would you design an experiment to test pricing changes?',
        'Design metrics to measure payment product success',
        'How would you handle class imbalance in fraud detection?',
        'Build a model for dynamic transaction limits',
        'How would you approach anomaly detection in payment patterns?',
        'Design a recommendation system for payment methods',
        'How would you measure the impact of a fraud model improvement?',
        'Build a forecasting model for transaction volume',
        'How would you approach feature engineering for financial data?',
        'Design a model for merchant categorization',
        'How would you handle concept drift in fraud models?',
        'Build a risk scoring system for new merchants',
        'How would you approach interpretability in financial ML?'
      ],
      behavioralQuestions: [
        'Tell me about a model you deployed in production',
        'Describe an analysis that changed a business decision',
        'How have you communicated complex findings to non-technical audiences?',
        'Tell me about an ML project that failed',
        'Describe partnering with engineering on production ML',
        'How have you handled ambiguous or incomplete data?',
        'Tell me about balancing rigor with speed',
        'Describe your approach to experimentation',
        'How have you influenced product decisions with data?',
        'Tell me about learning a new domain quickly',
        'Describe handling stakeholder disagreement on analysis',
        'How have you mentored other data scientists?',
        'Tell me about writing a document that drove decisions',
        'Describe building trust with cross-functional partners'
      ],
      whatTheyLookFor: [
        'Strong ML and statistics fundamentals',
        'Experience deploying models in production',
        'Excellent written communication',
        'Business acumen for financial products',
        'Coding proficiency in Python and SQL',
        'Rigor in analysis and documentation',
        'Collaborative mindset with engineering and product',
        'Curiosity about financial systems',
        'Ability to handle ambiguity',
        'Growth mindset and continuous learning'
      ],
      interviewTips: [
        'Prepare to write clearly—Stripe values documentation',
        'Study fraud detection and financial ML concepts',
        'Practice analytical cases with business context',
        'Be ready for production ML discussions',
        'Research Stripe\'s products and data challenges',
        'Prepare examples of deployed models with impact',
        'Practice explaining complex analyses simply',
        'Understand Stripe\'s mission and customer segments',
        'Be ready for a writing exercise',
        'Show curiosity about financial infrastructure',
        'Prepare questions about DS culture and growth',
        'Be authentic about both successes and failures',
        'Practice SQL and Python coding',
        'Research payment industry data challenges'
      ],
      salary: { min: 170000, max: 300000 },
      compensation: [
        'Highly competitive base salary',
        'Significant equity grants',
        'Annual refresher grants and bonuses',
        'Comprehensive health, dental, and vision insurance',
        'Generous parental leave',
        'Flexible PTO policy',
        '401(k) with company match',
        'Conference and research budget',
        'Learning and development support',
        'Home office stipend'
      ],
      dayInLife: {
        intro: 'A day as a Data Scientist at Stripe balances model development with analysis and cross-functional collaboration.',
        schedule: [
          '9:00 AM - Review model performance dashboards',
          '9:30 AM - Deep work on fraud model improvements',
          '11:00 AM - Sync with engineering on model deployment',
          '12:00 PM - Lunch with DS colleagues',
          '1:00 PM - Write analysis document for product decision',
          '2:30 PM - Experiment review meeting',
          '3:30 PM - Partner with product on metrics framework',
          '4:30 PM - Code review for teammate\'s model',
          '5:00 PM - Document findings and prepare presentation',
          '5:30 PM - Wrap up with planning'
        ],
        closing: 'Data Science at Stripe means building models that protect millions of businesses from fraud and power financial decisions, with a culture that values rigor and clear communication.'
      },
      similarRoles: ['Senior Data Scientist at Stripe', 'Staff Data Scientist at Stripe', 'ML Engineer at Stripe', 'Risk Data Scientist at Stripe', 'Analytics Lead at Stripe']
    }
