    'safety-manager': {
      title: 'Safety Manager',
      slug: 'safety-manager',
      industry: 'Technology',
      roleDescription: `Safety Managers at Lyft protect the millions of riders and drivers who use the platform daily, developing programs and policies that make transportation safer for everyone. This role combines operational excellence with policy development, working across the company to prevent incidents, respond effectively when they occur, and continuously improve safety systems. You'll lead initiatives spanning driver screening, in-app safety features, incident response, and regulatory compliance. Lyft's commitment to safety is central to its brand—riders and drivers choose Lyft because they trust they'll be protected. Safety at Lyft means balancing protection with accessibility, implementing measures that prevent harm without creating unnecessary friction. You'll partner with Product on safety features, Legal on compliance, Operations on implementation, and Government Relations on regulatory requirements. The role requires analytical thinking to identify risks, operational skills to implement solutions, and empathy to handle sensitive situations affecting real people.`,
      responsibilities: [
        'Develop and implement safety policies protecting riders and drivers',
        'Lead incident response and escalation processes for safety events',
        'Partner with Product on safety feature requirements and priorities',
        'Manage driver screening and background check programs',
        'Analyze safety data to identify trends and improvement opportunities',
        'Collaborate with Legal and Government Relations on regulatory compliance',
        'Build and train teams on safety protocols and procedures',
        'Lead crisis response for high-profile safety incidents',
        'Develop safety communications and education for users'
      ],
      growthOpportunities: [
        'Progress to Senior Safety Manager and Director roles',
        'Specialize in areas like driver safety, rider safety, or fraud prevention',
        'Move into Head of Safety with executive responsibilities',
        'Transition to Policy or Legal roles leveraging safety expertise',
        'Lead safety for new products and markets',
        'Shape industry standards for rideshare safety',
        'Build and lead safety teams'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial discussion of safety background and interest in Lyft' },
        { stage: 'Hiring Manager Interview', description: 'Deep dive into safety philosophy, experience, and problem-solving' },
        { stage: 'Case Study', description: 'Scenario-based exercise on handling safety situations' },
        { stage: 'Cross-functional Interview', description: 'Assessment of collaboration with Legal, Product, and Operations' },
        { stage: 'Leadership Interview', description: 'Discussion of crisis management and stakeholder handling' },
        { stage: 'Behavioral Interview', description: 'Values alignment and culture fit assessment' },
        { stage: 'Executive Interview', description: 'Final round with senior safety leader' }
      ],
      technicalQuestions: [
        'How would you design a driver screening program that balances safety with accessibility?',
        'Walk me through handling a high-profile safety incident',
        'How would you measure the effectiveness of a safety feature?',
        'Design a protocol for responding to in-ride emergencies',
        'How would you approach safety differently in different markets?',
        'Walk me through analyzing safety data to identify risk patterns',
        'How would you balance rider safety with driver safety?',
        'Design a safety training program for new drivers',
        'How would you communicate a safety incident to the public?',
        'Walk me through evaluating a new safety technology',
        'How would you handle a regulatory requirement that conflicts with operations?',
        'Design a framework for escalation decisions in ambiguous situations',
        'How would you measure the impact of safety programs on user trust?',
        'Walk me through developing safety protocols for autonomous vehicles',
        'How would you approach safety for vulnerable populations?',
        'Design a system for user safety reporting and response'
      ],
      behavioralQuestions: [
        'Tell me about a safety program you implemented with measurable impact',
        'Describe handling a crisis situation under pressure',
        'How have you balanced safety requirements with business needs?',
        'Tell me about a difficult decision involving user safety',
        'Describe building relationships with regulatory agencies',
        'How have you communicated sensitive safety information to stakeholders?',
        'Tell me about a safety initiative that didn\'t work as expected',
        'Describe leading a team through a challenging safety event',
        'How have you approached safety for users different from yourself?',
        'Tell me about influencing product decisions with safety concerns',
        'Describe building a culture of safety in an organization',
        'How have you handled pushback on safety requirements?',
        'Tell me about developing others in safety roles',
        'Describe managing competing priorities in safety decisions'
      ],
      whatTheyLookFor: [
        'Strong safety experience in transportation, technology, or related fields',
        'Excellent judgment in crisis situations and ambiguous scenarios',
        'Analytical skills for identifying risks and measuring impact',
        'Cross-functional collaboration with Legal, Product, and Operations',
        'Communication skills for sensitive topics and diverse audiences',
        'Strategic thinking about safety systems and programs',
        'Empathy for affected users while maintaining objectivity',
        'Alignment with Lyft\'s mission and values',
        'Resilience for emotionally challenging work',
        'Commitment to accessibility alongside safety'
      ],
      interviewTips: [
        'Research Lyft\'s public safety initiatives and features',
        'Prepare examples of safety programs with measurable outcomes',
        'Practice articulating decision frameworks for difficult situations',
        'Be ready to discuss balancing safety with accessibility',
        'Show understanding of rideshare-specific safety challenges',
        'Prepare questions about safety team structure and culture',
        'Be authentic about the challenges of safety work',
        'Show empathy while demonstrating analytical rigor',
        'Research regulatory landscape for rideshare safety',
        'Be ready to discuss crisis communication approaches',
        'Show strategic thinking beyond individual incidents',
        'Prepare examples of cross-functional collaboration',
        'Practice discussing sensitive topics professionally',
        'Be ready to discuss maintaining personal resilience'
      ],
      salary: { min: 120000, max: 200000 },
      compensation: [
        'Competitive base salary with equity (RSUs)',
        'Annual performance bonuses',
        'Lyft Pink membership (unlimited Lyft rides)',
        'Comprehensive health, dental, and vision coverage including mental health',
        'Flexible PTO policy',
        '401(k) with company match',
        'Professional development budget',
        'Wellness and resilience support',
        'Parental leave',
        'Home office stipend'
      ],
      dayInLife: {
        intro: 'A day as a Safety Manager at Lyft balances strategic program development with responsive incident handling.',
        schedule: [
          '8:30 AM - Review overnight incident reports and escalations',
          '9:00 AM - Morning sync with safety team on priorities and active issues',
          '9:30 AM - Partner meeting with Product on upcoming safety feature',
          '10:30 AM - Analyze safety data identifying emerging patterns',
          '11:30 AM - Call with Legal on regulatory compliance requirements',
          '12:00 PM - Lunch with cross-functional partners',
          '1:00 PM - Case review calibration on escalated incidents',
          '2:30 PM - Policy development work on new screening guidelines',
          '3:30 PM - Cross-functional sync with Operations on implementation',
          '4:30 PM - Strategic planning for upcoming quarter',
          '5:30 PM - Wrap up with incident monitoring check'
        ],
        closing: 'Safety at Lyft is demanding but meaningful work—ensuring millions of rides happen safely every day and maintaining the trust that makes the platform possible.'
      },
      similarRoles: ['Senior Safety Manager at Lyft', 'Safety Director at Lyft', 'Trust & Safety Manager at Lyft', 'Risk Manager at Lyft', 'Security Manager at Lyft']
    },

    'business-development-manager': {
      title: 'Business Development Manager',
      slug: 'business-development-manager',
      industry: 'Technology',
      roleDescription: `Business Development Managers at Lyft build and manage partnerships that expand Lyft's reach and create value for riders, drivers, and partners. Working across industries including healthcare, hospitality, enterprise, and entertainment, you'll develop relationships that integrate Lyft transportation into partners' ecosystems. This role combines strategic thinking with relationship management—identifying opportunities, structuring deals, and ensuring partnerships deliver results. Lyft's business development is distinctive because transportation touches nearly every industry; partners range from hospitals transporting patients to arenas moving fans to enterprises providing employee benefits. You'll work closely with Product on partner integrations, Operations on implementation, and Legal on deal structure. The role requires understanding partners' businesses deeply, crafting solutions that address their needs while advancing Lyft's strategic priorities.`,
      responsibilities: [
        'Identify and develop strategic partnerships expanding Lyft\'s market reach',
        'Build and maintain relationships with partner executives and stakeholders',
        'Structure partnership deals including commercial terms and integration requirements',
        'Partner with Product on partner integration features and APIs',
        'Collaborate with Operations on partnership implementation and success',
        'Manage partnership performance and optimize for growth',
        'Develop industry expertise in assigned verticals',
        'Present partnership opportunities to leadership',
        'Coordinate with Legal on contract negotiations'
      ],
      growthOpportunities: [
        'Progress to Senior BD Manager and Director roles',
        'Specialize in verticals like healthcare, enterprise, or hospitality',
        'Move into Head of Business Development',
        'Transition to General Management with P&L responsibility',
        'Lead new market or product expansion through partnerships',
        'Move into corporate development or M&A',
        'Build and lead BD teams'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial discussion of BD experience and interest in Lyft' },
        { stage: 'Hiring Manager Interview', description: 'Deep dive into partnership experience and deal structuring' },
        { stage: 'Case Study', description: 'Partnership strategy exercise for relevant vertical' },
        { stage: 'Cross-functional Interview', description: 'Assessment of collaboration with Product, Operations, and Legal' },
        { stage: 'Role Play', description: 'Partnership pitch or negotiation simulation' },
        { stage: 'Behavioral Interview', description: 'Values alignment and relationship-building assessment' },
        { stage: 'Leadership Interview', description: 'Final round with BD or business leader' }
      ],
      technicalQuestions: [
        'How would you approach developing partnerships in the healthcare vertical?',
        'Walk me through structuring a partnership deal with a major hotel chain',
        'How would you prioritize partnership opportunities with limited resources?',
        'Design a partnership program for enterprise employee transportation',
        'How would you measure partnership success and ROI?',
        'Walk me through evaluating a potential partner\'s fit with Lyft',
        'How would you handle a partnership that\'s underperforming?',
        'Design an integration approach for a major partner API',
        'How would you approach a partnership renewal negotiation?',
        'Walk me through developing a new vertical for partnerships',
        'How would you balance partner needs with Lyft\'s strategic priorities?',
        'Design a partnership go-to-market strategy',
        'How would you approach competitive partnerships?',
        'Walk me through presenting a partnership opportunity to leadership',
        'How would you structure incentives in a partnership agreement?',
        'Design a partner success program ensuring long-term value'
      ],
      behavioralQuestions: [
        'Tell me about a partnership you developed from scratch to launch',
        'Describe negotiating a complex deal with challenging terms',
        'How have you built relationships with senior executives?',
        'Tell me about a partnership that didn\'t work and what you learned',
        'Describe managing a partner relationship through difficulties',
        'How have you balanced multiple partnership priorities?',
        'Tell me about influencing internal stakeholders for partnership support',
        'Describe developing expertise in a new industry vertical',
        'How have you approached partnerships with competitors?',
        'Tell me about a creative partnership structure you developed',
        'Describe working with product teams on partner integrations',
        'How have you handled partner expectations that exceeded capacity?',
        'Tell me about turning around an underperforming partnership',
        'Describe building a partnership team or function'
      ],
      whatTheyLookFor: [
        'Strong BD track record with complex partnership deals',
        'Excellent relationship-building skills at executive level',
        'Strategic thinking about partnership opportunities and fit',
        'Deal structuring and negotiation expertise',
        'Cross-functional collaboration with Product, Ops, and Legal',
        'Industry knowledge in relevant verticals',
        'Communication skills for diverse stakeholders',
        'Alignment with Lyft\'s mission and values',
        'Execution ability to move from strategy to implementation',
        'Creativity in developing partnership solutions'
      ],
      interviewTips: [
        'Research Lyft\'s existing partnerships and verticals',
        'Prepare examples of partnerships with measurable outcomes',
        'Practice articulating deal structures and terms',
        'Be ready to discuss industry verticals relevant to Lyft',
        'Show understanding of transportation\'s role in different industries',
        'Prepare questions about BD team structure and priorities',
        'Practice partnership pitches and negotiation scenarios',
        'Show strategic thinking about partnership opportunities',
        'Research competitive partnership landscape',
        'Be ready to discuss handling partnership challenges',
        'Show cross-functional collaboration experience',
        'Prepare examples of executive relationship building',
        'Practice presenting partnership cases clearly',
        'Be authentic about both successes and failures'
      ],
      salary: { min: 130000, max: 220000 },
      compensation: [
        'Competitive base salary with equity (RSUs)',
        'Performance bonuses tied to partnership metrics',
        'Lyft Pink membership (unlimited Lyft rides)',
        'Comprehensive health, dental, and vision insurance',
        'Flexible PTO policy',
        '401(k) with company match',
        'Professional development budget',
        'Travel budget for partner meetings',
        'Parental leave',
        'Home office stipend'
      ],
      dayInLife: {
        intro: 'A day as a Business Development Manager at Lyft balances strategic opportunity development with partner relationship management.',
        schedule: [
          '9:00 AM - Review partnership performance dashboards and metrics',
          '9:30 AM - Team standup on active deals and priorities',
          '10:00 AM - Call with potential healthcare partner exploring integration',
          '11:00 AM - Internal meeting with Product on partner API requirements',
          '12:00 PM - Lunch with existing partner contact for relationship building',
          '1:30 PM - Deal structuring session with Legal on contract terms',
          '2:30 PM - Partnership opportunity analysis for new vertical',
          '3:30 PM - Cross-functional sync with Operations on partnership launch',
          '4:30 PM - Prepare presentation for leadership on pipeline update',
          '5:00 PM - Follow-up emails with partners and stakeholders',
          '5:30 PM - Wrap up with next-day prep'
        ],
        closing: 'Business Development at Lyft means building partnerships that expand how and where people access transportation, connecting Lyft with industries that benefit from mobility solutions.'
      },
      similarRoles: ['Senior BD Manager at Lyft', 'Strategic Partnerships Manager at Lyft', 'Enterprise Sales Manager at Lyft', 'Healthcare Partnerships Lead at Lyft', 'Corporate Development at Lyft']
    },

    'finance-analyst': {
      title: 'Finance Analyst',
      slug: 'finance-analyst',
      industry: 'Technology',
      roleDescription: `Finance Analysts at Lyft provide the financial insights and analysis that drive strategic decision-making for this transportation marketplace. Working with complex marketplace economics—driver incentives, pricing dynamics, and market-by-market performance—you'll help leaders understand business performance and make investment decisions. Lyft's finance function is sophisticated and strategic; analysts are true business partners who influence decisions rather than simply report numbers. The role requires understanding the unique economics of a two-sided marketplace: every incentive affects both rider demand and driver supply, often with complex interactions. You'll work on challenges spanning market profitability analysis, incentive ROI, budget planning, and investor relations support. As a public company, Lyft's finance team plays a critical role in governance and accountability while still maintaining the agility to support a dynamic business.`,
      responsibilities: [
        'Build financial models analyzing market performance and profitability',
        'Partner with operations teams to develop budgets and forecasts',
        'Analyze marketplace economics including incentive effectiveness',
        'Support monthly and quarterly business reviews with financial insights',
        'Evaluate investment opportunities and ROI for market initiatives',
        'Develop dashboards and reports for financial performance monitoring',
        'Collaborate with Accounting on close processes',
        'Support investor relations with financial data and analysis',
        'Identify opportunities for financial process improvement'
      ],
      growthOpportunities: [
        'Progress to Senior Finance Analyst and Manager levels',
        'Move into FP&A leadership overseeing major business areas',
        'Transition to Strategic Finance or Corporate Development',
        'Become Finance Business Partner embedded with operations',
        'Lead investor relations or treasury functions',
        'Move into operations roles leveraging financial expertise',
        'Build finance teams as a people manager'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial discussion of finance background and interest in Lyft' },
        { stage: 'Hiring Manager Interview', description: 'Deep dive into analytical skills and business acumen' },
        { stage: 'Technical Assessment', description: 'Financial modeling exercise testing analytical skills' },
        { stage: 'Case Study', description: 'Business analysis case testing strategic thinking' },
        { stage: 'Cross-functional Interview', description: 'Assessment of business partnership skills' },
        { stage: 'Behavioral Interview', description: 'Values alignment assessment' },
        { stage: 'Leadership Interview', description: 'Final round with finance leader' }
      ],
      technicalQuestions: [
        'Walk me through building a market profitability model',
        'How would you analyze the ROI of driver incentive programs?',
        'Describe your approach to forecasting in a seasonal business',
        'How would you evaluate investment in a new market?',
        'Build a sensitivity analysis for key marketplace drivers',
        'How would you approach pricing analysis for ride products?',
        'Describe your process for annual budget development',
        'How would you analyze the financial impact of a product feature?',
        'Walk me through variance analysis for market performance',
        'How would you model driver economics and earnings?',
        'Describe your approach to cash flow forecasting',
        'How would you analyze customer lifetime value?',
        'Build a framework for evaluating market expansion',
        'How would you approach scenario planning for uncertainty?',
        'Describe your process for investor presentations',
        'How would you measure return on marketing investment?'
      ],
      behavioralQuestions: [
        'Tell me about a financial analysis that influenced a business decision',
        'Describe delivering unwelcome financial news to stakeholders',
        'How have you communicated complex financial concepts simply?',
        'Tell me about an analysis where you discovered errors',
        'Describe balancing analytical rigor with delivering quickly',
        'How have you partnered with operations teams effectively?',
        'Tell me about navigating ambiguity in financial planning',
        'Describe building relationships with business stakeholders',
        'How have you approached analyzing an unfamiliar business area?',
        'Tell me about improving a financial process or model',
        'Describe handling conflicting priorities from stakeholders',
        'How have you developed others in finance skills?',
        'Tell me about a strategic recommendation based on your analysis',
        'Describe managing through business uncertainty'
      ],
      whatTheyLookFor: [
        'Strong financial modeling and analytical skills',
        'Business acumen connecting finance to strategic decisions',
        'Excel/Sheets expertise for complex modeling',
        'Clear communication explaining financial concepts',
        'Strategic thinking beyond numbers',
        'Collaborative business partner mindset',
        'Intellectual curiosity about marketplace dynamics',
        'Alignment with Lyft\'s mission and values',
        'Attention to detail with big-picture perspective',
        'Growth mindset adapting to business changes'
      ],
      interviewTips: [
        'Prepare for technical modeling exercises',
        'Understand Lyft\'s business model and key financial metrics',
        'Review Lyft\'s investor relations materials and earnings',
        'Practice explaining complex analyses simply',
        'Be ready to discuss marketplace economics',
        'Prepare questions about finance team and culture',
        'Show business partnership orientation',
        'Research transportation industry financial dynamics',
        'Be ready to discuss prioritization and time management',
        'Show intellectual curiosity about Lyft\'s challenges',
        'Prepare to walk through a complex model you\'ve built',
        'Be authentic about both strengths and development areas',
        'Demonstrate attention to detail in your work',
        'Show how finance supports business decisions'
      ],
      salary: { min: 85000, max: 150000 },
      compensation: [
        'Competitive base salary with equity (RSUs)',
        'Annual performance bonuses',
        'Lyft Pink membership (unlimited Lyft rides)',
        'Comprehensive health, dental, and vision insurance',
        'Flexible PTO policy',
        '401(k) with company match',
        'Professional development and CFA support',
        'Parental leave',
        'Home office stipend',
        'Finance certification sponsorship'
      ],
      dayInLife: {
        intro: 'A day as a Finance Analyst at Lyft balances deep analytical work with business partnership.',
        schedule: [
          '8:30 AM - Review overnight market performance data',
          '9:00 AM - Team standup on financial close and priorities',
          '9:30 AM - Deep work on market profitability model',
          '11:00 AM - Business partner meeting with operations on budget',
          '12:00 PM - Lunch with finance colleagues',
          '1:00 PM - Monthly business review preparation',
          '2:30 PM - Incentive ROI analysis deep dive',
          '3:30 PM - Cross-functional planning meeting',
          '4:30 PM - Dashboard updates and reporting',
          '5:00 PM - Prep materials for leadership presentation',
          '5:30 PM - Wrap up with quick metric review'
        ],
        closing: 'Finance at Lyft means being a strategic partner helping leaders make decisions that drive the business forward in a dynamic marketplace.'
      },
      similarRoles: ['Senior Finance Analyst at Lyft', 'FP&A Analyst at Lyft', 'Strategic Finance at Lyft', 'Finance Business Partner at Lyft', 'Market Finance Analyst at Lyft']
    },

    'driver-operations-manager': {
      title: 'Driver Operations Manager',
      slug: 'driver-operations-manager',
      industry: 'Technology',
      roleDescription: `Driver Operations Managers at Lyft ensure the driver side of the marketplace thrives, managing programs that attract, retain, and support the hundreds of thousands of drivers who make Lyft possible. This role focuses on the driver experience—from onboarding and activation to earnings optimization and long-term retention. You'll work on driver incentive programs, activation campaigns, support operations, and driver communications. Lyft's commitment to treating drivers well is core to its brand differentiation; drivers choose Lyft because of how they're treated. The role requires balancing driver experience with marketplace economics, implementing programs that help drivers succeed while maintaining healthy business metrics. You'll partner with Product on driver app features, Marketing on recruitment, Data Science on analytics, and Policy on driver programs. The work has real impact on people's livelihoods—helping drivers earn more and have better experiences on the platform.`,
      responsibilities: [
        'Develop and execute driver acquisition, activation, and retention programs',
        'Manage driver incentive programs optimizing for engagement and economics',
        'Analyze driver supply and performance data to inform strategy',
        'Partner with Product on driver app improvements and features',
        'Coordinate with Marketing on driver recruitment campaigns',
        'Build and manage driver communication strategies',
        'Lead driver support operations and quality improvement',
        'Develop driver education and onboarding programs',
        'Report on driver metrics and develop improvement plans'
      ],
      growthOpportunities: [
        'Progress to Senior Driver Ops Manager and Director roles',
        'Move into Head of Driver Operations',
        'Transition to General Operations or General Management',
        'Lead driver operations for new markets or products',
        'Move into Product Management for driver experience',
        'Build and lead driver operations teams',
        'Shape company strategy for driver relations'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial discussion of operations background and interest in Lyft' },
        { stage: 'Hiring Manager Interview', description: 'Deep dive into driver operations experience and philosophy' },
        { stage: 'Case Study', description: 'Driver program design or analysis exercise' },
        { stage: 'Analytical Assessment', description: 'Data analysis testing driver metrics understanding' },
        { stage: 'Cross-functional Interview', description: 'Assessment of collaboration with Product, Marketing, and Data' },
        { stage: 'Behavioral Interview', description: 'Values alignment and driver empathy assessment' },
        { stage: 'Leadership Interview', description: 'Final round with operations leader' }
      ],
      technicalQuestions: [
        'How would you design a driver activation program for new signups?',
        'Walk me through analyzing driver churn and developing retention strategies',
        'How would you optimize driver incentive spend for ROI?',
        'Design an onboarding program that sets drivers up for success',
        'How would you approach driver communication for a major policy change?',
        'Walk me through driver segmentation for targeted programs',
        'How would you measure driver satisfaction and experience?',
        'Design a program to improve driver earnings',
        'How would you balance driver experience with marketplace economics?',
        'Walk me through investigating a drop in driver activation rates',
        'How would you approach driver operations in a competitive market?',
        'Design a driver loyalty or rewards program',
        'How would you prioritize driver improvements with limited resources?',
        'Walk me through driver supply planning for a major event',
        'How would you approach driver feedback and communication channels?',
        'Design a program to reduce driver support contact rates'
      ],
      behavioralQuestions: [
        'Tell me about a driver program you implemented with measurable impact',
        'Describe handling a driver relations crisis or complaint surge',
        'How have you used data to improve driver experience?',
        'Tell me about balancing driver needs with business requirements',
        'Describe building relationships with drivers or driver communities',
        'How have you worked with product teams on driver features?',
        'Tell me about a driver initiative that didn\'t work as planned',
        'Describe leading a team through operational challenges',
        'How have you approached understanding driver perspectives?',
        'Tell me about an unpopular decision you had to communicate to drivers',
        'Describe collaborating with marketing on driver recruitment',
        'How have you handled competing priorities in driver operations?',
        'Tell me about improving driver support operations',
        'Describe developing others in driver-focused roles'
      ],
      whatTheyLookFor: [
        'Strong operations experience with driver or supply-side focus',
        'Analytical skills for data-driven program optimization',
        'Deep empathy for drivers and their experience',
        'Cross-functional collaboration with Product, Marketing, and Data',
        'Communication skills for driver audiences',
        'Strategic thinking about driver programs and economics',
        'Execution ability to implement programs at scale',
        'Alignment with Lyft\'s mission and driver-focused values',
        'Problem-solving for complex operational challenges',
        'Balance of driver advocacy with business needs'
      ],
      interviewTips: [
        'Research Lyft\'s driver programs and value proposition',
        'Prepare examples of driver or supply-side programs',
        'Be ready to work through driver data analysis problems',
        'Show understanding of driver economics and motivations',
        'Prepare to discuss driver experience from their perspective',
        'Practice discussing program ROI and optimization',
        'Show cross-functional collaboration experience',
        'Prepare questions about driver ops team structure',
        'Be authentic about driver empathy and advocacy',
        'Research competitive driver programs and dynamics',
        'Be ready to discuss balancing driver and business needs',
        'Prepare examples of handling operational challenges',
        'Show analytical rigor alongside operational execution',
        'Be ready to discuss driver communications approaches'
      ],
      salary: { min: 95000, max: 160000 },
      compensation: [
        'Competitive base salary with equity (RSUs)',
        'Annual performance bonuses',
        'Lyft Pink membership (unlimited Lyft rides)',
        'Comprehensive health, dental, and vision insurance',
        'Flexible PTO policy',
        '401(k) with company match',
        'Professional development budget',
        'Parental leave',
        'Home office stipend',
        'Phone and connectivity stipend'
      ],
      dayInLife: {
        intro: 'A day as a Driver Operations Manager at Lyft balances program development with driver-focused execution and analysis.',
        schedule: [
          '8:30 AM - Review driver metrics dashboards and overnight issues',
          '9:00 AM - Team standup on driver programs and priorities',
          '9:30 AM - Analyze driver activation data and develop improvements',
          '10:30 AM - Partner meeting with Product on driver app features',
          '11:30 AM - Driver incentive program optimization review',
          '12:00 PM - Lunch with driver support team for feedback',
          '1:00 PM - Cross-functional sync with Marketing on recruitment',
          '2:00 PM - Develop communication plan for upcoming driver changes',
          '3:30 PM - Data Science meeting on driver segmentation analysis',
          '4:30 PM - Update driver performance report for leadership',
          '5:00 PM - Review driver support trends and escalations',
          '5:30 PM - Wrap up with driver supply check for evening'
        ],
        closing: 'Driver Operations at Lyft means directly impacting the livelihoods of hundreds of thousands of drivers while building the supply that makes reliable transportation possible.'
      },
      similarRoles: ['Senior Driver Ops Manager at Lyft', 'Driver Experience Manager at Lyft', 'Supply Operations Manager at Lyft', 'Driver Success Manager at Lyft', 'Fleet Operations Manager at Lyft']
    }
