    'host-experience-manager': {
      title: 'Host Experience Manager',
      slug: 'host-experience-manager',
      industry: 'Technology',
      roleDescription: `Host Experience Managers at Airbnb ensure the millions of hosts who share their homes have the tools, support, and community they need to succeed. This unique role sits at the intersection of operations, product, and community building, directly embodying the "Be a Host" value that defines Airbnb's culture. You'll lead programs that support hosts throughout their journey—from first listing creation through becoming superhost status. The role requires understanding diverse host motivations: some host for supplemental income, others to meet travelers, and still others to share their local culture. You'll analyze host success metrics, develop education and training programs, manage community initiatives, and partner with Product to advocate for host needs in feature development. Airbnb's two-sided marketplace means every decision affects both hosts and guests, and your role is ensuring host perspectives are represented. The work is deeply meaningful—helping people around the world successfully share their homes and creating the supply that makes Airbnb's mission possible.`,
      responsibilities: [
        'Develop and manage programs that improve host success and satisfaction',
        'Analyze host metrics to identify opportunities for education and support',
        'Create training content and resources for hosts at different experience levels',
        'Build and nurture host community programs including meetups and online forums',
        'Partner with Product teams to advocate for host needs in feature development',
        'Manage host communication strategies for product launches and policy changes',
        'Work with support teams to improve host issue resolution',
        'Develop superhost program initiatives and recognition',
        'Lead research to understand host motivations and pain points across markets'
      ],
      growthOpportunities: [
        'Progress to Senior and Director levels in Host Experience',
        'Move into Product Management for host-focused products',
        'Transition to General Management overseeing broader marketplace operations',
        'Lead regional Host Experience programs across markets',
        'Build and lead high-performing Host Experience teams',
        'Shape company strategy for host relations and community',
        'Move into executive roles in Operations or Community'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial discussion of background, experience, and interest in host-facing work' },
        { stage: 'Hiring Manager Interview', description: 'Deep dive into host experience philosophy and program management skills' },
        { stage: 'Case Study', description: 'Scenario-based exercise developing a host support initiative' },
        { stage: 'Cross-functional Interview', description: 'Assessment of partnership skills with Product, Marketing, and Support' },
        { stage: 'Stakeholder Interview', description: 'Discussion with partner teams on collaboration approach' },
        { stage: 'Core Values Interview', description: 'Behavioral assessment focused on Airbnb\'s four core values, especially "Be a Host"' },
        { stage: 'Leadership Interview', description: 'Final round discussing strategy and organizational fit' }
      ],
      technicalQuestions: [
        'How would you design an onboarding program for new hosts?',
        'Describe your approach to measuring host success and satisfaction',
        'How would you prioritize which host segments to focus on?',
        'Design a program to reduce host churn in their first year',
        'How would you approach communicating a major policy change to hosts?',
        'Describe your strategy for building host community engagement',
        'How would you balance host needs with guest experience?',
        'Design a superhost recognition program that motivates quality',
        'How would you approach understanding host needs across different cultures?',
        'Describe your framework for developing host education content',
        'How would you measure the ROI of a host support program?',
        'Design a feedback system to capture host input for product development',
        'How would you handle a host community crisis or major complaint?',
        'Describe your approach to scaling host programs globally',
        'How would you partner with Product on a host-facing feature?',
        'Design a program to help hosts improve their listing quality'
      ],
      behavioralQuestions: [
        'Tell me about a program you created that significantly improved customer experience',
        'Describe a time you advocated for customer needs against business pressure',
        'How have you championed a mission that required changing organizational behavior?',
        'Tell me about a time you embraced adventure with an unconventional program approach',
        'Describe a creative solution to a customer experience challenge (Be a Cereal Entrepreneur)',
        'How have you embodied "Be a Host" in your previous work?',
        'Tell me about handling negative feedback from a community you serve',
        'How have you built trust with a diverse community of stakeholders?',
        'Describe a program that didn\'t succeed and what you learned',
        'How have you approached serving users very different from yourself?',
        'Tell me about leading through a crisis affecting your community',
        'How have you developed team members in customer-facing roles?',
        'Describe building inclusive community programs',
        'Tell me about balancing multiple stakeholder needs'
      ],
      whatTheyLookFor: [
        'Deep customer empathy and genuine passion for host success',
        'Program management skills developing and scaling initiatives',
        'Data fluency measuring program impact and identifying opportunities',
        'Strong communication for diverse host audiences globally',
        'Community building experience nurturing engaged user groups',
        'Cross-functional collaboration with Product, Marketing, and Support',
        'Strategic thinking connecting programs to business outcomes',
        'Alignment with Airbnb\'s mission and especially "Be a Host" value',
        'Cultural sensitivity for working with hosts worldwide',
        'Growth mindset with adaptability to changing needs'
      ],
      interviewTips: [
        'Use Airbnb as a host if possible—this experience is invaluable',
        'Research Airbnb\'s host programs including superhost criteria',
        'Prepare examples of programs you\'ve built with measurable impact',
        'Have specific examples demonstrating each of Airbnb\'s four core values',
        'Be ready to discuss serving diverse customer segments',
        'Show understanding of two-sided marketplace dynamics',
        'Prepare questions about host team culture and current challenges',
        'Be authentic about your passion for customer experience',
        'Show data fluency in measuring program success',
        'Research host community forums to understand real host concerns',
        'Prepare to discuss handling difficult community situations',
        'Show strategic thinking beyond individual programs',
        'Be ready to discuss cross-functional partnership experiences',
        'Demonstrate genuine curiosity about host motivations'
      ],
      salary: { min: 130000, max: 210000 },
      compensation: [
        'Competitive base salary with equity grants (RSUs)',
        'Annual performance bonuses',
        '$2,000 annual travel credit for Airbnb stays and Experiences',
        'Comprehensive health, dental, and vision insurance',
        'Generous parental leave (up to 22 weeks)',
        'Flexible PTO policy',
        '401(k) with company match',
        'Professional development budget',
        'Host community event budget',
        'Home office setup stipend'
      ],
      dayInLife: {
        intro: 'A day as a Host Experience Manager at Airbnb balances strategic program development with direct connection to the host community.',
        schedule: [
          '9:00 AM - Review host feedback and community forum discussions',
          '9:30 AM - Team standup on current initiatives and host issues',
          '10:00 AM - Partner meeting with Product on upcoming host-facing feature',
          '11:00 AM - Analyze host success metrics and identify improvement areas',
          '12:00 PM - Virtual host meetup with superhosts sharing best practices',
          '1:00 PM - Lunch brainstorming new host education content ideas',
          '2:00 PM - Work on host communication for upcoming policy change',
          '3:30 PM - Cross-functional sync with Support on host issue trends',
          '4:30 PM - Review host survey results with research team',
          '5:00 PM - Prep materials for tomorrow\'s host advisory board meeting',
          '5:30 PM - Wrap up with community monitoring check'
        ],
        closing: 'Host Experience at Airbnb means directly enabling the people who make the platform possible, building the supply that helps travelers belong anywhere in the world.'
      },
      similarRoles: ['Senior Host Experience Manager at Airbnb', 'Host Success Lead at Airbnb', 'Community Manager at Airbnb', 'Host Operations Manager at Airbnb', 'Host Programs Lead at Airbnb']
    },

    'marketing-manager': {
      title: 'Marketing Manager',
      slug: 'marketing-manager',
      industry: 'Technology',
      roleDescription: `Marketing Managers at Airbnb drive brand awareness, user acquisition, and engagement for one of the most recognized brands in travel and hospitality. Working on campaigns that inspire people to belong anywhere, you'll combine creative storytelling with data-driven performance optimization. Airbnb's marketing is distinctive—focusing less on traditional promotion and more on showcasing the authentic experiences hosts and guests create together. The company's brand values emphasize belonging, community, and the magic of travel, and marketing campaigns must embody these while driving measurable business results. You'll work across channels including digital, social, content, partnerships, and traditional media, managing campaigns from strategy through execution and optimization. Airbnb's two-sided marketplace means marketing must speak to both hosts and guests, often with different messages and channels. The global nature of the platform requires cultural sensitivity and localization expertise. Teams are collaborative and creative, with significant autonomy to experiment and innovate within brand guidelines.`,
      responsibilities: [
        'Develop and execute marketing campaigns that drive user acquisition and engagement',
        'Manage multi-channel marketing programs across digital, social, content, and partnerships',
        'Analyze campaign performance and optimize for ROI and key business metrics',
        'Collaborate with Creative teams on campaign concepts and content development',
        'Partner with Product Marketing on launches and feature adoption',
        'Develop marketing strategies for specific user segments, regions, or use cases',
        'Manage agency relationships and external partners',
        'Coordinate with international teams on localized marketing execution',
        'Build brand awareness while maintaining Airbnb\'s distinctive voice'
      ],
      growthOpportunities: [
        'Progress to Senior Marketing Manager and Director roles',
        'Specialize in areas like brand, performance, content, or partnerships',
        'Move into Head of Marketing for regions or verticals',
        'Transition to Product Marketing or Brand Strategy',
        'Lead new marketing initiatives for emerging products like Experiences',
        'Build and lead high-performing marketing teams',
        'Shape company marketing strategy at executive level'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial discussion of marketing experience and interest in Airbnb' },
        { stage: 'Hiring Manager Interview', description: 'Deep dive into marketing philosophy, campaign experience, and team fit' },
        { stage: 'Case Study', description: 'Marketing strategy exercise for Airbnb-relevant challenge' },
        { stage: 'Cross-functional Interview', description: 'Assessment of collaboration with Creative, Product, and Analytics' },
        { stage: 'Presentation Round', description: 'Present past campaign demonstrating strategy, execution, and results' },
        { stage: 'Core Values Interview', description: 'Behavioral assessment of alignment with Airbnb\'s four core values' },
        { stage: 'Leadership Interview', description: 'Final round with senior marketing leader on strategy and fit' }
      ],
      technicalQuestions: [
        'Design a marketing campaign to acquire hosts in a new market',
        'How would you measure marketing attribution across channels?',
        'Describe your approach to balancing brand marketing with performance',
        'How would you market Airbnb to travelers who haven\'t used the platform?',
        'Design a campaign to increase repeat booking rates',
        'How would you approach marketing differently in various cultural contexts?',
        'Describe your framework for allocating marketing budget across channels',
        'How would you market Airbnb Experiences to existing guests?',
        'Design a content strategy that builds brand while driving engagement',
        'How would you approach influencer partnerships for Airbnb?',
        'Describe your process for campaign optimization during flight',
        'How would you market to hosts who have become inactive?',
        'Design a marketing approach for seasonal travel demand',
        'How would you balance global brand consistency with local relevance?',
        'Describe your approach to A/B testing in marketing campaigns',
        'How would you measure the impact of brand marketing on business outcomes?'
      ],
      behavioralQuestions: [
        'Tell me about a marketing campaign you led that exceeded targets',
        'Describe a time you had to pivot a campaign strategy based on results',
        'How have you championed a creative direction that others initially resisted?',
        'Tell me about a time you embraced adventure with an unconventional marketing approach',
        'Describe a creative marketing solution that surprised people (Be a Cereal Entrepreneur)',
        'How have you created marketing that makes people feel welcomed (Be a Host)?',
        'Tell me about handling a campaign that underperformed',
        'How have you built trust with cross-functional creative partners?',
        'Describe balancing brand integrity with performance pressure',
        'How have you marketed to audiences very different from yourself?',
        'Tell me about leading through a marketing crisis or PR challenge',
        'How have you developed team members in marketing roles?',
        'Describe building inclusive marketing that resonates broadly',
        'Tell me about managing multiple stakeholder expectations'
      ],
      whatTheyLookFor: [
        'Strong marketing track record with measurable campaign success',
        'Balance of creative thinking and data-driven optimization',
        'Brand sensibility aligned with Airbnb\'s values and voice',
        'Multi-channel expertise across digital, social, and traditional',
        'Strategic thinking connecting marketing to business outcomes',
        'Cultural sensitivity for global marketing',
        'Collaboration skills with Creative, Product, and Analytics partners',
        'Alignment with Airbnb\'s mission and core values',
        'Agility adapting to changing market conditions',
        'Passion for travel and hospitality'
      ],
      interviewTips: [
        'Study Airbnb\'s recent marketing campaigns and brand voice',
        'Prepare campaign examples with clear metrics and results',
        'Be ready to discuss both brand building and performance marketing',
        'Have specific examples demonstrating each of Airbnb\'s four core values',
        'Research Airbnb\'s target audiences and how they differ',
        'Show cultural awareness for global marketing challenges',
        'Prepare questions about marketing culture and team dynamics',
        'Be ready to present creative ideas with strategic rationale',
        'Understand Airbnb\'s competitive landscape and positioning',
        'Show genuine passion for travel and the Airbnb experience',
        'Prepare to discuss marketing measurement and attribution',
        'Be authentic in values discussions',
        'Show how you balance creativity with data',
        'Research Airbnb\'s brand campaigns like "Made Possible by Hosts"'
      ],
      salary: { min: 130000, max: 220000 },
      compensation: [
        'Competitive base salary with equity grants (RSUs)',
        'Annual performance bonuses',
        '$2,000 annual travel credit for Airbnb stays and Experiences',
        'Comprehensive health, dental, and vision insurance',
        'Generous parental leave (up to 22 weeks)',
        'Flexible PTO policy',
        '401(k) with company match',
        'Marketing conference and professional development budget',
        'Creative tools and software access',
        'Home office setup stipend'
      ],
      dayInLife: {
        intro: 'A day as a Marketing Manager at Airbnb balances strategic planning with creative collaboration and performance optimization.',
        schedule: [
          '9:00 AM - Review overnight campaign performance dashboards',
          '9:30 AM - Team standup on active campaigns and priorities',
          '10:00 AM - Creative review meeting on new campaign concepts',
          '11:00 AM - Partner with Analytics on campaign optimization recommendations',
          '12:00 PM - Lunch with colleagues from Brand and Product Marketing',
          '1:00 PM - Agency call reviewing upcoming content production',
          '2:30 PM - Strategy session on Q4 campaign planning',
          '3:30 PM - Cross-functional sync on product launch marketing',
          '4:30 PM - Budget review and reallocation based on performance',
          '5:00 PM - Social listening and trend monitoring',
          '5:30 PM - Wrap up with campaign status updates'
        ],
        closing: 'Marketing at Airbnb means telling stories that inspire people to travel and belong, combining creative excellence with measurable business impact.'
      },
      similarRoles: ['Senior Marketing Manager at Airbnb', 'Brand Marketing Manager at Airbnb', 'Growth Marketing Manager at Airbnb', 'Content Marketing Manager at Airbnb', 'Product Marketing Manager at Airbnb']
    },

    'finance-analyst': {
      title: 'Finance Analyst',
      slug: 'finance-analyst',
      industry: 'Technology',
      roleDescription: `Finance Analysts at Airbnb provide the financial insights and analysis that enable strategic decision-making across this global travel marketplace. Working with financial data spanning 220+ countries and complex marketplace dynamics, you'll help leaders understand business performance, evaluate investments, and plan for growth. Airbnb's finance function is sophisticated and strategic—analysts are true business partners who influence decisions rather than simply reporting numbers. The role requires understanding the unique economics of a two-sided marketplace where revenue depends on both host supply and guest demand. You'll work on challenges ranging from pricing strategy analysis and investment evaluation to budget planning and investor relations support. The company's rapid evolution from startup to public company means finance plays an increasingly central role in governance and accountability. Teams use modern tools and processes, and there's significant opportunity to improve how financial analysis is conducted. Airbnb's culture emphasizes ownership and impact, and Finance is no exception.`,
      responsibilities: [
        'Build financial models and analyses to support strategic decisions',
        'Partner with business teams to develop budgets and forecasts',
        'Analyze marketplace economics including take rates, pricing, and unit economics',
        'Support monthly and quarterly business reviews with insightful analysis',
        'Evaluate investment opportunities and ROI for major initiatives',
        'Develop dashboards and reports for financial performance monitoring',
        'Collaborate with Accounting on close processes and variance analysis',
        'Support investor relations with financial data and presentations',
        'Identify opportunities for financial process improvement'
      ],
      growthOpportunities: [
        'Progress to Senior Finance Analyst and Manager levels',
        'Move into FP&A leadership overseeing major business units',
        'Transition to Strategic Finance or Corporate Development',
        'Become a Finance Business Partner embedded with product teams',
        'Lead investor relations or treasury functions',
        'Move into operations roles leveraging financial expertise',
        'Build finance teams as a people manager'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial discussion of finance background and interest in Airbnb' },
        { stage: 'Hiring Manager Interview', description: 'Deep dive into analytical skills, business acumen, and team fit' },
        { stage: 'Technical Assessment', description: 'Financial modeling exercise testing analytical and Excel skills' },
        { stage: 'Case Study', description: 'Business analysis case testing strategic thinking and financial judgment' },
        { stage: 'Cross-functional Interview', description: 'Assessment of business partnership skills with operations teams' },
        { stage: 'Core Values Interview', description: 'Behavioral assessment of alignment with Airbnb\'s four core values' },
        { stage: 'Leadership Interview', description: 'Final round with finance leader on strategy and fit' }
      ],
      technicalQuestions: [
        'Walk me through building a financial model for a new market expansion',
        'How would you analyze the unit economics of an Airbnb booking?',
        'Describe your approach to forecasting revenue in a seasonal business',
        'How would you evaluate the ROI of a major marketing investment?',
        'Build a sensitivity analysis for key business drivers',
        'How would you approach pricing analysis for marketplace take rates?',
        'Describe your process for annual budget development',
        'How would you analyze the financial impact of a new product feature?',
        'Walk me through a variance analysis framework',
        'How would you model the economics of Airbnb Experiences?',
        'Describe your approach to cash flow forecasting',
        'How would you analyze host lifetime value?',
        'Build a framework for evaluating acquisition targets',
        'How would you approach scenario planning for economic uncertainty?',
        'Describe your process for creating investor presentations',
        'How would you measure return on R&D investment?'
      ],
      behavioralQuestions: [
        'Tell me about a financial analysis that significantly influenced a business decision',
        'Describe a time you had to deliver unwelcome financial news to stakeholders',
        'How have you championed financial discipline in a growth-oriented environment?',
        'Tell me about a time you embraced adventure with an unconventional analytical approach',
        'Describe a creative financial solution others hadn\'t considered (Be a Cereal Entrepreneur)',
        'How have you gone above and beyond to support a business partner (Be a Host)?',
        'Tell me about an analysis where you later discovered errors',
        'How have you explained complex financial concepts to non-finance audiences?',
        'Describe balancing analytical rigor with delivering quickly',
        'How have you approached analyzing unfamiliar businesses or markets?',
        'Tell me about navigating ambiguity in a financial planning situation',
        'How have you developed others in finance skills?',
        'Describe building collaborative relationships with business teams',
        'Tell me about handling conflicting priorities from stakeholders'
      ],
      whatTheyLookFor: [
        'Strong financial modeling and analytical skills',
        'Business acumen connecting finance to strategic decisions',
        'Excel expertise with ability to build complex models',
        'Clear communication explaining financial concepts',
        'Strategic thinking beyond the numbers',
        'Collaborative mindset as a business partner',
        'Intellectual curiosity exploring business dynamics',
        'Alignment with Airbnb\'s mission and values',
        'Attention to detail with big-picture perspective',
        'Growth mindset adapting to evolving business needs'
      ],
      interviewTips: [
        'Prepare for technical modeling exercises in Excel or Google Sheets',
        'Understand Airbnb\'s business model and key financial metrics',
        'Review Airbnb\'s investor relations materials and earnings calls',
        'Have specific examples demonstrating each of Airbnb\'s four core values',
        'Practice explaining complex analyses simply',
        'Be ready to discuss marketplace economics',
        'Prepare questions about finance team culture and priorities',
        'Show business partnership orientation beyond number crunching',
        'Research travel industry financial dynamics',
        'Be ready to discuss how you prioritize and manage time',
        'Show intellectual curiosity about Airbnb\'s business challenges',
        'Prepare to walk through a complex model you\'ve built',
        'Be authentic in values discussions',
        'Demonstrate attention to detail in your work'
      ],
      salary: { min: 100000, max: 170000 },
      compensation: [
        'Competitive base salary with equity grants (RSUs)',
        'Annual performance bonuses',
        '$2,000 annual travel credit for Airbnb stays and Experiences',
        'Comprehensive health, dental, and vision insurance',
        'Generous parental leave (up to 22 weeks)',
        'Flexible PTO policy',
        '401(k) with company match',
        'Professional development and CFA support',
        'Finance certification sponsorship',
        'Home office setup stipend'
      ],
      dayInLife: {
        intro: 'A day as a Finance Analyst at Airbnb balances deep analytical work with collaborative business partnership.',
        schedule: [
          '8:30 AM - Review overnight booking and revenue trends',
          '9:00 AM - Team standup on financial close and analysis priorities',
          '9:30 AM - Deep work on financial model for new initiative evaluation',
          '11:00 AM - Business partner meeting with marketing on budget review',
          '12:00 PM - Lunch with finance colleagues discussing career paths',
          '1:00 PM - Monthly business review prep with operations team',
          '2:30 PM - Variance analysis deep dive on regional performance',
          '3:30 PM - Cross-functional planning meeting for next quarter',
          '4:30 PM - Dashboard updates and reporting refinements',
          '5:00 PM - Prep materials for tomorrow\'s leadership presentation',
          '5:30 PM - Wrap up with quick metric monitoring'
        ],
        closing: 'Finance at Airbnb means being a strategic partner who helps leaders make decisions that enable millions of people to belong anywhere.'
      },
      similarRoles: ['Senior Finance Analyst at Airbnb', 'FP&A Analyst at Airbnb', 'Strategic Finance Analyst at Airbnb', 'Business Finance Manager at Airbnb', 'Finance Business Partner at Airbnb']
    },

    'policy-manager': {
      title: 'Policy Manager',
      slug: 'policy-manager',
      industry: 'Technology',
      roleDescription: `Policy Managers at Airbnb shape the rules and standards that enable millions of hosts and guests to connect safely and fairly. This role sits at the intersection of trust, legal, product, and public affairs, developing policies that protect users while preserving the openness that makes Airbnb magical. You'll work on challenges like community standards, content moderation, host requirements, and guest protections—decisions with real-world impact on people's lives and livelihoods. Airbnb operates in a complex regulatory environment with different rules in 220+ countries, and policy must balance global consistency with local compliance. The role requires navigating tensions between safety and accessibility, host rights and guest expectations, company interests and community trust. Policy Managers partner closely with Legal on regulatory requirements, with Product on enforcement mechanisms, and with Trust & Safety on implementation. The work is intellectually challenging, requiring rigorous analysis and clear writing to articulate complex trade-offs. Policy decisions at Airbnb directly enable or constrain how hosts share their homes and guests experience travel.`,
      responsibilities: [
        'Develop and refine community policies for hosts, guests, and listings',
        'Partner with Legal to ensure policy compliance with global regulations',
        'Work with Product teams to translate policy into enforceable rules',
        'Analyze policy effectiveness and iterate based on data and feedback',
        'Collaborate with Trust & Safety on policy implementation and escalations',
        'Research industry best practices and emerging regulatory trends',
        'Draft clear policy documentation for internal and external audiences',
        'Lead stakeholder alignment on complex policy decisions',
        'Support public affairs on government and regulatory engagement'
      ],
      growthOpportunities: [
        'Progress to Senior Policy Manager and Director roles',
        'Specialize in areas like content, safety, accessibility, or regulatory',
        'Move into Head of Policy for regions or policy domains',
        'Transition to Legal, Public Affairs, or Trust & Safety leadership',
        'Lead policy for new products and markets',
        'Shape industry standards through external engagement',
        'Build and lead policy teams'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial discussion of policy background and interest in Airbnb' },
        { stage: 'Hiring Manager Interview', description: 'Deep dive into policy philosophy, analytical skills, and team fit' },
        { stage: 'Policy Case Study', description: 'Scenario-based exercise analyzing and recommending policy approach' },
        { stage: 'Writing Exercise', description: 'Assessment of ability to draft clear policy documentation' },
        { stage: 'Cross-functional Interview', description: 'Discussion with Legal, Product, and Trust & Safety partners' },
        { stage: 'Core Values Interview', description: 'Behavioral assessment of alignment with Airbnb\'s four core values' },
        { stage: 'Leadership Interview', description: 'Final round with policy leader on strategy and fit' }
      ],
      technicalQuestions: [
        'How would you develop a policy for handling discriminatory host behavior?',
        'Describe your framework for balancing host autonomy with guest safety',
        'How would you approach policy harmonization across different regulatory regimes?',
        'Design a policy for handling fraudulent listings',
        'How would you measure whether a policy is achieving its goals?',
        'Describe your approach to gathering input on a controversial policy change',
        'How would you balance policy consistency with cultural differences?',
        'Design a guest protection policy that doesn\'t overly burden hosts',
        'How would you approach accessibility requirements in host policies?',
        'Describe your process for drafting policy documentation',
        'How would you handle a policy that\'s technically compliant but creates bad outcomes?',
        'Design an appeals process for policy enforcement decisions',
        'How would you approach a policy that helps one side of the marketplace but hurts another?',
        'Describe your framework for policy prioritization',
        'How would you communicate a major policy change to the community?',
        'Design a policy for emerging technologies like smart locks or cameras'
      ],
      behavioralQuestions: [
        'Tell me about a policy you developed that balanced competing interests',
        'Describe a time you had to change a policy based on unintended consequences',
        'How have you championed a policy position that faced internal resistance?',
        'Tell me about a time you embraced adventure with an unconventional policy approach',
        'Describe a creative policy solution that others hadn\'t considered (Be a Cereal Entrepreneur)',
        'How have you developed policies that make people feel welcomed (Be a Host)?',
        'Tell me about handling pushback on a policy decision',
        'How have you built trust with cross-functional partners?',
        'Describe a policy that didn\'t work as intended and what you learned',
        'How have you approached policy for users very different from yourself?',
        'Tell me about leading through a policy crisis',
        'How have you developed team members in policy roles?',
        'Describe building inclusive policy that works for diverse communities',
        'Tell me about navigating regulatory ambiguity'
      ],
      whatTheyLookFor: [
        'Strong analytical skills for navigating complex trade-offs',
        'Excellent writing ability for clear policy documentation',
        'Judgment and nuance for sensitive decisions',
        'Cross-functional collaboration with Legal, Product, and T&S',
        'Research skills for understanding regulatory landscape',
        'Stakeholder management for building alignment',
        'Empathy for affected communities and users',
        'Alignment with Airbnb\'s mission and core values',
        'Strategic thinking connecting policy to business and user outcomes',
        'Resilience for handling controversial decisions'
      ],
      interviewTips: [
        'Study Airbnb\'s published community standards and policies',
        'Prepare examples of policies you\'ve developed with measurable outcomes',
        'Practice writing clear, concise policy documentation',
        'Have specific examples demonstrating each of Airbnb\'s four core values',
        'Be ready to discuss balancing competing stakeholder interests',
        'Research platform governance and content moderation trends',
        'Prepare questions about policy team culture and current challenges',
        'Show understanding of regulatory complexity across jurisdictions',
        'Be ready to discuss unintended consequences of past policies',
        'Demonstrate empathy for both hosts and guests',
        'Prepare to walk through your policy development process',
        'Be authentic about navigating difficult policy trade-offs',
        'Show strategic thinking about policy\'s role in business',
        'Research recent Airbnb policy changes and their rationale'
      ],
      salary: { min: 140000, max: 230000 },
      compensation: [
        'Competitive base salary with equity grants (RSUs)',
        'Annual performance bonuses',
        '$2,000 annual travel credit for Airbnb stays and Experiences',
        'Comprehensive health, dental, and vision insurance',
        'Generous parental leave (up to 22 weeks)',
        'Flexible PTO policy',
        '401(k) with company match',
        'Professional development and conference budget',
        'Industry networking support',
        'Home office setup stipend'
      ],
      dayInLife: {
        intro: 'A day as a Policy Manager at Airbnb balances deep analytical work with cross-functional collaboration on complex decisions.',
        schedule: [
          '9:00 AM - Review overnight policy escalations and urgent issues',
          '9:30 AM - Team standup on active policy initiatives',
          '10:00 AM - Draft policy documentation for upcoming community standards update',
          '11:30 AM - Legal sync on regulatory requirements for new market',
          '12:00 PM - Lunch with colleagues from Trust & Safety and Product',
          '1:00 PM - Cross-functional review of proposed policy change',
          '2:30 PM - Research industry best practices for emerging issue',
          '3:30 PM - Stakeholder input session on controversial policy question',
          '4:30 PM - One-on-one with manager on career development',
          '5:00 PM - Write summary of policy recommendation for leadership',
          '5:30 PM - Wrap up with policy monitoring check'
        ],
        closing: 'Policy at Airbnb means shaping the rules that enable safe, fair, and magical experiences for hosts and guests around the world.'
      },
      similarRoles: ['Senior Policy Manager at Airbnb', 'Policy Lead at Airbnb', 'Trust Policy Manager at Airbnb', 'Content Policy Manager at Airbnb', 'Public Policy Manager at Airbnb']
    }
