    'machine-learning-engineer': {
      title: 'Machine Learning Engineer',
      slug: 'machine-learning-engineer',
      industry: 'Technology',
      roleDescription: `Machine Learning Engineers at Spotify build the production systems that power personalization for over 600 million users. Unlike data scientists who develop experimental models, MLEs focus on building robust, scalable ML infrastructure that serves recommendations in real-time. You'll work on systems like Discover Weekly, Daily Mix, and search ranking—features that define how people experience music discovery. Spotify's ML infrastructure handles billions of predictions daily with strict latency requirements, requiring expertise in both ML and distributed systems. MLEs partner closely with Data Scientists who develop models and Backend Engineers who integrate ML into products. The role spans the full ML lifecycle: feature engineering, model training pipelines, serving infrastructure, and monitoring. Spotify invests heavily in ML infrastructure with internal platforms for experimentation, feature stores, and model deployment. Teams work on cutting-edge problems including real-time personalization, audio understanding, natural language processing for podcasts, and fairness in recommendations.`,
      responsibilities: [
        'Build production ML systems for personalization, search, and content understanding',
        'Design and maintain ML pipelines handling feature engineering, training, and serving',
        'Develop real-time prediction infrastructure meeting strict latency requirements',
        'Partner with Data Scientists to productionize experimental models',
        'Build and improve ML platform tools including feature stores and model serving',
        'Conduct A/B tests measuring model impact on user engagement',
        'Optimize models for inference efficiency and cost',
        'Collaborate with product teams on ML-powered features',
        'Contribute to ML best practices and team knowledge sharing'
      ],
      growthOpportunities: [
        'Progress through IC levels to Staff and Principal ML Engineer',
        'Specialize in areas like recommendations, NLP, audio ML, or ML infrastructure',
        'Transition into ML Platform engineering building core tools',
        'Move into Research roles for more exploratory work',
        'Lead ML architecture decisions across multiple squads',
        'Build and lead ML teams as an Engineering Manager',
        'Contribute to open source ML tools and Spotify\'s research publications',
        'Shape ML strategy for major product areas'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial call covering ML experience and interest in Spotify' },
        { stage: 'Technical Phone Screen', description: '75-minute interview combining ML fundamentals, coding, and system design' },
        { stage: 'Onsite - ML Depth', description: '60-minute deep dive into ML algorithms, training, and production systems' },
        { stage: 'Onsite - Coding', description: '60-minute algorithmic coding interview' },
        { stage: 'Onsite - ML System Design', description: '60-minute design of end-to-end ML system for audio/personalization' },
        { stage: 'Onsite - Values Interview', description: '45-minute behavioral interview assessing cultural fit' },
        { stage: 'Team Matching', description: 'Discussions with potential squads to find right fit' }
      ],
      technicalQuestions: [
        'Design the ML system powering Discover Weekly recommendations',
        'How would you build a real-time personalization system for the home feed?',
        'Design a search ranking model for songs, artists, and playlists',
        'How would you handle the cold-start problem for new users at scale?',
        'Design an ML pipeline for audio content understanding',
        'How would you build a model serving system with sub-100ms latency?',
        'Design a feature store for Spotify\'s recommendation systems',
        'How would you approach incremental model updates for personalization?',
        'Design an ML system for podcast episode recommendations',
        'How would you detect and handle concept drift in recommendation models?',
        'Design the training pipeline for a model on billions of interactions',
        'How would you approach multi-objective optimization in recommendations?',
        'Design an ML system for automatic music categorization',
        'How would you build an embedding model for songs and users?',
        'Design A/B testing infrastructure for ML model experiments',
        'How would you approach fairness in Spotify\'s recommendation systems?'
      ],
      behavioralQuestions: [
        'Tell me about an ML model you deployed in production at scale',
        'Describe choosing between model complexity and serving efficiency',
        'How have you collaborated with data scientists on production ML?',
        'Tell me about an ML project that failed and what you learned',
        'Describe debugging a production ML issue',
        'How have you communicated ML trade-offs to non-technical stakeholders?',
        'Tell me about improving an existing ML system significantly',
        'Describe your approach to monitoring models in production',
        'How have you handled disagreements about ML approaches?',
        'Tell me about working with engineers to integrate ML into products',
        'Describe balancing research exploration with production needs',
        'How have you mentored others in ML best practices?',
        'Tell me about staying current with ML research',
        'Describe a creative approach to an ML infrastructure challenge'
      ],
      whatTheyLookFor: [
        'Strong ML fundamentals with production deployment experience',
        'Excellent software engineering skills for robust systems',
        'Experience with recommendation systems and personalization',
        'Proficiency in Python and ML frameworks (TensorFlow, PyTorch)',
        'Understanding of distributed systems and data engineering',
        'Pragmatic approach balancing model quality with operational concerns',
        'Collaborative mindset for squad environment',
        'Passion for music and audio technology',
        'Cultural fit with Spotify\'s values',
        'Growth mindset with continuous learning orientation'
      ],
      interviewTips: [
        'Review recommendation system architectures and algorithms',
        'Practice ML system design with audio/personalization problems',
        'Be ready to discuss latency vs accuracy trade-offs',
        'Prepare examples of production ML with business impact',
        'Understand Spotify\'s personalization features deeply',
        'Know Spotify\'s values for the values interview',
        'Practice coding ML implementations in Python',
        'Be ready to discuss model monitoring and production issues',
        'Research Spotify\'s ML research and blog posts',
        'Show passion for music discovery and personalization',
        'Prepare questions about ML infrastructure and culture',
        'Be ready to discuss cold-start and long-tail problems',
        'Show how you balance innovation with shipping pragmatism',
        'Be authentic about both successes and failures'
      ],
      salary: { min: 170000, max: 300000 },
      compensation: [
        'Highly competitive base salary with significant equity (RSUs)',
        'Annual refresher grants and performance bonuses',
        'Spotify Premium subscription for life',
        'Comprehensive health, dental, and vision coverage',
        'Generous parental leave (6 months)',
        'Flexible PTO with minimum vacation requirements',
        '401(k) with company match',
        'Conference and research budget',
        'Learning and development support',
        'Home office stipend'
      ],
      dayInLife: {
        intro: 'A day as an ML Engineer at Spotify combines building production systems with advancing how people discover music.',
        schedule: [
          '9:30 AM - Review model performance dashboards and alerts',
          '10:00 AM - Squad standup with personalization team',
          '10:30 AM - Deep work on feature engineering for new ranking model',
          '12:00 PM - Lunch with ML colleagues discussing recent papers',
          '1:00 PM - Meeting with DS partner on productionizing new model',
          '2:00 PM - Code review for teammate\'s training pipeline',
          '3:00 PM - A/B test analysis meeting reviewing experiment results',
          '4:00 PM - Debug model serving latency issue',
          '5:00 PM - Design doc review for upcoming ML system improvement',
          '5:30 PM - Wrap up with experiment monitoring check'
        ],
        closing: 'ML Engineering at Spotify means building systems that directly improve music discovery for hundreds of millions of users, working at the intersection of cutting-edge ML and massive scale.'
      },
      similarRoles: ['Senior ML Engineer at Spotify', 'Staff ML Engineer at Spotify', 'ML Platform Engineer at Spotify', 'Research Scientist at Spotify', 'Data Scientist at Spotify']
    },

    'backend-engineer': {
      title: 'Backend Engineer',
      slug: 'backend-engineer',
      industry: 'Technology',
      roleDescription: `Backend Engineers at Spotify build the distributed systems that deliver music and audio to over 600 million users worldwide. Working on services handling billions of requests daily, you'll tackle challenges spanning audio streaming infrastructure, content delivery, playlist management, user data, and creator tools. Spotify's backend architecture is microservices-based with extensive investment in real-time processing, event-driven systems, and global content delivery. Engineers work in autonomous squads using technologies including Java, Python, Google Cloud Platform, and Spotify's internal platform tools. The company's commitment to scale is serious—backend systems must handle peak loads during new album releases and events like Spotify Wrapped. Backend Engineers partner with ML teams on serving recommendations, with mobile teams on API design, and with data teams on analytics infrastructure. The role offers opportunities to work on foundational platform services or product-focused features, all contributing to how people experience sound.`,
      responsibilities: [
        'Design and build scalable backend services handling billions of requests',
        'Develop APIs for mobile, web, and partner integrations',
        'Build audio streaming and content delivery infrastructure',
        'Collaborate in autonomous squads with product and design',
        'Ensure service reliability, performance, and observability',
        'Participate in on-call rotation supporting production services',
        'Contribute to Spotify\'s microservices platform and tooling',
        'Work with massive datasets on user behavior and content',
        'Partner with ML teams on model serving infrastructure'
      ],
      growthOpportunities: [
        'Progress through IC levels to Staff and Principal Engineer',
        'Specialize in areas like streaming, platform, or data infrastructure',
        'Transition into engineering management',
        'Lead cross-squad technical initiatives',
        'Contribute to open source and represent Spotify at conferences',
        'Shape platform strategy and architecture',
        'Work on emerging areas like live audio and creator tools',
        'Internal mobility across product and platform squads'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial conversation about background and interest in Spotify' },
        { stage: 'Technical Phone Screen', description: '75-minute interview combining coding, architecture, and behavioral' },
        { stage: 'Onsite - Coding Round 1', description: '60-minute algorithmic coding interview' },
        { stage: 'Onsite - Coding Round 2', description: '60-minute coding with focus on system implementation' },
        { stage: 'Onsite - System Design', description: '60-minute distributed systems design' },
        { stage: 'Onsite - Values Interview', description: '45-minute behavioral interview on cultural fit' },
        { stage: 'Team Matching', description: 'Discussions with potential squads' }
      ],
      technicalQuestions: [
        'Design Spotify\'s audio streaming architecture for global delivery',
        'How would you build a playlist service handling millions of playlists?',
        'Design a system for real-time play counting across millions of tracks',
        'How would you implement the follow/follower graph for artists and users?',
        'Design the content delivery system for new album releases',
        'How would you build the search indexing pipeline for all Spotify content?',
        'Design a system for managing user library and saved content',
        'How would you implement offline sync for mobile devices?',
        'Design the API gateway for Spotify\'s mobile and web clients',
        'How would you build the notification system for new releases?',
        'Design a system for handling payments and subscriptions globally',
        'How would you implement rate limiting for Spotify\'s APIs?',
        'Design the infrastructure for Spotify Wrapped statistics',
        'How would you build a service for lyrics synchronization?',
        'Design a system for real-time collaborative playlists',
        'How would you handle database scaling for user data?'
      ],
      behavioralQuestions: [
        'Tell me about designing a system that handles massive scale',
        'Describe debugging a complex distributed systems issue',
        'How have you approached service reliability and on-call?',
        'Tell me about collaborating with mobile or frontend teams',
        'Describe improving the performance of a critical system',
        'How have you balanced technical debt with feature work?',
        'Tell me about a project with high autonomy and ownership',
        'Describe working in cross-functional squads',
        'How have you approached capacity planning?',
        'Tell me about contributing to engineering culture',
        'Describe handling a production incident',
        'How have you mentored other engineers?',
        'Tell me about adopting a new technology on your team',
        'Describe making a difficult technical trade-off'
      ],
      whatTheyLookFor: [
        'Strong distributed systems and backend engineering skills',
        'Experience building services at scale',
        'Proficiency in Java, Python, or similar languages',
        'Understanding of microservices and event-driven architecture',
        'Problem-solving in ambiguous situations',
        'Collaboration skills for squad environment',
        'Passion for music and audio technology',
        'Cultural fit with Spotify\'s values',
        'Experience with cloud platforms (GCP preferred)',
        'Growth mindset and continuous learning'
      ],
      interviewTips: [
        'Practice system design with audio/streaming problems',
        'Be ready to code clean, production-quality solutions',
        'Understand Spotify\'s scale and technical challenges',
        'Know Spotify\'s values for the values interview',
        'Research Spotify\'s engineering blog',
        'Prepare examples of working with high autonomy',
        'Be ready to discuss microservices and event-driven systems',
        'Practice explaining technical decisions clearly',
        'Prepare questions about squad culture',
        'Show genuine passion for music and audio',
        'Be authentic about both successes and failures',
        'Understand the squad, chapter, tribe, guild structure',
        'Be ready to discuss on-call and operational excellence',
        'Prepare examples of cross-functional collaboration'
      ],
      salary: { min: 150000, max: 270000 },
      compensation: [
        'Competitive base salary with equity (RSUs)',
        'Annual performance bonuses and refreshers',
        'Spotify Premium subscription for life',
        'Comprehensive health, dental, and vision coverage',
        'Generous parental leave (6 months)',
        'Flexible PTO with minimum vacation',
        '401(k) with company match',
        'Learning and conference budget',
        'Home office stipend',
        'Mental health benefits'
      ],
      dayInLife: {
        intro: 'A day as a Backend Engineer at Spotify combines building scalable systems with collaborative squad work.',
        schedule: [
          '9:30 AM - Review service dashboards and overnight alerts',
          '10:00 AM - Squad standup on progress and priorities',
          '10:30 AM - Deep work on new API implementation',
          '12:00 PM - Design review for new service architecture',
          '12:30 PM - Lunch discussing favorite new music',
          '1:30 PM - Code review for teammates\' PRs',
          '2:30 PM - Pairing session on streaming optimization',
          '3:30 PM - Meeting with mobile team on API requirements',
          '4:30 PM - Incident retro for last week\'s issue',
          '5:30 PM - Wrap up deploying changes to staging'
        ],
        closing: 'Backend Engineering at Spotify means building the infrastructure that delivers music to hundreds of millions of people, working with talented squads on systems at massive scale.'
      },
      similarRoles: ['Senior Backend Engineer at Spotify', 'Staff Backend Engineer at Spotify', 'Platform Engineer at Spotify', 'Infrastructure Engineer at Spotify', 'Software Engineer at Spotify']
    },

    'content-strategist': {
      title: 'Content Strategist',
      slug: 'content-strategist',
      industry: 'Technology',
      roleDescription: `Content Strategists at Spotify shape how over 600 million users discover and engage with music, podcasts, and audio content. Working at the intersection of editorial curation, data insights, and platform features, you'll develop strategies that surface the right content to the right listeners. Spotify's content strategy spans playlist programming, genre and mood categorization, editorial features, and algorithmic content understanding. Content Strategists partner with Data Science on content recommendations, with Product on discovery features, and with Music and Podcast teams on editorial initiatives. The role requires balancing art and science—understanding cultural trends and artist narratives while using data to measure impact. Spotify's global scale means content strategy must work across cultures, languages, and listening contexts. You'll work on flagship playlists like RapCaviar and Today's Top Hits, editorial features like Spotify Sessions, and emerging formats like audiobooks and live audio.`,
      responsibilities: [
        'Develop content strategies that improve listener discovery and engagement',
        'Curate and program playlists across genres, moods, and listening contexts',
        'Partner with Data Science on content recommendation and categorization',
        'Collaborate with Product on content-focused features and experiences',
        'Analyze listening data to inform content decisions and measure impact',
        'Work with artist and label partners on content initiatives',
        'Develop editorial voice and content for Spotify\'s owned properties',
        'Identify emerging trends and cultural moments for content programming',
        'Support global content strategy working with regional teams'
      ],
      growthOpportunities: [
        'Progress to Senior Content Strategist and Lead roles',
        'Specialize in genres, formats, or regional content',
        'Move into Head of Content Strategy for major areas',
        'Transition to Product Management with content expertise',
        'Lead content strategy for new formats like audiobooks or live',
        'Shape company content direction at strategic level',
        'Build and lead content teams',
        'Represent Spotify in industry and creator relationships'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial conversation about content background and passion for music' },
        { stage: 'Hiring Manager Interview', description: 'Deep dive into content philosophy, strategy experience, and cultural knowledge' },
        { stage: 'Content Case Study', description: 'Develop content strategy for given scenario demonstrating thinking' },
        { stage: 'Cross-functional Interview', description: 'Assessment of collaboration with Product, Data, and Music teams' },
        { stage: 'Editorial/Creative Review', description: 'Discussion of music knowledge, trends, and editorial judgment' },
        { stage: 'Values Interview', description: 'Behavioral interview on cultural fit' },
        { stage: 'Leadership Interview', description: 'Final round with content leadership' }
      ],
      technicalQuestions: [
        'How would you develop a content strategy for a new genre playlist?',
        'Design a framework for categorizing songs by mood and activity',
        'How would you measure the success of a curated playlist?',
        'Develop a content strategy for breaking new artists',
        'How would you approach content programming for a major cultural moment?',
        'Design a strategy for podcast content discovery',
        'How would you balance editorial curation with algorithmic recommendations?',
        'Develop a content approach for audiobooks on Spotify',
        'How would you localize content strategy for different markets?',
        'Design a content strategy for seasonal listening (summer, holidays)',
        'How would you approach content for emerging audio formats?',
        'Develop a framework for playlist refreshes and updates',
        'How would you measure and improve playlist diversity?',
        'Design a content strategy for listener re-engagement',
        'How would you approach content for specific listening contexts?',
        'Develop a strategy for editorial content (articles, stories, features)'
      ],
      behavioralQuestions: [
        'Tell me about a content strategy you developed with measurable impact',
        'Describe using data to inform a content decision',
        'How have you collaborated with product teams on features?',
        'Tell me about identifying and capitalizing on a cultural trend',
        'Describe balancing editorial judgment with data insights',
        'How have you worked with artists or creators on content?',
        'Tell me about a content initiative that didn\'t work',
        'Describe developing content for audiences different from yourself',
        'How have you approached global content strategy?',
        'Tell me about partnering with data teams effectively',
        'Describe managing competing priorities in content',
        'How have you communicated content strategy to stakeholders?',
        'Tell me about building or leading content teams',
        'Describe your approach to staying current with music trends'
      ],
      whatTheyLookFor: [
        'Deep music and audio content knowledge across genres',
        'Strategic thinking connecting content to listener engagement',
        'Data fluency for measuring impact and informing decisions',
        'Collaboration skills for cross-functional partnership',
        'Editorial judgment balanced with analytical rigor',
        'Cultural awareness across global markets',
        'Communication skills for diverse stakeholders',
        'Passion for music discovery and creator success',
        'Cultural fit with Spotify\'s values',
        'Adaptability to evolving audio landscape'
      ],
      interviewTips: [
        'Know Spotify\'s major playlists and editorial properties',
        'Prepare a content case demonstrating strategic thinking',
        'Show deep music knowledge across genres and eras',
        'Be ready to discuss balancing art and science in content',
        'Research Spotify\'s content initiatives and recent launches',
        'Know Spotify\'s values for the values interview',
        'Prepare examples of data-informed content decisions',
        'Show awareness of cultural trends and moments',
        'Be ready to discuss global content considerations',
        'Prepare questions about content team culture',
        'Show genuine passion for music discovery',
        'Be authentic about your music tastes and knowledge',
        'Prepare to discuss emerging audio formats',
        'Show how you stay current with music and culture'
      ],
      salary: { min: 100000, max: 170000 },
      compensation: [
        'Competitive base salary with equity (RSUs)',
        'Annual performance bonuses',
        'Spotify Premium subscription for life',
        'Comprehensive health, dental, and vision coverage',
        'Generous parental leave (6 months)',
        'Flexible PTO with minimum vacation',
        '401(k) with company match',
        'Industry event access',
        'Learning and development budget',
        'Home office stipend'
      ],
      dayInLife: {
        intro: 'A day as a Content Strategist at Spotify balances cultural curation with data analysis and cross-functional collaboration.',
        schedule: [
          '9:00 AM - Review playlist performance metrics and listener feedback',
          '9:30 AM - Team standup on content priorities',
          '10:00 AM - Listen to new releases and update playlist queues',
          '11:00 AM - Meeting with Data Science on content recommendation model',
          '12:00 PM - Lunch with Music team discussing upcoming releases',
          '1:00 PM - Product review for new discovery feature',
          '2:00 PM - Develop content brief for upcoming cultural moment',
          '3:00 PM - Analyze A/B test results for playlist experiment',
          '4:00 PM - Cross-functional sync on editorial content',
          '5:00 PM - Review regional content team submissions',
          '5:30 PM - Wrap up with music discovery and planning'
        ],
        closing: 'Content Strategy at Spotify means shaping how hundreds of millions of people discover music and audio, combining cultural expertise with data-driven insights.'
      },
      similarRoles: ['Senior Content Strategist at Spotify', 'Playlist Editor at Spotify', 'Music Editor at Spotify', 'Podcast Content Strategist at Spotify', 'Editorial Manager at Spotify']
    },

    'ux-designer': {
      title: 'UX Designer',
      slug: 'ux-designer',
      industry: 'Technology',
      roleDescription: `UX Designers at Spotify create the experiences that help over 600 million users discover, listen to, and create audio. Working in autonomous squads alongside engineers and PMs, you'll design for one of the most used apps in the world across mobile, desktop, and emerging platforms. Spotify's design culture values craft, experimentation, and understanding users deeply—from casual listeners to music obsessives to podcast creators. Designers work on challenges spanning personalization interfaces, search and discovery, playback experiences, social features, and creator tools. The company's design system ensures consistency while enabling creativity for novel experiences. Spotify's global scale means designing for diverse users, contexts, and cultures—from commute listening to workout playlists to focused work sessions. The interview process evaluates both design craft and cultural fit, with emphasis on how you collaborate with cross-functional partners.`,
      responsibilities: [
        'Design intuitive experiences for music discovery, playback, and creation',
        'Conduct user research including interviews, usability testing, and data analysis',
        'Create wireframes, prototypes, and high-fidelity designs',
        'Partner with PM and Engineering in autonomous squads',
        'Contribute to and evolve Spotify\'s design system',
        'Present designs and incorporate feedback across stakeholders',
        'Design for accessibility and diverse global users',
        'Collaborate with researchers to develop deep user empathy',
        'Mentor junior designers and contribute to design culture'
      ],
      growthOpportunities: [
        'Progress through IC levels to Senior, Staff, and Principal Designer',
        'Specialize in areas like interaction, visual, motion, or research',
        'Transition into Design Management leading teams',
        'Move into Product Management with design foundation',
        'Lead design for major product initiatives',
        'Shape company design direction and strategy',
        'Represent Spotify at design conferences',
        'Work on emerging platforms and experiences'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial conversation about design background and portfolio' },
        { stage: 'Hiring Manager Call', description: 'Discussion of design philosophy and squad fit' },
        { stage: 'Portfolio Review', description: 'Detailed walkthrough of past work focusing on process' },
        { stage: 'Design Exercise', description: 'Take-home or whiteboard exercise for audio/music problem' },
        { stage: 'Onsite - Craft Review', description: 'Assessment of design skills and systems thinking' },
        { stage: 'Onsite - Cross-functional', description: 'Interviews with PM and Engineering on collaboration' },
        { stage: 'Onsite - Values Interview', description: 'Behavioral interview on cultural fit' }
      ],
      technicalQuestions: [
        'How would you redesign Spotify\'s home screen experience?',
        'Design a feature to help users discover new music genres',
        'Walk me through your design process from research to launch',
        'How would you approach designing for audio playback?',
        'Design a social feature for sharing music with friends',
        'How do you approach designing for diverse global users?',
        'Design an improved search experience for Spotify',
        'How would you design for accessibility in an audio app?',
        'Design a feature to help creators engage with listeners',
        'How do you balance consistency with innovation in design systems?',
        'Design an onboarding experience for new Spotify users',
        'How would you approach designing for different listening contexts?',
        'Design a feature to help users manage their music library',
        'How do you collaborate with engineers during implementation?',
        'Design a visualization for personal listening statistics',
        'How would you approach designing for emerging audio formats?'
      ],
      behavioralQuestions: [
        'Tell me about a design you\'re most proud of and why',
        'Describe advocating for users when stakeholders disagreed',
        'How have you used data to inform design decisions?',
        'Tell me about design feedback that changed your approach',
        'Describe collaborating with engineers on complex implementation',
        'How have you designed for users different from yourself?',
        'Tell me about a design that didn\'t work as expected',
        'Describe building inclusive design culture',
        'How have you mentored other designers?',
        'Tell me about navigating ambiguity in a design project',
        'Describe your approach to design systems',
        'How have you balanced craft with shipping quickly?',
        'Tell me about handling conflicting feedback',
        'Describe growing in your design practice'
      ],
      whatTheyLookFor: [
        'Strong portfolio demonstrating end-to-end product design',
        'User empathy and research skills',
        'Excellent collaboration with PM and Engineering',
        'Design systems thinking and craft excellence',
        'Communication skills for presenting and incorporating feedback',
        'Passion for music and audio experiences',
        'Cultural fit with Spotify\'s values',
        'Experience with mobile and multi-platform design',
        'Data-informed design approach',
        'Growth mindset and curiosity'
      ],
      interviewTips: [
        'Prepare a portfolio that tells process stories',
        'Use Spotify extensively and form opinions about the design',
        'Practice presenting designs with clear rationale',
        'Know Spotify\'s values for the values interview',
        'Research Spotify\'s design system and recent launches',
        'Be ready to discuss designing for audio experiences',
        'Show how you collaborate with PM and Engineering',
        'Prepare for design exercises with audio/music context',
        'Be authentic about your design philosophy',
        'Prepare thoughtful questions about design culture',
        'Show passion for music and discovery',
        'Be ready to discuss accessibility and inclusive design',
        'Practice articulating design trade-offs',
        'Show how you use data alongside design intuition'
      ],
      salary: { min: 130000, max: 230000 },
      compensation: [
        'Competitive base salary with equity (RSUs)',
        'Annual performance bonuses',
        'Spotify Premium subscription for life',
        'Comprehensive health, dental, and vision coverage',
        'Generous parental leave (6 months)',
        'Flexible PTO with minimum vacation',
        '401(k) with company match',
        'Design conference and learning budget',
        'Latest design tools and hardware',
        'Home office stipend'
      ],
      dayInLife: {
        intro: 'A day as a UX Designer at Spotify blends creative exploration with user research and squad collaboration.',
        schedule: [
          '9:00 AM - Review user feedback and research findings',
          '9:30 AM - Squad standup with PM and Engineering',
          '10:00 AM - Deep design work on new feature concepts',
          '12:00 PM - Lunch with design team sharing inspiration',
          '1:00 PM - User testing session observing listener behavior',
          '2:30 PM - Design critique with broader design team',
          '3:30 PM - Sync with engineer on implementation details',
          '4:30 PM - Prototype new interaction for testing',
          '5:00 PM - Document design decisions and update specs',
          '5:30 PM - Wrap up with music discovery'
        ],
        closing: 'Design at Spotify means creating experiences that connect hundreds of millions of people with music and audio they love, working with autonomous squads that value craft and collaboration.'
      },
      similarRoles: ['Senior UX Designer at Spotify', 'Product Designer at Spotify', 'Design Lead at Spotify', 'Visual Designer at Spotify', 'Interaction Designer at Spotify']
    }
