    'research-scientist': {
      title: 'Research Scientist',
      slug: 'research-scientist',
      industry: 'Technology',
      roleDescription: `Research Scientists at IBM Research push the boundaries of technology across AI, quantum computing, cloud systems, and semiconductor innovation. Working in one of the world\'s premier industrial research labs—with locations in Yorktown Heights, Almaden, Zurich, and beyond—you\'ll pursue breakthrough discoveries that shape the future of computing. IBM Research has a storied history: researchers have earned six Nobel Prizes, contributed fundamental advances in AI and quantum computing, and created technologies from magnetic stripe cards to relational databases. The role combines academic-style research with industry impact—you\'ll publish at top conferences while also working to transfer innovations into IBM products. Research Scientists collaborate with universities worldwide, access cutting-edge computing resources including quantum systems, and work on problems that matter at global scale. IBM\'s research culture values both fundamental science and practical application, with pathways to bring discoveries from lab to market.`,
      responsibilities: [
        'Conduct original research in AI, quantum computing, or systems',
        'Publish papers at top-tier academic conferences and journals',
        'Develop prototypes and proof-of-concepts for new technologies',
        'Collaborate with IBM product teams on technology transfer',
        'Partner with universities and external research institutions',
        'Present research findings at conferences and internal forums',
        'Mentor junior researchers and interns',
        'Contribute to patent portfolio and intellectual property',
        'Advise on technical direction for IBM products and strategy'
      ],
      growthOpportunities: [
        'Progress from Research Scientist to Senior, Principal, and Distinguished levels',
        'Lead research projects and teams',
        'Become a Fellow (highest technical honor at IBM)',
        'Transition into product development or architecture roles',
        'Build world-renowned expertise in research area',
        'Lead industry-academic collaborations',
        'Shape IBM\'s technical strategy in emerging areas',
        'Contribute to standards bodies and open-source communities'
      ],
      interviewProcess: [
        { stage: 'Application Review', description: 'Review of publications, research statement, and CV' },
        { stage: 'Phone Screen', description: '45-minute conversation about research background and interests' },
        { stage: 'Research Presentation', description: '60-minute presentation of research work to lab team' },
        { stage: 'Technical Interviews', description: 'Multiple rounds assessing technical depth and problem-solving' },
        { stage: 'Team Fit Interviews', description: 'Conversations about collaboration and research direction' },
        { stage: 'Lab Leadership Interview', description: 'Final round with research management' }
      ],
      technicalQuestions: [
        'Describe your most significant research contribution.',
        'How do you identify promising research directions?',
        'Explain how you approach experimental design and validation.',
        'How do you balance publishing with industrial impact?',
        'Describe your experience with research collaboration.',
        'How do you handle negative or unexpected results?',
        'Explain your approach to research reproducibility.',
        'How do you stay current with developments in your field?',
        'Describe your experience with technology transfer.',
        'How do you communicate research to non-expert audiences?',
        'Explain your approach to mentoring junior researchers.',
        'How do you prioritize across multiple research projects?',
        'Describe your experience with patents and intellectual property.',
        'How do you evaluate the potential impact of research directions?',
        'Explain your experience with large-scale experiments or systems.',
        'How do you approach interdisciplinary collaboration?'
      ],
      behavioralQuestions: [
        'Tell me about a research challenge you overcame.',
        'Describe a time your research took an unexpected direction.',
        'How have you built research collaborations?',
        'Tell me about your experience mentoring others.',
        'Describe how you\'ve communicated research impact to stakeholders.',
        'How have you handled criticism of your work?',
        'Tell me about a research project that didn\'t succeed.',
        'Describe your approach to work-life balance in research.',
        'How have you contributed to the research community?',
        'Tell me about a time you had to learn something outside your expertise.',
        'Describe your experience with industry vs. academic research.',
        'How have you prioritized research vs. other responsibilities?',
        'Tell me about your most impactful collaboration.',
        'Describe how you\'ve influenced technical direction in an organization.'
      ],
      whatTheyLookFor: [
        'Strong publication record at top venues',
        'Original and impactful research contributions',
        'Deep expertise in research area',
        'Ability to identify and pursue important problems',
        'Collaboration and communication skills',
        'Track record of technology transfer or applied impact',
        'Mentoring and leadership potential',
        'Intellectual curiosity and drive',
        'Balance of fundamental and applied research interests',
        'PhD in relevant field (typically required)'
      ],
      interviewTips: [
        'Prepare a compelling research presentation',
        'Articulate the significance and impact of your work',
        'Show both depth in your area and breadth of interests',
        'Research IBM\'s current work in your area',
        'Demonstrate ability to connect research to products',
        'Prepare to discuss future research directions',
        'Show collaboration experience and communication skills',
        'Be ready to discuss industry vs. academic research tradeoffs',
        'Highlight publications, patents, and impact metrics',
        'Show interest in IBM\'s research culture and resources',
        'Prepare questions about the specific lab and team',
        'Demonstrate mentoring experience and potential',
        'Be ready to discuss technology transfer experiences',
        'Show enthusiasm for both research and applied impact'
      ],
      salary: {
        min: 130000,
        max: 220000,
        average: 175000
      },
      compensation: [
        'Competitive base salary ($130K-$220K based on level)',
        'Annual performance bonus',
        'Restricted Stock Units (RSUs)',
        '5% automatic retirement benefit contribution',
        'Comprehensive health benefits',
        'Conference travel and publication support',
        'Sabbatical opportunities',
        'Access to cutting-edge computing resources',
        'Patent bonuses for filed and granted patents',
        'Collaboration budget for academic partnerships'
      ],
      dayInLife: {
        intro: 'A typical day as a Research Scientist at IBM balances individual research, collaboration, and knowledge sharing.',
        schedule: [
          '9:00 AM - Review literature and experiment results',
          '10:00 AM - Deep work on research experiments or writing',
          '12:00 PM - Lunch with research colleagues',
          '1:00 PM - Lab meeting or research presentation',
          '2:00 PM - Continue experiments or analysis',
          '3:30 PM - Collaboration call with university partner',
          '4:30 PM - Meeting with product team on technology transfer',
          '5:30 PM - Plan tomorrow and respond to collaborations'
        ],
        closing: 'Research at IBM means pursuing breakthrough discoveries with world-class colleagues, with opportunities to publish at top venues and see your work impact IBM products.'
      },
      similarRoles: ['Senior Research Scientist at IBM', 'Principal Research Scientist at IBM', 'Research Staff Member at IBM', 'Distinguished Research Scientist at IBM', 'Research Manager at IBM']
    },

    'technical-sales-specialist': {
      title: 'Technical Sales Specialist',
      slug: 'technical-sales-specialist',
      industry: 'Technology',
      roleDescription: `Technical Sales Specialists at IBM bridge the gap between complex enterprise technology and client business needs, providing technical expertise throughout the sales cycle for IBM\'s portfolio of solutions. Working at the intersection of technology and business, you\'ll demonstrate product capabilities, design technical solutions, and address client concerns for offerings spanning watsonx AI, Red Hat OpenShift, IBM Cloud, and enterprise software. Technical Sales Specialists are product experts who can translate technical capabilities into business value. The role combines deep product knowledge with client advisory skills: you\'ll conduct technical discovery, deliver compelling demonstrations, and architect solutions that meet complex requirements. IBM\'s breadth of portfolio means Technical Sales Specialists often specialize in areas like AI, cloud, security, or automation. You\'ll work closely with IBM sales teams and partners, serving as the technical voice of the customer and helping clients envision transformational possibilities.`,
      responsibilities: [
        'Provide technical expertise in complex enterprise sales cycles',
        'Conduct product demonstrations tailored to client needs',
        'Design technical solutions addressing client requirements',
        'Answer technical questions and address client concerns',
        'Support RFPs and proposals with technical content',
        'Train and enable sales teams on product capabilities',
        'Gather client feedback for product teams',
        'Build relationships with client technical stakeholders',
        'Stay current on IBM products and competitive landscape'
      ],
      growthOpportunities: [
        'Progress from Technical Sales Specialist to Senior and Principal levels',
        'Specialize in high-growth areas like AI or cloud',
        'Move into sales leadership or management',
        'Transition into product management or customer success',
        'Become a technical specialist for strategic accounts',
        'Lead technical sales for regions or industry verticals',
        'Build deep expertise across the IBM portfolio',
        'Move into IBM Consulting for technical advisory'
      ],
      interviewProcess: [
        { stage: 'Application Review', description: 'Resume screening for technical sales experience' },
        { stage: 'Recruiter Screen', description: '30-minute conversation about background and interests' },
        { stage: 'Hiring Manager Interview', description: '45-minute discussion of technical sales approach' },
        { stage: 'Technical Interview', description: '60-minute interview on product knowledge and technical depth' },
        { stage: 'Demo Presentation', description: 'Deliver a product demonstration to interviewers' },
        { stage: 'Sales Leadership Interview', description: 'Final round with technical sales leadership' }
      ],
      technicalQuestions: [
        'How would you demonstrate AI value to a skeptical client?',
        'Explain your approach to technical discovery.',
        'How do you handle technical objections during sales cycles?',
        'Describe your experience with cloud platform differentiation.',
        'How would you position IBM against competitors?',
        'Explain your approach to sizing and scoping solutions.',
        'How do you stay current on rapidly evolving technology?',
        'Describe your experience with proof-of-concept demonstrations.',
        'How would you handle a technical question you don\'t know?',
        'Explain your approach to technical RFP responses.',
        'How do you balance technical accuracy with sales messaging?',
        'Describe your experience with complex integration scenarios.',
        'How would you demonstrate ROI for enterprise software?',
        'Explain your approach to competitive win strategies.',
        'How do you build credibility with client CTOs and architects?',
        'Describe your experience with security and compliance discussions.'
      ],
      behavioralQuestions: [
        'Tell me about a complex deal you helped close.',
        'Describe a time you turned a technical objection into a win.',
        'How have you built relationships with client technical teams?',
        'Tell me about a demo that went wrong and how you recovered.',
        'Describe your experience working with sales teams.',
        'How have you handled competitive pressure in a deal?',
        'Tell me about a time you had to learn a product quickly.',
        'Describe how you prioritize across multiple opportunities.',
        'How have you communicated technical complexity simply?',
        'Tell me about a time you influenced product direction.',
        'Describe your experience with channel partner enablement.',
        'How have you handled pressure to close quickly?',
        'Tell me about a deal you lost and what you learned.',
        'Describe how you stay current with technology trends.'
      ],
      whatTheyLookFor: [
        'Strong technical foundation with ability to learn products quickly',
        'Experience in technical sales or pre-sales engineering',
        'Excellent presentation and demonstration skills',
        'Understanding of enterprise IT decision-making',
        'Ability to translate technical features into business value',
        'Client relationship and communication skills',
        'Knowledge of IBM products or competing technologies',
        'Competitive awareness and positioning skills',
        'Collaboration skills with sales teams',
        'Problem-solving for complex client requirements'
      ],
      interviewTips: [
        'Research IBM\'s current product portfolio deeply',
        'Prepare to deliver a compelling product demonstration',
        'Show ability to translate technology into business value',
        'Be ready to handle technical objections',
        'Prepare examples of deals you\'ve influenced',
        'Show understanding of enterprise sales cycles',
        'Demonstrate competitive awareness',
        'Prepare to discuss how you learn new products',
        'Show client empathy and advisory approach',
        'Be ready to role-play a technical discovery',
        'Highlight any IBM or competing product experience',
        'Show enthusiasm for technology and client success',
        'Prepare questions about the team and territory',
        'Demonstrate ability to work with sales partners'
      ],
      salary: {
        min: 100000,
        max: 180000,
        average: 140000
      },
      compensation: [
        'Competitive base salary ($100K-$180K based on level)',
        'Sales commission/bonus (can significantly increase total comp)',
        'Restricted Stock Units (RSUs)',
        '5% automatic retirement benefit contribution',
        'Comprehensive health benefits',
        'Travel expense coverage',
        'Certification and training support',
        'Employee stock purchase plan',
        'President\'s Club for top performers',
        'Career development programs'
      ],
      dayInLife: {
        intro: 'A typical day as a Technical Sales Specialist at IBM varies based on sales cycle stage and client needs.',
        schedule: [
          '8:30 AM - Review pipeline and prepare for client meetings',
          '9:00 AM - Client discovery call for new opportunity',
          '10:30 AM - Work on demo customization for upcoming presentation',
          '12:00 PM - Lunch with sales partner',
          '1:00 PM - Deliver product demonstration to prospect',
          '3:00 PM - Technical follow-up call addressing client questions',
          '4:00 PM - RFP response collaboration with proposal team',
          '5:30 PM - Update CRM and prepare for tomorrow'
        ],
        closing: 'Technical Sales at IBM means being the trusted technical advisor to enterprise clients, with variety across accounts and solutions and rewards for successful deals.'
      },
      similarRoles: ['Senior Technical Sales Specialist at IBM', 'Solutions Engineer at IBM', 'Client Technical Specialist at IBM', 'Pre-Sales Engineer at IBM', 'Technical Account Manager at IBM']
    },

    'ux-designer': {
      title: 'UX Designer',
      slug: 'ux-designer',
      industry: 'Technology',
      roleDescription: `UX Designers at IBM create user experiences for enterprise products used by millions of professionals worldwide—from data scientists using watsonx AI to developers deploying on Red Hat OpenShift. Working within IBM Design, the company\'s globally recognized design practice, you\'ll apply human-centered design methodologies to complex enterprise challenges. IBM pioneered corporate design programs and continues to invest heavily in design: the IBM Design Language and Carbon Design System set standards across the industry. UX Designers work on products that require balancing power-user needs with accessibility, handling complex workflows while maintaining simplicity. The role spans user research, interaction design, visual design, and prototyping. IBM\'s design culture emphasizes collaboration with engineering and product teams, using IBM\'s Enterprise Design Thinking framework to drive innovation. You\'ll work on products that transform how enterprises operate, with opportunities to contribute to IBM\'s design system and influence standards across the portfolio.`,
      responsibilities: [
        'Design user experiences for enterprise software products',
        'Conduct user research to understand professional user needs',
        'Create wireframes, prototypes, and interaction designs',
        'Apply IBM Design Language and Carbon Design System standards',
        'Collaborate with product managers and engineers on solutions',
        'Lead Enterprise Design Thinking workshops and sessions',
        'Validate designs through usability testing and iteration',
        'Contribute to design system components and patterns',
        'Create design documentation and specifications'
      ],
      growthOpportunities: [
        'Progress from UX Designer to Senior, Staff, and Principal levels',
        'Specialize in research, interaction, or visual design',
        'Lead design for product areas or portfolios',
        'Move into design management or leadership',
        'Contribute to Carbon Design System and IBM Design standards',
        'Become a design thought leader and speaker',
        'Lead Design Thinking transformation for clients',
        'Transition into product management or strategy'
      ],
      interviewProcess: [
        { stage: 'Application Review', description: 'Portfolio review for design skills and enterprise experience' },
        { stage: 'Recruiter Screen', description: '30-minute conversation about background and interests' },
        { stage: 'Portfolio Presentation', description: '60-minute presentation of design work to design team' },
        { stage: 'Design Exercise', description: 'Take-home or live design challenge for enterprise scenario' },
        { stage: 'Team Interviews', description: 'Conversations with designers, PMs, and engineers' },
        { stage: 'Design Leadership Interview', description: 'Final round with design management' }
      ],
      technicalQuestions: [
        'Walk me through your design process.',
        'How do you approach designing for complex enterprise workflows?',
        'Describe your experience with design systems.',
        'How do you balance user needs with business requirements?',
        'Explain your approach to user research.',
        'How do you design for accessibility?',
        'Describe your experience with data visualization.',
        'How do you handle designing for power users vs. beginners?',
        'Explain your approach to information architecture.',
        'How do you work with engineering on design implementation?',
        'Describe your experience with prototyping tools.',
        'How do you measure design success?',
        'Explain your approach to responsive design.',
        'How do you incorporate feedback into your designs?',
        'Describe your experience with mobile vs. desktop design.',
        'How do you stay current with design trends and tools?'
      ],
      behavioralQuestions: [
        'Tell me about a complex design challenge you solved.',
        'Describe a time you had to advocate for user needs.',
        'How have you handled stakeholder disagreement on design direction?',
        'Tell me about a design decision you changed based on feedback.',
        'Describe your experience facilitating design workshops.',
        'How have you collaborated with engineers on technical constraints?',
        'Tell me about a project where user research changed your approach.',
        'Describe how you prioritize design work across projects.',
        'How have you contributed to design culture on a team?',
        'Tell me about a design that didn\'t achieve its goals.',
        'Describe your experience working with global or remote teams.',
        'How have you handled tight timelines for design delivery?',
        'Tell me about a time you mentored another designer.',
        'Describe how you stay current with design practices.'
      ],
      whatTheyLookFor: [
        'Strong portfolio demonstrating enterprise or B2B design',
        'User research and human-centered design skills',
        'Experience with design systems and component libraries',
        'Ability to handle complex workflows and information architecture',
        'Collaboration skills with product and engineering',
        'Understanding of accessibility and inclusive design',
        'Proficiency in design tools (Figma, Sketch, etc.)',
        'Clear communication of design rationale',
        'Enterprise Design Thinking or similar methodology experience',
        'Data visualization and dashboard design experience valued'
      ],
      interviewTips: [
        'Prepare a portfolio focused on process, not just outcomes',
        'Include enterprise or B2B design work if available',
        'Research IBM Design Language and Carbon Design System',
        'Be ready to walk through your design process in detail',
        'Prepare to discuss designing for complex workflows',
        'Show user research skills and evidence-based design',
        'Practice the design exercise—IBM often gives enterprise scenarios',
        'Demonstrate collaboration with cross-functional teams',
        'Show accessibility awareness in your work',
        'Research Enterprise Design Thinking methodology',
        'Prepare questions about the design team culture',
        'Show how you handle feedback and iteration',
        'Highlight any design system contributions',
        'Demonstrate passion for enterprise user challenges'
      ],
      salary: {
        min: 90000,
        max: 160000,
        average: 125000
      },
      compensation: [
        'Competitive base salary ($90K-$160K based on level)',
        'Annual performance bonus (10-15% of base)',
        'Restricted Stock Units (RSUs)',
        '5% automatic retirement benefit contribution',
        'Comprehensive health benefits',
        'Conference and training budget',
        'Design tools and software provided',
        'Employee stock purchase plan',
        'Generous PTO policy',
        'Remote work flexibility'
      ],
      dayInLife: {
        intro: 'A typical day as a UX Designer at IBM balances design work, research, and collaboration.',
        schedule: [
          '9:00 AM - Review design feedback and prepare for meetings',
          '9:30 AM - Design team standup',
          '10:00 AM - User interview for research project',
          '11:00 AM - Work on wireframes and prototypes',
          '12:00 PM - Lunch with product team',
          '1:00 PM - Design review and critique session',
          '2:30 PM - Collaboration with engineering on implementation',
          '4:00 PM - Update design specifications and documentation',
          '5:00 PM - Design system contribution work',
          '5:30 PM - Plan and wrap up for tomorrow'
        ],
        closing: 'UX Design at IBM means solving complex enterprise challenges with human-centered methods, with opportunities to impact millions of users and contribute to industry-leading design systems.'
      },
      similarRoles: ['Senior UX Designer at IBM', 'Staff UX Designer at IBM', 'Product Designer at IBM', 'UX Researcher at IBM', 'Visual Designer at IBM']
    },

    'project-manager': {
      title: 'Project Manager',
      slug: 'project-manager',
      industry: 'Technology',
      roleDescription: `Project Managers at IBM lead the delivery of complex technology implementations for the world\'s largest enterprises, ensuring projects meet scope, timeline, and quality objectives. Working across IBM\'s portfolio—from watsonx AI deployments to Red Hat OpenShift implementations—you\'ll coordinate cross-functional teams, manage stakeholder expectations, and navigate the complexities of enterprise IT delivery. IBM\'s project management practice combines rigorous methodology with agile flexibility, adapting to client needs across industries like financial services, healthcare, and manufacturing. PMs work closely with IBM Consulting teams on transformational programs and with product teams on internal initiatives. The role requires balancing technical understanding with business acumen: knowing enough about the technology to manage effectively while focusing on delivery excellence. IBM invests in PM development through certifications and the IBM Project Management community.`,
      responsibilities: [
        'Lead delivery of technology implementation projects',
        'Create and maintain project plans, schedules, and budgets',
        'Manage project risks, issues, and dependencies',
        'Coordinate cross-functional teams including developers and consultants',
        'Communicate project status to stakeholders and executives',
        'Ensure quality deliverables meeting client expectations',
        'Manage scope and change requests',
        'Facilitate team meetings and remove blockers',
        'Build relationships with client project stakeholders'
      ],
      growthOpportunities: [
        'Progress from Project Manager to Senior PM, Program Manager, and Director',
        'Lead larger programs with multiple project streams',
        'Specialize in delivery for specific industries or technologies',
        'Move into portfolio management or PMO leadership',
        'Transition into consulting or client partner roles',
        'Earn PMP, Agile, and IBM certifications',
        'Lead transformational programs for strategic clients',
        'Build expertise in specific delivery methodologies'
      ],
      interviewProcess: [
        { stage: 'Application Review', description: 'Resume screening for project management experience' },
        { stage: 'Recruiter Screen', description: '30-minute conversation about background and interests' },
        { stage: 'Hiring Manager Interview', description: '45-minute discussion of PM approach and experience' },
        { stage: 'Scenario Interview', description: '60-minute interview handling project situations' },
        { stage: 'Stakeholder Interview', description: 'Conversation with client-facing or technical leadership' },
        { stage: 'HR Interview', description: 'Discussion of cultural fit and career goals' }
      ],
      technicalQuestions: [
        'How do you approach creating a project plan for a complex implementation?',
        'Describe your experience with Agile vs. Waterfall methodologies.',
        'How do you manage project risks proactively?',
        'Explain your approach to scope management and change control.',
        'How do you handle resource constraints on a project?',
        'Describe your experience with project financial management.',
        'How do you ensure quality in project deliverables?',
        'Explain your approach to stakeholder communication.',
        'How do you handle multiple projects simultaneously?',
        'Describe your experience with project management tools.',
        'How do you measure and report project progress?',
        'Explain your approach to vendor or partner management.',
        'How do you handle project dependencies across teams?',
        'Describe your experience with governance and escalation.',
        'How do you adapt your PM approach to different contexts?',
        'Explain your experience with project recovery or turnaround.'
      ],
      behavioralQuestions: [
        'Tell me about a project you successfully delivered under pressure.',
        'Describe a time you managed a project that went off track.',
        'How have you handled difficult stakeholder relationships?',
        'Tell me about a time you had to deliver bad news to a client.',
        'Describe your experience managing remote or global teams.',
        'How have you resolved conflict on project teams?',
        'Tell me about a time you had to make a difficult tradeoff.',
        'Describe how you build trust with project stakeholders.',
        'How have you handled scope creep on projects?',
        'Tell me about a time you improved project processes.',
        'Describe your experience with executive communications.',
        'How have you mentored or developed project team members?',
        'Tell me about a project failure and what you learned.',
        'Describe how you stay organized across multiple priorities.'
      ],
      whatTheyLookFor: [
        'Proven track record delivering complex projects',
        'Experience with enterprise technology implementations',
        'Strong stakeholder management and communication',
        'Understanding of Agile and traditional PM methodologies',
        'Risk management and problem-solving skills',
        'Experience with project financials and budgets',
        'Client-facing professionalism',
        'PMP or similar certification valued',
        'Technical understanding of IT systems',
        'Leadership and team coordination abilities'
      ],
      interviewTips: [
        'Prepare specific examples of projects with measurable outcomes',
        'Be ready to discuss PM methodologies and when to use each',
        'Show experience with enterprise or client-facing projects',
        'Prepare for scenario questions about project challenges',
        'Demonstrate stakeholder management skills',
        'Highlight certifications (PMP, Agile, etc.)',
        'Show understanding of IBM\'s delivery model',
        'Prepare examples of risk management and mitigation',
        'Be ready to discuss team leadership and motivation',
        'Show technical understanding without overstepping PM role',
        'Prepare questions about project types and team structure',
        'Demonstrate client service orientation',
        'Show ability to adapt to different project contexts',
        'Highlight experience with project recovery if applicable'
      ],
      salary: {
        min: 90000,
        max: 160000,
        average: 125000
      },
      compensation: [
        'Competitive base salary ($90K-$160K based on level)',
        'Annual performance bonus (10-20% of base)',
        'Restricted Stock Units (RSUs) at senior levels',
        '5% automatic retirement benefit contribution',
        'Comprehensive health benefits',
        'PMP and certification reimbursement',
        'Employee stock purchase plan',
        'Generous PTO policy',
        'Travel expense coverage',
        'Career development programs'
      ],
      dayInLife: {
        intro: 'A typical day as a Project Manager at IBM varies based on project phase and client needs.',
        schedule: [
          '8:30 AM - Review project status and prepare for meetings',
          '9:00 AM - Team standup with developers and consultants',
          '9:30 AM - Client status meeting',
          '10:30 AM - Work on project plan updates and risk review',
          '11:30 AM - 1:1 with team member',
          '12:00 PM - Lunch',
          '1:00 PM - Cross-functional coordination meeting',
          '2:00 PM - Address project issues and blockers',
          '3:30 PM - Prepare executive status report',
          '4:30 PM - Internal project review',
          '5:30 PM - Update project documentation and plan tomorrow'
        ],
        closing: 'Project Management at IBM means leading teams to deliver transformational technology for the world\'s largest organizations, with variety across projects and clear career progression.'
      },
      similarRoles: ['Senior Project Manager at IBM', 'Program Manager at IBM', 'Delivery Manager at IBM', 'Technical Project Manager at IBM', 'Agile Project Manager at IBM']
    }