    'ux-designer': {
      title: 'UX Designer',
      slug: 'ux-designer',
      industry: 'Technology',
      roleDescription: `UX Designers at Cisco create user experiences for products that millions of people use to connect and collaborate—from Webex video conferencing to Meraki network management dashboards to security operations interfaces. Working on products that range from consumer-facing collaboration tools to complex enterprise network management systems, you\'ll apply human-centered design to diverse challenges. Cisco\'s UX teams work across the portfolio: designing intuitive video calling experiences, creating dashboards for IT administrators, and simplifying complex security workflows. The role requires balancing simplicity for end users with power for technical administrators. UX Designers collaborate closely with product and engineering teams, advocating for users while understanding technical constraints. With Cisco\'s focus on experience-led transformation and hybrid work enablement, UX designers have opportunities to shape products used by millions worldwide.`,
      responsibilities: [
        'Design user experiences for collaboration, networking, and security products',
        'Conduct user research to understand customer needs',
        'Create wireframes, prototypes, and interaction designs',
        'Collaborate with product managers and engineers',
        'Develop and maintain design systems and guidelines',
        'Test designs through usability studies and iteration',
        'Present design rationale to stakeholders',
        'Create documentation and specifications',
        'Advocate for user-centered design across projects'
      ],
      growthOpportunities: [
        'Progress from UX Designer to Senior and Principal levels',
        'Lead design for specific product areas',
        'Move into UX management or leadership',
        'Specialize in research, interaction, or visual design',
        'Build expertise in design systems',
        'Lead design thinking initiatives',
        'Transition into product management',
        'Become a design advocate across Cisco'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '30-minute conversation about background and interests' },
        { stage: 'Portfolio Presentation', description: '60-minute presentation of design work' },
        { stage: 'Design Exercise', description: 'Take-home or live design challenge' },
        { stage: 'Technical Interview', description: 'Discussion of design process and collaboration' },
        { stage: 'Cross-functional Interview', description: 'Conversations with product and engineering' }
      ],
      technicalQuestions: [
        'Walk me through your design process.',
        'How do you approach designing for both technical and non-technical users?',
        'Describe your experience with design systems.',
        'How do you balance simplicity with functionality?',
        'Explain your approach to user research.',
        'How do you design for enterprise vs. consumer products?',
        'Describe your experience with accessibility.',
        'How do you work with engineering on implementation?',
        'Explain your approach to information architecture.',
        'How do you measure design success?',
        'Describe your experience with prototyping tools.',
        'How do you handle stakeholder feedback?',
        'Explain your approach to responsive design.',
        'How do you design for real-time collaboration experiences?',
        'Describe your experience with data visualization.',
        'How do you stay current with design trends?'
      ],
      behavioralQuestions: [
        'Tell me about a complex design challenge you solved.',
        'Describe a time you advocated for users.',
        'How have you handled disagreement on design direction?',
        'Tell me about a design decision based on research.',
        'Describe your experience facilitating design workshops.',
        'How have you worked with engineers on constraints?',
        'Tell me about a project where research changed your approach.',
        'Describe how you prioritize design work.',
        'How have you contributed to design culture?',
        'Tell me about a design that didn\'t achieve its goals.',
        'Describe your experience with global design.',
        'How have you handled tight timelines?',
        'Tell me about mentoring other designers.',
        'Describe how you stay current with design practices.'
      ],
      whatTheyLookFor: [
        'Strong portfolio demonstrating design process',
        'Experience with enterprise or B2B design valued',
        'User research and human-centered design skills',
        'Ability to design for diverse user types',
        'Collaboration skills with cross-functional teams',
        'Understanding of accessibility requirements',
        'Proficiency in design tools (Figma, etc.)',
        'Clear communication of design rationale',
        'Experience with design systems',
        'Problem-solving for complex information design'
      ],
      interviewTips: [
        'Prepare a portfolio focused on process and outcomes',
        'Include collaboration or enterprise design if available',
        'Be ready to walk through your design process in detail',
        'Research Cisco\'s products: Webex, Meraki, security',
        'Prepare to discuss designing for different user types',
        'Show user research skills and evidence-based design',
        'Practice the design exercise',
        'Demonstrate collaboration with engineering teams',
        'Show accessibility awareness',
        'Prepare questions about design team culture',
        'Show how you handle feedback and iteration',
        'Highlight design system contributions',
        'Demonstrate passion for user experience',
        'Research Cisco\'s design philosophy'
      ],
      salary: {
        min: 100000,
        max: 180000,
        average: 140000
      },
      compensation: [
        'Competitive base salary ($100K-$180K based on level)',
        'Annual performance bonus',
        'Restricted Stock Units (RSUs)',
        '401(k) with company match',
        'Employee Stock Purchase Plan',
        'Comprehensive health benefits',
        'Conference and training budget',
        'Design tools and software provided',
        'Generous PTO and flexibility',
        'Remote work options'
      ],
      dayInLife: {
        intro: 'A typical day as a UX Designer at Cisco balances design work, research, and collaboration.',
        schedule: [
          '9:00 AM - Review feedback and prepare for meetings',
          '9:30 AM - Team standup with UX colleagues',
          '10:00 AM - User interview for research project',
          '11:00 AM - Work on wireframes and prototypes',
          '12:00 PM - Lunch with product team',
          '1:00 PM - Design review and critique session',
          '2:30 PM - Collaboration with engineering',
          '4:00 PM - Update design documentation',
          '5:00 PM - Design system contribution',
          '5:30 PM - Plan and wrap up'
        ],
        closing: 'UX Design at Cisco means creating experiences that help millions connect and collaborate, with opportunities across diverse product areas.'
      },
      similarRoles: ['Senior UX Designer at Cisco', 'Principal UX Designer at Cisco', 'UX Researcher at Cisco', 'Product Designer at Cisco', 'Interaction Designer at Cisco']
    },

    'technical-marketing-engineer': {
      title: 'Technical Marketing Engineer',
      slug: 'technical-marketing-engineer',
      industry: 'Technology',
      roleDescription: `Technical Marketing Engineers at Cisco bridge the gap between complex networking technology and the customers, partners, and sales teams who need to understand it. Working at the intersection of engineering and marketing, you\'ll create technical content, develop demos, conduct benchmarks, and enable the field to position Cisco products effectively. TMEs are product experts who translate Cisco\'s technical capabilities into compelling value propositions—whether creating Webex demos, developing Meraki proof-of-concepts, or benchmarking security products against competitors. The role combines deep technical knowledge with communication skills: you\'ll present at industry events, create training materials, and work directly with customers on technical validation. With Cisco competing across networking, security, and collaboration markets, TMEs play a crucial role in demonstrating technology leadership.`,
      responsibilities: [
        'Create technical content explaining Cisco product capabilities',
        'Develop and deliver product demonstrations and proof-of-concepts',
        'Conduct competitive benchmarks and analysis',
        'Present at industry conferences and customer events',
        'Enable sales and partner teams on technical positioning',
        'Work with customers on technical validation',
        'Collaborate with product teams on messaging',
        'Create technical documentation and guides',
        'Gather competitive intelligence and market feedback'
      ],
      growthOpportunities: [
        'Progress from TME to Senior TME and Principal levels',
        'Move into product management or strategic marketing',
        'Specialize in specific product areas: security, collaboration, networking',
        'Lead technical marketing for product lines',
        'Transition into solutions architecture',
        'Build industry thought leadership',
        'Move into customer-facing technical sales',
        'Take on global technical marketing roles'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '30-minute conversation about background and interests' },
        { stage: 'Hiring Manager Interview', description: '45-minute discussion of TME experience' },
        { stage: 'Technical Interview', description: '60-minute interview on technical depth' },
        { stage: 'Presentation Exercise', description: 'Present a technical topic to demonstrate communication' },
        { stage: 'Cross-functional Interviews', description: 'Conversations with product and sales stakeholders' }
      ],
      technicalQuestions: [
        'How would you demonstrate Cisco networking advantages to a customer?',
        'Explain your approach to competitive positioning.',
        'How do you translate technical features into business value?',
        'Describe your experience with demo development.',
        'How would you position Cisco security against competitors?',
        'Explain your approach to creating technical content.',
        'How do you ensure benchmark validity?',
        'Describe your experience with technical presentations.',
        'How do you handle competitive situations where you have weaknesses?',
        'Explain your approach to enabling sales teams.',
        'How do you stay current with competitive products?',
        'Describe your experience with customer technical validation.',
        'How do you balance technical accuracy with marketing messaging?',
        'Explain your experience with different presentation formats.',
        'How do you gather and act on field feedback?',
        'Describe your experience with industry events.'
      ],
      behavioralQuestions: [
        'Tell me about a successful technical presentation.',
        'Describe a time you translated complex technology for business audiences.',
        'How have you handled pushback on positioning?',
        'Tell me about a demo that had significant impact.',
        'Describe your experience working with sales teams.',
        'How have you stayed credible while advocating for products?',
        'Tell me about a time you learned technology quickly.',
        'Describe your experience at industry events.',
        'How have you handled situations where data didn\'t support your position?',
        'Tell me about creating content that drove results.',
        'Describe your experience training or enabling others.',
        'How have you built relationships across functions?',
        'Tell me about influencing product direction.',
        'Describe how you prioritize TME responsibilities.'
      ],
      whatTheyLookFor: [
        'Strong technical foundation in networking or related areas',
        'Excellent presentation and communication skills',
        'Experience with demo development and delivery',
        'Ability to translate technology into business value',
        'Credibility with technical and business audiences',
        'Competitive analysis experience',
        'Customer-facing technical skills',
        'Content creation abilities',
        'Understanding of Cisco or networking technology',
        'Industry event and speaking experience valued'
      ],
      interviewTips: [
        'Prepare a technical presentation on a topic you know well',
        'Show ability to explain complex concepts simply',
        'Research Cisco\'s competitive positioning',
        'Demonstrate demo development skills',
        'Be ready to discuss competitive landscape candidly',
        'Show technical depth—TMEs must be credible',
        'Prepare examples of customer-facing work',
        'Research Cisco\'s product portfolio',
        'Show enthusiasm for communicating technology',
        'Be ready to discuss handling competitive disadvantages',
        'Prepare examples of content creation',
        'Show understanding of different audience needs',
        'Research Cisco Live and industry events',
        'Balance technical depth with communication skills'
      ],
      salary: {
        min: 120000,
        max: 200000,
        average: 160000
      },
      compensation: [
        'Competitive base salary ($120K-$200K based on level)',
        'Annual performance bonus',
        'Restricted Stock Units (RSUs)',
        '401(k) with company match',
        'Employee Stock Purchase Plan',
        'Comprehensive health benefits',
        'Conference and travel budget',
        'Certification support',
        'Generous PTO and flexibility',
        'Remote work options'
      ],
      dayInLife: {
        intro: 'A typical day as a Technical Marketing Engineer at Cisco balances content creation, customer engagement, and competitive analysis.',
        schedule: [
          '8:30 AM - Review competitive news and industry updates',
          '9:00 AM - Work on demo development',
          '10:30 AM - Customer call for technical validation',
          '11:30 AM - Prepare presentation for event',
          '12:00 PM - Lunch with sales team',
          '1:00 PM - Create technical blog post or white paper',
          '3:00 PM - Internal sync with product marketing',
          '4:00 PM - Competitive benchmark analysis',
          '5:30 PM - Plan tomorrow and respond to field requests'
        ],
        closing: 'Technical Marketing Engineering at Cisco means making Cisco technology compelling and understandable, combining deep expertise with communication skills.'
      },
      similarRoles: ['Senior TME at Cisco', 'Principal TME at Cisco', 'Product Marketing Engineer at Cisco', 'Solutions Marketing Manager at Cisco', 'Field Marketing Engineer at Cisco']
    },

    'customer-success-manager': {
      title: 'Customer Success Manager',
      slug: 'customer-success-manager',
      industry: 'Technology',
      roleDescription: `Customer Success Managers at Cisco ensure enterprise customers achieve their desired outcomes with Cisco technology—driving adoption, retention, and growth across networking, security, and collaboration solutions. Working at the intersection of relationship management and technical expertise, you\'ll guide customers through implementation, optimize their use of Cisco products, and identify opportunities to expand the relationship. Cisco\'s Customer Experience (CX) organization is central to the company\'s subscription and recurring revenue strategy, making CSMs critical to business success. The role requires understanding both technical capabilities and business outcomes: helping a customer improve network performance, increase collaboration adoption, or strengthen security posture. CSMs work with enterprise accounts, building relationships with IT leaders and ensuring Cisco delivers long-term value.`,
      responsibilities: [
        'Own customer relationships and drive adoption of Cisco solutions',
        'Develop success plans aligned with customer business objectives',
        'Monitor customer health metrics and proactively address risks',
        'Guide customers through implementation and optimization',
        'Identify and develop expansion opportunities',
        'Coordinate resources across Cisco to deliver customer value',
        'Conduct business reviews and executive engagements',
        'Drive renewals and prevent churn',
        'Gather customer feedback for product improvement'
      ],
      growthOpportunities: [
        'Progress from CSM to Senior CSM and Director levels',
        'Lead customer success for strategic accounts',
        'Move into customer success leadership or strategy',
        'Transition into sales or solutions architecture',
        'Specialize in specific product areas or verticals',
        'Build expertise in customer success methodology',
        'Move into product management or strategy',
        'Take on global or regional leadership roles'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '30-minute conversation about CS background' },
        { stage: 'Hiring Manager Interview', description: '45-minute discussion of customer success approach' },
        { stage: 'Customer Scenario', description: '60-minute interview handling customer situations' },
        { stage: 'Technical Interview', description: 'Assessment of technical understanding' },
        { stage: 'Cross-functional Interviews', description: 'Conversations with sales and technical stakeholders' },
        { stage: 'Leadership Interview', description: 'Final round with CS leadership' }
      ],
      technicalQuestions: [
        'How do you approach building a customer success plan?',
        'Describe your experience with customer health metrics.',
        'How do you drive adoption of new technology?',
        'Explain your approach to identifying expansion opportunities.',
        'How do you handle a customer considering competitor solutions?',
        'Describe your experience with business reviews.',
        'How do you balance multiple accounts with different needs?',
        'Explain your approach to customer onboarding.',
        'How do you measure customer success?',
        'Describe your technical understanding of networking/security.',
        'How do you coordinate internal resources for customers?',
        'Explain your approach to renewal management.',
        'How do you handle escalations?',
        'Describe your experience with CRM and CS platforms.',
        'How do you stay current with product updates?',
        'Explain your approach to executive relationships.'
      ],
      behavioralQuestions: [
        'Tell me about a customer you saved from churning.',
        'Describe a time you identified and closed expansion.',
        'How have you handled a dissatisfied customer?',
        'Tell me about building an executive relationship.',
        'Describe your experience with challenging renewals.',
        'How have you prioritized across multiple accounts?',
        'Tell me about a successful customer business review.',
        'Describe how you\'ve coordinated cross-functional resources.',
        'How have you handled competing customer and company priorities?',
        'Tell me about improving a customer success process.',
        'Describe your experience with customer advocacy.',
        'How have you used data to drive customer decisions?',
        'Tell me about a time you exceeded customer expectations.',
        'Describe how you\'ve handled organizational change with customers.'
      ],
      whatTheyLookFor: [
        'Customer success or account management experience',
        'Technical aptitude for enterprise technology',
        'Relationship building and communication skills',
        'Data-driven approach to customer health',
        'Experience with subscription or recurring revenue',
        'Problem-solving and coordination abilities',
        'Executive presence and business acumen',
        'Understanding of networking or enterprise IT',
        'Experience with customer success platforms',
        'Results orientation and drive'
      ],
      interviewTips: [
        'Prepare examples of saving at-risk customers',
        'Show data-driven approach to customer health',
        'Research Cisco\'s CX organization and strategy',
        'Demonstrate technical understanding without being an engineer',
        'Prepare for customer scenario role-plays',
        'Show experience with executive relationships',
        'Prepare examples of expansion success',
        'Research Cisco\'s subscription and recurring revenue model',
        'Show understanding of customer success metrics',
        'Be ready to discuss renewal strategies',
        'Demonstrate coordination and influence skills',
        'Prepare questions about CS team structure',
        'Show passion for customer outcomes',
        'Highlight any networking or Cisco experience'
      ],
      salary: {
        min: 100000,
        max: 180000,
        average: 140000
      },
      compensation: [
        'Competitive base salary ($100K-$180K based on level)',
        'Annual performance bonus tied to customer metrics',
        'Restricted Stock Units (RSUs)',
        '401(k) with company match',
        'Employee Stock Purchase Plan',
        'Comprehensive health benefits',
        'Professional development support',
        'Generous PTO and flexibility',
        'Travel budget for customer visits',
        'Remote work options'
      ],
      dayInLife: {
        intro: 'A typical day as a Customer Success Manager at Cisco balances customer engagement, internal coordination, and strategic planning.',
        schedule: [
          '8:30 AM - Review customer health dashboards and alerts',
          '9:00 AM - Team standup on account priorities',
          '9:30 AM - Customer call: quarterly business review prep',
          '10:30 AM - Internal sync with technical resources',
          '11:30 AM - Work on customer success plans',
          '12:00 PM - Lunch',
          '1:00 PM - Customer executive call',
          '2:30 PM - Coordinate renewal with sales',
          '4:00 PM - Address customer escalation',
          '5:00 PM - Update CRM and plan tomorrow',
          '5:30 PM - Respond to customer requests'
        ],
        closing: 'Customer Success Management at Cisco means ensuring customers achieve their goals with Cisco technology, driving adoption and long-term value.'
      },
      similarRoles: ['Senior Customer Success Manager at Cisco', 'Customer Success Director at Cisco', 'Technical Account Manager at Cisco', 'Customer Experience Manager at Cisco', 'Renewal Manager at Cisco']
    },

    'program-manager': {
      title: 'Program Manager',
      slug: 'program-manager',
      industry: 'Technology',
      roleDescription: `Program Managers at Cisco orchestrate complex, cross-functional initiatives that deliver networking, security, and collaboration products to market. Working at the intersection of engineering, product, and business, you\'ll coordinate programs spanning multiple teams, track milestones, manage risks, and drive alignment across Cisco\'s global organization. The role covers the full product lifecycle: from early planning through development, launch, and ongoing operations. Program Managers at Cisco navigate both hardware and software development, understanding the different cadences and dependencies. With Cisco\'s diverse portfolio—from physical networking devices to cloud services like Webex and Meraki—PMs work on varied technical challenges. The company\'s matrix organization requires strong influence and coordination skills to drive results across teams and geographies.`,
      responsibilities: [
        'Lead cross-functional programs for product development and launches',
        'Develop and maintain program plans, schedules, and milestones',
        'Manage program risks and drive mitigation strategies',
        'Coordinate across engineering, product, and business teams',
        'Track and report program status to executives',
        'Drive decision-making and resolve cross-team issues',
        'Manage program budgets and resource planning',
        'Ensure quality and schedule commitments',
        'Facilitate post-launch support and operations'
      ],
      growthOpportunities: [
        'Progress from Program Manager to Senior PM, Director, and VP',
        'Lead larger programs with greater strategic impact',
        'Move into engineering management or business leadership',
        'Specialize in specific domains: hardware, software, cloud',
        'Take on cross-Cisco program leadership',
        'Build expertise in product development processes',
        'Transition into product management or strategy',
        'Move into general management roles'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '30-minute conversation about PM experience' },
        { stage: 'Hiring Manager Interview', description: '45-minute discussion of program management approach' },
        { stage: 'Scenario Interview', description: '60-minute interview handling program situations' },
        { stage: 'Cross-functional Interviews', description: 'Conversations with engineering and business stakeholders' },
        { stage: 'Leadership Interview', description: 'Final round with program leadership' }
      ],
      technicalQuestions: [
        'How do you approach planning for a complex product program?',
        'Describe your experience with program risk management.',
        'How do you handle schedule pressure?',
        'Explain your approach to cross-team coordination.',
        'How do you manage dependencies in large programs?',
        'Describe your experience with hardware vs. software programs.',
        'How do you drive decisions when teams disagree?',
        'Explain your approach to executive communication.',
        'How do you handle scope changes?',
        'Describe your experience with product launches.',
        'How do you balance multiple competing priorities?',
        'Explain your approach to resource management.',
        'How do you track progress across distributed teams?',
        'Describe your experience with agile and waterfall.',
        'How do you handle programs that are behind schedule?',
        'Explain your approach to lessons learned.'
      ],
      behavioralQuestions: [
        'Tell me about a complex program you led successfully.',
        'Describe a time you recovered a program in trouble.',
        'How have you built relationships across functions?',
        'Tell me about a difficult decision you drove.',
        'Describe your experience with executive stakeholders.',
        'How have you handled conflict between teams?',
        'Tell me about managing through ambiguity.',
        'Describe how you prioritize when everything is urgent.',
        'How have you developed team members?',
        'Tell me about a program failure and what you learned.',
        'Describe your experience with organizational change.',
        'How have you influenced without direct authority?',
        'Tell me about navigating a complex situation.',
        'Describe communicating bad news to stakeholders.'
      ],
      whatTheyLookFor: [
        'Experience with complex, cross-functional programs',
        'Understanding of hardware and software development',
        'Strong stakeholder management and communication',
        'Risk management and problem-solving skills',
        'Cross-functional leadership and influence',
        'Experience with global team coordination',
        'Technical understanding to work with engineering',
        'Business acumen for budget and resource decisions',
        'PMP certification valued but not required',
        'Networking or technology industry experience'
      ],
      interviewTips: [
        'Prepare specific examples of programs with outcomes',
        'Show understanding of product development cycles',
        'Be ready to discuss risk management in detail',
        'Demonstrate stakeholder management experience',
        'Prepare for scenario questions about challenges',
        'Show experience with global programs',
        'Research Cisco\'s product development approach',
        'Demonstrate ability to drive decisions',
        'Prepare examples of executive communication',
        'Show technical understanding without overstepping',
        'Highlight experience with launches',
        'Be ready to discuss lessons from failures',
        'Show adaptability for changing requirements',
        'Prepare questions about PM organization'
      ],
      salary: {
        min: 120000,
        max: 200000,
        average: 160000
      },
      compensation: [
        'Competitive base salary ($120K-$200K based on level)',
        'Annual performance bonus (15-25% of base)',
        'Restricted Stock Units (RSUs)',
        '401(k) with company match',
        'Employee Stock Purchase Plan',
        'Comprehensive health benefits',
        'Professional development support',
        'Generous PTO and flexibility',
        'Leadership development programs',
        'Remote work options'
      ],
      dayInLife: {
        intro: 'A typical day as a Program Manager at Cisco balances coordination, problem-solving, and driving programs forward.',
        schedule: [
          '8:30 AM - Review program status and overnight updates',
          '9:00 AM - Program team standup',
          '9:30 AM - Cross-functional sync on critical path',
          '10:30 AM - Risk review and mitigation planning',
          '11:30 AM - Engineering leadership meeting',
          '12:00 PM - Lunch',
          '1:00 PM - Prepare executive status update',
          '2:00 PM - Stakeholder meeting on program decisions',
          '3:30 PM - 1:1s with team leads',
          '4:30 PM - Address program issues and blockers',
          '5:30 PM - Update plans and prepare for tomorrow'
        ],
        closing: 'Program Management at Cisco means driving the programs that deliver networking technology to the world, coordinating across global teams to make products happen.'
      },
      similarRoles: ['Senior Program Manager at Cisco', 'Director of Program Management at Cisco', 'Technical Program Manager at Cisco', 'Product Program Manager at Cisco', 'Engineering Program Manager at Cisco']
    }