    'network-engineer': {
      title: 'Network Engineer',
      slug: 'network-engineer',
      industry: 'Technology',
      roleDescription: `Network Engineers at Cisco design, implement, and optimize the networking solutions that connect organizations worldwide. Working at the company that invented the router and defines networking standards, you\'ll work on enterprise networks, data center infrastructure, cloud connectivity, and service provider solutions. The role spans design, deployment, and troubleshooting of Cisco networking products—from campus switches and routers to SD-WAN solutions and cloud-managed Meraki networks. Cisco Network Engineers often work directly with enterprise customers and partners, architecting solutions that meet complex requirements for performance, security, and reliability. The company\'s certification program (CCNA, CCNP, CCIE) provides clear career progression, and deep networking expertise is highly valued. With networking evolving toward software-defined, cloud-managed, and intent-based approaches, network engineers have opportunities to work on cutting-edge infrastructure technologies.`,
      responsibilities: [
        'Design and implement enterprise networking solutions',
        'Configure and optimize Cisco routers, switches, and firewalls',
        'Deploy SD-WAN and cloud networking solutions',
        'Troubleshoot complex network issues and outages',
        'Work with customers on network architecture and design',
        'Implement network security and access control',
        'Create network documentation and diagrams',
        'Support network migrations and upgrades',
        'Collaborate with security and systems teams'
      ],
      growthOpportunities: [
        'Progress through CCNA, CCNP, and CCIE certifications',
        'Advance from Network Engineer to Senior and Principal levels',
        'Specialize in data center, security, collaboration, or service provider',
        'Move into solutions architecture or technical consulting',
        'Transition into network software development',
        'Lead network design for major customer engagements',
        'Build expertise in emerging areas: SD-WAN, intent-based networking',
        'Move into technical leadership or management'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '30-minute conversation about background and certifications' },
        { stage: 'Technical Phone Screen', description: '60-minute interview on networking fundamentals' },
        { stage: 'Onsite Technical Rounds', description: 'Multiple interviews on routing, switching, and troubleshooting' },
        { stage: 'Lab Exercise', description: 'Hands-on networking scenario or design exercise' },
        { stage: 'Behavioral Interview', description: 'Discussion of customer experience and teamwork' }
      ],
      technicalQuestions: [
        'Explain how OSPF establishes neighbor adjacencies.',
        'How do you troubleshoot a network connectivity issue systematically?',
        'Describe the differences between Layer 2 and Layer 3 switching.',
        'How does BGP path selection work?',
        'Explain VLAN trunking and native VLANs.',
        'How do you design a redundant network architecture?',
        'Describe your experience with SD-WAN technologies.',
        'How does QoS work and when would you implement it?',
        'Explain spanning tree protocol and its variants.',
        'How do you secure a network against common threats?',
        'Describe your experience with network automation.',
        'How do you approach capacity planning for networks?',
        'Explain IPv6 addressing and transition mechanisms.',
        'How do you troubleshoot high latency issues?',
        'Describe your experience with wireless networking.',
        'How do you approach network documentation?'
      ],
      behavioralQuestions: [
        'Tell me about a complex network issue you resolved.',
        'Describe a time you designed a network under tight constraints.',
        'How have you worked with customers on technical requirements?',
        'Tell me about a network outage you handled under pressure.',
        'Describe your experience with network migrations.',
        'How do you prioritize when multiple issues arise?',
        'Tell me about a time you improved network performance.',
        'Describe your approach to network documentation.',
        'How have you stayed current with networking technologies?',
        'Tell me about a time you had to learn a new technology quickly.',
        'Describe your experience working with cross-functional teams.',
        'How have you handled disagreement on network design?',
        'Tell me about a time you mentored others in networking.',
        'Describe your experience with vendor management.'
      ],
      whatTheyLookFor: [
        'Strong foundation in networking protocols and concepts',
        'Cisco certifications (CCNA minimum, CCNP/CCIE preferred)',
        'Experience with Cisco routing and switching platforms',
        'Troubleshooting skills for complex network issues',
        'Customer-facing communication skills',
        'Experience with network security and firewalls',
        'Understanding of cloud and SD-WAN technologies',
        'Network design and architecture experience',
        'Documentation and process discipline',
        'Ability to work under pressure during outages'
      ],
      interviewTips: [
        'Review routing protocols thoroughly: OSPF, BGP, EIGRP',
        'Be prepared to troubleshoot scenarios on whiteboard',
        'Know spanning tree, VLANs, and switching concepts',
        'Prepare to discuss your certification journey',
        'Research Cisco\'s current networking portfolio',
        'Be ready to explain concepts to different audience levels',
        'Prepare examples of customer interactions',
        'Show experience with network automation tools',
        'Understand SD-WAN and cloud networking trends',
        'Be ready for hands-on lab exercises',
        'Highlight any CCIE or advanced certifications',
        'Show understanding of network security',
        'Prepare questions about the team and technologies',
        'Demonstrate continuous learning mindset'
      ],
      salary: {
        min: 90000,
        max: 170000,
        average: 130000
      },
      compensation: [
        'Competitive base salary ($90K-$170K based on level and certs)',
        'Annual performance bonus',
        'Restricted Stock Units (RSUs)',
        '401(k) with company match',
        'Certification bonuses and reimbursement',
        'Comprehensive health benefits',
        'Generous PTO and flexibility',
        'Training and lab access',
        'Tuition reimbursement',
        'Remote work options'
      ],
      dayInLife: {
        intro: 'A typical day as a Network Engineer at Cisco balances design, implementation, and troubleshooting work.',
        schedule: [
          '8:30 AM - Review network alerts and overnight tickets',
          '9:00 AM - Team standup on project status',
          '9:30 AM - Work on network design for customer project',
          '11:00 AM - Customer call to discuss requirements',
          '12:00 PM - Lunch',
          '1:00 PM - Lab work on new configuration or testing',
          '2:30 PM - Troubleshoot escalated network issue',
          '4:00 PM - Document network changes and designs',
          '5:00 PM - Research new features or technologies',
          '5:30 PM - Wrap up and prepare for tomorrow'
        ],
        closing: 'Network Engineering at Cisco means working on the infrastructure that connects the world, with clear career progression through certifications.'
      },
      similarRoles: ['Senior Network Engineer at Cisco', 'Network Architect at Cisco', 'SD-WAN Engineer at Cisco', 'Data Center Network Engineer at Cisco', 'Wireless Network Engineer at Cisco']
    },

    'security-engineer': {
      title: 'Security Engineer',
      slug: 'security-engineer',
      industry: 'Technology',
      roleDescription: `Security Engineers at Cisco protect organizations worldwide by building and implementing security solutions across the networking industry. Working at a company that secures over 85% of internet traffic, you\'ll develop and deploy security products from firewalls and intrusion prevention to cloud security, endpoint protection, and zero-trust solutions. Cisco\'s security portfolio spans Secure Firewall, Umbrella DNS security, Duo authentication, and following the Splunk acquisition, leading SIEM and observability capabilities. Security Engineers work across product development, customer implementations, and internal security operations. The role combines deep security expertise with networking knowledge—understanding how to secure traffic at every layer. With cybersecurity threats constantly evolving and Cisco\'s strategic focus on security, security engineers have high-impact opportunities.`,
      responsibilities: [
        'Design and implement security solutions for enterprise customers',
        'Develop security features for Cisco products',
        'Conduct security assessments and penetration testing',
        'Configure and optimize firewalls, IPS, and security appliances',
        'Implement zero-trust and identity-based access solutions',
        'Respond to security incidents and develop mitigation strategies',
        'Create security policies and documentation',
        'Collaborate with networking teams on secure architectures',
        'Stay current with threat landscape and vulnerabilities'
      ],
      growthOpportunities: [
        'Progress from Security Engineer to Senior, Principal, and Distinguished',
        'Earn security certifications: CISSP, CCIE Security, OSCP',
        'Specialize in network security, cloud security, or threat intelligence',
        'Lead security architecture for major engagements',
        'Move into security product management or strategy',
        'Transition into security research or threat hunting',
        'Build expertise across Cisco\'s security portfolio',
        'Move into security leadership or CISO advisory'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '30-minute conversation about security background' },
        { stage: 'Technical Phone Screen', description: '60-minute interview on security fundamentals' },
        { stage: 'Onsite Technical Rounds', description: 'Multiple interviews on security concepts and scenarios' },
        { stage: 'Security Scenario', description: 'Walk through incident response or security design' },
        { stage: 'Behavioral Interview', description: 'Discussion of teamwork and communication' }
      ],
      technicalQuestions: [
        'How do you design a zero-trust network architecture?',
        'Explain your approach to threat modeling.',
        'How do firewalls and IPS systems work together?',
        'Describe your experience with DNS security.',
        'How would you secure a hybrid cloud environment?',
        'Explain the MITRE ATT&CK framework.',
        'How do you detect and respond to a network breach?',
        'Describe your experience with multi-factor authentication.',
        'How do you secure IoT devices on an enterprise network?',
        'Explain techniques for detecting lateral movement.',
        'How do you prioritize vulnerabilities for remediation?',
        'Describe your experience with SIEM platforms.',
        'How do you secure encrypted traffic inspection?',
        'Explain your approach to security automation.',
        'How do you handle compliance requirements?',
        'Describe your experience with penetration testing.'
      ],
      behavioralQuestions: [
        'Tell me about a security incident you handled.',
        'Describe how you\'ve communicated security risks to leadership.',
        'How have you balanced security with business needs?',
        'Tell me about a time you found a critical vulnerability.',
        'Describe your experience with compliance audits.',
        'How have you stayed current with evolving threats?',
        'Tell me about a time you improved security processes.',
        'Describe a challenging security implementation.',
        'How have you handled disagreement on security priorities?',
        'Tell me about a time you trained others on security.',
        'Describe your experience with incident response.',
        'How have you handled high-pressure security situations?',
        'Tell me about a security project you\'re proud of.',
        'Describe how you build security culture in organizations.'
      ],
      whatTheyLookFor: [
        'Strong foundation in security concepts and frameworks',
        'Experience with network security and firewalls',
        'Security certifications valued (CISSP, CCIE Security, etc.)',
        'Understanding of threat landscape and attack techniques',
        'Incident response and forensics experience',
        'Cloud security knowledge',
        'Programming/scripting for automation',
        'Customer-facing communication skills',
        'Understanding of compliance requirements',
        'Balance of technical depth and business understanding'
      ],
      interviewTips: [
        'Research Cisco\'s security portfolio thoroughly',
        'Be ready to walk through security scenarios',
        'Understand zero-trust and modern security architectures',
        'Prepare examples of incident response experience',
        'Show knowledge of current threat landscape',
        'Highlight relevant certifications',
        'Prepare to discuss network security specifically',
        'Show experience with automation and scripting',
        'Research the Splunk acquisition and integration',
        'Be ready to discuss compliance frameworks',
        'Show continuous learning about evolving threats',
        'Demonstrate understanding of cloud security',
        'Prepare questions about Cisco\'s security strategy',
        'Show balance of technical and advisory skills'
      ],
      salary: {
        min: 110000,
        max: 200000,
        average: 155000
      },
      compensation: [
        'Competitive base salary ($110K-$200K based on level)',
        'Annual performance bonus',
        'Restricted Stock Units (RSUs)',
        '401(k) with company match',
        'Certification bonuses and reimbursement',
        'Comprehensive health benefits',
        'Conference attendance support',
        'Generous PTO and flexibility',
        'Training and lab access',
        'Remote work options'
      ],
      dayInLife: {
        intro: 'A typical day as a Security Engineer at Cisco balances design, implementation, and threat response.',
        schedule: [
          '8:30 AM - Review security alerts and threat intelligence',
          '9:00 AM - Team standup on security projects',
          '9:30 AM - Work on security architecture for customer',
          '11:00 AM - Customer call on security implementation',
          '12:00 PM - Lunch',
          '1:00 PM - Investigate security incident or alert',
          '2:30 PM - Develop security automation scripts',
          '4:00 PM - Cross-functional meeting with networking team',
          '5:00 PM - Research new threats and vulnerabilities',
          '5:30 PM - Document findings and wrap up'
        ],
        closing: 'Security Engineering at Cisco means protecting organizations worldwide with industry-leading security solutions.'
      },
      similarRoles: ['Senior Security Engineer at Cisco', 'Security Architect at Cisco', 'Threat Intelligence Analyst at Cisco', 'Penetration Tester at Cisco', 'Cloud Security Engineer at Cisco']
    },

    'solutions-architect': {
      title: 'Solutions Architect',
      slug: 'solutions-architect',
      industry: 'Technology',
      roleDescription: `Solutions Architects at Cisco design comprehensive technology solutions that address complex enterprise challenges—integrating networking, security, collaboration, and cloud technologies. Working at the intersection of technical depth and customer advisory, you\'ll translate business requirements into architectures spanning Cisco\'s portfolio: from campus and data center networking to Webex collaboration, Meraki cloud management, and security solutions. Cisco Solutions Architects are technical leaders who guide customers through digital transformation, helping them modernize networks, enable hybrid work, and secure their operations. The role requires both broad technology understanding and the ability to dive deep into specific domains. You\'ll work closely with sales teams on complex opportunities, create solution designs, and present to technical and business audiences.`,
      responsibilities: [
        'Design end-to-end technology solutions for enterprise customers',
        'Translate business requirements into technical architectures',
        'Lead solution design for complex, multi-technology opportunities',
        'Present technical solutions to customer executives and IT teams',
        'Create solution documentation and implementation guides',
        'Collaborate with sales teams on strategic opportunities',
        'Stay current on Cisco portfolio and competitive landscape',
        'Guide customers on technology roadmaps and modernization',
        'Ensure solutions meet performance, security, and scalability requirements'
      ],
      growthOpportunities: [
        'Progress from Solutions Architect to Senior and Principal levels',
        'Specialize in enterprise, data center, security, or collaboration',
        'Move into technical leadership or chief architect roles',
        'Lead architecture practices for regions or verticals',
        'Transition into product management or strategy',
        'Build deep expertise across Cisco portfolio',
        'Present at industry conferences and events',
        'Move into customer-facing leadership roles'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '30-minute conversation about architecture experience' },
        { stage: 'Technical Phone Screen', description: '60-minute interview on architecture approach' },
        { stage: 'Architecture Design Interview', description: '60-minute interview designing a solution for customer scenario' },
        { stage: 'Technical Deep Dive', description: 'Deep dive into specific technology areas' },
        { stage: 'Customer Scenario', description: 'Interview on presenting and defending technical recommendations' },
        { stage: 'Leadership Interview', description: 'Final round with architecture leadership' }
      ],
      technicalQuestions: [
        'How would you design a secure hybrid cloud architecture?',
        'Explain your approach to enterprise network modernization.',
        'How do you evaluate build vs. buy decisions for customers?',
        'Describe your experience with data center architecture.',
        'How would you integrate collaboration tools with network infrastructure?',
        'Explain your approach to ensuring security in solution design.',
        'How do you address scalability requirements?',
        'Describe your experience with SD-WAN architecture.',
        'How would you design a solution for a multi-site enterprise?',
        'Explain your approach to high availability and resilience.',
        'How do you handle non-functional requirements?',
        'Describe your experience with cloud-managed networking.',
        'How would you approach zero-trust network design?',
        'Explain your approach to solution documentation.',
        'How do you ensure solutions are cost-effective?',
        'Describe your experience with intent-based networking.'
      ],
      behavioralQuestions: [
        'Tell me about a complex architecture you designed.',
        'Describe a time you had to defend a technical recommendation.',
        'How have you communicated technical concepts to executives?',
        'Tell me about a time your approach changed based on customer feedback.',
        'Describe your experience working with sales teams.',
        'How have you handled disagreement on architecture decisions?',
        'Tell me about a time you learned new technology for a customer.',
        'Describe how you stay current with technology trends.',
        'How have you balanced ideal architecture with customer constraints?',
        'Tell me about a challenging customer engagement.',
        'Describe your experience with solution documentation.',
        'How have you mentored others on architecture?',
        'Tell me about a time you identified a technical risk.',
        'Describe how you\'ve influenced customer technology direction.'
      ],
      whatTheyLookFor: [
        'Broad technology knowledge across Cisco portfolio',
        'Experience designing enterprise-scale solutions',
        'Strong customer-facing communication skills',
        'Understanding of business drivers and ROI',
        'Architecture patterns and best practices',
        'Cisco certifications valued (CCNP, CCIE, etc.)',
        'Experience with competitive technologies',
        'Ability to translate business to technical requirements',
        'Collaboration skills with sales and engineering',
        'Continuous learning orientation'
      ],
      interviewTips: [
        'Research Cisco\'s full portfolio: networking, security, collaboration',
        'Prepare to whiteboard an architecture for customer scenario',
        'Show breadth across multiple technology domains',
        'Demonstrate customer-facing experience',
        'Be ready to discuss architecture trade-offs',
        'Prepare examples of presenting to executives',
        'Show understanding of competitive landscape',
        'Highlight relevant certifications',
        'Be ready to discuss both Cisco and non-Cisco technologies',
        'Prepare examples of guiding customer decisions',
        'Show how you stay current with trends',
        'Demonstrate structured approach to design',
        'Prepare questions about architecture community',
        'Show balance of technical depth and business understanding'
      ],
      salary: {
        min: 140000,
        max: 230000,
        average: 185000
      },
      compensation: [
        'Competitive base salary ($140K-$230K based on level)',
        'Annual performance bonus (15-25% of base)',
        'Restricted Stock Units (RSUs)',
        '401(k) with company match',
        'Employee Stock Purchase Plan',
        'Comprehensive health benefits',
        'Conference and training budget',
        'Certification support',
        'Generous PTO and flexibility',
        'Travel budget for customer meetings'
      ],
      dayInLife: {
        intro: 'A typical day as a Solutions Architect at Cisco balances customer engagement, design work, and technical leadership.',
        schedule: [
          '8:30 AM - Review opportunities and prepare for meetings',
          '9:00 AM - Customer architecture workshop',
          '11:00 AM - Design solution for complex opportunity',
          '12:00 PM - Lunch with sales team',
          '1:00 PM - Internal architecture review',
          '2:30 PM - Create solution documentation',
          '4:00 PM - Call with partner on joint solution',
          '5:00 PM - Research new technologies',
          '5:30 PM - Prepare for tomorrow\'s customer meeting'
        ],
        closing: 'Solutions Architecture at Cisco means designing technology solutions that transform how organizations connect and collaborate.'
      },
      similarRoles: ['Senior Solutions Architect at Cisco', 'Principal Architect at Cisco', 'Enterprise Architect at Cisco', 'Cloud Architect at Cisco', 'Security Solutions Architect at Cisco']
    },

    'technical-consulting-engineer': {
      title: 'Technical Consulting Engineer',
      slug: 'technical-consulting-engineer',
      industry: 'Technology',
      roleDescription: `Technical Consulting Engineers (TCEs) at Cisco are the frontline technical experts who support customers in designing, implementing, and troubleshooting Cisco solutions. Working at the intersection of deep technical expertise and customer service, you\'ll resolve complex technical issues, provide implementation guidance, and help customers get maximum value from Cisco products. TCEs are product experts—whether in routing and switching, security, collaboration, or data center—who combine hands-on technical skills with excellent communication. The role spans proactive design reviews, break-fix support, and strategic guidance. Cisco\'s Technical Assistance Center (TAC) is renowned in the industry, and TCEs are a key part of Cisco\'s commitment to customer success. With certifications driving career progression and exposure to diverse customer environments, TCEs develop deep technical expertise.`,
      responsibilities: [
        'Provide expert technical support for Cisco products',
        'Troubleshoot complex networking and security issues',
        'Guide customers on best practices and implementation',
        'Conduct design reviews and proactive consultations',
        'Document solutions and contribute to knowledge base',
        'Collaborate with engineering on product issues',
        'Mentor junior engineers and share expertise',
        'Participate in on-call rotation for critical issues',
        'Stay current on product features and updates'
      ],
      growthOpportunities: [
        'Progress through TCE levels to Principal and Distinguished',
        'Earn advanced certifications: CCIE, CCDE',
        'Specialize in specific technology areas',
        'Move into escalation engineering or customer advocacy',
        'Transition into solutions architecture or field engineering',
        'Lead technical communities and mentorship',
        'Move into engineering or product development',
        'Take on customer success leadership roles'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '30-minute conversation about technical background' },
        { stage: 'Technical Phone Screen', description: '60-minute interview on networking fundamentals' },
        { stage: 'Onsite Technical Rounds', description: 'Multiple interviews on troubleshooting and product knowledge' },
        { stage: 'Troubleshooting Scenario', description: 'Work through a complex technical issue' },
        { stage: 'Customer Interaction', description: 'Role-play handling a customer situation' },
        { stage: 'Behavioral Interview', description: 'Discussion of customer service and teamwork' }
      ],
      technicalQuestions: [
        'How do you systematically troubleshoot a network outage?',
        'Explain your approach to analyzing packet captures.',
        'Describe a complex routing issue you resolved.',
        'How do you prioritize when handling multiple cases?',
        'Explain your experience with Cisco debugging commands.',
        'How do you handle a situation where you don\'t know the answer?',
        'Describe your approach to documenting solutions.',
        'How do you explain technical issues to non-technical customers?',
        'What\'s your experience with log analysis?',
        'Explain your approach to reproducing intermittent issues.',
        'How do you handle an escalated or frustrated customer?',
        'Describe your experience with specific Cisco products.',
        'How do you stay current with product updates?',
        'Explain your approach to root cause analysis.',
        'How do you balance thoroughness with time pressure?',
        'Describe your experience with cross-team troubleshooting.'
      ],
      behavioralQuestions: [
        'Tell me about a difficult technical issue you resolved.',
        'Describe a time you turned a frustrated customer around.',
        'How have you handled a situation where you were stuck?',
        'Tell me about a time you went above and beyond for a customer.',
        'Describe your experience with on-call support.',
        'How do you handle multiple high-priority issues?',
        'Tell me about a time you learned from a mistake.',
        'Describe how you\'ve mentored others.',
        'How have you contributed to team knowledge?',
        'Tell me about a time you collaborated across teams.',
        'Describe your approach to customer communication.',
        'How have you handled disagreement on technical approach?',
        'Tell me about a time you improved a support process.',
        'Describe how you stay current with technology.'
      ],
      whatTheyLookFor: [
        'Deep expertise in Cisco technologies',
        'Strong troubleshooting and analytical skills',
        'Excellent customer communication',
        'Certifications: CCNA, CCNP, CCIE valued',
        'Patience and empathy in customer interactions',
        'Ability to work under pressure',
        'Documentation and knowledge sharing skills',
        'Teamwork and collaboration',
        'Continuous learning mindset',
        'Experience with support environments'
      ],
      interviewTips: [
        'Be ready to troubleshoot live scenarios',
        'Review Cisco CLI and debugging commands',
        'Prepare examples of customer success stories',
        'Show systematic troubleshooting methodology',
        'Highlight relevant certifications',
        'Demonstrate customer empathy in role-play',
        'Research the specific product area',
        'Show experience with documentation',
        'Be ready to explain complex concepts simply',
        'Prepare for questions on handling pressure',
        'Show continuous learning and curiosity',
        'Demonstrate teamwork and collaboration',
        'Prepare questions about the team and growth',
        'Show passion for helping customers'
      ],
      salary: {
        min: 85000,
        max: 160000,
        average: 120000
      },
      compensation: [
        'Competitive base salary ($85K-$160K based on level)',
        'Annual performance bonus',
        'Restricted Stock Units (RSUs)',
        '401(k) with company match',
        'Certification bonuses and support',
        'Comprehensive health benefits',
        'Generous PTO',
        'Shift differential for off-hours support',
        'Training and lab access',
        'Career development programs'
      ],
      dayInLife: {
        intro: 'A typical day as a Technical Consulting Engineer at Cisco balances customer support, troubleshooting, and continuous learning.',
        schedule: [
          '9:00 AM - Review assigned cases and prioritize',
          '9:30 AM - Work on complex troubleshooting case',
          '11:00 AM - Customer call to discuss issue and solution',
          '12:00 PM - Lunch',
          '1:00 PM - Continue case work or research',
          '2:30 PM - Team knowledge sharing session',
          '3:30 PM - Document solution and close case',
          '4:30 PM - Review new cases and prepare for tomorrow',
          '5:30 PM - Training or certification study'
        ],
        closing: 'Technical Consulting Engineering at Cisco means being the expert customers rely on, with clear career progression and continuous learning.'
      },
      similarRoles: ['Senior TCE at Cisco', 'Principal TCE at Cisco', 'Customer Support Engineer at Cisco', 'Escalation Engineer at Cisco', 'Technical Leader at Cisco']
    }