    'audio-engineer': {
      title: 'Audio Engineer',
      slug: 'audio-engineer',
      industry: 'Technology',
      roleDescription: `Audio Engineers at Spotify work on the science and technology of sound that delivers music to over 600 million listeners. This unique role combines software engineering with audio signal processing, psychoacoustics, and codec development. You'll work on challenges spanning audio quality optimization, codec development, loudness normalization, spatial audio, and acoustic fingerprinting. Spotify streams billions of songs daily, and Audio Engineers ensure every track sounds as the artist intended across devices, network conditions, and listening environments. The team works on cutting-edge projects including high-resolution audio, Dolby Atmos integration, AI-powered audio enhancement, and next-generation codecs. Audio Engineers partner with ML teams on audio understanding, with Backend teams on streaming infrastructure, and with Product teams on audio quality features. The role requires deep expertise in digital signal processing alongside software engineering skills to implement solutions at scale.`,
      responsibilities: [
        'Develop audio codecs and processing algorithms for streaming at scale',
        'Build audio quality optimization systems adapting to network conditions',
        'Work on spatial audio, Dolby Atmos, and immersive sound experiences',
        'Implement loudness normalization and audio enhancement features',
        'Develop acoustic fingerprinting and content identification systems',
        'Partner with ML teams on audio understanding and classification',
        'Ensure audio quality across diverse devices and playback environments',
        'Research and prototype new audio technologies and formats',
        'Contribute to industry audio standards and open-source projects'
      ],
      growthOpportunities: [
        'Progress through IC levels to Staff and Principal Audio Engineer',
        'Specialize in areas like codecs, spatial audio, or ML for audio',
        'Lead audio technology strategy for major initiatives',
        'Transition into research roles for exploratory work',
        'Shape the future of audio streaming technology',
        'Contribute to industry standards bodies',
        'Build and lead audio engineering teams',
        'Work on emerging formats like high-res and immersive audio'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial conversation about audio engineering background' },
        { stage: 'Technical Phone Screen', description: '60-minute interview on DSP, audio systems, and coding' },
        { stage: 'Onsite - Audio Deep Dive', description: '60-minute assessment of audio signal processing expertise' },
        { stage: 'Onsite - Coding', description: '60-minute algorithmic and systems coding interview' },
        { stage: 'Onsite - System Design', description: '60-minute design of audio processing system at scale' },
        { stage: 'Onsite - Values Interview', description: '45-minute behavioral interview on cultural fit' },
        { stage: 'Team Matching', description: 'Discussions with potential teams' }
      ],
      technicalQuestions: [
        'Design an audio codec optimized for music streaming',
        'How would you implement adaptive bitrate audio streaming?',
        'Design a loudness normalization system for diverse music',
        'How would you build spatial audio for different playback devices?',
        'Design an acoustic fingerprinting system at scale',
        'How would you implement audio quality measurement at scale?',
        'Design a system for seamless crossfade between tracks',
        'How would you optimize audio for different network conditions?',
        'Design an audio enhancement system using ML',
        'How would you implement Dolby Atmos support for mobile?',
        'Design a system for detecting audio quality issues',
        'How would you approach high-resolution audio streaming?',
        'Design a lyrics timing synchronization system',
        'How would you build audio watermarking for content protection?',
        'Design a system for audio-to-audio recommendations',
        'How would you approach real-time audio processing for live streaming?'
      ],
      behavioralQuestions: [
        'Tell me about an audio system you built at scale',
        'Describe solving a complex audio quality issue',
        'How have you balanced audio quality with bandwidth constraints?',
        'Tell me about collaborating with non-audio engineers',
        'Describe working on audio standards or specifications',
        'How have you approached perceptual audio evaluation?',
        'Tell me about an audio project that didn\'t work as expected',
        'Describe staying current with audio technology advances',
        'How have you made audio trade-offs for different devices?',
        'Tell me about your passion for audio and music',
        'Describe communicating audio concepts to non-experts',
        'How have you mentored others in audio engineering?',
        'Tell me about contributing to open-source audio projects',
        'Describe adapting to new audio formats or standards'
      ],
      whatTheyLookFor: [
        'Deep expertise in digital signal processing and audio systems',
        'Strong software engineering skills (C++, Python)',
        'Experience with audio codecs and streaming',
        'Understanding of psychoacoustics and perceptual audio',
        'Problem-solving at the intersection of audio and scale',
        'Collaboration skills for cross-functional work',
        'Passion for music and audio quality',
        'Cultural fit with Spotify\'s values',
        'Research orientation for emerging audio technology',
        'Experience with ML for audio applications'
      ],
      interviewTips: [
        'Review DSP fundamentals and audio processing',
        'Be ready to discuss audio codec architectures',
        'Understand perceptual audio quality metrics',
        'Know Spotify\'s audio quality features',
        'Prepare for the values interview',
        'Research Spotify\'s audio technology publications',
        'Be ready to code DSP algorithms efficiently',
        'Prepare examples of audio systems at scale',
        'Show passion for audio quality and music',
        'Be ready to discuss spatial and immersive audio',
        'Understand the challenges of streaming audio',
        'Prepare questions about audio team culture',
        'Show how you stay current with audio research',
        'Be authentic about your audio expertise'
      ],
      salary: { min: 160000, max: 280000 },
      compensation: [
        'Highly competitive base salary with equity (RSUs)',
        'Annual refresher grants and bonuses',
        'Spotify Premium subscription for life',
        'Comprehensive health, dental, and vision coverage',
        'Generous parental leave (6 months)',
        'Flexible PTO with minimum vacation',
        '401(k) with company match',
        'Conference and research budget',
        'Professional audio equipment budget',
        'Home office and studio stipend'
      ],
      dayInLife: {
        intro: 'A day as an Audio Engineer at Spotify combines deep technical work on sound with collaboration on streaming infrastructure.',
        schedule: [
          '9:30 AM - Review audio quality metrics and test results',
          '10:00 AM - Squad standup with audio team',
          '10:30 AM - Deep work on codec optimization',
          '12:00 PM - Listening session evaluating audio improvements',
          '1:00 PM - Lunch with colleagues discussing audio research',
          '2:00 PM - Meeting with ML team on audio understanding models',
          '3:00 PM - Research prototype for spatial audio feature',
          '4:00 PM - Code review for streaming audio changes',
          '5:00 PM - Document findings and update specifications',
          '5:30 PM - Wrap up with music listening'
        ],
        closing: 'Audio Engineering at Spotify means ensuring hundreds of millions of people hear music exactly as artists intended, working on the cutting edge of sound technology.'
      },
      similarRoles: ['Senior Audio Engineer at Spotify', 'Staff Audio Engineer at Spotify', 'DSP Engineer at Spotify', 'ML Audio Engineer at Spotify', 'Backend Engineer at Spotify']
    },

    'marketing-manager': {
      title: 'Marketing Manager',
      slug: 'marketing-manager',
      industry: 'Technology',
      roleDescription: `Marketing Managers at Spotify drive growth and engagement for one of the world's most beloved audio brands. Working across consumer marketing, brand campaigns, and product marketing, you'll develop strategies that connect listeners with music and audio they love. Spotify's marketing is distinctive—from viral campaigns like Wrapped to artist partnerships and culturally resonant moments. The role requires balancing data-driven performance marketing with creative brand building, local relevance with global scale, and listener acquisition with creator partnerships. Marketing Managers partner with Product on feature launches, with Content on editorial campaigns, and with regional teams on localization. Spotify's rich data on listening behavior enables sophisticated targeting and personalization, and marketers are expected to leverage these insights. The brand's playful, music-obsessed personality means marketing must feel authentic to music culture while driving measurable results.`,
      responsibilities: [
        'Develop and execute marketing campaigns driving growth and engagement',
        'Manage multi-channel programs across digital, social, partnerships, and events',
        'Analyze campaign performance and optimize for ROI and brand metrics',
        'Partner with Creative on campaign concepts and content',
        'Collaborate with Product Marketing on feature launches',
        'Develop localized marketing strategies for different markets',
        'Build brand awareness while driving acquisition and retention',
        'Work with artist and creator partnerships on co-marketing',
        'Leverage Spotify\'s data for targeting and personalization'
      ],
      growthOpportunities: [
        'Progress to Senior Marketing Manager and Director roles',
        'Specialize in brand, performance, product marketing, or partnerships',
        'Move into Head of Marketing for regions or products',
        'Transition to Product Management with marketing expertise',
        'Lead marketing for new products like audiobooks or podcasts',
        'Build and lead marketing teams',
        'Shape company marketing strategy at executive level',
        'Work on flagship campaigns like Wrapped'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial discussion of marketing experience and passion for Spotify' },
        { stage: 'Hiring Manager Interview', description: 'Deep dive into marketing philosophy and campaign experience' },
        { stage: 'Marketing Case Study', description: 'Develop marketing strategy for given scenario' },
        { stage: 'Cross-functional Interview', description: 'Assessment of collaboration with Product, Creative, and Data' },
        { stage: 'Creative/Campaign Review', description: 'Discussion of past campaigns and creative thinking' },
        { stage: 'Values Interview', description: 'Behavioral interview on cultural fit' },
        { stage: 'Leadership Interview', description: 'Final round with marketing leader' }
      ],
      technicalQuestions: [
        'How would you design a campaign to acquire new Spotify users?',
        'Develop a marketing strategy for Spotify Wrapped',
        'How would you approach marketing in a new international market?',
        'Design a campaign to increase podcast listening engagement',
        'How would you balance brand building with performance marketing?',
        'Develop a marketing strategy for Spotify Premium conversion',
        'How would you leverage Spotify data for marketing personalization?',
        'Design a co-marketing campaign with an artist partner',
        'How would you measure brand awareness impact?',
        'Develop a strategy for marketing audiobooks on Spotify',
        'How would you approach competitive marketing moments?',
        'Design a campaign for re-engaging lapsed users',
        'How would you localize a global campaign?',
        'Develop a social media strategy for Spotify',
        'How would you approach influencer partnerships?',
        'Design a marketing strategy for a new product feature'
      ],
      behavioralQuestions: [
        'Tell me about a marketing campaign you led that exceeded goals',
        'Describe pivoting a campaign based on performance data',
        'How have you balanced creative vision with data-driven decisions?',
        'Tell me about marketing to an audience different from yourself',
        'Describe collaborating with creative teams effectively',
        'How have you handled budget constraints while driving growth?',
        'Tell me about a campaign that underperformed',
        'Describe working with product teams on launches',
        'How have you built brand while driving performance?',
        'Tell me about leading through ambiguity',
        'Describe managing agency relationships',
        'How have you approached competitive situations?',
        'Tell me about adapting campaigns for local markets',
        'Describe influencing stakeholders on strategy'
      ],
      whatTheyLookFor: [
        'Strong marketing track record with measurable success',
        'Balance of creative thinking and analytical optimization',
        'Brand sensibility aligned with Spotify\'s culture',
        'Multi-channel expertise across digital and traditional',
        'Strategic thinking connecting marketing to business goals',
        'Cultural awareness and music passion',
        'Collaboration skills for cross-functional work',
        'Cultural fit with Spotify\'s values',
        'Data-driven approach with creative intuition',
        'Global mindset with local sensitivity'
      ],
      interviewTips: [
        'Study Spotify\'s marketing campaigns and brand voice',
        'Prepare campaign examples with clear metrics',
        'Be ready to discuss both brand and performance marketing',
        'Know Spotify\'s values for the values interview',
        'Research Spotify Wrapped and understand its success',
        'Show genuine passion for music and audio',
        'Prepare for marketing cases with Spotify context',
        'Understand Spotify\'s competitive positioning',
        'Be ready to discuss data-driven personalization',
        'Prepare questions about marketing culture',
        'Show creative thinking with strategic rationale',
        'Be authentic about your marketing philosophy',
        'Research recent Spotify launches and campaigns',
        'Show how you balance art and science in marketing'
      ],
      salary: { min: 120000, max: 200000 },
      compensation: [
        'Competitive base salary with equity (RSUs)',
        'Annual performance bonuses',
        'Spotify Premium subscription for life',
        'Comprehensive health, dental, and vision coverage',
        'Generous parental leave (6 months)',
        'Flexible PTO with minimum vacation',
        '401(k) with company match',
        'Marketing conference and learning budget',
        'Industry event access',
        'Home office stipend'
      ],
      dayInLife: {
        intro: 'A day as a Marketing Manager at Spotify balances strategic planning with creative collaboration on campaigns that connect people with music.',
        schedule: [
          '9:00 AM - Review campaign performance dashboards',
          '9:30 AM - Team standup on active campaigns',
          '10:00 AM - Creative review meeting on new campaign',
          '11:00 AM - Partner with Analytics on targeting optimization',
          '12:00 PM - Lunch with colleagues from product marketing',
          '1:00 PM - Agency call on upcoming production',
          '2:00 PM - Strategy session on Q4 campaign planning',
          '3:00 PM - Cross-functional sync with Product on launch',
          '4:00 PM - Budget review and allocation',
          '5:00 PM - Social and cultural trend monitoring',
          '5:30 PM - Wrap up with campaign status updates'
        ],
        closing: 'Marketing at Spotify means building campaigns that connect hundreds of millions of people with music they love, combining creative excellence with data-driven impact.'
      },
      similarRoles: ['Senior Marketing Manager at Spotify', 'Brand Marketing Manager at Spotify', 'Growth Marketing Manager at Spotify', 'Product Marketing Manager at Spotify', 'Content Marketing Manager at Spotify']
    },

    'product-designer': {
      title: 'Product Designer',
      slug: 'product-designer',
      industry: 'Technology',
      roleDescription: `Product Designers at Spotify shape the end-to-end experience of how over 600 million users interact with music and audio. Working in autonomous squads, you'll own design from concept through launch, combining UX strategy, interaction design, and visual craft. Product Designers at Spotify are T-shaped—deep in design craft while broad in understanding product strategy, user research, and technical constraints. The role differs from UX Design in its emphasis on owning the full product experience and partnering as equals with PM and Engineering. You'll work on features that define how people discover music, create playlists, follow artists, and engage with creators. Spotify's design culture values craft excellence, experimentation, and deep user understanding. The interview process evaluates both design skills and how you collaborate to ship products that matter.`,
      responsibilities: [
        'Own end-to-end product design from concept through launch',
        'Develop design strategy aligned with product and business goals',
        'Create user flows, wireframes, prototypes, and production designs',
        'Partner with PM and Engineering as equals in squad leadership',
        'Lead design research to inform product decisions',
        'Contribute to and evolve Spotify\'s design system',
        'Present design work and build alignment across stakeholders',
        'Mentor designers and elevate team craft',
        'Design for accessibility and diverse global users'
      ],
      growthOpportunities: [
        'Progress through IC levels to Staff and Principal Product Designer',
        'Lead design for major product areas',
        'Transition into Design Management',
        'Move into Product Management',
        'Shape company design direction and strategy',
        'Lead design system evolution',
        'Work on new products and emerging platforms',
        'Represent Spotify at design conferences'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial conversation about design background' },
        { stage: 'Hiring Manager Call', description: 'Discussion of design philosophy and experience' },
        { stage: 'Portfolio Deep Dive', description: 'Detailed walkthrough of 2-3 projects showing process' },
        { stage: 'Design Exercise', description: 'Collaborative design session on audio/music problem' },
        { stage: 'Cross-functional Interviews', description: 'Sessions with PM, Engineering, and Design partners' },
        { stage: 'Values Interview', description: 'Behavioral interview on cultural fit' },
        { stage: 'Leadership Interview', description: 'Final round with design leadership' }
      ],
      technicalQuestions: [
        'How would you approach redesigning the Spotify library experience?',
        'Walk me through a project from research to launch',
        'Design a feature to help users discover live concerts',
        'How do you approach design systems at scale?',
        'Design an improved sharing experience for Spotify',
        'How do you balance user needs with business objectives?',
        'Design a feature for collaborative listening',
        'How do you approach designing for multiple platforms?',
        'Design a more personalized home screen experience',
        'How do you validate design decisions with research?',
        'Design a feature for podcast creators',
        'How do you handle design debt and system evolution?',
        'Design an improved onboarding for new users',
        'How do you approach accessibility in your designs?',
        'Design a new way to visualize listening history',
        'How do you collaborate with engineers on complex interactions?'
      ],
      behavioralQuestions: [
        'Tell me about a product you designed end-to-end',
        'Describe leading design strategy for a major initiative',
        'How have you built alignment across stakeholders?',
        'Tell me about a design you championed that faced resistance',
        'Describe collaborating with engineers on challenging implementation',
        'How have you mentored other designers?',
        'Tell me about using research to change product direction',
        'Describe designing for users unlike yourself',
        'How have you contributed to design systems?',
        'Tell me about balancing craft with shipping speed',
        'Describe handling conflicting feedback',
        'How have you grown as a designer?',
        'Tell me about a design failure and what you learned',
        'Describe your approach to presenting design work'
      ],
      whatTheyLookFor: [
        'Strong end-to-end product design portfolio',
        'Strategic thinking connecting design to product goals',
        'Craft excellence in interaction and visual design',
        'Experience partnering with PM and Engineering as equals',
        'Research skills and data-informed design',
        'Systems thinking for design at scale',
        'Communication skills for building alignment',
        'Passion for music and audio experiences',
        'Cultural fit with Spotify\'s values',
        'Growth mindset and design leadership'
      ],
      interviewTips: [
        'Prepare portfolio showing full design process',
        'Use Spotify and form strong opinions',
        'Be ready to discuss design strategy and rationale',
        'Know Spotify\'s values for the values interview',
        'Research Spotify\'s design principles',
        'Prepare for collaborative design exercises',
        'Show how you partner with PM and Engineering',
        'Be ready to discuss design systems',
        'Show genuine passion for music and audio',
        'Prepare thoughtful questions about design culture',
        'Be authentic about your design philosophy',
        'Practice articulating design decisions',
        'Show how you use data alongside intuition',
        'Be ready to discuss design leadership'
      ],
      salary: { min: 140000, max: 250000 },
      compensation: [
        'Competitive base salary with significant equity (RSUs)',
        'Annual performance bonuses',
        'Spotify Premium subscription for life',
        'Comprehensive health, dental, and vision coverage',
        'Generous parental leave (6 months)',
        'Flexible PTO with minimum vacation',
        '401(k) with company match',
        'Design conference and learning budget',
        'Latest design tools and hardware',
        'Home office stipend'
      ],
      dayInLife: {
        intro: 'A day as a Product Designer at Spotify combines strategic thinking with hands-on craft in autonomous squads.',
        schedule: [
          '9:00 AM - Review user feedback and analytics',
          '9:30 AM - Squad standup with PM and Engineering',
          '10:00 AM - Deep design work on new feature',
          '11:30 AM - Research synthesis session',
          '12:00 PM - Lunch with design team',
          '1:00 PM - Design review with stakeholders',
          '2:30 PM - Collaboration session with engineer',
          '3:30 PM - Design system contribution',
          '4:30 PM - Prototype and test new interaction',
          '5:30 PM - Wrap up with documentation'
        ],
        closing: 'Product Design at Spotify means owning the experience that connects hundreds of millions of people with music, working with talented squads that value craft and impact.'
      },
      similarRoles: ['Senior Product Designer at Spotify', 'Staff Product Designer at Spotify', 'Design Lead at Spotify', 'UX Designer at Spotify', 'Interaction Designer at Spotify']
    },

    'creator-partnerships-manager': {
      title: 'Creator Partnerships Manager',
      slug: 'creator-partnerships-manager',
      industry: 'Technology',
      roleDescription: `Creator Partnerships Managers at Spotify build relationships with the artists, podcasters, and audio creators who make the platform possible. Working at the intersection of entertainment, technology, and business, you'll develop partnerships that help creators succeed while growing Spotify's content ecosystem. The role spans artist marketing partnerships, podcast deals, exclusive content, and creator tools adoption. Spotify's mission includes giving creators opportunities to live off their art, and partnerships are central to this goal. You'll work with labels, management, agencies, and directly with creators to develop initiatives that benefit both Spotify and the creative community. The role requires understanding both the creative and business sides of the music and podcast industries, building relationships based on trust and mutual value. Creator Partnerships partners with Content Strategy on editorial features, with Product on creator tools, and with Marketing on campaigns.`,
      responsibilities: [
        'Build and manage relationships with artists, podcasters, and creators',
        'Develop partnership deals including exclusives, marketing, and content',
        'Partner with labels, management, and agencies on strategic initiatives',
        'Drive adoption of Spotify\'s creator tools and platform features',
        'Collaborate with Content Strategy on editorial partnerships',
        'Work with Marketing on creator-focused campaigns',
        'Analyze partnership performance and optimize strategies',
        'Represent Spotify at industry events and with creator community',
        'Identify emerging creators and new partnership opportunities'
      ],
      growthOpportunities: [
        'Progress to Senior Partnerships Manager and Director',
        'Specialize in music, podcasts, or emerging audio formats',
        'Move into Head of Creator Partnerships for regions or verticals',
        'Transition to General Management or business leadership',
        'Lead partnerships for new products like audiobooks',
        'Build and lead partnerships teams',
        'Shape creator strategy at executive level',
        'Work on flagship creator relationships and deals'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial discussion of partnerships experience and industry knowledge' },
        { stage: 'Hiring Manager Interview', description: 'Deep dive into partnership philosophy and deal experience' },
        { stage: 'Partnership Case Study', description: 'Develop partnership strategy for given scenario' },
        { stage: 'Cross-functional Interview', description: 'Assessment of collaboration with Content, Product, and Marketing' },
        { stage: 'Industry/Relationship Discussion', description: 'Discussion of creator relationships and industry knowledge' },
        { stage: 'Values Interview', description: 'Behavioral interview on cultural fit' },
        { stage: 'Leadership Interview', description: 'Final round with partnerships or business leader' }
      ],
      technicalQuestions: [
        'How would you approach a partnership with a major label for exclusive content?',
        'Develop a strategy for growing podcast creator partnerships',
        'How would you measure the success of a creator partnership?',
        'Design a partnership program for emerging artists',
        'How would you approach a high-profile artist relationship?',
        'Develop a strategy for driving Spotify for Artists adoption',
        'How would you structure an exclusive content deal?',
        'Design a partnership initiative for podcast creators',
        'How would you handle a difficult creator relationship?',
        'Develop a strategy for regional creator partnerships',
        'How would you balance creator needs with Spotify\'s goals?',
        'Design a co-marketing campaign with a creator',
        'How would you approach partnerships in emerging audio?',
        'Develop a framework for evaluating partnership opportunities',
        'How would you scale partnerships for long-tail creators?',
        'Design a creator success program for the platform'
      ],
      behavioralQuestions: [
        'Tell me about a partnership you developed that had significant impact',
        'Describe navigating a complex deal negotiation',
        'How have you built trust with creative partners?',
        'Tell me about a partnership that didn\'t work out',
        'Describe managing relationships across stakeholder types',
        'How have you balanced multiple partnership priorities?',
        'Tell me about advocating for creators internally',
        'Describe collaborating with product teams on creator tools',
        'How have you approached new areas of partnerships?',
        'Tell me about turning around a difficult relationship',
        'Describe measuring and communicating partnership value',
        'How have you built partnerships teams or functions?',
        'Tell me about representing your company at industry events',
        'Describe adapting partnership strategy based on results'
      ],
      whatTheyLookFor: [
        'Strong partnerships experience in music, media, or entertainment',
        'Deep industry knowledge and relationships',
        'Deal structuring and negotiation skills',
        'Cross-functional collaboration abilities',
        'Strategic thinking about partnership opportunities',
        'Communication skills for diverse stakeholders',
        'Passion for creators and the creative community',
        'Cultural fit with Spotify\'s values',
        'Results orientation with relationship focus',
        'Adaptability to evolving audio landscape'
      ],
      interviewTips: [
        'Know Spotify\'s creator initiatives and tools',
        'Prepare partnership examples with clear outcomes',
        'Show deep industry knowledge and relationships',
        'Know Spotify\'s values for the values interview',
        'Research recent Spotify creator partnerships',
        'Be ready to discuss deal structuring',
        'Show how you balance creator and platform needs',
        'Prepare questions about partnerships culture',
        'Show genuine passion for creators and music',
        'Be ready to discuss industry trends',
        'Prepare partnership cases with strategic thinking',
        'Show how you measure partnership success',
        'Be authentic about your industry experience',
        'Understand Spotify for Artists and creator tools'
      ],
      salary: { min: 120000, max: 200000 },
      compensation: [
        'Competitive base salary with equity (RSUs)',
        'Annual performance bonuses',
        'Spotify Premium subscription for life',
        'Comprehensive health, dental, and vision coverage',
        'Generous parental leave (6 months)',
        'Flexible PTO with minimum vacation',
        '401(k) with company match',
        'Industry event and conference budget',
        'Entertainment expense allowance',
        'Home office stipend'
      ],
      dayInLife: {
        intro: 'A day as a Creator Partnerships Manager at Spotify balances relationship building with strategic partnership development.',
        schedule: [
          '9:00 AM - Review partnership metrics and creator feedback',
          '9:30 AM - Team standup on active deals and relationships',
          '10:00 AM - Call with label partner on upcoming release',
          '11:00 AM - Cross-functional meeting with Product on creator tools',
          '12:00 PM - Lunch with artist manager relationship building',
          '1:30 PM - Develop partnership proposal for new initiative',
          '3:00 PM - Sync with Content Strategy on editorial partnership',
          '4:00 PM - Meeting with Marketing on creator campaign',
          '5:00 PM - Prepare for tomorrow\'s industry event',
          '5:30 PM - Wrap up with creator communication'
        ],
        closing: 'Creator Partnerships at Spotify means building relationships that help artists and creators succeed while growing the platform, working at the intersection of creativity and technology.'
      },
      similarRoles: ['Senior Creator Partnerships Manager at Spotify', 'Artist Partnerships Manager at Spotify', 'Podcast Partnerships Manager at Spotify', 'Music Partnerships Lead at Spotify', 'Business Development Manager at Spotify']
    }
