    'software-engineer': {
      title: 'Software Engineer',
      slug: 'software-engineer',
      industry: 'Technology',
      roleDescription: `Software Engineers at Airbnb build the platforms and systems that connect millions of travelers with unique accommodations and experiences worldwide. Working across teams like Pricing & Availability, Guest Growth, Host Success, and Core Platform, you'll tackle complex distributed systems challenges while maintaining the reliability that hosts and guests depend on. Airbnb's engineering culture emphasizes craftsmanship, shipping products that delight users, and maintaining systems that handle massive scale during peak travel seasons. Engineers work in a highly collaborative environment where product, design, and engineering partner closely to create experiences that feel magical. The company's "belong anywhere" mission drives technical decisions, whether you're optimizing search algorithms, building real-time messaging systems, or ensuring payment reliability across 220+ countries. Airbnb uses a modern tech stack including React, Java, Kotlin, and extensive internal tooling, with strong emphasis on testing, code review, and documentation. The interview process heavily weighs cultural fit through their core values assessment alongside technical skills.`,
      responsibilities: [
        'Design and implement scalable backend services handling millions of bookings and searches daily',
        'Build responsive web and mobile experiences using React and native technologies',
        'Collaborate with product managers and designers to ship features that improve host and guest experiences',
        'Write clean, well-tested code following Airbnb\'s engineering best practices and style guides',
        'Participate in on-call rotations to ensure platform reliability during peak travel periods',
        'Mentor junior engineers and contribute to team technical decisions and architecture reviews',
        'Optimize system performance to handle seasonal traffic spikes and global growth',
        'Contribute to internal tools and frameworks that improve developer productivity across the company'
      ],
      growthOpportunities: [
        'Progress through IC levels from L4 to Staff (L6) and Principal (L7) engineering tracks',
        'Transition into engineering management while maintaining technical involvement',
        'Lead cross-functional initiatives spanning multiple teams and product areas',
        'Become a domain expert in areas like payments, search, pricing algorithms, or trust & safety',
        'Contribute to open source projects and represent Airbnb at industry conferences',
        'Shape technical strategy and architecture for major product initiatives',
        'Build expertise in emerging technologies like ML-powered personalization'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial call covering background, experience, and role fit with discussion of Airbnb\'s mission and culture' },
        { stage: 'Technical Phone Screen', description: '60-minute coding interview via CoderPad focusing on algorithms, data structures, and problem-solving approach' },
        { stage: 'Onsite - Coding Rounds', description: 'Two 45-minute coding interviews testing algorithms, system design thinking, and code quality' },
        { stage: 'Onsite - System Design', description: '45-minute system design discussion for designing scalable systems relevant to Airbnb\'s domain' },
        { stage: 'Onsite - Core Values', description: 'Behavioral interview assessing alignment with Airbnb\'s four core values: Champion the Mission, Be a Host, Embrace the Adventure, Be a Cereal Entrepreneur' },
        { stage: 'Hiring Committee Review', description: 'Cross-functional committee reviews all feedback for final hiring decision with strong emphasis on values fit' }
      ],
      technicalQuestions: [
        'Design a search ranking system that balances relevance, availability, and host quality scores',
        'How would you implement a real-time pricing system that adjusts based on demand and local events?',
        'Design a messaging system that supports conversations between hosts and guests across time zones',
        'How would you build a review system that detects fraudulent or biased reviews?',
        'Implement an algorithm to match guests with listings based on preferences and past behavior',
        'How would you design a calendar availability system that handles complex booking rules?',
        'Design a notification system that reaches users across email, push, and SMS without overwhelming them',
        'How would you implement search autocomplete with personalization based on user history?',
        'Design a system to detect and prevent payment fraud across 220+ countries',
        'How would you build a recommendation engine for Airbnb Experiences?',
        'Implement a rate limiter that protects APIs while ensuring legitimate users aren\'t blocked',
        'How would you design the data pipeline for real-time analytics on booking patterns?',
        'Design a system for dynamic pricing that considers seasonality, events, and competitor rates',
        'How would you implement instant book verification that maintains host control?',
        'Design a photo ranking algorithm that showcases listings most effectively',
        'How would you build a system to handle partial refunds for complex multi-night bookings?'
      ],
      behavioralQuestions: [
        'Tell me about a time you championed a mission or cause you believed in despite obstacles',
        'Describe a situation where you went above and beyond to help a teammate or customer (Be a Host)',
        'Tell me about a time you embraced adventure and tried something completely new',
        'Describe a creative solution you developed that others thought was unconventional (Be a Cereal Entrepreneur)',
        'How have you built belonging in your previous teams or communities?',
        'Tell me about a project where you had to balance technical excellence with shipping quickly',
        'Describe a time you received critical feedback and how you responded',
        'How do you approach working with team members from different cultural backgrounds?',
        'Tell me about a time you simplified a complex problem for non-technical stakeholders',
        'Describe a situation where you had to make a difficult trade-off decision',
        'How have you contributed to building an inclusive engineering culture?',
        'Tell me about a time you failed and what you learned from the experience',
        'Describe how you\'ve mentored or helped grow other engineers',
        'Tell me about a time you had to push back on a product requirement'
      ],
      whatTheyLookFor: [
        'Strong alignment with Airbnb\'s mission of creating a world where anyone can belong anywhere',
        'Technical excellence combined with product intuition and user empathy',
        'Collaborative mindset with ability to partner effectively across functions',
        'Creative problem-solving approach (the "Cereal Entrepreneur" mindset)',
        'Experience building systems at scale with focus on reliability and performance',
        'Strong communication skills and ability to explain complex concepts clearly',
        'Growth mindset with genuine curiosity and desire to continuously learn',
        'Demonstrated ability to ship impactful products that improve user experiences',
        'Cultural sensitivity and appreciation for diverse perspectives',
        'Balance of pragmatism and craftsmanship in engineering approach'
      ],
      interviewTips: [
        'Deeply research Airbnb\'s four core values and prepare specific examples demonstrating each',
        'Practice coding problems on CoderPad - Airbnb uses this platform exclusively',
        'Prepare system design answers using Airbnb\'s domain (bookings, search, messaging, payments)',
        'Show genuine passion for travel and creating belonging - this matters significantly',
        'Be ready to discuss how you\'ve built inclusive environments or communities',
        'Study Airbnb\'s tech blog for insights into their engineering challenges and solutions',
        'Prepare thoughtful questions about team culture and how values are practiced daily',
        'Practice explaining your thought process clearly - communication is heavily weighted',
        'Review Airbnb\'s product thoroughly as both a guest and host perspective',
        'Be authentic in values interviews - interviewers are trained to detect rehearsed answers',
        'Prepare examples of creative or unconventional solutions you\'ve implemented',
        'Show how you balance technical quality with practical shipping constraints',
        'Discuss experiences working with global or distributed teams',
        'Research recent Airbnb product launches and be ready to discuss them technically'
      ],
      salary: { min: 160000, max: 260000 },
      compensation: [
        'Competitive base salary with significant equity grants (RSUs)',
        'Annual refresher grants based on performance and level',
        '$2,000 annual travel credit to use on Airbnb stays and Experiences',
        'Comprehensive health, dental, and vision insurance',
        'Generous parental leave policy (up to 22 weeks)',
        'Flexible PTO with encouragement to actually take vacation',
        '401(k) with company match',
        'Learning and development budget for conferences and courses',
        'Home office setup stipend for remote work',
        'Monthly wellness and fitness reimbursement'
      ],
      dayInLife: {
        intro: 'A day as a Software Engineer at Airbnb balances focused coding time with collaborative design sessions and mission-driven discussions.',
        schedule: [
          '9:00 AM - Start day reviewing notifications and catching up on team Slack channels',
          '9:30 AM - Morning standup with your squad covering sprint progress and blockers',
          '10:00 AM - Deep coding block working on a new feature for the booking flow',
          '12:00 PM - Lunch with team, often discussing travel stories and trip recommendations',
          '1:00 PM - Design review meeting with product and design partners on upcoming initiative',
          '2:30 PM - Code review for teammates\' pull requests, providing thoughtful feedback',
          '3:30 PM - Pairing session with a teammate to debug a tricky distributed systems issue',
          '4:30 PM - Writing technical documentation for the feature you\'re shipping',
          '5:30 PM - Quick sync with your manager on career goals and upcoming opportunities',
          '6:00 PM - Wrap up day, deploy to staging and monitor metrics'
        ],
        closing: 'Days at Airbnb combine technical challenge with meaningful work connecting people around the world, supported by a culture that genuinely cares about belonging.'
      },
      similarRoles: ['Backend Engineer at Airbnb', 'Frontend Engineer at Airbnb', 'Full Stack Engineer at Airbnb', 'Mobile Engineer at Airbnb', 'Platform Engineer at Airbnb']
    },

    'product-manager': {
      title: 'Product Manager',
      slug: 'product-manager',
      industry: 'Technology',
      roleDescription: `Product Managers at Airbnb shape the future of travel by leading cross-functional teams to build products that serve millions of hosts and guests worldwide. Working at the intersection of user experience, business strategy, and technical feasibility, PMs at Airbnb own end-to-end product development from identifying opportunities through launch and iteration. Airbnb's PM culture emphasizes deep user empathy—many PMs regularly host or stay on the platform to truly understand both sides of the marketplace. Teams operate with significant autonomy, and PMs are expected to be both strategic thinkers and hands-on executors. The company's design-forward culture means PMs work extremely closely with designers and researchers, often co-creating solutions rather than simply writing requirements. Airbnb's global scale presents unique challenges: products must work across 220+ countries, multiple languages, and diverse cultural expectations around hospitality. The core values—Champion the Mission, Be a Host, Embrace the Adventure, and Be a Cereal Entrepreneur—permeate every product decision, with teams constantly asking how their work contributes to a world where anyone can belong anywhere.`,
      responsibilities: [
        'Define product vision and strategy for your area in alignment with company mission and goals',
        'Lead cross-functional teams of engineers, designers, data scientists, and researchers',
        'Conduct user research and analysis to deeply understand host and guest needs across markets',
        'Write detailed product specs and work with engineering to scope and prioritize features',
        'Define success metrics and use data to measure impact and inform iteration decisions',
        'Communicate product strategy and progress to leadership and stakeholders across the company',
        'Balance marketplace health by considering both host and guest perspectives in every decision',
        'Drive experimentation through A/B testing to validate hypotheses before full rollout',
        'Partner with international teams to ensure products work globally with appropriate localization'
      ],
      growthOpportunities: [
        'Progress from PM to Senior PM to Group PM leading multiple product areas',
        'Transition to Director of Product Management overseeing entire product domains',
        'Move into general management or business leadership roles',
        'Become a domain expert in marketplace dynamics, trust & safety, or growth',
        'Lead new product initiatives from zero to one, launching entirely new offerings',
        'Build and lead high-performing product teams as a people manager',
        'Shape company strategy through influence at the executive level'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial conversation about background, interest in Airbnb, and alignment with company mission' },
        { stage: 'Hiring Manager Call', description: '45-minute deep dive into PM experience, approach to product development, and team fit' },
        { stage: 'Product Sense Interview', description: 'Case study evaluating how you approach product problems, user empathy, and prioritization' },
        { stage: 'Execution Interview', description: 'Assessment of how you work with engineering, handle trade-offs, and drive projects to completion' },
        { stage: 'Analytical Interview', description: 'Data analysis and metrics discussion testing how you use data to inform decisions' },
        { stage: 'Core Values Interview', description: 'Behavioral assessment of alignment with Airbnb\'s four core values through past experiences' },
        { stage: 'Leadership Interview', description: 'Final round with senior product leader discussing strategy, leadership, and career goals' }
      ],
      technicalQuestions: [
        'How would you improve the Airbnb search experience to increase booking conversion?',
        'Design a feature to help new hosts get their first booking faster',
        'How would you measure the success of a new trust and safety feature?',
        'Prioritize these three features: instant book improvements, messaging redesign, or review system updates',
        'How would you approach launching Airbnb in a new country with different cultural norms?',
        'Design a solution to reduce cancellation rates without hurting host flexibility',
        'How would you balance host earnings optimization with guest value perception?',
        'What metrics would you track to measure marketplace health?',
        'How would you design an experiment to test a new pricing algorithm?',
        'Design a feature to help guests discover Airbnb Experiences relevant to their trip',
        'How would you handle a situation where a feature helps guests but hurts host conversion?',
        'What would your roadmap look like for improving the host onboarding experience?',
        'How would you approach personalizing the home feed for different traveler types?',
        'Design a loyalty program that works for both frequent travelers and occasional users',
        'How would you measure and improve the quality of listings on the platform?',
        'What framework would you use to decide between building vs. buying a capability?'
      ],
      behavioralQuestions: [
        'Tell me about a product you shipped that you\'re most proud of and why',
        'Describe a time you had to make a difficult prioritization decision with incomplete information',
        'How have you championed the user when the business wanted to go a different direction?',
        'Tell me about a time you embraced adventure and tried something completely new in your product approach',
        'Describe a creative solution you developed that others initially doubted (Be a Cereal Entrepreneur)',
        'How have you built trust and collaboration with engineering teams?',
        'Tell me about a product launch that didn\'t go as planned and what you learned',
        'Describe how you\'ve incorporated diverse perspectives into product decisions',
        'How do you stay connected to users and maintain empathy at scale?',
        'Tell me about a time you had to influence without authority',
        'Describe a situation where you had to balance short-term wins with long-term strategy',
        'How have you gone above and beyond to help a teammate or stakeholder succeed?',
        'Tell me about a time you received feedback that changed your product approach',
        'How do you approach building products for users different from yourself?'
      ],
      whatTheyLookFor: [
        'Deep user empathy and genuine curiosity about host and guest experiences',
        'Strong product sense with ability to identify high-impact opportunities',
        'Data fluency combined with qualitative research skills',
        'Excellent communication and ability to inspire cross-functional teams',
        'Strategic thinking balanced with hands-on execution capability',
        'Comfort with ambiguity and ability to make decisions with incomplete information',
        'Creative problem-solving aligned with Airbnb\'s entrepreneurial culture',
        'Global mindset with appreciation for cultural differences',
        'Passion for travel and genuine connection to Airbnb\'s mission',
        'Track record of shipping impactful products that users love'
      ],
      interviewTips: [
        'Use Airbnb extensively as both guest and host before interviewing—this experience is invaluable',
        'Prepare specific examples demonstrating each of the four core values',
        'Practice product cases using Airbnb\'s actual product challenges and opportunities',
        'Show you understand marketplace dynamics and two-sided platform challenges',
        'Be ready to discuss how you\'d approach products for global, diverse user bases',
        'Demonstrate both strategic thinking and willingness to get into execution details',
        'Prepare thoughtful questions about team culture and how product decisions are made',
        'Research recent Airbnb product launches and be ready to discuss what you\'d improve',
        'Show genuine passion for the mission—interviewers can tell when it\'s authentic',
        'Practice structuring your answers clearly, especially for case questions',
        'Be ready to discuss metrics and how you\'d measure success for different features',
        'Prepare examples of creative solutions that seemed unconventional initially',
        'Show how you balance quantitative data with qualitative user insights',
        'Be authentic in values discussions—Airbnb takes culture fit very seriously'
      ],
      salary: { min: 170000, max: 280000 },
      compensation: [
        'Competitive base salary with substantial equity package (RSUs)',
        'Annual performance bonuses tied to individual and company goals',
        '$2,000 annual travel credit for Airbnb stays and Experiences',
        'Comprehensive health benefits including mental health support',
        'Generous parental leave (up to 22 weeks)',
        'Flexible PTO policy with encouragement to travel and recharge',
        '401(k) with company match',
        'Professional development budget for conferences and learning',
        'Sabbatical program for long-tenured employees',
        'Employee stock purchase program (ESPP)'
      ],
      dayInLife: {
        intro: 'A day as a Product Manager at Airbnb blends strategic thinking with hands-on collaboration, all connected to the mission of belonging.',
        schedule: [
          '8:30 AM - Review overnight metrics and user feedback from global markets',
          '9:00 AM - Morning coffee chat with design partner discussing upcoming feature concepts',
          '9:30 AM - Team standup reviewing sprint progress and addressing blockers',
          '10:00 AM - User research session observing hosts onboard new listings',
          '11:30 AM - One-on-one with engineering lead planning next quarter\'s technical investments',
          '12:00 PM - Lunch with cross-functional partners from marketing and policy teams',
          '1:00 PM - Product review presenting roadmap to leadership and gathering feedback',
          '2:30 PM - Deep work time writing product spec for new feature initiative',
          '4:00 PM - A/B test analysis review with data science partner',
          '5:00 PM - Sync with international PM counterpart on localization requirements',
          '5:30 PM - Wrap up with quick check on experiment results and next-day prep'
        ],
        closing: 'Product management at Airbnb means constant connection to users, close partnership with world-class designers and engineers, and the satisfaction of building products that help people belong anywhere.'
      },
      similarRoles: ['Senior Product Manager at Airbnb', 'Group Product Manager at Airbnb', 'Product Lead at Airbnb', 'Growth PM at Airbnb', 'Platform PM at Airbnb']
    },

    'engineering-manager': {
      title: 'Engineering Manager',
      slug: 'engineering-manager',
      industry: 'Technology',
      roleDescription: `Engineering Managers at Airbnb lead teams building the technology that powers global travel and hospitality. Unlike companies where EMs are purely people managers, Airbnb expects EMs to maintain technical credibility, contribute to architectural decisions, and deeply understand the systems their teams own. You'll lead teams of 5-10 engineers working on critical areas like search and discovery, payments, trust and safety, or host tools, balancing technical excellence with people development. Airbnb's culture heavily emphasizes the "Be a Host" value in management—creating environments where engineers feel welcomed, supported, and able to do their best work. EMs partner closely with Product Managers and Design leads as part of "triads" that collectively own product outcomes. The company's global scale means managing complexity across time zones, diverse user needs, and systems that must maintain reliability during peak travel seasons. Career growth paths support both continued people management and return to individual contributor roles, reflecting Airbnb's belief that great leaders should have options.`,
      responsibilities: [
        'Lead, mentor, and grow a team of 5-10 software engineers across experience levels',
        'Partner with Product and Design as part of a triad to drive product strategy and execution',
        'Conduct regular one-on-ones, performance reviews, and career development conversations',
        'Contribute to technical architecture and code review to maintain hands-on understanding',
        'Build inclusive team culture aligned with Airbnb\'s core values, especially "Be a Host"',
        'Drive hiring for your team including interview calibration and process improvement',
        'Manage project execution ensuring on-time delivery while maintaining engineering quality',
        'Collaborate with other EMs to drive engineering-wide initiatives and best practices',
        'Handle on-call escalations and ensure team maintains production reliability standards'
      ],
      growthOpportunities: [
        'Progress to Senior Engineering Manager leading multiple teams or larger scope',
        'Advance to Director of Engineering overseeing entire product areas',
        'Move into VP of Engineering role with executive responsibilities',
        'Transition back to Staff or Principal Engineer roles (path is supported)',
        'Lead new organization formation as Airbnb expands into new areas',
        'Drive engineering-wide transformation initiatives',
        'Build expertise in specific domains becoming the company authority'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial discussion of management experience, leadership style, and interest in Airbnb' },
        { stage: 'Hiring Manager Interview', description: 'Deep dive into management philosophy, team building experience, and technical background' },
        { stage: 'Technical Assessment', description: 'System design or architecture discussion demonstrating technical depth and decision-making' },
        { stage: 'People Management Interview', description: 'Scenarios covering difficult conversations, team dynamics, and performance management' },
        { stage: 'Cross-functional Interview', description: 'Assessment of partnership skills with Product and Design counterparts' },
        { stage: 'Core Values Interview', description: 'Behavioral assessment focused on demonstrating Airbnb\'s four core values through leadership examples' },
        { stage: 'Executive Interview', description: 'Final round with senior engineering leader discussing strategy and organizational fit' }
      ],
      technicalQuestions: [
        'Describe your approach to balancing technical debt reduction with feature development',
        'How do you make build vs. buy decisions for your team\'s systems?',
        'Walk me through a complex system your team owns and key architectural decisions',
        'How do you ensure your team maintains on-call reliability standards?',
        'Describe your approach to driving technical standards across multiple teams',
        'How do you stay technically credible while spending significant time on management?',
        'How would you approach migrating a critical system with zero downtime?',
        'Describe your process for conducting architecture reviews',
        'How do you balance team velocity with code quality and testing standards?',
        'What\'s your approach to capacity planning for systems with seasonal traffic?',
        'How do you evaluate and adopt new technologies on your team?',
        'Describe a technical decision you made that didn\'t work out and what you learned',
        'How do you approach system reliability and SLO setting for your team?',
        'What\'s your philosophy on code review and engineering best practices?',
        'How do you handle disagreements between engineers on technical approaches?',
        'Describe your approach to incident management and post-mortems'
      ],
      behavioralQuestions: [
        'Tell me about a time you helped an underperforming engineer turn around their performance',
        'Describe how you\'ve built an inclusive team culture where everyone feels they belong',
        'How have you championed a mission or initiative that required significant organizational change?',
        'Tell me about a time you embraced adventure and tried a completely new management approach',
        'Describe a creative solution to a team or organizational challenge (Be a Cereal Entrepreneur)',
        'How do you handle giving critical feedback to a high performer?',
        'Tell me about a time you had to manage through organizational uncertainty or change',
        'How have you gone above and beyond to support a team member\'s growth (Be a Host)?',
        'Describe a situation where you had to balance team needs with business demands',
        'How do you approach building psychological safety on your team?',
        'Tell me about the most difficult termination decision you\'ve made',
        'How do you develop senior engineers into leadership roles?',
        'Describe how you\'ve partnered with Product to influence roadmap priorities',
        'Tell me about a time you had to make an unpopular decision'
      ],
      whatTheyLookFor: [
        'Strong people leadership with genuine care for team member growth and wellbeing',
        'Technical credibility to earn respect and make sound architectural decisions',
        'Embodiment of "Be a Host" creating welcoming, inclusive team environments',
        'Strategic thinking about team building, technical direction, and organizational design',
        'Excellent partnership skills with Product and Design counterparts',
        'Track record of building high-performing, engaged engineering teams',
        'Clear communication style effective with engineers, executives, and cross-functional partners',
        'Growth mindset applying to both self-development and team development',
        'Alignment with Airbnb\'s mission and ability to connect team work to company purpose',
        'Comfort with ambiguity and ability to lead through uncertainty'
      ],
      interviewTips: [
        'Prepare specific examples of how you\'ve embodied each of Airbnb\'s four core values as a leader',
        'Be ready to discuss your management philosophy and how it\'s evolved over time',
        'Prepare to demonstrate technical depth—Airbnb EMs need credibility with engineers',
        'Have concrete examples of building inclusive teams and supporting diverse engineers',
        'Practice discussing difficult management situations with nuance and learning orientation',
        'Understand Airbnb\'s triad model and be ready to discuss cross-functional partnership',
        'Research Airbnb\'s engineering culture through tech blog posts and employee interviews',
        'Be authentic about your leadership style—Airbnb values genuine leaders',
        'Prepare questions about engineering culture, growth opportunities, and team challenges',
        'Show how you connect team work to larger mission and purpose',
        'Be ready to discuss how you maintain technical skills while managing',
        'Prepare examples of creative approaches to team or organizational challenges',
        'Practice articulating how you\'ve grown engineers from junior to senior levels',
        'Show vulnerability—discuss mistakes you\'ve made and how you\'ve learned from them'
      ],
      salary: { min: 200000, max: 320000 },
      compensation: [
        'Competitive base salary with significant equity grants (RSUs)',
        'Annual refresher grants based on performance and scope growth',
        'Performance bonuses tied to team and company goals',
        '$2,000 annual travel credit for Airbnb stays and Experiences',
        'Comprehensive health, dental, and vision coverage',
        'Generous parental leave (up to 22 weeks)',
        'Flexible PTO with expectation that managers model healthy time off',
        '401(k) with company match',
        'Leadership development programs and executive coaching',
        'Home office setup and ongoing remote work support'
      ],
      dayInLife: {
        intro: 'A day as an Engineering Manager at Airbnb balances people leadership, technical engagement, and strategic partnership.',
        schedule: [
          '8:30 AM - Review team dashboards and overnight on-call activity before meetings',
          '9:00 AM - One-on-one with engineer discussing career goals and current project challenges',
          '9:30 AM - Team standup facilitating discussion of sprint progress and dependencies',
          '10:00 AM - Triad meeting with PM and Design lead planning next quarter initiatives',
          '11:00 AM - Architecture review providing input on major technical decision',
          '12:00 PM - Lunch with new team member as part of onboarding buddy program',
          '1:00 PM - Engineering leadership meeting discussing hiring and organizational topics',
          '2:00 PM - Code review and technical deep-dive to stay connected to team\'s work',
          '3:00 PM - Interview debrief calibrating on recent engineering candidates',
          '4:00 PM - One-on-one with struggling engineer providing support and coaching',
          '5:00 PM - Prepare for tomorrow\'s performance review conversation',
          '5:30 PM - Quick team wins celebration before wrapping up'
        ],
        closing: 'Engineering management at Airbnb means building teams that do their best work, staying technically engaged, and creating environments where everyone can belong.'
      },
      similarRoles: ['Senior Engineering Manager at Airbnb', 'Director of Engineering at Airbnb', 'Technical Program Manager at Airbnb', 'Staff Engineer at Airbnb']
    },

    'data-scientist': {
      title: 'Data Scientist',
      slug: 'data-scientist',
      industry: 'Technology',
      roleDescription: `Data Scientists at Airbnb drive decision-making across the company through rigorous experimentation, advanced analytics, and machine learning. Working on one of the world's largest marketplace datasets, you'll tackle challenges spanning pricing optimization, search ranking, fraud detection, demand forecasting, and user personalization. Airbnb pioneered many industry-standard experimentation practices and maintains a strong culture of data-driven decision making. Data Scientists work embedded within product teams, partnering closely with Product Managers and Engineers to identify opportunities, design experiments, and build data products that improve host and guest experiences. The company's two-sided marketplace creates unique analytical challenges—every change affects both hosts and guests, often in complex ways. Airbnb's data infrastructure is world-class, with extensive internal tools for experimentation, feature engineering, and ML model deployment. The team publishes regularly on their approaches, contributing to the broader data science community. You'll join a team of exceptional scientists who bring diverse backgrounds in statistics, economics, physics, and computer science.`,
      responsibilities: [
        'Design and analyze A/B tests to measure product impact and guide decision-making',
        'Build machine learning models for ranking, personalization, pricing, and fraud detection',
        'Partner with Product Managers to define metrics and success criteria for product initiatives',
        'Develop deep understanding of user behavior through exploratory analysis and research',
        'Create dashboards and automated reports to monitor key business metrics',
        'Contribute to Airbnb\'s data infrastructure and experiment platform improvements',
        'Present findings to leadership and influence strategic product decisions',
        'Mentor junior data scientists and contribute to team best practices',
        'Collaborate with ML Engineers to productionize models at scale'
      ],
      growthOpportunities: [
        'Progress through IC levels to Staff and Principal Data Scientist',
        'Transition into Data Science management leading teams of scientists',
        'Specialize in machine learning engineering or applied research',
        'Move into Product Management leveraging analytical foundation',
        'Become a domain expert in marketplace economics, pricing, or personalization',
        'Lead cross-functional initiatives shaping company data strategy',
        'Contribute to open source and publish research advancing the field'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial conversation covering background, experience, and interest in Airbnb\'s data challenges' },
        { stage: 'Technical Phone Screen', description: '45-minute screen covering statistics, experimentation design, and analytical problem-solving' },
        { stage: 'Take-Home Assignment', description: 'Data analysis project using sample dataset, typically 4-6 hours of work' },
        { stage: 'Onsite - Case Study', description: 'Product analytics case testing metrics definition, analysis approach, and business thinking' },
        { stage: 'Onsite - Technical Deep Dive', description: 'Assessment of statistics, ML, and coding skills through applied problems' },
        { stage: 'Onsite - Core Values', description: 'Behavioral interview assessing alignment with Airbnb\'s four core values' },
        { stage: 'Onsite - Presentation', description: 'Present take-home results to team, demonstrating communication and analytical rigor' }
      ],
      technicalQuestions: [
        'How would you design an experiment to test a new search ranking algorithm?',
        'Explain how you\'d detect and handle network effects in an A/B test on our platform',
        'How would you build a pricing recommendation model for hosts?',
        'Describe your approach to measuring the long-term impact of a product change',
        'How would you design a fraud detection system for fake reviews?',
        'Explain how you\'d handle multiple comparisons in an experiment with many variants',
        'How would you build a demand forecasting model accounting for seasonality and events?',
        'Describe techniques for dealing with selection bias in marketplace experiments',
        'How would you measure and improve the quality of Airbnb listings?',
        'Explain your approach to causal inference when A/B testing isn\'t possible',
        'How would you build a recommendation system for personalized search results?',
        'Describe how you\'d analyze cannibalization effects between listings',
        'How would you design metrics to capture marketplace health?',
        'Explain techniques for handling imbalanced classes in fraud detection',
        'How would you approach attribution modeling for marketing effectiveness?',
        'Describe your process for feature engineering in a large-scale ML system'
      ],
      behavioralQuestions: [
        'Tell me about an analysis that significantly changed a product decision',
        'Describe a time when your data contradicted stakeholder expectations',
        'How have you championed data-driven decision making in a skeptical environment?',
        'Tell me about a time you embraced adventure and tried a novel analytical approach',
        'Describe a creative solution to a data problem that others hadn\'t considered (Be a Cereal Entrepreneur)',
        'How have you helped non-technical stakeholders understand complex analysis?',
        'Tell me about an analysis you later realized was flawed and how you handled it',
        'How have you gone above and beyond to support a teammate or stakeholder (Be a Host)?',
        'Describe a situation where you had to balance rigor with speed',
        'How do you approach understanding users who are different from yourself?',
        'Tell me about a time you had to influence a decision without direct authority',
        'Describe how you\'ve mentored or developed other data scientists',
        'How have you contributed to building an inclusive team culture?',
        'Tell me about navigating ambiguity in a project with unclear requirements'
      ],
      whatTheyLookFor: [
        'Strong statistical foundation with expertise in experimental design and causal inference',
        'Machine learning skills applicable to ranking, recommendation, and classification problems',
        'Excellent communication ability to explain complex findings to diverse audiences',
        'Product intuition and business acumen connecting analysis to user and company impact',
        'Coding proficiency in Python or R with SQL expertise',
        'Intellectual curiosity and passion for using data to understand human behavior',
        'Collaborative mindset working effectively with Product, Engineering, and Design',
        'Alignment with Airbnb\'s mission and values, especially user empathy',
        'Rigor balanced with pragmatism—knowing when perfect is the enemy of good',
        'Growth mindset with desire to continuously learn and improve'
      ],
      interviewTips: [
        'Deeply review Airbnb\'s Medium publications on experimentation and data science',
        'Practice product sense cases using Airbnb\'s actual product as context',
        'Prepare to discuss your approach to common DS challenges: selection bias, network effects, multiple testing',
        'Be ready to write SQL and Python code to solve analytical problems',
        'Understand Airbnb\'s two-sided marketplace dynamics and how they affect analysis',
        'Prepare specific examples demonstrating each of the four core values',
        'Practice explaining statistical concepts to non-technical audiences',
        'Review your past work for examples of analysis driving business impact',
        'Be ready to discuss machine learning fundamentals and when to apply different techniques',
        'Prepare thoughtful questions about team culture, data infrastructure, and challenges',
        'Show genuine curiosity about Airbnb\'s unique data challenges',
        'Practice the take-home presentation with focus on clear communication',
        'Be ready to discuss limitations and assumptions in your analyses',
        'Show how you balance statistical rigor with practical business needs'
      ],
      salary: { min: 165000, max: 280000 },
      compensation: [
        'Competitive base salary with substantial equity grants (RSUs)',
        'Annual performance bonuses and equity refreshers',
        '$2,000 annual travel credit for Airbnb stays and Experiences',
        'Comprehensive health, dental, and vision insurance',
        'Generous parental leave (up to 22 weeks)',
        'Flexible PTO policy encouraging actual time off',
        '401(k) with company match',
        'Conference attendance and professional development budget',
        'Access to internal data science training and learning resources',
        'Home office setup stipend'
      ],
      dayInLife: {
        intro: 'A day as a Data Scientist at Airbnb balances deep analytical work with collaborative partnership and strategic thinking.',
        schedule: [
          '9:00 AM - Review experiment results from overnight data pipeline runs',
          '9:30 AM - Team standup discussing ongoing analyses and upcoming experiments',
          '10:00 AM - Deep work on pricing model feature engineering',
          '11:30 AM - Meeting with PM to discuss metrics framework for new initiative',
          '12:00 PM - Lunch with data science colleagues sharing interesting findings',
          '1:00 PM - Experiment review meeting presenting A/B test results to stakeholders',
          '2:00 PM - Code review for teammate\'s model implementation',
          '2:30 PM - SQL analysis exploring user behavior patterns for new hypothesis',
          '4:00 PM - Office hours helping product team interpret dashboards',
          '4:30 PM - One-on-one with manager discussing career growth',
          '5:00 PM - Document findings and prepare presentation for tomorrow',
          '5:30 PM - Wrap up and review next day\'s priorities'
        ],
        closing: 'Data Science at Airbnb means working on impactful problems with world-class colleagues, using data to improve how people connect and belong around the world.'
      },
      similarRoles: ['Senior Data Scientist at Airbnb', 'Staff Data Scientist at Airbnb', 'ML Engineer at Airbnb', 'Analytics Engineer at Airbnb', 'Research Scientist at Airbnb']
    }
