    'machine-learning-engineer': {
      title: 'Machine Learning Engineer',
      slug: 'machine-learning-engineer',
      industry: 'Technology',
      roleDescription: `Machine Learning Engineers at Airbnb build the intelligent systems that power search ranking, pricing recommendations, personalization, fraud detection, and demand forecasting across the world's largest hospitality marketplace. Unlike pure research roles, MLEs at Airbnb focus on building production ML systems that serve millions of users daily, requiring strong engineering skills alongside ML expertise. You'll work with some of the richest behavioral data in travel—booking patterns, search intent, host-guest interactions, and seasonal trends across 220+ countries. Airbnb has pioneered many ML infrastructure innovations, including sophisticated experimentation platforms and feature stores that enable rapid model iteration. Teams work on challenges unique to two-sided marketplaces: optimizing for both host success and guest satisfaction simultaneously. The company's ML culture emphasizes pragmatism—using the right technique for the problem rather than chasing novel approaches. You'll partner closely with Data Scientists for experimentation, Product Managers for strategy, and platform teams to scale your models. Airbnb's core values, especially "Be a Cereal Entrepreneur," encourage creative approaches to seemingly intractable problems.`,
      responsibilities: [
        'Design, build, and deploy machine learning models for search ranking, pricing, and personalization',
        'Build robust ML pipelines handling feature engineering, training, and serving at scale',
        'Partner with Data Scientists to translate experimental models into production systems',
        'Develop and maintain ML infrastructure including feature stores, model serving, and monitoring',
        'Conduct A/B tests to measure model impact on key business metrics',
        'Optimize model performance for latency, cost, and accuracy trade-offs',
        'Collaborate with Product teams to identify ML opportunities that improve user experiences',
        'Mentor engineers on ML best practices and contribute to team technical standards',
        'Stay current with ML research and evaluate applicability to Airbnb problems'
      ],
      growthOpportunities: [
        'Progress through IC levels to Staff and Principal ML Engineer',
        'Specialize in areas like NLP, computer vision, recommendations, or forecasting',
        'Transition into ML Platform engineering building core infrastructure',
        'Move into Research Scientist roles for more exploratory work',
        'Lead ML architecture decisions across multiple product areas',
        'Build and lead ML teams as an Engineering Manager',
        'Contribute to open source and advance Airbnb\'s ML reputation'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial call covering ML experience, background, and interest in Airbnb\'s challenges' },
        { stage: 'Technical Phone Screen', description: '60-minute interview covering ML fundamentals, coding, and system design' },
        { stage: 'Onsite - ML Depth', description: 'Deep dive into ML algorithms, model selection, and feature engineering approach' },
        { stage: 'Onsite - Coding', description: 'Algorithmic coding interview testing implementation skills and code quality' },
        { stage: 'Onsite - ML System Design', description: 'Design end-to-end ML system for Airbnb-relevant problem' },
        { stage: 'Onsite - Core Values', description: 'Behavioral assessment of alignment with Airbnb\'s four core values' },
        { stage: 'Team Matching', description: 'Discussions with potential teams to find right fit' }
      ],
      technicalQuestions: [
        'Design a search ranking system that balances listing relevance with host success',
        'How would you build a dynamic pricing recommendation engine for hosts?',
        'Explain your approach to handling cold-start problems for new listings',
        'Design a real-time fraud detection system for fake bookings',
        'How would you build a personalized home feed for returning users?',
        'Describe techniques for handling class imbalance in cancellation prediction',
        'How would you design an ML system for demand forecasting across cities?',
        'Explain your approach to feature engineering for a recommendation system',
        'How would you detect and handle concept drift in production models?',
        'Design an ML pipeline for image quality scoring of listing photos',
        'How would you approach multi-objective optimization in marketplace ranking?',
        'Explain techniques for interpretable ML in pricing recommendations',
        'How would you build an NLP system for review sentiment analysis?',
        'Describe your approach to online learning for real-time personalization',
        'How would you design a similar listings recommendation system?',
        'Explain your strategy for A/B testing ML model changes'
      ],
      behavioralQuestions: [
        'Tell me about an ML model you deployed that had significant business impact',
        'Describe a time you chose a simpler approach over a more complex model',
        'How have you championed the mission in your ML work?',
        'Tell me about a time you embraced adventure with a novel ML technique',
        'Describe a creative solution to an ML problem that others hadn\'t considered (Be a Cereal Entrepreneur)',
        'How have you helped non-technical stakeholders understand ML capabilities and limitations?',
        'Tell me about an ML project that failed and what you learned',
        'How have you gone above and beyond to help a teammate succeed (Be a Host)?',
        'Describe how you balance model complexity with maintainability',
        'How do you approach building ML systems for users different from yourself?',
        'Tell me about a time you had to influence a product decision with ML insights',
        'Describe how you\'ve mentored others in ML best practices',
        'How have you contributed to an inclusive team culture?',
        'Tell me about debugging a challenging ML issue in production'
      ],
      whatTheyLookFor: [
        'Strong ML fundamentals with experience deploying models in production',
        'Excellent software engineering skills for building robust ML systems',
        'Experience with ranking, recommendations, or marketplace ML problems',
        'Pragmatic approach choosing the right technique for the problem',
        'Strong communication skills explaining ML to diverse audiences',
        'Collaborative mindset working with Data Science, Product, and Engineering',
        'Curiosity and passion for solving complex ML challenges',
        'Alignment with Airbnb\'s mission and core values',
        'Experience with ML infrastructure and scalable system design',
        'Growth mindset and desire to continuously learn'
      ],
      interviewTips: [
        'Review Airbnb\'s tech blog for ML posts on ranking, personalization, and infrastructure',
        'Practice ML system design focusing on end-to-end production systems',
        'Be ready to discuss trade-offs between model complexity and operational concerns',
        'Prepare examples demonstrating each of Airbnb\'s four core values',
        'Understand two-sided marketplace dynamics and their ML implications',
        'Practice coding ML implementations in Python with clean, tested code',
        'Be ready to explain feature engineering strategies for different problem types',
        'Prepare questions about ML infrastructure and team challenges',
        'Show genuine interest in Airbnb\'s unique ML problems',
        'Be ready to discuss when simpler approaches beat complex models',
        'Review recommendation system fundamentals and ranking algorithms',
        'Prepare to discuss model monitoring and handling production issues',
        'Show how you balance innovation with pragmatic shipping',
        'Be authentic in values discussions—Airbnb values genuine fit'
      ],
      salary: { min: 180000, max: 300000 },
      compensation: [
        'Highly competitive base salary with significant equity (RSUs)',
        'Annual refresher grants based on performance',
        '$2,000 annual travel credit for Airbnb stays and Experiences',
        'Comprehensive health, dental, and vision coverage',
        'Generous parental leave (up to 22 weeks)',
        'Flexible PTO policy',
        '401(k) with company match',
        'Conference attendance and ML learning budget',
        'Access to GPU resources for experimentation',
        'Home office and equipment stipend'
      ],
      dayInLife: {
        intro: 'A day as an ML Engineer at Airbnb combines deep technical work with collaborative product partnership.',
        schedule: [
          '9:00 AM - Review model performance dashboards and overnight experiment results',
          '9:30 AM - Team standup discussing ML projects and blockers',
          '10:00 AM - Deep work on feature engineering for new ranking model',
          '12:00 PM - Lunch with ML colleagues discussing recent papers',
          '1:00 PM - Meeting with PM to discuss ML approach for new product initiative',
          '2:00 PM - Code review for teammate\'s model training pipeline',
          '3:00 PM - Experiment analysis meeting reviewing A/B test results with Data Science',
          '4:00 PM - Debug model serving latency issue with platform team',
          '5:00 PM - Write design doc for upcoming ML system improvement',
          '5:30 PM - Wrap up with experiment monitoring check'
        ],
        closing: 'ML Engineering at Airbnb means building systems that directly improve travel experiences for millions while working with world-class colleagues on unique marketplace challenges.'
      },
      similarRoles: ['Senior ML Engineer at Airbnb', 'Staff ML Engineer at Airbnb', 'Research Scientist at Airbnb', 'ML Platform Engineer at Airbnb', 'Data Scientist at Airbnb']
    },

    'ux-designer': {
      title: 'UX Designer',
      slug: 'ux-designer',
      industry: 'Technology',
      roleDescription: `UX Designers at Airbnb craft experiences that help travelers find unique places to stay and hosts share their homes with the world. Working in one of the most design-forward technology companies, you'll join a team that has shaped how millions think about travel and hospitality. Airbnb's design culture is legendary—co-founder Brian Chesky's design background has permeated the company, making design a core strategic function rather than a service. Designers work embedded in product triads with Product Managers and Engineering leads, having equal voice in product direction. The company's design system ensures consistency while allowing creativity for novel experiences. You'll design for an incredibly diverse user base spanning 220+ countries, multiple languages, and vastly different cultural expectations around hospitality and travel. Airbnb Experiences, Luxe properties, and long-term stays each require distinct design thinking. The "Be a Host" value means designing with empathy for both hosts sharing their homes and guests seeking belonging. User research is deeply integrated, with designers regularly participating in interviews and usability testing to stay connected to real user needs.`,
      responsibilities: [
        'Design intuitive user experiences for web and mobile across guest and host journeys',
        'Conduct user research including interviews, usability testing, and journey mapping',
        'Create wireframes, prototypes, and high-fidelity designs using Figma',
        'Partner closely with PM and Engineering as part of product triads',
        'Contribute to and evolve Airbnb\'s design system ensuring consistency',
        'Present design work to leadership and incorporate feedback effectively',
        'Design for global accessibility across languages, cultures, and abilities',
        'Collaborate with researchers to develop deep user empathy',
        'Mentor junior designers and contribute to design team culture'
      ],
      growthOpportunities: [
        'Progress through IC levels to Senior, Staff, and Principal Designer',
        'Specialize in areas like motion design, design systems, or interaction design',
        'Transition into Design Management leading design teams',
        'Move into Product Management leveraging design foundation',
        'Lead design for major new product initiatives from zero to one',
        'Shape company design direction and strategy',
        'Become a thought leader representing Airbnb at industry conferences'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial conversation about design background, portfolio, and interest in Airbnb' },
        { stage: 'Hiring Manager Call', description: 'Deep discussion of design philosophy, process, and team fit' },
        { stage: 'Portfolio Review', description: 'Detailed walkthrough of past work focusing on process, decisions, and outcomes' },
        { stage: 'Design Exercise', description: 'Take-home or whiteboard exercise solving Airbnb-relevant design problem' },
        { stage: 'Onsite - Craft Review', description: 'Assessment of design skills, attention to detail, and design system thinking' },
        { stage: 'Onsite - Cross-functional', description: 'Interviews with PM and Engineering assessing collaboration approach' },
        { stage: 'Onsite - Core Values', description: 'Behavioral assessment of alignment with Airbnb\'s four core values' }
      ],
      technicalQuestions: [
        'Walk me through your design process from problem definition to launch',
        'How would you redesign the Airbnb search experience for first-time users?',
        'Design a feature to help hosts improve their listing quality',
        'How do you approach designing for users across different cultures?',
        'Show us how you\'ve used data to inform design decisions',
        'How would you design an onboarding flow for new hosts?',
        'Describe your approach to mobile-first design for travel contexts',
        'How do you handle feedback that challenges your design direction?',
        'Design an experience for booking group trips with multiple decision-makers',
        'How do you balance consistency with innovation in a design system?',
        'Show us how you collaborate with engineers during implementation',
        'How would you design for accessibility in a visually-rich product?',
        'Design a feature to help guests discover Airbnb Experiences',
        'How do you prioritize when you have multiple design projects?',
        'Show us how you prototype and test ideas quickly',
        'How would you design for trust between strangers in a marketplace?'
      ],
      behavioralQuestions: [
        'Tell me about a design you\'re most proud of and why',
        'Describe a time you had to advocate for the user against business pressure',
        'How have you championed a design mission that required changing minds?',
        'Tell me about a time you embraced adventure with an unconventional design approach',
        'Describe a creative solution that others initially doubted (Be a Cereal Entrepreneur)',
        'How have you created welcoming experiences for users (Be a Host)?',
        'Tell me about design feedback that significantly changed your approach',
        'How do you build trust and collaboration with engineering partners?',
        'Describe a design that didn\'t work as expected and what you learned',
        'How have you designed for users very different from yourself?',
        'Tell me about navigating ambiguity in a design project',
        'How have you mentored or helped grow other designers?',
        'Describe building inclusive design culture on your team',
        'Tell me about balancing design quality with shipping speed'
      ],
      whatTheyLookFor: [
        'Strong portfolio demonstrating end-to-end product design skills',
        'Deep user empathy with ability to design for diverse global audiences',
        'Excellent collaboration skills working with PM, Engineering, and Research',
        'Clear communication presenting design rationale to various stakeholders',
        'Strategic thinking connecting design work to business outcomes',
        'Craft excellence with attention to visual and interaction details',
        'Growth mindset with openness to feedback and iteration',
        'Alignment with Airbnb\'s mission and especially "Be a Host" value',
        'Design system thinking balancing consistency with creativity',
        'Passion for travel and creating experiences of belonging'
      ],
      interviewTips: [
        'Prepare a portfolio that tells stories of process, not just final designs',
        'Use Airbnb extensively as both guest and host to understand the product deeply',
        'Practice presenting designs with clear rationale and business context',
        'Prepare specific examples demonstrating each of Airbnb\'s four core values',
        'Be ready to discuss designing for diverse global audiences',
        'Show how you collaborate with PM and Engineering in your work',
        'Prepare for design exercises with structured problem-solving approach',
        'Research Airbnb\'s design culture through Medium posts and conference talks',
        'Be ready to discuss failures and what you learned from them',
        'Show genuine passion for hospitality and creating belonging',
        'Prepare thoughtful questions about design culture and team structure',
        'Be authentic—Airbnb values genuine alignment over polished answers',
        'Practice articulating design decisions with multiple options and trade-offs',
        'Show how you use research and data alongside design intuition'
      ],
      salary: { min: 140000, max: 240000 },
      compensation: [
        'Competitive base salary with equity grants (RSUs)',
        'Annual performance bonuses and refresher grants',
        '$2,000 annual travel credit for Airbnb stays and Experiences',
        'Comprehensive health, dental, and vision insurance',
        'Generous parental leave (up to 22 weeks)',
        'Flexible PTO policy',
        '401(k) with company match',
        'Design conference and learning budget',
        'Latest hardware and software tools',
        'Home office setup stipend'
      ],
      dayInLife: {
        intro: 'A day as a UX Designer at Airbnb blends creative exploration with collaborative refinement and user connection.',
        schedule: [
          '9:00 AM - Review user research findings from recent study',
          '9:30 AM - Triad standup with PM and Engineering lead on sprint progress',
          '10:00 AM - Deep design work on new feature concepts in Figma',
          '12:00 PM - Lunch with design teammates sharing inspiration and feedback',
          '1:00 PM - User testing session observing guests book their first stay',
          '2:30 PM - Design critique with broader design team',
          '3:30 PM - Sync with engineer on implementation details and edge cases',
          '4:30 PM - Prototype new interaction for tomorrow\'s user test',
          '5:00 PM - Document design decisions and update specifications',
          '5:30 PM - Wrap up reviewing tomorrow\'s schedule'
        ],
        closing: 'Design at Airbnb means crafting experiences that help people belong anywhere in the world, supported by a culture that truly values design as a core function.'
      },
      similarRoles: ['Senior UX Designer at Airbnb', 'Product Designer at Airbnb', 'Design Lead at Airbnb', 'Interaction Designer at Airbnb', 'Visual Designer at Airbnb']
    },

    'trust-and-safety-manager': {
      title: 'Trust & Safety Manager',
      slug: 'trust-and-safety-manager',
      industry: 'Technology',
      roleDescription: `Trust & Safety Managers at Airbnb protect the community of hosts and guests that makes global travel possible. In a platform where strangers open their homes to other strangers, trust is the fundamental product—and your role is to ensure it's maintained through policy development, risk mitigation, and incident response. You'll lead teams that handle everything from fraud prevention and identity verification to community standards enforcement and crisis response. Airbnb's T&S organization is among the most sophisticated in tech, developing approaches that balance safety with the openness that makes the platform magical. The role requires navigating complex trade-offs: protecting users without creating friction, enforcing standards while respecting cultural differences, and maintaining community trust while handling sensitive incidents. You'll work across policy, product, operations, and legal teams, driving initiatives that have real-world safety implications. The "Be a Host" value is paramount—creating environments where people feel safe and welcomed is core to Airbnb's mission. This role has significant impact on lives around the world, making it both challenging and deeply meaningful.`,
      responsibilities: [
        'Lead teams developing and enforcing community standards and safety policies',
        'Design trust and safety systems for fraud prevention, identity verification, and risk detection',
        'Manage incident response for safety-critical situations affecting hosts and guests',
        'Partner with Product and Engineering to build safety features into the platform',
        'Develop escalation protocols and train support teams on sensitive cases',
        'Analyze safety data to identify emerging risks and prevention opportunities',
        'Collaborate with legal and policy teams on regulatory compliance globally',
        'Build relationships with law enforcement and safety organizations worldwide',
        'Lead crisis response efforts for high-profile incidents'
      ],
      growthOpportunities: [
        'Progress to Senior and Director levels within Trust & Safety',
        'Specialize in areas like fraud, physical safety, content moderation, or compliance',
        'Move into Head of Trust & Safety with executive responsibilities',
        'Transition to Policy or Legal roles leveraging T&S expertise',
        'Lead new T&S initiatives as Airbnb expands into new markets',
        'Shape industry standards for platform safety',
        'Build and grow high-performing T&S teams'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial discussion of T&S experience, background, and interest in Airbnb' },
        { stage: 'Hiring Manager Interview', description: 'Deep dive into T&S philosophy, leadership style, and complex case handling' },
        { stage: 'Case Study', description: 'Scenario-based exercise on handling complex safety situations' },
        { stage: 'Cross-functional Interview', description: 'Assessment of collaboration with Legal, Policy, Product, and Operations' },
        { stage: 'Leadership Interview', description: 'Evaluation of team leadership, stakeholder management, and strategic thinking' },
        { stage: 'Core Values Interview', description: 'Behavioral assessment of alignment with Airbnb\'s four core values' },
        { stage: 'Executive Interview', description: 'Final round with senior T&S leader discussing strategy and fit' }
      ],
      technicalQuestions: [
        'How would you design a system to verify user identity while minimizing friction?',
        'Walk me through handling a high-profile safety incident on the platform',
        'How would you balance community openness with safety requirements?',
        'Design a policy for handling hosts who repeatedly receive safety complaints',
        'How would you approach fraud detection for fake listings?',
        'Describe your framework for escalation decisions in ambiguous situations',
        'How would you measure the effectiveness of a new safety feature?',
        'Design a response protocol for crisis situations affecting multiple users',
        'How would you approach cultural differences in safety expectations globally?',
        'Walk me through investigating a potential scam pattern on the platform',
        'How would you balance automated systems with human review for sensitive decisions?',
        'Design training for support agents handling emotionally difficult cases',
        'How would you prioritize which safety risks to address with limited resources?',
        'Describe your approach to partnering with law enforcement',
        'How would you communicate a major policy change to the community?',
        'Design a feedback mechanism to improve safety based on user reports'
      ],
      behavioralQuestions: [
        'Tell me about a complex safety situation you managed and its resolution',
        'Describe a time you had to make a difficult policy decision under pressure',
        'How have you championed user safety when it conflicted with business goals?',
        'Tell me about a time you embraced adventure in your approach to a safety challenge',
        'Describe a creative solution to a trust problem that others hadn\'t considered (Be a Cereal Entrepreneur)',
        'How have you created safe, welcoming environments for users (Be a Host)?',
        'Tell me about handling feedback that changed your safety approach',
        'How have you built trust with cross-functional partners?',
        'Describe a safety initiative that didn\'t work and what you learned',
        'How have you approached safety for users different from yourself?',
        'Tell me about leading through a crisis situation',
        'How have you developed team members in T&S roles?',
        'Describe building a culture of empathy and care in your team',
        'Tell me about balancing transparency with confidentiality'
      ],
      whatTheyLookFor: [
        'Strong T&S experience in platform, marketplace, or consumer technology',
        'Excellent judgment navigating complex, ambiguous situations',
        'Crisis management skills remaining calm under pressure',
        'Deep empathy for users while maintaining necessary objectivity',
        'Strategic thinking about systems and policies, not just individual cases',
        'Leadership ability to build and motivate high-performing teams',
        'Strong communication skills for sensitive topics and diverse stakeholders',
        'Collaboration skills working with Legal, Policy, Product, and Operations',
        'Alignment with Airbnb\'s mission and "Be a Host" value especially',
        'Resilience for emotionally challenging work while maintaining wellbeing'
      ],
      interviewTips: [
        'Research Airbnb\'s public T&S policies and recent safety initiatives',
        'Prepare examples of handling complex, ambiguous safety situations',
        'Practice articulating decision frameworks for sensitive cases',
        'Prepare specific examples demonstrating each of Airbnb\'s four core values',
        'Be ready to discuss balancing safety with user experience',
        'Show understanding of global cultural differences in safety expectations',
        'Prepare questions about T&S team culture and support structures',
        'Be authentic about the challenges of T&S work',
        'Show empathy for all parties in difficult situations',
        'Prepare to discuss how you maintain resilience in demanding roles',
        'Research platform safety industry best practices',
        'Be ready to discuss working with law enforcement and regulators',
        'Show strategic thinking beyond individual cases',
        'Prepare examples of building safety culture in teams'
      ],
      salary: { min: 150000, max: 250000 },
      compensation: [
        'Competitive base salary with equity grants (RSUs)',
        'Annual performance bonuses',
        '$2,000 annual travel credit for Airbnb stays and Experiences',
        'Comprehensive health, dental, and vision coverage including mental health',
        'Generous parental leave (up to 22 weeks)',
        'Flexible PTO policy',
        '401(k) with company match',
        'Professional development and conference budget',
        'Wellness and resilience support resources',
        'Home office stipend'
      ],
      dayInLife: {
        intro: 'A day as a Trust & Safety Manager at Airbnb balances strategic planning with responsive support for urgent situations.',
        schedule: [
          '8:30 AM - Review overnight incident reports and escalations from global teams',
          '9:00 AM - Morning sync with T&S leadership on priorities and emerging risks',
          '9:30 AM - One-on-one with team member discussing career development',
          '10:00 AM - Policy review meeting developing new community standards',
          '11:00 AM - Partner with Product on safety feature requirements',
          '12:00 PM - Lunch with cross-functional partners from Legal and Policy',
          '1:00 PM - Case review calibration with team on escalated situations',
          '2:30 PM - Data analysis reviewing fraud patterns with analytics team',
          '3:30 PM - Stakeholder update on major initiative progress',
          '4:30 PM - Strategic planning for upcoming quarter priorities',
          '5:30 PM - Wrap up with incident monitoring check before end of day'
        ],
        closing: 'Trust & Safety at Airbnb is demanding but deeply meaningful work—protecting the community that makes belonging anywhere possible for millions of people.'
      },
      similarRoles: ['Senior Trust & Safety Manager at Airbnb', 'Trust & Safety Director at Airbnb', 'Fraud Operations Manager at Airbnb', 'Policy Manager at Airbnb', 'Community Standards Lead at Airbnb']
    },

    'data-analyst': {
      title: 'Data Analyst',
      slug: 'data-analyst',
      industry: 'Technology',
      roleDescription: `Data Analysts at Airbnb transform the company's rich marketplace data into actionable insights that drive product decisions and business strategy. Working with one of the most interesting datasets in travel—billions of searches, millions of bookings, and complex host-guest interactions across 220+ countries—you'll answer questions that directly impact how people experience travel. Airbnb's data culture is mature and deeply integrated; analysts are embedded within product teams and have direct access to decision-makers. The role balances exploratory analysis discovering new patterns with operational analytics measuring what matters. You'll work closely with Data Scientists on experimentation design, with Product Managers on metrics definition, and with stakeholders across the company who depend on your insights. Airbnb's analytical infrastructure is world-class, with extensive tooling for SQL, visualization, and self-service analytics. The company values clear communication as much as technical skill—your ability to translate data into compelling narratives for non-technical audiences is essential. Every analysis you do connects to helping people belong anywhere in the world.`,
      responsibilities: [
        'Conduct exploratory analysis to identify opportunities and understand user behavior patterns',
        'Build dashboards and automated reports to monitor key metrics across product areas',
        'Partner with Product Managers to define success metrics and measure feature impact',
        'Support A/B test analysis providing clear recommendations to stakeholders',
        'Develop deep domain expertise in assigned product areas',
        'Create data narratives and presentations for leadership and cross-functional teams',
        'Improve data quality and documentation within your domain',
        'Collaborate with Data Scientists and Analytics Engineers on complex analyses',
        'Mentor junior analysts and contribute to analytics team practices'
      ],
      growthOpportunities: [
        'Progress through IC levels to Senior and Staff Data Analyst',
        'Transition to Data Science for more advanced statistical work',
        'Move into Product Management leveraging analytical foundation',
        'Become an Analytics Engineer focusing on data infrastructure',
        'Lead analytics for major product areas with strategic influence',
        'Move into management leading analytics teams',
        'Specialize in areas like marketplace economics, growth, or experimentation'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial discussion of analytics background and interest in Airbnb' },
        { stage: 'Hiring Manager Call', description: 'Deep dive into analytical experience, problem-solving approach, and team fit' },
        { stage: 'SQL Assessment', description: 'Technical evaluation of SQL skills and data manipulation abilities' },
        { stage: 'Case Study', description: 'Product analytics case testing metrics thinking and business acumen' },
        { stage: 'Presentation Round', description: 'Present past analysis demonstrating communication and storytelling skills' },
        { stage: 'Core Values Interview', description: 'Behavioral assessment of alignment with Airbnb\'s four core values' },
        { stage: 'Cross-functional Interview', description: 'Assessment of partnership skills with Product, Engineering, and other stakeholders' }
      ],
      technicalQuestions: [
        'How would you measure the success of a new search feature?',
        'Design a dashboard to monitor marketplace health for a city',
        'Write SQL to analyze booking conversion by user segment',
        'How would you investigate a sudden drop in booking rates?',
        'Describe your approach to defining metrics for a new product initiative',
        'How would you segment users based on behavior for targeting?',
        'Design an analysis to understand why hosts become inactive',
        'How would you measure the impact of a pricing change on bookings?',
        'Explain how you would analyze cancellation patterns',
        'How would you approach attribution for marketing effectiveness?',
        'Design metrics to understand guest satisfaction beyond reviews',
        'How would you analyze seasonal patterns in booking behavior?',
        'Describe your process for validating data quality issues',
        'How would you prioritize multiple analysis requests?',
        'Explain how you communicate uncertainty in your findings',
        'How would you design a self-service analytics solution for stakeholders?'
      ],
      behavioralQuestions: [
        'Tell me about an analysis that significantly changed a business decision',
        'Describe a time when your data contradicted stakeholder expectations',
        'How have you championed data-driven decision making?',
        'Tell me about a time you embraced adventure with a new analytical approach',
        'Describe a creative analytical solution that others hadn\'t considered (Be a Cereal Entrepreneur)',
        'How have you gone above and beyond to support a stakeholder (Be a Host)?',
        'Tell me about an analysis you later realized had flaws',
        'How have you helped non-technical people understand complex findings?',
        'Describe balancing rigorous analysis with delivering quickly',
        'How do you approach analyzing users different from yourself?',
        'Tell me about navigating ambiguity when problem was unclear',
        'How have you mentored other analysts?',
        'Describe building collaborative relationships with stakeholders',
        'Tell me about handling conflicting priorities from different teams'
      ],
      whatTheyLookFor: [
        'Strong SQL skills with ability to work with complex datasets',
        'Excellent data visualization and communication abilities',
        'Product intuition connecting data to user experiences and business outcomes',
        'Curiosity and initiative to explore data beyond assigned tasks',
        'Clear, structured thinking breaking down ambiguous problems',
        'Collaboration skills working with diverse stakeholders',
        'Attention to data quality and analytical rigor',
        'Alignment with Airbnb\'s mission and core values',
        'Balance of speed and thoroughness in analysis',
        'Growth mindset with desire to learn and improve'
      ],
      interviewTips: [
        'Practice SQL extensively—Airbnb emphasizes strong query skills',
        'Prepare to present past analyses with clear storytelling structure',
        'Review Airbnb\'s product and think about metrics you would track',
        'Prepare specific examples demonstrating each of Airbnb\'s four core values',
        'Practice product sense cases framed around Airbnb scenarios',
        'Be ready to discuss handling conflicting stakeholder requests',
        'Show how you communicate technical findings to non-technical audiences',
        'Prepare questions about analytics culture and team structure',
        'Review marketplace and two-sided platform concepts',
        'Practice explaining your analytical process step by step',
        'Show genuine curiosity about Airbnb\'s data and challenges',
        'Be ready to discuss examples of proactive analysis',
        'Prepare to talk about data quality and validation approaches',
        'Be authentic in values discussions—Airbnb takes culture seriously'
      ],
      salary: { min: 120000, max: 200000 },
      compensation: [
        'Competitive base salary with equity grants (RSUs)',
        'Annual performance bonuses and equity refreshers',
        '$2,000 annual travel credit for Airbnb stays and Experiences',
        'Comprehensive health, dental, and vision insurance',
        'Generous parental leave (up to 22 weeks)',
        'Flexible PTO policy',
        '401(k) with company match',
        'Professional development budget',
        'Learning and conference attendance support',
        'Home office setup stipend'
      ],
      dayInLife: {
        intro: 'A day as a Data Analyst at Airbnb blends deep data exploration with collaborative partnership and clear communication.',
        schedule: [
          '9:00 AM - Review dashboards and check overnight data pipeline health',
          '9:30 AM - Team standup sharing analysis progress and priorities',
          '10:00 AM - Deep SQL work exploring booking pattern anomalies',
          '11:30 AM - Sync with PM on metrics definition for new feature',
          '12:00 PM - Lunch with analytics colleagues discussing interesting findings',
          '1:00 PM - Stakeholder meeting presenting quarterly marketplace trends',
          '2:00 PM - Build new dashboard for team self-service needs',
          '3:30 PM - Data quality investigation with Analytics Engineering',
          '4:30 PM - Office hours helping stakeholders with ad-hoc questions',
          '5:00 PM - Document analysis and prepare materials for tomorrow',
          '5:30 PM - Wrap up with quick metric monitoring check'
        ],
        closing: 'Data Analysis at Airbnb connects you directly to decisions that affect how millions of people experience travel, supported by excellent data infrastructure and a strong culture of analytics.'
      },
      similarRoles: ['Senior Data Analyst at Airbnb', 'Staff Data Analyst at Airbnb', 'Product Analyst at Airbnb', 'Business Analyst at Airbnb', 'Analytics Engineer at Airbnb']
    }
