    'software-engineer': {
      title: 'Software Engineer',
      slug: 'software-engineer',
      industry: 'Technology',
      roleDescription: `Software Engineers at Spotify build the products that bring music and audio to over 600 million users worldwide. Working in autonomous "squads" with product managers and designers, you'll tackle challenges spanning personalization algorithms, audio streaming infrastructure, creator tools, and discovery features that shape how people experience sound. Spotify's engineering culture is defined by high autonomy and aligned autonomy—squads own their missions end-to-end while staying connected to company goals. Engineers work on cutting-edge technology including machine learning for recommendations, large-scale data systems, real-time audio streaming, and mobile experiences across platforms. The company's commitment to experimentation means A/B testing is fundamental to how features ship. Spotify invests heavily in engineering culture with internal tech conferences, extensive open-source contributions, and a collaborative environment where engineers share code and knowledge across squads. The interview process evaluates technical skills alongside cultural fit, with a unique "values interview" assessing alignment with Spotify's band culture.`,
      responsibilities: [
        'Design and build features for music streaming, discovery, and personalization',
        'Develop scalable backend services handling billions of requests daily',
        'Create engaging mobile and desktop user experiences across platforms',
        'Build recommendation and personalization algorithms using machine learning',
        'Collaborate in autonomous squads with product managers and designers',
        'Participate in A/B testing and experimentation to validate features',
        'Contribute to Spotify\'s open-source projects and engineering culture',
        'Work with massive datasets on user behavior, audio content, and creator metrics',
        'Optimize audio streaming quality and performance across network conditions'
      ],
      growthOpportunities: [
        'Progress through IC levels to Staff and Principal Engineer',
        'Specialize in areas like ML, audio engineering, mobile, or infrastructure',
        'Transition into engineering management while maintaining technical work',
        'Lead cross-squad initiatives with company-wide impact',
        'Contribute to open source and represent Spotify at conferences',
        'Work on emerging audio formats including podcasts, audiobooks, and live audio',
        'Shape technical strategy through architecture guilds and chapters',
        'Internal mobility across listener, creator, and platform squads'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '30-minute conversation about background, experience, and interest in Spotify' },
        { stage: 'Technical Phone Screen', description: '75-minute technical interview combining coding, domain discussion, and behavioral questions' },
        { stage: 'Onsite - Coding Round 1', description: '60-minute coding interview testing algorithms and problem-solving' },
        { stage: 'Onsite - System Design', description: '60-minute system design discussion for audio/streaming relevant problems' },
        { stage: 'Onsite - Case Study', description: '60-minute production debugging scenario simulating real on-call situations' },
        { stage: 'Onsite - Values Interview', description: '45-minute behavioral interview assessing fit with Spotify\'s band culture and values' },
        { stage: 'Team Matching', description: 'Discussions with potential squads to find right fit based on interests and skills' }
      ],
      technicalQuestions: [
        'Design Spotify\'s music recommendation system for Discover Weekly',
        'Implement a shuffle algorithm that feels random but doesn\'t repeat songs',
        'Design the audio streaming architecture that adapts to network conditions',
        'How would you build a real-time collaborative playlist feature?',
        'Design Spotify\'s search system for songs, artists, playlists, and podcasts',
        'Implement an algorithm for generating personalized Daily Mix playlists',
        'Design the offline download and sync system for mobile',
        'How would you optimize audio quality based on bandwidth and user preferences?',
        'Design a system for tracking music royalties across millions of plays',
        'Implement lyrics synchronization with audio playback',
        'How would you design the podcast episode recommendation system?',
        'Design a system for detecting explicit content in audio automatically',
        'How would you build the audio fingerprinting system for copyright detection?',
        'Design the infrastructure for Spotify Wrapped year-end statistics',
        'How would you implement crossfade between tracks with different audio properties?',
        'Design a system for real-time audio transcription and search'
      ],
      behavioralQuestions: [
        'Tell me about a time you innovated on a product feature',
        'Describe how you\'ve worked in autonomous, cross-functional teams',
        'How have you balanced user needs with technical constraints?',
        'Tell me about improving system performance or scalability significantly',
        'Describe your experience with recommendation systems or personalization',
        'How do you stay current with new technologies and best practices?',
        'Tell me about a project where you had high ownership and impact',
        'Describe collaborating across engineering disciplines or teams',
        'How have you contributed to engineering culture or mentorship?',
        'Tell me about a time you failed and what you learned',
        'Describe how you approach experimentation and A/B testing',
        'How have you handled disagreements about technical approaches?',
        'Tell me about adapting to a new codebase or technology quickly',
        'Describe a time you simplified a complex system or process'
      ],
      whatTheyLookFor: [
        'Strong computer science fundamentals in algorithms and data structures',
        'Experience building scalable distributed systems',
        'Product mindset with user-centric thinking about features',
        'Autonomy and ability to drive projects independently within squads',
        'Collaboration skills for cross-functional squad environment',
        'Passion for music, audio, and the creator economy',
        'Innovative thinking with willingness to experiment',
        'Cultural fit with Spotify\'s values: innovative, collaborative, sincere, passionate, playful',
        'Experience with A/B testing and data-driven development',
        'Growth mindset with curiosity to learn continuously'
      ],
      interviewTips: [
        'Understand Spotify\'s squad model and autonomous culture deeply',
        'Be prepared to discuss recommendation systems and personalization',
        'Show genuine passion for music and audio experiences',
        'Research Spotify\'s engineering blog for technical insights',
        'Prepare for the case study round—practice debugging production scenarios',
        'Know Spotify\'s values: innovative, collaborative, sincere, passionate, playful',
        'Be ready to discuss audio streaming challenges and trade-offs',
        'Prepare examples of working with high autonomy and ownership',
        'Research Spotify\'s open-source contributions',
        'Express interest in creator tools and emerging audio formats',
        'Practice system design with music/audio domain problems',
        'Be authentic in the values interview—cultural fit matters significantly',
        'Prepare questions about squad culture and team dynamics',
        'Know the difference between squads, chapters, tribes, and guilds'
      ],
      salary: { min: 150000, max: 270000 },
      compensation: [
        'Competitive base salary based on level and location',
        'Equity grants (RSUs) with annual refreshers',
        'Annual performance bonuses',
        'Spotify Premium subscription for life',
        'Comprehensive health, dental, and vision insurance',
        'Generous parental leave (6 months)',
        'Flexible PTO with minimum vacation requirements',
        '401(k) with company match',
        'Mental health and wellness benefits',
        'Home office stipend and equipment budget',
        'Learning and development budget'
      ],
      dayInLife: {
        intro: 'A day as a Software Engineer at Spotify combines autonomous work with collaborative squad culture, all focused on improving how people experience music.',
        schedule: [
          '9:30 AM - Start day reviewing overnight metrics and experiment results',
          '10:00 AM - Squad standup syncing on progress, blockers, and priorities',
          '10:30 AM - Deep coding block building recommendation feature',
          '12:00 PM - Product critique reviewing design prototypes for playlist flow',
          '12:30 PM - Lunch with squad discussing favorite new music releases',
          '1:30 PM - A/B test analysis session with data scientist',
          '2:30 PM - Technical design collaboration on offline playback improvements',
          '3:30 PM - Code review and pairing on streaming optimization',
          '4:30 PM - Hack time experimenting with new audio codec ideas',
          '5:30 PM - Wrap up with quick check on experiment dashboards'
        ],
        closing: 'Engineering at Spotify means building technology that connects hundreds of millions of people with the music and audio they love, working with talented squads in a culture that values autonomy and innovation.'
      },
      similarRoles: ['Senior Software Engineer at Spotify', 'Staff Engineer at Spotify', 'Mobile Engineer at Spotify', 'Backend Engineer at Spotify', 'Platform Engineer at Spotify']
    },

    'product-manager': {
      title: 'Product Manager',
      slug: 'product-manager',
      industry: 'Technology',
      roleDescription: `Product Managers at Spotify shape how over 600 million users discover, listen to, and create audio content. Working in autonomous squads alongside engineers and designers, you'll own products ranging from personalized recommendations (Discover Weekly, Daily Mix) to creator tools and emerging audio experiences. Spotify's PM culture emphasizes user empathy, data-driven decision making, and balancing the needs of listeners, creators, and the business. The company's "band" metaphor extends to PMs—you're part of a squad making music together, not a traditional hierarchy. PMs at Spotify have significant autonomy to define strategy and execute within their squads, while staying aligned with company bets through transparent goal-setting. The role requires navigating complex multi-sided marketplace dynamics: what's good for listeners must also work for artists, labels, and podcasters. Spotify's rich data on listening behavior enables sophisticated experimentation, and PMs are expected to be fluent in using data to drive decisions.`,
      responsibilities: [
        'Define product vision and strategy for listener or creator experiences',
        'Collaborate with engineers, designers, and data scientists in autonomous squads',
        'Analyze data and user research to inform product decisions and priorities',
        'Drive discovery, personalization, and engagement features',
        'Partner with content teams on artist, podcaster, and creator experiences',
        'Design and analyze A/B experiments to validate hypotheses',
        'Balance needs of listeners, creators, labels, and business objectives',
        'Communicate product strategy to leadership and stakeholders',
        'Define success metrics and monitor product health'
      ],
      growthOpportunities: [
        'Progress from PM to Senior PM to Group PM leading multiple squads',
        'Advance to Director of Product overseeing product areas',
        'Specialize in areas like personalization, creator tools, or platform',
        'Work on products affecting hundreds of millions of users',
        'High autonomy in squad-based organization to drive strategy',
        'Internal mobility across listener, creator, and platform products',
        'Collaborate with world-class engineers, designers, and data scientists',
        'Influence the future of audio and creator monetization'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '30-minute conversation about PM experience and passion for Spotify' },
        { stage: 'Product Case Interview', description: '60-minute product design or strategy case with focus on user insight and structured thinking' },
        { stage: 'Onsite - Product Sense', description: '60-minute deep dive into product intuition and feature design' },
        { stage: 'Onsite - Analytical', description: '60-minute case testing metrics definition, data analysis, and experimentation' },
        { stage: 'Onsite - Technical Collaboration', description: '45-minute discussion with engineers on technical trade-offs and partnership' },
        { stage: 'Onsite - Values Interview', description: '45-minute behavioral interview assessing cultural fit with Spotify\'s band values' },
        { stage: 'Leadership Interview', description: 'Final round with senior product leader on strategy and fit' }
      ],
      technicalQuestions: [
        'How would you improve Spotify\'s Discover Weekly playlist?',
        'Design a feature to help new artists get discovered on Spotify',
        'How would you measure the success of personalized Daily Mixes?',
        'Design a feature to increase podcast listening engagement',
        'How would you approach monetization for podcast creators?',
        'Design the product strategy for audiobooks on Spotify',
        'How would you improve the social features on Spotify?',
        'Design a feature to reduce music streaming churn',
        'How would you prioritize between listener features and creator tools?',
        'Design a live audio feature for Spotify',
        'How would you approach lyrics as a product feature?',
        'Design metrics for measuring playlist quality and engagement',
        'How would you improve the search experience on Spotify?',
        'Design a feature to help listeners discover local artists',
        'How would you approach the cold-start problem for new users?',
        'Design Spotify Wrapped to maximize engagement and sharing'
      ],
      behavioralQuestions: [
        'Tell me about a product you launched and its impact',
        'Describe using data to make a difficult product decision',
        'How have you balanced competing stakeholder needs?',
        'Tell me about a product that failed and what you learned',
        'Describe your experience with marketplace products',
        'How do you prioritize features with limited resources?',
        'Tell me about influencing without authority',
        'Describe collaborating with engineers on technical trade-offs',
        'How have you incorporated user research into product decisions?',
        'Tell me about navigating ambiguity in a product role',
        'Describe building trust with design and engineering partners',
        'How have you communicated product strategy to leadership?',
        'Tell me about a time you had to kill a feature you believed in',
        'Describe your approach to experimentation and A/B testing'
      ],
      whatTheyLookFor: [
        'Strong product sense with deep user empathy',
        'Analytical rigor and data-driven decision making',
        'Experience with consumer products and marketplace dynamics',
        'Strategic thinking balanced with execution ability',
        'Collaboration skills for autonomous squad environment',
        'Technical fluency to partner effectively with engineers',
        'Passion for music, audio, and creator economy',
        'Cultural fit with Spotify\'s values: innovative, collaborative, sincere, passionate, playful',
        'Experience with experimentation and growth',
        'Clear communication for diverse stakeholders'
      ],
      interviewTips: [
        'Use Spotify extensively and form opinions about the product',
        'Understand Spotify\'s squad model and autonomous culture',
        'Prepare product cases using Spotify\'s actual features',
        'Know Spotify\'s values and be ready for the values interview',
        'Research Spotify\'s personalization features (Discover Weekly, Daily Mix, Wrapped)',
        'Understand the multi-sided marketplace: listeners, artists, labels, podcasters',
        'Be ready to discuss metrics and experimentation deeply',
        'Prepare examples of working with high autonomy',
        'Research recent Spotify product launches and form opinions',
        'Show genuine passion for music and audio experiences',
        'Practice structuring answers for case interviews',
        'Be authentic—cultural fit is heavily weighted',
        'Prepare thoughtful questions about squad culture',
        'Know the difference between squads, chapters, tribes, and guilds'
      ],
      salary: { min: 160000, max: 290000 },
      compensation: [
        'Competitive base salary with significant equity (RSUs)',
        'Annual performance bonuses',
        'Spotify Premium subscription for life',
        'Comprehensive health, dental, and vision insurance',
        'Generous parental leave (6 months)',
        'Flexible PTO with minimum vacation requirements',
        '401(k) with company match',
        'Mental health and wellness benefits',
        'Learning and development budget',
        'Home office stipend'
      ],
      dayInLife: {
        intro: 'A day as a Product Manager at Spotify balances strategic thinking with squad collaboration on products that shape how people experience audio.',
        schedule: [
          '9:00 AM - Review overnight metrics and user feedback',
          '9:30 AM - Squad standup with engineering and design on sprint progress',
          '10:00 AM - User research debrief discussing recent listener interviews',
          '11:00 AM - Product strategy session with leadership on quarterly bets',
          '12:00 PM - Lunch with cross-squad PMs discussing shared challenges',
          '1:00 PM - A/B test analysis session with data scientist',
          '2:00 PM - Design review providing feedback on new discovery feature',
          '3:00 PM - Technical trade-off discussion with engineering lead',
          '4:00 PM - Write product brief for upcoming initiative',
          '5:00 PM - Stakeholder sync with creator partnerships team',
          '5:30 PM - Wrap up reviewing tomorrow\'s priorities'
        ],
        closing: 'Product management at Spotify means owning products that connect hundreds of millions of people with the music and audio they love, working with autonomous squads in a culture that values experimentation and impact.'
      },
      similarRoles: ['Senior Product Manager at Spotify', 'Group Product Manager at Spotify', 'Product Lead at Spotify', 'Growth PM at Spotify', 'Platform PM at Spotify']
    },

    'engineering-manager': {
      title: 'Engineering Manager',
      slug: 'engineering-manager',
      industry: 'Technology',
      roleDescription: `Engineering Managers at Spotify lead squads building the technology that brings music and audio to over 600 million users. The EM role at Spotify is unique—you're part of the squad's "band," leading engineers while partnering with Product and Design as equals. Spotify's autonomous squad model means EMs have significant ownership over their teams' technical direction and delivery, while also investing heavily in people development. The company uses a "chapter" structure where EMs belong to engineering chapters that support career growth, share practices, and build community across squads. EMs are expected to maintain technical credibility, participating in architecture discussions and code review, while focusing primarily on people leadership. The role requires balancing individual engineer growth with squad delivery, technical excellence with shipping pragmatism, and squad autonomy with cross-squad alignment. Spotify's values—innovative, collaborative, sincere, passionate, playful—shape how EMs lead their teams.`,
      responsibilities: [
        'Lead, mentor, and grow a squad of 5-8 software engineers',
        'Partner with Product Manager and Design as part of squad leadership',
        'Conduct regular 1:1s, performance reviews, and career development conversations',
        'Contribute to technical direction and maintain credibility with engineers',
        'Build inclusive squad culture aligned with Spotify\'s band values',
        'Drive hiring for your squad including interview calibration',
        'Participate in chapter activities supporting engineering excellence',
        'Manage project execution ensuring quality delivery on squad mission',
        'Collaborate with other EMs in your tribe on cross-squad initiatives'
      ],
      growthOpportunities: [
        'Progress to Senior EM managing multiple squads or leading chapters',
        'Advance to Engineering Director overseeing tribes',
        'Move into VP of Engineering with executive scope',
        'Transition back to Staff or Principal Engineer (supported path)',
        'Lead chapter or guild initiatives improving engineering practice',
        'Drive tribe-wide technical strategy and architecture',
        'Build expertise in specific domains (personalization, audio, platform)',
        'Shape engineering culture through organizational initiatives'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial discussion of management experience and interest in Spotify' },
        { stage: 'Hiring Manager Interview', description: 'Deep dive into leadership philosophy, squad experience, and technical background' },
        { stage: 'Technical Assessment', description: 'System design or architecture discussion demonstrating technical depth' },
        { stage: 'People Leadership Interview', description: 'Scenarios on coaching, difficult conversations, and team development' },
        { stage: 'Cross-functional Interview', description: 'Assessment of partnership with Product and Design' },
        { stage: 'Values Interview', description: 'Behavioral interview assessing fit with Spotify\'s band culture' },
        { stage: 'Executive Interview', description: 'Final round with senior engineering leader' }
      ],
      technicalQuestions: [
        'How do you balance technical debt with feature development in your squad?',
        'Describe your approach to making architecture decisions with your team',
        'How do you ensure your squad maintains production reliability?',
        'Walk me through a complex system your squad owns',
        'How do you stay technically credible while managing a growing team?',
        'Describe your approach to driving engineering standards',
        'How would you handle a major incident in your squad\'s service?',
        'What\'s your philosophy on code review and engineering practices?',
        'How do you approach capacity planning for your squad?',
        'Describe how you evaluate and adopt new technologies',
        'How do you handle technical disagreements within your squad?',
        'What\'s your approach to on-call and production support?',
        'How do you balance squad autonomy with alignment to company goals?',
        'Describe your approach to technical hiring and interview calibration',
        'How do you support engineers\' technical growth?',
        'What role do chapters play in your engineering leadership?'
      ],
      behavioralQuestions: [
        'Tell me about helping an underperforming engineer improve',
        'Describe building inclusive squad culture where everyone belongs',
        'How have you handled disagreements with Product about priorities?',
        'Tell me about a difficult termination decision you made',
        'Describe giving critical feedback to a high performer',
        'How have you managed through organizational change?',
        'Tell me about developing an engineer from junior to senior',
        'Describe partnering with Product to influence roadmap',
        'How do you build psychological safety on your squad?',
        'Tell me about handling conflicting priorities from leadership',
        'Describe your most effective team building initiative',
        'How have you approached a situation with low team morale?',
        'Tell me about delivering difficult news to your squad',
        'Describe balancing being hands-on with delegating'
      ],
      whatTheyLookFor: [
        'Strong people leadership with genuine investment in engineer growth',
        'Technical credibility to guide architectural decisions',
        'Experience with autonomous, empowered team structures',
        'Partnership skills working as equals with Product and Design',
        'Track record building high-performing, engaged teams',
        'Clear communication across squads, chapters, and leadership',
        'Cultural fit with Spotify\'s values: innovative, collaborative, sincere, passionate, playful',
        'Growth mindset for self and team development',
        'Experience with chapter or community-of-practice models',
        'Comfort with ambiguity and leading through change'
      ],
      interviewTips: [
        'Understand Spotify\'s squad model and how EMs fit in',
        'Research chapters, tribes, and guilds—know how they work',
        'Prepare examples of leading autonomous, empowered teams',
        'Be ready to demonstrate technical depth—Spotify EMs stay technical',
        'Know Spotify\'s values and prepare examples demonstrating them',
        'Practice discussing difficult management situations with nuance',
        'Show how you\'ve partnered with Product as an equal',
        'Prepare questions about chapter culture and EM community',
        'Be authentic about your leadership style and philosophy',
        'Research Spotify\'s engineering blog and culture',
        'Show vulnerability—discuss mistakes and what you learned',
        'Prepare examples of building inclusive team culture',
        'Understand the balance between squad autonomy and alignment',
        'Be ready to discuss how you stay technically engaged'
      ],
      salary: { min: 190000, max: 320000 },
      compensation: [
        'Competitive base salary with significant equity (RSUs)',
        'Annual refresher grants based on performance',
        'Performance bonuses tied to squad and company goals',
        'Spotify Premium subscription for life',
        'Comprehensive health, dental, and vision coverage',
        'Generous parental leave (6 months)',
        'Flexible PTO with managers modeling healthy time off',
        '401(k) with company match',
        'Leadership development programs',
        'Home office stipend and equipment budget'
      ],
      dayInLife: {
        intro: 'A day as an Engineering Manager at Spotify balances people leadership with technical engagement in an autonomous squad structure.',
        schedule: [
          '9:00 AM - Review squad dashboards and overnight activity',
          '9:30 AM - 1:1 with engineer discussing career growth',
          '10:00 AM - Squad standup facilitating discussion of priorities',
          '10:30 AM - Architecture review providing input on design',
          '11:30 AM - Cross-functional sync with PM and Design on planning',
          '12:00 PM - Lunch with new squad member for onboarding',
          '1:00 PM - Chapter meeting with fellow EMs sharing practices',
          '2:00 PM - Code review staying connected to squad\'s work',
          '3:00 PM - Interview debrief calibrating on candidates',
          '3:30 PM - 1:1 coaching conversation with struggling engineer',
          '4:30 PM - Performance review preparation',
          '5:30 PM - Squad celebration for shipped feature'
        ],
        closing: 'Engineering management at Spotify means leading autonomous squads that build products for hundreds of millions of users, while investing deeply in engineer growth within a unique band culture.'
      },
      similarRoles: ['Senior Engineering Manager at Spotify', 'Engineering Director at Spotify', 'Chapter Lead at Spotify', 'Staff Engineer at Spotify']
    },

    'data-scientist': {
      title: 'Data Scientist',
      slug: 'data-scientist',
      industry: 'Technology',
      roleDescription: `Data Scientists at Spotify power the personalization, recommendations, and insights that help over 600 million users discover music and audio they love. Working with one of the richest behavioral datasets in consumer technology—billions of streams, skips, saves, and playlist additions—you'll build models that shape how people experience sound. Spotify's data science culture emphasizes both rigorous ML research and practical product impact. Data Scientists work embedded in squads alongside engineers and PMs, owning everything from exploratory analysis to production ML models. The company's recommendation systems are legendary (Discover Weekly serves 100+ million users), and DS teams continuously innovate on personalization, search ranking, content understanding, and creator analytics. Spotify invests in research with publications at top conferences and a dedicated research organization. The interview evaluates both technical depth in ML and statistics alongside product intuition and experimentation rigor.`,
      responsibilities: [
        'Build recommendation and personalization models serving millions of users',
        'Design and analyze A/B experiments measuring product and algorithm impact',
        'Develop ML models for content understanding, search ranking, and user modeling',
        'Partner with engineers to deploy models in production at scale',
        'Collaborate with PMs to define metrics and inform product strategy',
        'Conduct exploratory analysis to uncover user behavior insights',
        'Present findings and recommendations to leadership and stakeholders',
        'Contribute to Spotify\'s research agenda and publications',
        'Mentor junior data scientists and contribute to team practices'
      ],
      growthOpportunities: [
        'Progress through IC levels to Staff and Principal Data Scientist',
        'Specialize in areas like recommendations, NLP, audio ML, or experimentation',
        'Transition into Data Science management leading teams',
        'Move into Research Scientist roles for more exploratory work',
        'Become domain expert in personalization, creator analytics, or search',
        'Lead cross-squad initiatives shaping company data strategy',
        'Publish research and represent Spotify at conferences',
        'Internal mobility across listener, creator, and platform squads'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial conversation about background and interest in Spotify' },
        { stage: 'Technical Phone Screen', description: '60-minute interview covering statistics, ML, and analytical problem-solving' },
        { stage: 'Onsite - ML Deep Dive', description: '60-minute assessment of machine learning fundamentals and applied experience' },
        { stage: 'Onsite - Product/Analytics Case', description: '60-minute case testing metrics definition, analysis approach, and product thinking' },
        { stage: 'Onsite - Coding/SQL', description: '45-minute assessment of coding skills and data manipulation' },
        { stage: 'Onsite - Values Interview', description: '45-minute behavioral interview assessing cultural fit' },
        { stage: 'Presentation', description: 'Present past work demonstrating technical depth and communication' }
      ],
      technicalQuestions: [
        'How would you improve Spotify\'s Discover Weekly recommendation algorithm?',
        'Design a recommendation system for podcast discovery',
        'How would you measure the success of personalized Daily Mixes?',
        'Build a model to predict user churn and intervention strategies',
        'How would you categorize and tag millions of songs automatically?',
        'Design an experiment to test a new shuffle algorithm',
        'Build a model to detect explicit content in audio',
        'How would you handle the cold-start problem for new users?',
        'Design metrics for measuring playlist quality and engagement',
        'How would you build a search ranking model for Spotify?',
        'Design an algorithm for generating Spotify Wrapped statistics',
        'How would you approach music similarity and artist recommendation?',
        'Build a model to predict which songs will go viral',
        'How would you optimize audio quality recommendations based on network?',
        'Design an ML system for real-time personalization',
        'How would you approach fairness in recommendation systems?'
      ],
      behavioralQuestions: [
        'Tell me about a recommendation system or ML model you built',
        'Describe using data to influence product strategy',
        'How have you collaborated with engineers on production ML?',
        'Tell me about an A/B test that produced unexpected results',
        'Describe your experience with audio data or content understanding',
        'How do you approach problems with ambiguous requirements?',
        'Tell me about analysis that changed a key decision',
        'Describe balancing rigor with speed in your work',
        'How have you communicated complex findings to non-technical audiences?',
        'Tell me about a model that didn\'t work and what you learned',
        'Describe collaborating with product managers effectively',
        'How have you mentored other data scientists?',
        'Tell me about staying current with ML research',
        'Describe handling disagreement about analytical approaches'
      ],
      whatTheyLookFor: [
        'Strong foundation in machine learning and recommendation systems',
        'Proficiency in Python, SQL, and data science tools',
        'Experience deploying ML models in production',
        'Understanding of experimentation and causal inference',
        'Product sense for music and audio experiences',
        'Ability to translate analysis into actionable insights',
        'Strong communication for diverse audiences',
        'Passion for music and content discovery',
        'Cultural fit with Spotify\'s values',
        'Collaborative mindset for squad environment'
      ],
      interviewTips: [
        'Review collaborative filtering and recommendation algorithms',
        'Understand Spotify\'s personalization features deeply',
        'Be prepared to discuss audio ML and content understanding',
        'Prepare examples of ML models you\'ve deployed in production',
        'Know Spotify\'s values for the values interview',
        'Practice experimentation methodology and A/B testing',
        'Prepare ideas for improving music discovery',
        'Be ready to discuss cold-start and long-tail problems',
        'Research Spotify\'s published research papers',
        'Express genuine passion for music and audio',
        'Practice presenting technical work clearly',
        'Be ready for both ML depth and product breadth questions',
        'Prepare questions about research culture and squad structure',
        'Show how you balance innovation with practical impact'
      ],
      salary: { min: 155000, max: 280000 },
      compensation: [
        'Competitive base salary with significant equity (RSUs)',
        'Annual performance bonuses',
        'Spotify Premium subscription for life',
        'Comprehensive health, dental, and vision insurance',
        'Generous parental leave (6 months)',
        'Flexible PTO with minimum vacation requirements',
        '401(k) with company match',
        'Conference attendance and research budget',
        'Learning and development support',
        'Home office stipend'
      ],
      dayInLife: {
        intro: 'A day as a Data Scientist at Spotify balances model development, experimentation, and collaboration on products that shape how people discover music.',
        schedule: [
          '9:30 AM - Review experiment results from overnight pipeline runs',
          '10:00 AM - Squad standup with personalization team',
          '10:30 AM - Deep work on recommendation model improvements',
          '12:00 PM - Research seminar on transformer models for audio',
          '1:00 PM - Lunch with DS colleagues discussing new papers',
          '2:00 PM - Product collaboration defining metrics for new feature',
          '3:00 PM - Analysis investigating patterns in skip behavior',
          '4:00 PM - Model review presenting results to content team',
          '5:00 PM - Experiment design session with engineer',
          '5:30 PM - Wrap up with documentation and planning'
        ],
        closing: 'Data Science at Spotify means building the algorithms that connect hundreds of millions of people with music they love, working at the intersection of cutting-edge ML and products people use every day.'
      },
      similarRoles: ['Senior Data Scientist at Spotify', 'Staff Data Scientist at Spotify', 'ML Engineer at Spotify', 'Research Scientist at Spotify', 'Analytics Lead at Spotify']
    }
