    'technical-program-manager': {
      title: 'Technical Program Manager',
      slug: 'technical-program-manager',
      industry: 'Technology',
      roleDescription: `Technical Program Managers at Stripe orchestrate complex, cross-functional initiatives that shape the future of global payments infrastructure. Working at the intersection of engineering, product, and business, you'll drive programs that span multiple teams and months of execution: platform migrations, product launches, infrastructure upgrades, and compliance initiatives. Stripe's TPMs are technically deep—you'll understand system architectures, read code, and participate in design reviews, earning credibility with world-class engineers. The role requires managing ambiguity in a fast-moving environment where priorities shift and new challenges emerge. Stripe's written culture is central to TPM work: you'll create detailed program plans, risk registers, and status documents that keep stakeholders aligned. TPMs at Stripe own outcomes, not just process—you're measured by whether programs succeed, not just whether meetings happen. The team values proactive problem-solving: identifying risks before they become blockers, navigating organizational complexity, and keeping large initiatives on track despite competing priorities.`,
      responsibilities: [
        'Lead cross-functional programs spanning multiple engineering teams',
        'Create detailed program plans with milestones, dependencies, and risk mitigation',
        'Drive technical decisions and tradeoffs with engineering leadership',
        'Communicate program status to executives and stakeholders',
        'Identify and resolve blockers proactively across teams',
        'Manage program scope, timeline, and resource allocation',
        'Coordinate product launches and platform migrations',
        'Write detailed documentation for program decisions and outcomes',
        'Build relationships across engineering, product, and business teams'
      ],
      growthOpportunities: [
        'Progress from TPM to Senior, Staff, and Principal TPM levels',
        'Lead larger and more complex programs with company-wide impact',
        'Specialize in infrastructure, product, or compliance programs',
        'Transition into engineering management or product management',
        'Build expertise in payments industry and financial regulations',
        'Shape TPM practices and methodologies across Stripe',
        'Mentor junior TPMs on program management',
        'Influence technical and product roadmaps'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '30-minute conversation about background and TPM experience' },
        { stage: 'Hiring Manager Screen', description: '45-minute conversation about program management approach and experience' },
        { stage: 'Onsite - Program Design', description: '60-minute interview designing a program for a Stripe-relevant scenario' },
        { stage: 'Onsite - Technical Depth', description: '60-minute interview on technical understanding and engineering collaboration' },
        { stage: 'Onsite - Cross-functional', description: '60-minute interview on stakeholder management and communication' },
        { stage: 'Hiring Committee Review', description: 'Panel review of all feedback to make final decision' }
      ],
      technicalQuestions: [
        'How would you structure a program to migrate a critical payment system?',
        'Explain your approach to managing dependencies across multiple teams.',
        'How do you create realistic program timelines with engineering input?',
        'Describe your approach to risk management in complex programs.',
        'How would you handle a major scope change mid-program?',
        'Explain techniques for tracking progress across distributed teams.',
        'How do you ensure program alignment with business objectives?',
        'Describe your approach to technical decision-making as a TPM.',
        'How would you manage a program with competing team priorities?',
        'Explain your approach to program documentation and communication.',
        'How do you identify and escalate blockers effectively?',
        'Describe techniques for managing technical debt in programs.',
        'How would you coordinate a security or compliance initiative?',
        'Explain your approach to post-mortem and lessons learned.',
        'How do you balance program process with engineering productivity?',
        'Describe your experience with large-scale product launches.'
      ],
      behavioralQuestions: [
        'Tell me about a complex program you led and its outcome.',
        'Describe how you\'ve handled a program that went off track.',
        'How have you built credibility with engineering teams?',
        'Tell me about a time you had to make a difficult tradeoff decision.',
        'Describe your approach to managing stakeholder expectations.',
        'How have you navigated organizational complexity in programs?',
        'Tell me about a time you identified a risk before it became a problem.',
        'Describe how you\'ve communicated bad news to executives.',
        'How have you handled scope creep in programs?',
        'Tell me about a time you resolved conflict between teams.',
        'Describe your experience with programs involving compliance or regulations.',
        'How have you driven alignment across competing priorities?',
        'Tell me about a time you had to say no to stakeholders.',
        'Describe how you\'ve improved program management practices.'
      ],
      whatTheyLookFor: [
        'Strong technical background with ability to understand complex systems',
        'Experience leading large, cross-functional programs',
        'Excellent written and verbal communication skills',
        'Ability to build credibility with engineers and executives',
        'Proactive problem-solving and risk identification',
        'Experience with ambiguity and changing requirements',
        'Strong organizational and planning skills',
        'Ability to drive decisions and resolve blockers',
        'Data-driven approach to program management',
        'Customer-focused mindset in technical work'
      ],
      interviewTips: [
        'Stripe TPMs are technically deep—be ready to discuss system architecture',
        'Prepare specific examples of programs with clear outcomes',
        'Show how you build credibility with engineering teams',
        'Demonstrate proactive risk identification and mitigation',
        'Be ready to discuss how you handle ambiguity and change',
        'Practice designing a program for a complex technical initiative',
        'Show experience with written communication and documentation',
        'Research Stripe\'s products and technical challenges',
        'Prepare examples of navigating organizational complexity',
        'Demonstrate outcome-orientation, not just process management',
        'Show how you balance detail with big-picture thinking',
        'Be ready to discuss lessons from program failures',
        'Understand financial industry compliance requirements',
        'Show how you communicate with different audiences'
      ],
      salary: {
        min: 180000,
        max: 320000,
        average: 250000
      },
      compensation: [
        'Highly competitive base salary ($180K-$320K+ based on level)',
        'Significant equity grants with annual refreshers',
        'Annual performance bonuses',
        '$1,000/month remote work stipend',
        'Comprehensive health, dental, and vision insurance',
        '401(k) with company match',
        'Generous parental leave',
        'Unlimited PTO with encouraged minimums',
        'Learning and development budget',
        'Home office setup allowance'
      ],
      dayInLife: {
        intro: 'A typical day as a Technical Program Manager at Stripe involves program coordination, stakeholder communication, and cross-functional problem-solving.',
        schedule: [
          '9:00 AM - Review program status across tracked initiatives',
          '9:30 AM - Engineering sync for infrastructure migration program',
          '10:00 AM - Update program documentation and risk register',
          '10:30 AM - 1:1 with engineering lead to discuss blockers',
          '11:00 AM - Product review meeting for launch readiness',
          '12:00 PM - Lunch break',
          '1:00 PM - Cross-functional sync for compliance program',
          '2:00 PM - Work on program plan for upcoming initiative',
          '3:00 PM - Executive status update preparation',
          '3:30 PM - Stakeholder meeting on timeline and scope',
          '4:30 PM - Resolve action items and update trackers',
          '5:30 PM - Wrap up and plan tomorrow'
        ],
        closing: 'Technical Program Management at Stripe means driving the programs that shape payments infrastructure, working with talented engineers to deliver initiatives that impact millions of businesses.'
      },
      similarRoles: ['Senior TPM at Stripe', 'Staff TPM at Stripe', 'Principal TPM at Stripe', 'Program Manager at Stripe', 'Engineering Program Manager at Stripe']
    },

    'risk-analyst': {
      title: 'Risk Analyst',
      slug: 'risk-analyst',
      industry: 'Technology',
      roleDescription: `Risk Analysts at Stripe protect the payments ecosystem by identifying, assessing, and mitigating risks that could impact Stripe and its users. Working at the intersection of data analysis, financial crime prevention, and operational excellence, you'll tackle challenges spanning fraud detection, merchant risk assessment, regulatory compliance, and credit exposure. Stripe processes hundreds of billions of dollars annually, making risk management critical—every decision impacts real businesses and their customers. The role combines quantitative analysis with investigative skills: you'll build risk models, analyze transaction patterns, investigate suspicious activity, and develop policies that balance protection with user experience. Stripe's written culture means you'll document your analysis thoroughly, creating risk assessments that inform business decisions. Risk Analysts collaborate closely with engineering teams to implement automated risk controls, with product teams to design secure features, and with operations teams to handle escalations. The team values both analytical rigor and practical judgment.`,
      responsibilities: [
        'Analyze transaction data to identify fraud patterns and emerging risks',
        'Conduct merchant risk assessments for onboarding and ongoing monitoring',
        'Develop and refine risk policies balancing protection with user experience',
        'Investigate suspicious activity and conduct detailed risk reviews',
        'Build dashboards and reports tracking risk metrics and trends',
        'Collaborate with engineering on automated risk controls',
        'Support regulatory compliance and audit requirements',
        'Create documentation for risk assessments and decisions',
        'Respond to escalations and high-priority risk cases'
      ],
      growthOpportunities: [
        'Progress from Risk Analyst to Senior, Staff, and Lead levels',
        'Specialize in fraud, credit, compliance, or merchant risk',
        'Transition into risk data science or risk engineering',
        'Lead risk initiatives for products or regions',
        'Build expertise in financial regulations and compliance',
        'Shape risk strategy and policy development',
        'Move into risk management leadership',
        'Contribute to industry risk standards'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '30-minute conversation about background and risk experience' },
        { stage: 'Hiring Manager Screen', description: '45-minute conversation about risk analysis approach and experience' },
        { stage: 'Onsite - Case Study', description: '60-minute interview analyzing a risk scenario and presenting findings' },
        { stage: 'Onsite - Technical', description: '60-minute interview on data analysis and SQL skills' },
        { stage: 'Onsite - Judgment', description: '60-minute interview on risk decision-making and policy tradeoffs' },
        { stage: 'Hiring Committee Review', description: 'Panel review of all feedback to make final decision' }
      ],
      technicalQuestions: [
        'How would you design a risk scoring system for merchant onboarding?',
        'Explain approaches to detecting fraudulent transaction patterns.',
        'How do you balance fraud prevention with false positive rates?',
        'Describe your approach to analyzing a new type of fraud attack.',
        'How would you measure the effectiveness of risk controls?',
        'Explain techniques for identifying high-risk merchant categories.',
        'How do you approach credit risk assessment for businesses?',
        'Describe your experience with risk monitoring dashboards.',
        'How would you design a velocity check for payment fraud?',
        'Explain approaches to detecting account takeover attacks.',
        'How do you prioritize risk alerts and escalations?',
        'Describe your approach to policy development for edge cases.',
        'How would you assess risk for a new payment method or product?',
        'Explain techniques for investigating suspicious activity.',
        'How do you handle risk tradeoffs in fast-moving situations?',
        'Describe your experience with regulatory risk requirements.'
      ],
      behavioralQuestions: [
        'Tell me about a time you identified a significant risk before it caused damage.',
        'Describe how you\'ve handled a high-pressure risk escalation.',
        'How have you balanced strict risk controls with business needs?',
        'Tell me about a time you changed your assessment based on new information.',
        'Describe your experience communicating risk to non-risk stakeholders.',
        'How have you dealt with ambiguous risk situations?',
        'Tell me about a time you advocated for stronger risk controls.',
        'Describe how you\'ve improved risk processes or policies.',
        'How have you handled disagreement on risk decisions?',
        'Tell me about a time you had to make a fast risk judgment.',
        'Describe your experience with regulatory examinations or audits.',
        'How have you prioritized across multiple competing risks?',
        'Tell me about a time you learned from a risk miss.',
        'Describe how you\'ve trained others on risk assessment.'
      ],
      whatTheyLookFor: [
        'Strong analytical skills with attention to detail',
        'Experience with fraud detection or financial risk',
        'Proficiency in SQL and data analysis tools',
        'Understanding of payments industry and fraud types',
        'Excellent judgment and decision-making skills',
        'Strong written and verbal communication',
        'Ability to work under pressure on escalations',
        'Experience with risk policy development',
        'Balance of rigor and practical judgment',
        'Customer-focused approach to risk management'
      ],
      interviewTips: [
        'Prepare to analyze a risk case study during the interview',
        'Brush up on SQL and data analysis skills',
        'Understand common fraud types: card testing, ATO, friendly fraud',
        'Be ready to discuss tradeoffs between security and user experience',
        'Show experience with risk metrics and KPIs',
        'Prepare examples of risk decisions with clear rationale',
        'Research Stripe\'s products and potential risk considerations',
        'Demonstrate structured analytical thinking',
        'Show how you communicate risk to different audiences',
        'Be ready to discuss regulatory requirements (PCI, AML, etc.)',
        'Prepare examples of improving risk processes',
        'Show experience with cross-functional collaboration',
        'Understand the merchant risk lifecycle',
        'Be ready to discuss how you handle pressure and urgency'
      ],
      salary: {
        min: 100000,
        max: 180000,
        average: 140000
      },
      compensation: [
        'Competitive base salary ($100K-$180K+ based on level)',
        'Equity grants with annual refreshers',
        'Annual performance bonuses',
        '$1,000/month remote work stipend',
        'Comprehensive health, dental, and vision insurance',
        '401(k) with company match',
        'Generous parental leave',
        'Unlimited PTO with encouraged minimums',
        'Learning and development budget',
        'Home office setup allowance'
      ],
      dayInLife: {
        intro: 'A typical day as a Risk Analyst at Stripe balances proactive risk analysis, reactive escalations, and cross-functional collaboration.',
        schedule: [
          '9:00 AM - Review overnight risk alerts and queue priorities',
          '9:30 AM - Work through escalated merchant reviews',
          '10:30 AM - Analyze fraud trends for weekly report',
          '11:00 AM - Risk team sync on emerging threats',
          '12:00 PM - Lunch break',
          '1:00 PM - Deep dive analysis on suspicious pattern',
          '2:30 PM - Cross-functional meeting with product on new feature risk',
          '3:30 PM - Update risk dashboards and documentation',
          '4:00 PM - Handle urgent escalation from operations',
          '4:30 PM - Policy review session with senior risk team',
          '5:30 PM - Wrap up and prepare for tomorrow'
        ],
        closing: 'Risk Analysis at Stripe means protecting the payments ecosystem while enabling commerce, balancing rigorous analysis with practical judgment to keep businesses safe.'
      },
      similarRoles: ['Senior Risk Analyst at Stripe', 'Risk Operations Lead at Stripe', 'Fraud Analyst at Stripe', 'Credit Risk Analyst at Stripe', 'Compliance Analyst at Stripe']
    },

    'developer-advocate': {
      title: 'Developer Advocate',
      slug: 'developer-advocate',
      industry: 'Technology',
      roleDescription: `Developer Advocates at Stripe bridge the gap between Stripe's technical products and the millions of developers who build with them, creating content, tools, and community experiences that make payment integration delightful. Working at the intersection of engineering, education, and community, you'll create technical content that teaches developers how to build with Stripe APIs—tutorials, sample applications, videos, and documentation. Stripe's Developer Advocates are engineers first: you'll write production-quality code, contribute to open-source projects, and understand the technical challenges developers face. The role involves extensive community engagement: speaking at conferences, hosting workshops, engaging on social media, and building relationships with developers worldwide. Stripe's written culture extends to advocacy—you'll create detailed technical content with the same rigor as internal documentation. Developer Advocates also serve as the voice of developers internally, advocating for improvements based on community feedback and contributing to product decisions.`,
      responsibilities: [
        'Create technical content: tutorials, guides, sample apps, and videos',
        'Speak at conferences and host technical workshops',
        'Build and maintain open-source tools and integrations',
        'Engage with the developer community on social media and forums',
        'Contribute to Stripe\'s documentation and developer resources',
        'Gather community feedback to inform product improvements',
        'Develop demos showcasing Stripe product capabilities',
        'Build relationships with developer communities and influencers',
        'Collaborate with product teams on developer experience'
      ],
      growthOpportunities: [
        'Progress to Senior, Staff, and Principal Developer Advocate',
        'Specialize in specific technologies, languages, or platforms',
        'Lead developer advocacy for products or regions',
        'Transition into product management or engineering',
        'Build personal brand as a technical thought leader',
        'Shape Stripe\'s developer relations strategy',
        'Contribute to industry standards and best practices',
        'Mentor junior advocates and community managers'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '30-minute conversation about background and developer advocacy experience' },
        { stage: 'Hiring Manager Screen', description: '45-minute conversation about approach to developer relations' },
        { stage: 'Onsite - Technical Content', description: '60-minute interview creating technical content on the spot' },
        { stage: 'Onsite - Coding', description: '60-minute practical coding interview building a demo' },
        { stage: 'Onsite - Presentation', description: '30-minute technical presentation on a topic of your choice' },
        { stage: 'Hiring Committee Review', description: 'Panel review of all feedback to make final decision' }
      ],
      technicalQuestions: [
        'How would you explain Stripe\'s payment intent flow to a beginner developer?',
        'Describe your approach to creating a technical tutorial.',
        'How do you determine what content developers need most?',
        'Explain your process for building sample applications.',
        'How do you make complex technical concepts accessible?',
        'Describe your approach to code quality in sample projects.',
        'How would you design a workshop for experienced developers?',
        'Explain techniques for creating engaging technical videos.',
        'How do you balance technical depth with accessibility?',
        'Describe your experience with developer documentation.',
        'How do you measure the impact of developer content?',
        'Explain your approach to debugging in public (streams, videos).',
        'How do you stay current with multiple programming languages?',
        'Describe your experience contributing to open source.',
        'How do you handle technical questions you don\'t know the answer to?',
        'Explain your approach to engaging developers on social media.'
      ],
      behavioralQuestions: [
        'Tell me about a piece of content you created that had significant impact.',
        'Describe how you\'ve built relationships in developer communities.',
        'How have you advocated for developer needs within an organization?',
        'Tell me about a time you received negative feedback on your content.',
        'Describe your experience speaking at conferences or meetups.',
        'How have you handled a controversial technical topic?',
        'Tell me about a time you learned a new technology to create content.',
        'Describe how you\'ve balanced content creation with community engagement.',
        'How have you measured and improved content effectiveness?',
        'Tell me about a time you turned a frustrated developer into an advocate.',
        'Describe your experience with live coding or streaming.',
        'How have you collaborated with product teams on developer experience?',
        'Tell me about a time you influenced a product decision through community feedback.',
        'Describe how you\'ve managed competing priorities in advocacy.'
      ],
      whatTheyLookFor: [
        'Strong software engineering skills with production experience',
        'Excellent written and verbal communication',
        'Experience creating technical content (blogs, videos, talks)',
        'Public speaking and presentation skills',
        'Community building and engagement experience',
        'Proficiency in multiple programming languages',
        'Passion for teaching and helping developers',
        'Understanding of developer experience and API design',
        'Ability to translate complex concepts simply',
        'Authentic presence in developer communities'
      ],
      interviewTips: [
        'Stripe values engineers who can advocate, not marketers who can code',
        'Bring a portfolio of technical content you\'ve created',
        'Prepare a technical presentation you can deliver during interviews',
        'Be ready to create content (blog post, tutorial) on the spot',
        'Show depth in multiple programming languages and frameworks',
        'Demonstrate community engagement and relationship building',
        'Research Stripe\'s developer documentation and content',
        'Prepare examples of gathering and acting on developer feedback',
        'Show authentic enthusiasm for developer education',
        'Be ready to discuss your approach to different content formats',
        'Demonstrate how you measure content impact',
        'Show experience with live coding and debugging publicly',
        'Prepare to discuss developer experience improvements you\'ve influenced',
        'Show how you balance technical depth with accessibility'
      ],
      salary: {
        min: 150000,
        max: 280000,
        average: 215000
      },
      compensation: [
        'Competitive base salary ($150K-$280K+ based on level)',
        'Significant equity grants with annual refreshers',
        'Annual performance bonuses',
        '$1,000/month remote work stipend',
        'Comprehensive health, dental, and vision insurance',
        '401(k) with company match',
        'Generous parental leave',
        'Unlimited PTO with encouraged minimums',
        'Conference travel and speaking budget',
        'Equipment and content creation budget'
      ],
      dayInLife: {
        intro: 'A typical day as a Developer Advocate at Stripe balances content creation, community engagement, and cross-functional collaboration.',
        schedule: [
          '9:00 AM - Check community channels and respond to developer questions',
          '9:30 AM - Review and respond to tweets and social engagement',
          '10:00 AM - Deep work on tutorial or sample application',
          '12:00 PM - Lunch break',
          '1:00 PM - Record video content or prepare presentation',
          '2:30 PM - Sync with product team on upcoming launch',
          '3:30 PM - Review documentation PRs',
          '4:00 PM - Community call or developer office hours',
          '5:00 PM - Write blog post draft',
          '5:30 PM - Plan content calendar and wrap up'
        ],
        closing: 'Developer Advocacy at Stripe means helping millions of developers build with payments, combining engineering skills with communication to create content and community that makes integration delightful.'
      },
      similarRoles: ['Senior Developer Advocate at Stripe', 'Staff Developer Advocate at Stripe', 'Developer Relations Manager at Stripe', 'Technical Writer at Stripe', 'Developer Experience Engineer at Stripe']
    },

    'finance-analyst': {
      title: 'Finance Analyst',
      slug: 'finance-analyst',
      industry: 'Technology',
      roleDescription: `Finance Analysts at Stripe build the financial models and analysis that guide one of the world's most valuable private companies through its next phases of growth. Working at the intersection of finance and technology, you'll analyze the economics of payment processing, model new product profitability, support strategic decisions with data, and help manage the financial operations of a complex global business. Stripe's finance team operates with engineering rigor—building automated systems, using SQL fluently, and treating financial processes as products to optimize. The work spans FP&A, strategic finance, and business operations: you'll build models for investor reporting, analyze unit economics across payment products, support pricing decisions, and track performance against goals. Stripe's written culture extends to finance: analysts create detailed memos explaining their analysis and recommendations. The team collaborates closely with business leaders, providing the financial insights that inform decisions about products, pricing, and growth investments.`,
      responsibilities: [
        'Build financial models for business planning and investment decisions',
        'Analyze unit economics and profitability across payment products',
        'Support monthly and quarterly financial reporting processes',
        'Create dashboards tracking key financial and operational metrics',
        'Collaborate with business teams on pricing and go-to-market analysis',
        'Support strategic projects including M&A and partnerships',
        'Automate financial processes and reporting with SQL and scripting',
        'Prepare materials for board meetings and investor communications',
        'Analyze variances and provide insights on business performance'
      ],
      growthOpportunities: [
        'Progress from Finance Analyst to Senior, Lead, and Director levels',
        'Specialize in FP&A, strategic finance, or treasury',
        'Transition into business operations or strategy roles',
        'Lead finance for specific products or business units',
        'Build expertise in payments industry economics',
        'Move into investor relations or corporate development',
        'Develop technical skills with engineering collaboration',
        'Take on international finance responsibilities'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '30-minute conversation about background and finance experience' },
        { stage: 'Hiring Manager Screen', description: '45-minute conversation about finance analysis approach' },
        { stage: 'Onsite - Case Study', description: '60-minute interview building a financial model and presenting analysis' },
        { stage: 'Onsite - Technical', description: '60-minute interview on SQL, Excel, and financial modeling skills' },
        { stage: 'Onsite - Business Acumen', description: '60-minute interview on strategic thinking and business analysis' },
        { stage: 'Hiring Committee Review', description: 'Panel review of all feedback to make final decision' }
      ],
      technicalQuestions: [
        'How would you model the unit economics of payment processing?',
        'Explain your approach to building a revenue forecasting model.',
        'How do you analyze profitability across customer segments?',
        'Describe your experience with variance analysis.',
        'How would you evaluate the economics of a new pricing model?',
        'Explain techniques for modeling subscription revenue.',
        'How do you approach financial analysis with incomplete data?',
        'Describe your experience building automated financial reports.',
        'How would you analyze the ROI of a growth investment?',
        'Explain your approach to foreign exchange analysis.',
        'How do you validate financial model assumptions?',
        'Describe your experience with cohort analysis.',
        'How would you structure a make vs. buy analysis?',
        'Explain techniques for scenario planning and sensitivity analysis.',
        'How do you communicate complex financial analysis?',
        'Describe your experience with SQL in financial analysis.'
      ],
      behavioralQuestions: [
        'Tell me about a financial model that influenced a significant decision.',
        'Describe how you\'ve improved financial processes or reporting.',
        'How have you communicated financial insights to non-finance stakeholders?',
        'Tell me about a time you identified an error in financial analysis.',
        'Describe your experience working under tight deadlines.',
        'How have you handled requests with ambiguous requirements?',
        'Tell me about a time you disagreed with a business team on analysis.',
        'Describe how you\'ve automated financial processes.',
        'How have you balanced accuracy with speed in financial work?',
        'Tell me about a time you had to learn a new business area quickly.',
        'Describe your experience with board or investor reporting.',
        'How have you prioritized across multiple competing requests?',
        'Tell me about a time your analysis led to unexpected insights.',
        'Describe how you\'ve collaborated with engineering or data teams.'
      ],
      whatTheyLookFor: [
        'Strong financial modeling and Excel skills',
        'SQL proficiency for data analysis',
        'Understanding of SaaS and payments economics',
        'Clear communication of complex financial concepts',
        'Experience with FP&A or strategic finance',
        'Attention to detail with ability to see big picture',
        'Comfort with ambiguity and incomplete information',
        'Automation mindset for financial processes',
        'Collaboration skills with technical and business teams',
        'Intellectual curiosity about business drivers'
      ],
      interviewTips: [
        'Stripe finance is technical—be ready to demonstrate SQL skills',
        'Prepare to build a model during the case study interview',
        'Understand payments industry economics and unit economics concepts',
        'Show experience automating financial processes',
        'Be ready to explain financial concepts to non-finance audiences',
        'Prepare examples of analysis that influenced business decisions',
        'Research Stripe\'s business model and revenue drivers',
        'Demonstrate comfort with ambiguity and assumptions',
        'Show strong attention to detail in modeling',
        'Prepare examples of cross-functional collaboration',
        'Understand subscription and transaction-based revenue models',
        'Be ready to discuss variance analysis and forecasting',
        'Show how you balance speed with accuracy',
        'Demonstrate intellectual curiosity about the business'
      ],
      salary: {
        min: 100000,
        max: 180000,
        average: 140000
      },
      compensation: [
        'Competitive base salary ($100K-$180K+ based on level)',
        'Equity grants with annual refreshers',
        'Annual performance bonuses',
        '$1,000/month remote work stipend',
        'Comprehensive health, dental, and vision insurance',
        '401(k) with company match',
        'Generous parental leave',
        'Unlimited PTO with encouraged minimums',
        'Learning and development budget',
        'Home office setup allowance'
      ],
      dayInLife: {
        intro: 'A typical day as a Finance Analyst at Stripe balances financial modeling, stakeholder collaboration, and process improvement.',
        schedule: [
          '9:00 AM - Review overnight data loads and dashboard updates',
          '9:30 AM - Work on monthly forecast model updates',
          '10:30 AM - Business team sync on pricing analysis request',
          '11:00 AM - Continue forecast and variance analysis',
          '12:00 PM - Lunch break',
          '1:00 PM - Finance team meeting on quarterly close',
          '2:00 PM - Build model for new product economics',
          '3:30 PM - Prepare slides for leadership review',
          '4:30 PM - Automate report with SQL and Python',
          '5:30 PM - Wrap up and respond to ad-hoc requests'
        ],
        closing: 'Finance at Stripe means bringing analytical rigor to one of the world\'s most innovative companies, combining financial expertise with technical skills to guide strategic decisions.'
      },
      similarRoles: ['Senior Finance Analyst at Stripe', 'FP&A Analyst at Stripe', 'Strategic Finance at Stripe', 'Business Operations at Stripe', 'Finance Manager at Stripe']
    }