    'software-engineer': {
      title: 'Software Engineer',
      slug: 'software-engineer',
      industry: 'Technology',
      roleDescription: `Software Engineers at Lyft build the technology powering millions of rides daily, creating transportation solutions that improve people's lives and transform cities. Working on one of the most complex real-time systems in technology, you'll tackle challenges spanning ride matching algorithms, dynamic pricing, mapping and routing, fraud detection, and seamless rider-driver experiences. Lyft's engineering culture emphasizes collaboration, impact, and building products that genuinely help communities. Engineers work in cross-functional teams with significant ownership over their domains, from mobile apps handling location updates every second to backend systems processing billions of events daily. The company's mission—improving people's lives through better transportation—drives technical decisions, whether optimizing for driver earnings, reducing wait times, or ensuring safety. Lyft uses a modern tech stack including Python, Go, and Kotlin, with extensive investment in machine learning and real-time data infrastructure. The interview process evaluates both technical skills and alignment with Lyft's values of collaboration, inclusion, and community impact.`,
      responsibilities: [
        'Design and build scalable backend services for ride matching, dispatch, and routing',
        'Develop features for rider and driver mobile applications across iOS and Android',
        'Optimize algorithms for pricing, ETAs, and marketplace efficiency',
        'Build safety and trust systems including real-time fraud detection',
        'Collaborate with product, design, and data science on feature development',
        'Participate in on-call rotations supporting 24/7 production reliability',
        'Contribute to engineering culture through mentorship and code reviews',
        'Work with big data systems processing billions of location events daily',
        'Drive technical architecture decisions and documentation'
      ],
      growthOpportunities: [
        'Progress through IC levels from L3 to Staff (L6) and Principal (L7) engineering',
        'Transition into engineering management while staying technically engaged',
        'Lead cross-functional initiatives spanning multiple teams and systems',
        'Become a domain expert in areas like marketplace, mapping, safety, or payments',
        'Contribute to Lyft\'s open source projects and technical blog',
        'Shape technical strategy and architecture for major product initiatives',
        'Build expertise in real-time systems, ML infrastructure, and location services'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '30-minute conversation covering background, interest in Lyft, and logistics' },
        { stage: 'Technical Phone Screen', description: '60-minute coding interview focusing on data structures, algorithms, and problem-solving via CoderPad' },
        { stage: 'Onsite - Coding Round 1', description: '60-minute coding interview testing algorithmic thinking and code quality' },
        { stage: 'Onsite - Coding Round 2', description: '60-minute coding interview with different focus area or domain-specific problems' },
        { stage: 'Onsite - System Design', description: '60-minute system design discussion designing scalable systems relevant to rideshare' },
        { stage: 'Onsite - Behavioral', description: '45-minute behavioral interview assessing collaboration, impact, and values alignment' },
        { stage: 'Team Matching', description: 'If successful, exploratory calls with potential teams to find right fit' }
      ],
      technicalQuestions: [
        'Design Lyft\'s ride matching system that pairs drivers with riders in real-time',
        'How would you implement a surge pricing algorithm that responds to supply and demand?',
        'Design a real-time tracking system showing driver location to waiting riders',
        'How would you calculate accurate ETAs accounting for traffic and routing?',
        'Implement an algorithm for efficient driver-rider pairing minimizing wait times',
        'Design the notification system that alerts drivers of new ride requests',
        'How would you build a fraud detection system for fake rides or payment fraud?',
        'Design a routing algorithm that handles multiple stops and traffic conditions',
        'How would you implement a queuing system for high-demand locations like airports?',
        'Design the driver availability system managing when drivers go online/offline',
        'How would you build a ratings system that\'s fair to both drivers and riders?',
        'Implement a geofencing system for airport pickups and special zones',
        'Design a system for scheduled rides that books drivers in advance',
        'How would you handle payment processing across millions of daily transactions?',
        'Design a system for driver incentives and bonus programs',
        'How would you build real-time analytics for marketplace health monitoring?'
      ],
      behavioralQuestions: [
        'Tell me about a time you improved a product that impacted users\' daily lives',
        'Describe a situation where you had to balance technical quality with shipping speed',
        'How have you collaborated with product managers and designers to ship features?',
        'Tell me about a time you identified and resolved a critical production issue',
        'Describe your experience building real-time systems or location-based services',
        'How do you approach making technical decisions with incomplete information?',
        'Tell me about a time you advocated for a better user experience',
        'Describe a project where your work had significant measurable business impact',
        'How have you contributed to building an inclusive engineering team?',
        'Tell me about a time you simplified a complex system or process',
        'Describe how you\'ve mentored other engineers or helped teammates grow',
        'How have you approached debugging a challenging distributed systems problem?',
        'Tell me about a time you had to push back on a product decision',
        'Describe how you balance innovation with maintaining system reliability'
      ],
      whatTheyLookFor: [
        'Strong computer science fundamentals in data structures and algorithms',
        'Experience building scalable distributed systems and real-time applications',
        'Product thinking and understanding of how technology impacts users',
        'Collaboration skills and ability to work effectively cross-functionally',
        'Passion for transportation, mobility, and improving communities',
        'Bias for action and ability to ship iteratively',
        'Problem-solving skills in ambiguous situations',
        'Commitment to inclusion, diversity, and building welcoming teams',
        'Clear communication skills for technical and non-technical audiences',
        'Growth mindset with curiosity to learn new technologies'
      ],
      interviewTips: [
        'Study Lyft\'s mission and understand how it differs from competitors',
        'Practice system design problems using rideshare domain examples',
        'Be ready to discuss trade-offs in real-time systems (latency vs consistency)',
        'Show product thinking—how technical decisions impact riders and drivers',
        'Prepare examples demonstrating collaboration and cross-functional work',
        'Research Lyft\'s engineering blog for insights into their tech stack',
        'Practice coding problems focusing on graphs, dynamic programming, and optimization',
        'Express genuine interest in transportation and community impact',
        'Be ready to discuss location-based services and mapping challenges',
        'Prepare questions about team culture and engineering practices',
        'Show how you\'ve contributed to inclusive team environments',
        'Be authentic about both successes and failures with learnings',
        'Understand Lyft\'s marketplace dynamics—two-sided platform challenges',
        'Prepare to discuss on-call experience and production reliability'
      ],
      salary: { min: 140000, max: 250000 },
      compensation: [
        'Competitive base salary based on level and location',
        'Equity grants (RSUs) with annual refreshers',
        'Annual performance bonuses',
        'Comprehensive health, dental, and vision insurance',
        'Lyft Pink membership (unlimited Lyft rides)',
        'Flexible PTO policy',
        '401(k) with company match',
        'Mental health and wellness benefits',
        'Professional development and conference budget',
        'Home office stipend for hybrid work'
      ],
      dayInLife: {
        intro: 'A day as a Software Engineer at Lyft combines focused coding with collaborative problem-solving on real-time transportation systems.',
        schedule: [
          '9:30 AM - Start day reviewing overnight metrics and any on-call alerts',
          '10:00 AM - Team standup covering sprint progress, blockers, and priorities',
          '10:30 AM - Deep coding block working on new ride matching optimization',
          '12:00 PM - Product review demoing completed driver experience feature',
          '12:30 PM - Lunch with team discussing recent engineering blog posts',
          '1:30 PM - System design discussion collaborating on architecture for new safety feature',
          '3:00 PM - Code review session providing feedback on teammates\' PRs',
          '4:00 PM - 1:1 with manager discussing career growth and project priorities',
          '4:30 PM - Monitoring dashboards and deploying feature to production',
          '5:30 PM - Wrap up documenting decisions and updating tickets for tomorrow'
        ],
        closing: 'Engineering at Lyft means building technology that directly improves how millions of people get around, working with a collaborative team passionate about transportation\'s impact on communities.'
      },
      similarRoles: ['Senior Software Engineer at Lyft', 'Staff Engineer at Lyft', 'Mobile Engineer at Lyft', 'Backend Engineer at Lyft', 'Platform Engineer at Lyft']
    },

    'product-manager': {
      title: 'Product Manager',
      slug: 'product-manager',
      industry: 'Technology',
      roleDescription: `Product Managers at Lyft drive product strategy and execution for features impacting millions of riders and drivers daily. Working at the intersection of business, technology, and user experience, you'll own products that shape how people move through cities. Lyft's PM culture emphasizes data-driven decision making, deep user empathy for both sides of the marketplace, and rapid iteration. PMs partner closely with engineering, design, data science, and operations to build transportation solutions that improve communities. The two-sided marketplace presents unique challenges—every feature affects both riders and drivers, often with competing needs. You'll work on problems ranging from reducing wait times and improving driver earnings to launching new markets and products. Lyft's mission of improving people's lives through better transportation means PMs must balance business metrics with genuine community impact. The company values PMs who can think strategically while staying grounded in execution details.`,
      responsibilities: [
        'Define product vision and roadmap for rider, driver, or platform experiences',
        'Partner with engineering and design to ship features that improve the marketplace',
        'Analyze data and user research to inform product strategy and prioritization',
        'Drive marketplace efficiency through pricing, matching, and incentive improvements',
        'Collaborate with operations on launch strategies and city-specific rollouts',
        'Define and monitor success metrics, iterating based on performance data',
        'Communicate product strategy to leadership and stakeholders across the company',
        'Balance needs of riders, drivers, and business objectives in every decision',
        'Lead cross-functional initiatives spanning multiple teams and domains'
      ],
      growthOpportunities: [
        'Progress from PM to Senior PM to Group PM leading multiple product areas',
        'Advance to Director of Product overseeing entire product domains',
        'Move into general management roles with broader business scope',
        'Become an expert in marketplace dynamics, pricing, or growth',
        'Lead new product initiatives from zero to one',
        'Build and lead high-performing product teams',
        'Shape company strategy through executive-level influence'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '30-minute conversation about background, product experience, and interest in Lyft\'s mission' },
        { stage: 'Hiring Manager Call', description: '45-minute deep dive into PM philosophy, past products, and team fit' },
        { stage: 'Product Design Case', description: '60-minute product design case study solving a Lyft-relevant problem' },
        { stage: 'Analytical Case', description: '60-minute case testing data analysis, metrics definition, and structured thinking' },
        { stage: 'Technical Interview', description: '45-minute discussion with engineering partner assessing technical fluency' },
        { stage: 'Behavioral Interview', description: '45-minute interview assessing leadership, collaboration, and values alignment' },
        { stage: 'Leadership Interview', description: 'Final round with senior product leader discussing strategy and fit' }
      ],
      technicalQuestions: [
        'How would you improve rider retention at Lyft?',
        'Design a feature to increase driver earnings without hurting rider experience',
        'How would you measure the success of a new safety feature?',
        'What metrics would you track for the ride matching system?',
        'How would you prioritize building a rider feature vs driver feature?',
        'Design a loyalty program for frequent Lyft riders',
        'How would you approach launching Lyft in a new city?',
        'What would you do if average wait times increased 20% in a major market?',
        'How would you improve the airport pickup experience?',
        'Design a feature to reduce rider cancellations',
        'How would you approach pricing for a new product like scheduled rides?',
        'What would you build to improve driver onboarding and retention?',
        'How would you measure and improve marketplace liquidity?',
        'Design a feature to increase shared ride adoption',
        'How would you approach a situation where driver supply is consistently low?',
        'What metrics define a healthy transportation marketplace?'
      ],
      behavioralQuestions: [
        'Tell me about a product you launched and its measurable impact',
        'Describe a time you used data to make a difficult product decision',
        'How have you worked with engineering teams to ship features on tight timelines?',
        'Tell me about balancing competing stakeholder needs in a product decision',
        'Describe your experience building marketplace or platform products',
        'How do you prioritize features with limited engineering resources?',
        'Tell me about a product that failed and what you learned from it',
        'Describe a time you influenced a decision without direct authority',
        'How have you incorporated user research into product decisions?',
        'Tell me about navigating ambiguity in a product role',
        'Describe how you\'ve built trust with engineering and design partners',
        'How have you communicated difficult trade-offs to stakeholders?',
        'Tell me about a time you had to kill a feature or project you believed in',
        'Describe your approach to learning a new product domain quickly'
      ],
      whatTheyLookFor: [
        'Strong analytical skills with data-driven decision making approach',
        'Deep empathy for users on both sides of the marketplace',
        'Technical fluency to collaborate effectively with engineers',
        'Strategic thinking about marketplace dynamics and network effects',
        'Execution focus with proven ability to ship products',
        'Cross-functional leadership and clear communication',
        'Passion for transportation and genuine interest in community impact',
        'Comfort with ambiguity in fast-paced environments',
        'Product intuition balanced with data validation',
        'Inclusive mindset considering diverse user needs'
      ],
      interviewTips: [
        'Deeply understand Lyft\'s two-sided marketplace dynamics',
        'Prepare product cases using frameworks like AARRR or HEART metrics',
        'Have specific examples of data-driven product decisions ready',
        'Research Lyft\'s products, competitors, and recent launches',
        'Understand unit economics in rideshare (take rate, incentives, LTV)',
        'Prepare transportation-related product ideas and opinions',
        'Practice discussing trade-offs between rider and driver needs',
        'Express genuine passion for improving cities through technology',
        'Be ready to do quick calculations and estimations',
        'Show how you\'ve partnered with engineering on technical products',
        'Prepare questions about PM culture and team structure',
        'Research Lyft\'s mission and values—authenticity matters',
        'Practice structuring answers for case interviews',
        'Be ready to discuss mobile product challenges'
      ],
      salary: { min: 150000, max: 270000 },
      compensation: [
        'Competitive base salary with equity grants (RSUs)',
        'Annual performance bonuses based on individual and company goals',
        'Lyft Pink membership (unlimited Lyft rides)',
        'Comprehensive health, dental, and vision insurance',
        'Flexible PTO policy',
        '401(k) with company match',
        'Mental health benefits and wellness programs',
        'Professional development budget',
        'Parental leave',
        'Home office stipend for hybrid work'
      ],
      dayInLife: {
        intro: 'A day as a Product Manager at Lyft balances strategic thinking with hands-on execution across the rider-driver marketplace.',
        schedule: [
          '8:30 AM - Review overnight metrics and market performance dashboards',
          '9:00 AM - Team standup with engineering and design on sprint progress',
          '9:30 AM - User research debrief discussing recent driver interview findings',
          '10:30 AM - Product review with leadership presenting roadmap updates',
          '11:30 AM - 1:1 with engineering lead on technical approach for new feature',
          '12:00 PM - Lunch with cross-functional partners from operations',
          '1:00 PM - A/B test analysis session with data science partner',
          '2:00 PM - Design critique providing feedback on new rider flow mockups',
          '3:00 PM - Stakeholder alignment meeting on upcoming market launch',
          '4:00 PM - Write product spec for next sprint\'s priority feature',
          '5:00 PM - Quick sync with PM peers on cross-team dependencies',
          '5:30 PM - Wrap up reviewing tomorrow\'s schedule and priorities'
        ],
        closing: 'Product management at Lyft means owning products that directly affect how millions of people get around, partnering with talented teams to build transportation that improves communities.'
      },
      similarRoles: ['Senior Product Manager at Lyft', 'Group Product Manager at Lyft', 'Product Lead at Lyft', 'Growth PM at Lyft', 'Platform PM at Lyft']
    },

    'engineering-manager': {
      title: 'Engineering Manager',
      slug: 'engineering-manager',
      industry: 'Technology',
      roleDescription: `Engineering Managers at Lyft lead teams building the real-time systems that power millions of rides daily. You'll manage engineers working on critical infrastructure—ride matching, pricing, mapping, safety, and marketplace optimization—while developing talent and shaping technical direction. Lyft's EM culture expects strong people leadership combined with technical credibility; EMs participate in architecture decisions, contribute to code review, and maintain deep understanding of their team's systems. You'll partner closely with Product Managers and Design leads as part of cross-functional teams with shared accountability for outcomes. The role requires balancing individual engineer growth with team delivery, technical excellence with shipping pragmatism, and immediate needs with long-term sustainability. Lyft values EMs who build inclusive teams, foster psychological safety, and help engineers do their best work. The company's mission of improving lives through better transportation means your team's work has direct impact on communities.`,
      responsibilities: [
        'Lead, mentor, and grow a team of 5-10 software engineers',
        'Partner with Product and Design to drive product strategy and execution',
        'Conduct regular 1:1s, performance reviews, and career development conversations',
        'Contribute to technical architecture and maintain credibility with the team',
        'Build inclusive team culture aligned with Lyft\'s values',
        'Drive hiring for your team including interview calibration and process improvement',
        'Manage project execution ensuring quality delivery on commitments',
        'Collaborate with peer EMs on cross-team dependencies and engineering initiatives',
        'Handle escalations and ensure team maintains production reliability'
      ],
      growthOpportunities: [
        'Progress to Senior EM managing multiple teams or larger scope',
        'Advance to Director of Engineering overseeing product areas',
        'Move into VP of Engineering with executive responsibilities',
        'Transition back to Staff or Principal Engineer (path is supported)',
        'Lead new organization formation for emerging products',
        'Drive engineering-wide transformation initiatives',
        'Build expertise in specific domains becoming company authority'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial discussion of management experience, leadership style, and interest in Lyft' },
        { stage: 'Hiring Manager Interview', description: 'Deep dive into management philosophy, team building, and technical background' },
        { stage: 'Technical Assessment', description: 'System design or architecture discussion demonstrating technical depth' },
        { stage: 'People Management Interview', description: 'Scenarios covering coaching, difficult conversations, and team development' },
        { stage: 'Cross-functional Interview', description: 'Assessment of partnership skills with Product, Design, and peer EMs' },
        { stage: 'Behavioral Interview', description: 'Leadership examples and values alignment assessment' },
        { stage: 'Executive Interview', description: 'Final round with senior engineering leader on strategy and fit' }
      ],
      technicalQuestions: [
        'How do you balance technical debt reduction with feature development?',
        'Describe your approach to making build vs. buy decisions',
        'Walk me through a complex system your team owns and key architectural decisions',
        'How do you ensure your team maintains production reliability standards?',
        'Describe your approach to driving engineering standards across teams',
        'How do you stay technically credible while managing a growing team?',
        'How would you approach migrating a critical system without downtime?',
        'Describe your process for conducting architecture reviews',
        'How do you balance team velocity with code quality and testing?',
        'What\'s your approach to capacity planning for systems with variable load?',
        'How do you evaluate and adopt new technologies on your team?',
        'Describe a technical decision that didn\'t work out and how you handled it',
        'How do you approach incident response and post-mortems?',
        'What\'s your philosophy on code review and engineering best practices?',
        'How do you handle technical disagreements within your team?',
        'Describe your approach to on-call and production support'
      ],
      behavioralQuestions: [
        'Tell me about helping an underperforming engineer improve',
        'Describe how you\'ve built inclusive teams where everyone belongs',
        'How have you handled a situation where you disagreed with product direction?',
        'Tell me about a time you had to make a difficult termination decision',
        'Describe your approach to giving critical feedback to a strong performer',
        'How have you managed through organizational change or uncertainty?',
        'Tell me about developing an engineer from junior to senior level',
        'Describe how you\'ve partnered with Product to influence roadmap',
        'How do you build psychological safety on your team?',
        'Tell me about handling conflicting priorities from leadership',
        'Describe your most effective team building or culture initiative',
        'How have you approached a situation with low team morale?',
        'Tell me about a time you had to deliver difficult news to your team',
        'Describe how you balance being hands-on with delegating'
      ],
      whatTheyLookFor: [
        'Strong people leadership with genuine investment in engineer growth',
        'Technical credibility to earn respect and guide architectural decisions',
        'Inclusive leadership building teams where everyone can belong',
        'Strategic thinking about team structure and technical direction',
        'Excellent partnership skills with Product and Design',
        'Track record of building high-performing, engaged teams',
        'Clear communication across engineers, peers, and leadership',
        'Growth mindset applying to both self and team development',
        'Alignment with Lyft\'s mission and community impact values',
        'Comfort with ambiguity and leading through change'
      ],
      interviewTips: [
        'Prepare specific examples of developing engineers at different levels',
        'Be ready to discuss technical architecture with depth—Lyft EMs stay technical',
        'Have concrete examples of building inclusive team culture',
        'Practice discussing difficult management situations with nuance',
        'Understand Lyft\'s cross-functional model and triad partnerships',
        'Research Lyft\'s engineering culture through blog and talks',
        'Be authentic about your leadership style and philosophy',
        'Prepare questions about EM growth paths and support',
        'Show how you\'ve connected team work to company mission',
        'Be ready to discuss managing through ambiguity and change',
        'Prepare examples of balancing people needs with delivery pressure',
        'Show vulnerability—discuss mistakes and what you learned',
        'Practice articulating how you\'ve grown engineers\' careers',
        'Understand the two-sided marketplace and real-time systems challenges'
      ],
      salary: { min: 180000, max: 300000 },
      compensation: [
        'Competitive base salary with significant equity grants (RSUs)',
        'Annual refresher grants based on performance',
        'Performance bonuses tied to team and company goals',
        'Lyft Pink membership (unlimited Lyft rides)',
        'Comprehensive health, dental, and vision coverage',
        'Generous parental leave',
        'Flexible PTO with expectation that managers model healthy time off',
        '401(k) with company match',
        'Leadership development programs and coaching',
        'Home office stipend for hybrid work'
      ],
      dayInLife: {
        intro: 'A day as an Engineering Manager at Lyft balances people leadership, technical engagement, and strategic partnership.',
        schedule: [
          '9:00 AM - Review team dashboards and overnight on-call activity',
          '9:30 AM - 1:1 with engineer discussing career growth and current project',
          '10:00 AM - Team standup facilitating discussion of blockers and priorities',
          '10:30 AM - Architecture review providing input on new system design',
          '11:30 AM - Cross-functional sync with PM and Design on quarterly planning',
          '12:00 PM - Lunch with new team member as part of onboarding',
          '1:00 PM - Engineering leadership meeting on hiring and org topics',
          '2:00 PM - Code review staying connected to team\'s technical work',
          '3:00 PM - Interview debrief calibrating on recent candidates',
          '3:30 PM - 1:1 with direct report working through a challenging situation',
          '4:30 PM - Performance review prep for upcoming cycle',
          '5:30 PM - Quick wins celebration with team before wrapping up'
        ],
        closing: 'Engineering management at Lyft means building teams that ship impactful transportation technology while creating environments where engineers grow and thrive.'
      },
      similarRoles: ['Senior Engineering Manager at Lyft', 'Director of Engineering at Lyft', 'Technical Program Manager at Lyft', 'Staff Engineer at Lyft']
    },

    'data-scientist': {
      title: 'Data Scientist',
      slug: 'data-scientist',
      industry: 'Technology',
      roleDescription: `Data Scientists at Lyft use data, analytics, and machine learning to optimize the transportation marketplace serving millions of riders and drivers. Working with one of the richest real-time datasets in technology—every ride generates location traces, pricing decisions, and behavioral signals—you'll tackle challenges spanning dynamic pricing, demand forecasting, fraud detection, and marketplace optimization. Lyft's data culture emphasizes experimentation, statistical rigor, and measurable impact. Data Scientists partner closely with product, engineering, and operations to turn insights into products and features. The company's two-sided marketplace presents unique analytical challenges: optimizing for riders and drivers simultaneously, understanding network effects, and building models that work across diverse cities and conditions. Lyft invests heavily in data infrastructure, with sophisticated platforms for experimentation, feature engineering, and ML deployment. The interview process evaluates both technical depth and ability to translate analysis into business impact.`,
      responsibilities: [
        'Analyze marketplace dynamics including supply-demand patterns and driver-rider matching',
        'Build machine learning models for pricing, ETAs, fraud detection, and personalization',
        'Design and analyze A/B experiments measuring product and algorithm impact',
        'Create dashboards and metrics frameworks for product and operations teams',
        'Partner with product managers on feature development and prioritization',
        'Develop deep domain expertise in assigned areas of the marketplace',
        'Present findings and recommendations to leadership',
        'Collaborate with ML engineers to deploy models at scale',
        'Mentor junior data scientists and contribute to team best practices'
      ],
      growthOpportunities: [
        'Progress through IC levels to Staff and Principal Data Scientist',
        'Transition into Data Science management leading teams',
        'Specialize in machine learning engineering or applied research',
        'Move into Product Management leveraging analytical foundation',
        'Become domain expert in pricing, marketplace, or specific verticals',
        'Lead cross-functional initiatives shaping company data strategy',
        'Contribute to research and publish findings'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: 'Initial conversation about background, experience, and interest in Lyft' },
        { stage: 'Technical Phone Screen', description: '45-minute screen covering statistics, SQL, and analytical problem-solving' },
        { stage: 'Take-Home Assignment', description: 'Data analysis project with sample dataset, typically 3-4 hours of work' },
        { stage: 'Onsite - Case Study', description: 'Product analytics case testing metrics definition and business thinking' },
        { stage: 'Onsite - Technical Deep Dive', description: 'Statistics, ML, and coding assessment through applied problems' },
        { stage: 'Onsite - Behavioral', description: 'Assessment of collaboration, communication, and values alignment' },
        { stage: 'Onsite - Presentation', description: 'Present take-home results demonstrating communication and rigor' }
      ],
      technicalQuestions: [
        'How would you design an experiment to test a new surge pricing algorithm?',
        'Explain how you\'d handle network effects when analyzing a marketplace feature',
        'How would you build a model to predict driver churn?',
        'Describe your approach to measuring long-term impact of incentive programs',
        'How would you design a fraud detection system for fake rides?',
        'Explain techniques for handling multiple comparisons in experimentation',
        'How would you build a demand forecasting model for different markets?',
        'Describe approaches to handling selection bias in marketplace experiments',
        'How would you measure the impact of a feature on both riders and drivers?',
        'Explain your approach to causal inference when A/B testing isn\'t possible',
        'How would you build a recommendation system for driver positioning?',
        'Describe techniques for analyzing cannibalization effects',
        'How would you design metrics to capture marketplace health?',
        'Explain approaches to real-time model scoring at scale',
        'How would you approach customer lifetime value modeling?',
        'Describe your process for feature engineering in transportation ML'
      ],
      behavioralQuestions: [
        'Tell me about an analysis that significantly changed a product decision',
        'Describe a time your data contradicted stakeholder expectations',
        'How have you communicated complex findings to non-technical audiences?',
        'Tell me about an experiment that produced surprising results',
        'Describe a model you built that was deployed in production',
        'How have you balanced statistical rigor with practical business needs?',
        'Tell me about an analysis you later realized had flaws',
        'Describe how you\'ve partnered with product managers effectively',
        'How have you influenced product direction through data insights?',
        'Tell me about navigating ambiguity in an analytical project',
        'Describe how you prioritize when you have multiple analysis requests',
        'How have you mentored other data scientists?',
        'Tell me about working with engineers to deploy ML models',
        'Describe building dashboards that drove business decisions'
      ],
      whatTheyLookFor: [
        'Strong statistical foundation with expertise in experimentation and causal inference',
        'Machine learning skills applicable to ranking, forecasting, and classification',
        'Excellent communication translating analysis into business recommendations',
        'Product intuition connecting data to user and business impact',
        'Strong coding skills in Python and SQL',
        'Intellectual curiosity about transportation and marketplace dynamics',
        'Collaborative mindset working with Product, Engineering, and Operations',
        'Rigor balanced with pragmatism—knowing when good enough is enough',
        'Growth mindset with desire to continuously learn',
        'Alignment with Lyft\'s mission and values'
      ],
      interviewTips: [
        'Review Lyft\'s engineering blog for data science and experimentation posts',
        'Practice product analytics cases using rideshare context',
        'Be ready to discuss experimentation challenges: network effects, interference',
        'Prepare to write SQL and Python code for analytical problems',
        'Understand two-sided marketplace dynamics and how they affect analysis',
        'Practice explaining statistical concepts to non-technical audiences',
        'Review past work for examples of analysis driving business impact',
        'Be ready to discuss ML fundamentals and production deployment',
        'Prepare thoughtful questions about data culture and team challenges',
        'Show genuine curiosity about transportation and marketplace problems',
        'Practice presenting analysis clearly with appropriate caveats',
        'Be ready to discuss handling bias and ensuring fair models',
        'Prepare examples of collaborating with engineering on data products',
        'Show how you balance speed with analytical rigor'
      ],
      salary: { min: 145000, max: 260000 },
      compensation: [
        'Competitive base salary with equity grants (RSUs)',
        'Annual performance bonuses and equity refreshers',
        'Lyft Pink membership (unlimited Lyft rides)',
        'Comprehensive health, dental, and vision insurance',
        'Flexible PTO policy',
        '401(k) with company match',
        'Conference attendance and professional development budget',
        'Access to internal data science training',
        'Parental leave',
        'Home office stipend'
      ],
      dayInLife: {
        intro: 'A day as a Data Scientist at Lyft balances deep analytical work with collaborative partnership on marketplace challenges.',
        schedule: [
          '9:00 AM - Review experiment results from overnight pipeline runs',
          '9:30 AM - Team standup discussing ongoing analyses and priorities',
          '10:00 AM - Deep work on pricing model feature engineering',
          '11:30 AM - Meeting with PM to discuss metrics for new feature',
          '12:00 PM - Lunch with data science colleagues sharing interesting findings',
          '1:00 PM - Experiment review presenting A/B test results to stakeholders',
          '2:00 PM - Code review for teammate\'s model implementation',
          '2:30 PM - SQL analysis exploring driver behavior patterns',
          '4:00 PM - Office hours helping product team with dashboard questions',
          '4:30 PM - 1:1 with manager on career growth',
          '5:00 PM - Document findings and prepare for tomorrow\'s presentation',
          '5:30 PM - Wrap up with quick experiment monitoring check'
        ],
        closing: 'Data Science at Lyft means working on problems that directly impact how millions of people get around, using one of the richest real-time datasets in technology.'
      },
      similarRoles: ['Senior Data Scientist at Lyft', 'Staff Data Scientist at Lyft', 'ML Engineer at Lyft', 'Analytics Manager at Lyft', 'Research Scientist at Lyft']
    }
