    'technical-marketing-engineer': {
      title: 'Technical Marketing Engineer',
      slug: 'technical-marketing-engineer',
      industry: 'Technology',
      roleDescription: `Technical Marketing Engineers at Intel bridge the gap between Intel\'s complex silicon technology and the developers, OEMs, and customers who use it. Working at the intersection of engineering and marketing, you\'ll translate processor capabilities into compelling technical content, benchmarks, and enablement materials. Intel\'s TMEs work across the product portfolio—Core processors for PCs, Xeon for data centers, and AI accelerators—helping customers understand how to get the most from Intel technology. The role combines technical depth with communication skills: you\'ll run benchmarks, create technical documentation, present at industry events, and work directly with customers on optimization. With Intel competing intensely against AMD, ARM, and Nvidia, TMEs play a crucial role in demonstrating Intel\'s value proposition through rigorous technical analysis.`,
      responsibilities: [
        'Create technical content explaining Intel product capabilities',
        'Develop and execute competitive benchmarks and analysis',
        'Present at industry conferences and customer events',
        'Work with customers on performance optimization',
        'Enable sales and field teams on technical positioning',
        'Collaborate with product teams on messaging and launches',
        'Create demos and proof-of-concepts for key workloads',
        'Analyze competitive products and positioning',
        'Develop technical documentation and guides'
      ],
      growthOpportunities: [
        'Progress from TME to Senior TME and Principal Engineer',
        'Move into product management or strategic marketing',
        'Specialize in specific segments: data center, client, AI',
        'Lead technical marketing for product lines',
        'Transition into field application engineering',
        'Build expertise in competitive analysis',
        'Become an industry thought leader and speaker',
        'Move into customer-facing technical sales roles'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '30-minute conversation about background and interests' },
        { stage: 'Hiring Manager Interview', description: '45-minute discussion of TME experience and approach' },
        { stage: 'Technical Interview', description: '60-minute interview on technical depth and communication' },
        { stage: 'Presentation Exercise', description: 'Present a technical topic to demonstrate communication skills' },
        { stage: 'Cross-functional Interviews', description: 'Conversations with product and sales stakeholders' }
      ],
      technicalQuestions: [
        'How would you demonstrate Intel processor advantages to a customer?',
        'Explain your approach to competitive benchmarking.',
        'How do you translate technical capabilities into customer value?',
        'Describe your experience with performance analysis and optimization.',
        'How would you position Intel against AMD for a data center customer?',
        'Explain your approach to creating technical content.',
        'How do you ensure benchmark validity and reproducibility?',
        'Describe your experience with workload characterization.',
        'How do you handle situations where competitors have advantages?',
        'Explain your approach to technical presentations.',
        'How do you stay current with competitive products?',
        'Describe your experience enabling sales teams.',
        'How would you approach a customer skeptical of marketing claims?',
        'Explain your experience with performance profiling tools.',
        'How do you balance technical accuracy with marketing messaging?',
        'Describe your experience with customer technical engagements.'
      ],
      behavioralQuestions: [
        'Tell me about a successful technical presentation you delivered.',
        'Describe a time you translated complex technology for non-technical audiences.',
        'How have you handled pushback on competitive positioning?',
        'Tell me about a benchmark or analysis that influenced a customer decision.',
        'Describe your experience working with product engineering.',
        'How have you stayed credible while advocating for products?',
        'Tell me about a time you had to learn new technology quickly.',
        'Describe your experience at industry events or conferences.',
        'How have you handled situations where data didn\'t support your position?',
        'Tell me about a technical demo that had significant impact.',
        'Describe your experience training or enabling others.',
        'How have you built relationships with customers or partners?',
        'Tell me about a time you influenced product direction.',
        'Describe how you prioritize across multiple TME responsibilities.'
      ],
      whatTheyLookFor: [
        'Strong technical foundation in computer architecture or systems',
        'Excellent presentation and communication skills',
        'Experience with performance analysis and benchmarking',
        'Ability to translate technical features to business value',
        'Credibility with both engineers and business audiences',
        'Competitive analysis and positioning experience',
        'Experience with customer-facing technical roles',
        'Understanding of processor and platform technology',
        'Content creation and documentation skills',
        'Industry event and conference experience valued'
      ],
      interviewTips: [
        'Prepare a technical presentation on a topic you know well',
        'Show ability to explain complex concepts simply',
        'Research Intel\'s current competitive positioning',
        'Demonstrate benchmarking methodology knowledge',
        'Be ready to discuss competitive landscape candidly',
        'Show technical depth—TMEs must be credible with engineers',
        'Prepare examples of customer-facing technical work',
        'Understand Intel\'s product portfolio and strategy',
        'Show enthusiasm for communicating technology',
        'Be ready to discuss how you handle competitive disadvantages',
        'Prepare examples of content creation',
        'Show understanding of different audience needs',
        'Research industry events and Intel\'s participation',
        'Demonstrate balance of technical and communication skills'
      ],
      salary: {
        min: 110000,
        max: 190000,
        average: 150000
      },
      compensation: [
        'Competitive base salary ($110K-$190K based on level)',
        'Annual performance bonus (15-25% of base)',
        'Restricted Stock Units (RSUs)',
        '7% 401(k) match',
        'Employee Stock Purchase Plan',
        'Comprehensive health benefits',
        'Conference and travel budget',
        'Professional development support',
        'Sabbatical program after 7 years',
        'Remote work flexibility'
      ],
      dayInLife: {
        intro: 'A typical day as a Technical Marketing Engineer at Intel balances content creation, customer engagement, and competitive analysis.',
        schedule: [
          '8:30 AM - Review competitive news and industry updates',
          '9:00 AM - Work on benchmark execution and analysis',
          '10:30 AM - Customer call discussing technical capabilities',
          '11:30 AM - Prepare presentation for upcoming event',
          '12:00 PM - Lunch with sales team',
          '1:00 PM - Create technical documentation or blog post',
          '3:00 PM - Internal sync with product marketing',
          '4:00 PM - Review and analyze competitive benchmarks',
          '5:30 PM - Plan tomorrow and respond to field requests'
        ],
        closing: 'Technical Marketing Engineering at Intel means making Intel\'s technology understandable and compelling, combining engineering depth with communication skills.'
      },
      similarRoles: ['Senior Technical Marketing Engineer at Intel', 'Principal TME at Intel', 'Field Application Engineer at Intel', 'Solutions Architect at Intel', 'Product Marketing Engineer at Intel']
    },

    'supply-chain-manager': {
      title: 'Supply Chain Manager',
      slug: 'supply-chain-manager',
      industry: 'Technology',
      roleDescription: `Supply Chain Managers at Intel orchestrate one of the world\'s most complex supply chains—coordinating the production of billions of processors across global fabs, managing component suppliers, and ensuring products reach customers in a rapidly changing market. Working at the intersection of manufacturing, logistics, and business strategy, you\'ll balance demand forecasting with manufacturing capacity, manage inventory across a global network, and navigate supply disruptions that can impact the entire technology industry. Intel\'s supply chain spans from raw materials through fab production to finished products, with billions of dollars in inventory and strategic sourcing decisions. The role requires analytical skills for demand planning and operational excellence for execution. With semiconductor shortages demonstrating supply chain criticality and Intel\'s foundry expansion, supply chain managers have high-visibility opportunities to shape Intel\'s operations.`,
      responsibilities: [
        'Develop and execute supply chain strategies for Intel products',
        'Manage demand forecasting and production planning',
        'Coordinate with manufacturing to optimize fab utilization',
        'Lead supplier relationships and strategic sourcing',
        'Monitor and manage inventory across global network',
        'Drive supply chain efficiency and cost optimization',
        'Navigate supply disruptions and develop mitigation plans',
        'Collaborate with sales on customer fulfillment',
        'Analyze supply chain data for continuous improvement'
      ],
      growthOpportunities: [
        'Progress from Supply Chain Manager to Senior Manager and Director',
        'Lead supply chain for specific product lines or regions',
        'Move into procurement or strategic sourcing leadership',
        'Transition into manufacturing operations leadership',
        'Build expertise in specific supply chain domains',
        'Take on global supply chain leadership roles',
        'Move into general management or business unit leadership',
        'Lead supply chain transformation initiatives'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '30-minute conversation about background and supply chain experience' },
        { stage: 'Hiring Manager Interview', description: '45-minute discussion of supply chain approach and experience' },
        { stage: 'Case Study', description: '60-minute interview working through a supply chain scenario' },
        { stage: 'Cross-functional Interviews', description: 'Conversations with manufacturing, sales, and planning stakeholders' },
        { stage: 'Leadership Interview', description: 'Final round with supply chain leadership' }
      ],
      technicalQuestions: [
        'How do you approach demand forecasting for semiconductor products?',
        'Describe your experience with supply-demand balancing.',
        'How do you optimize inventory across a global network?',
        'Explain your approach to supplier risk management.',
        'How do you handle supply disruptions?',
        'Describe your experience with capacity planning.',
        'How do you balance service levels with inventory costs?',
        'Explain your approach to strategic sourcing decisions.',
        'How do you measure supply chain performance?',
        'Describe your experience with S&OP processes.',
        'How do you handle long-lead-time components?',
        'Explain techniques for demand sensing and planning.',
        'How do you approach sustainability in supply chain?',
        'Describe your experience with supply chain technology and tools.',
        'How do you prioritize allocation during constrained supply?',
        'Explain your approach to total cost of ownership analysis.'
      ],
      behavioralQuestions: [
        'Tell me about a supply disruption you successfully navigated.',
        'Describe a time you improved supply chain efficiency.',
        'How have you built relationships with key suppliers?',
        'Tell me about a difficult allocation decision you made.',
        'Describe your experience working with manufacturing.',
        'How have you handled conflicting priorities across functions?',
        'Tell me about a supply chain transformation you led.',
        'Describe how you\'ve used data to drive decisions.',
        'How have you managed in a rapidly changing market?',
        'Tell me about a time you had to deliver bad news to stakeholders.',
        'Describe your experience with global supply chain operations.',
        'How have you developed your team or mentored others?',
        'Tell me about a project that didn\'t go as planned.',
        'Describe how you stay current with supply chain best practices.'
      ],
      whatTheyLookFor: [
        'Strong analytical and quantitative skills',
        'Experience with semiconductor or technology supply chain',
        'Understanding of manufacturing operations',
        'Strategic thinking balanced with operational execution',
        'Experience with demand planning and forecasting',
        'Supplier relationship and negotiation skills',
        'Cross-functional collaboration abilities',
        'Experience with supply chain technology and tools',
        'Problem-solving for complex operational challenges',
        'Understanding of global trade and logistics'
      ],
      interviewTips: [
        'Prepare for case study on supply chain scenario',
        'Research semiconductor industry supply chain dynamics',
        'Show understanding of Intel\'s supply chain challenges',
        'Demonstrate analytical skills with data-driven examples',
        'Prepare examples of navigating supply disruptions',
        'Show experience with manufacturing collaboration',
        'Understand the complexity of semiconductor production',
        'Be ready to discuss trade-offs in supply chain decisions',
        'Show knowledge of supply chain technology and analytics',
        'Prepare questions about Intel\'s supply chain transformation',
        'Demonstrate strategic thinking and operational excellence',
        'Show cross-functional collaboration experience',
        'Understand global supply chain considerations',
        'Highlight any semiconductor or tech industry experience'
      ],
      salary: {
        min: 110000,
        max: 180000,
        average: 145000
      },
      compensation: [
        'Competitive base salary ($110K-$180K based on level)',
        'Annual performance bonus (15-25% of base)',
        'Restricted Stock Units (RSUs)',
        '7% 401(k) match',
        'Employee Stock Purchase Plan',
        'Comprehensive health benefits',
        'Sabbatical program after 7 years',
        'Relocation assistance',
        'Professional development support',
        'Global mobility opportunities'
      ],
      dayInLife: {
        intro: 'A typical day as a Supply Chain Manager at Intel balances planning, coordination, and problem-solving across the global network.',
        schedule: [
          '7:30 AM - Review overnight supply and demand updates',
          '8:00 AM - Morning sync with global operations teams',
          '9:00 AM - Demand planning meeting with sales',
          '10:00 AM - Supplier performance review call',
          '11:00 AM - Inventory analysis and optimization',
          '12:00 PM - Lunch',
          '1:00 PM - Manufacturing capacity planning session',
          '2:30 PM - Cross-functional S&OP meeting',
          '4:00 PM - Address supply exceptions and escalations',
          '5:30 PM - Plan tomorrow and handoff to global team'
        ],
        closing: 'Supply Chain Management at Intel means orchestrating one of the world\'s most complex supply chains, with direct impact on Intel\'s ability to serve customers.'
      },
      similarRoles: ['Senior Supply Chain Manager at Intel', 'Supply Chain Director at Intel', 'Demand Planning Manager at Intel', 'Procurement Manager at Intel', 'Operations Manager at Intel']
    },

    'ux-designer': {
      title: 'UX Designer',
      slug: 'ux-designer',
      industry: 'Technology',
      roleDescription: `UX Designers at Intel create user experiences for the tools, applications, and interfaces that engineers and customers use to work with Intel technology. Working on products from development tools and debugging software to customer portals and internal applications, you\'ll apply human-centered design to complex technical challenges. Intel\'s UX team works on experiences for diverse users: hardware engineers designing chips, software developers optimizing code, IT professionals deploying systems, and business users making purchasing decisions. The role requires balancing technical complexity with usability: understanding the sophisticated workflows of technical users while making interfaces intuitive and efficient. UX Designers collaborate closely with engineering teams who build these tools, advocating for user needs while understanding technical constraints.`,
      responsibilities: [
        'Design user experiences for technical tools and applications',
        'Conduct user research to understand engineer and customer needs',
        'Create wireframes, prototypes, and interaction designs',
        'Collaborate with engineering teams on implementation',
        'Develop and maintain design systems and guidelines',
        'Test designs through usability studies and iteration',
        'Present design rationale to stakeholders',
        'Create documentation and specifications for development',
        'Advocate for user-centered design across projects'
      ],
      growthOpportunities: [
        'Progress from UX Designer to Senior and Principal levels',
        'Lead design for specific product areas',
        'Move into UX management or leadership',
        'Specialize in UX research or interaction design',
        'Build expertise in design systems',
        'Lead design thinking initiatives',
        'Transition into product management',
        'Become a design advocate across Intel'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '30-minute conversation about background and interests' },
        { stage: 'Portfolio Presentation', description: '60-minute presentation of design work to UX team' },
        { stage: 'Design Exercise', description: 'Take-home or live design challenge' },
        { stage: 'Technical Interview', description: 'Discussion of design process and collaboration' },
        { stage: 'Cross-functional Interview', description: 'Conversation with engineering or product stakeholders' }
      ],
      technicalQuestions: [
        'Walk me through your design process.',
        'How do you approach designing for technical users?',
        'Describe your experience with design systems.',
        'How do you balance user needs with technical constraints?',
        'Explain your approach to user research.',
        'How do you design for complex workflows?',
        'Describe your experience with accessibility.',
        'How do you work with engineering on implementation?',
        'Explain your approach to information architecture.',
        'How do you measure design success?',
        'Describe your experience with prototyping tools.',
        'How do you handle stakeholder feedback?',
        'Explain your approach to responsive design.',
        'How do you prioritize design improvements?',
        'Describe your experience with data visualization.',
        'How do you stay current with design trends?'
      ],
      behavioralQuestions: [
        'Tell me about a complex design challenge you solved.',
        'Describe a time you had to advocate for users.',
        'How have you handled disagreement on design direction?',
        'Tell me about a design decision you changed based on research.',
        'Describe your experience facilitating design workshops.',
        'How have you collaborated with engineers on constraints?',
        'Tell me about a project where research changed your approach.',
        'Describe how you prioritize design work.',
        'How have you contributed to design culture?',
        'Tell me about a design that didn\'t achieve its goals.',
        'Describe your experience with global or remote teams.',
        'How have you handled tight timelines?',
        'Tell me about mentoring other designers.',
        'Describe how you stay current with design practices.'
      ],
      whatTheyLookFor: [
        'Strong portfolio demonstrating design process',
        'Experience designing for technical users valued',
        'User research and human-centered design skills',
        'Ability to handle complex workflows',
        'Collaboration skills with engineering teams',
        'Understanding of accessibility requirements',
        'Proficiency in design tools (Figma, Sketch, etc.)',
        'Clear communication of design rationale',
        'Experience with design systems',
        'Problem-solving for complex information design'
      ],
      interviewTips: [
        'Prepare a portfolio focused on process, not just outcomes',
        'Include B2B or technical tool design if available',
        'Be ready to walk through your design process in detail',
        'Prepare to discuss designing for complex workflows',
        'Show user research skills and evidence-based design',
        'Practice the design exercise—Intel may give technical scenarios',
        'Demonstrate collaboration with engineering teams',
        'Show accessibility awareness in your work',
        'Prepare questions about the UX team and culture',
        'Show how you handle feedback and iteration',
        'Highlight design system contributions',
        'Demonstrate passion for technical user challenges',
        'Research Intel\'s products and potential UX opportunities',
        'Show understanding of B2B and enterprise design'
      ],
      salary: {
        min: 90000,
        max: 160000,
        average: 125000
      },
      compensation: [
        'Competitive base salary ($90K-$160K based on level)',
        'Annual performance bonus (10-15% of base)',
        'Restricted Stock Units (RSUs)',
        '7% 401(k) match',
        'Employee Stock Purchase Plan',
        'Comprehensive health benefits',
        'Conference and training budget',
        'Design tools and software provided',
        'Sabbatical program after 7 years',
        'Remote work flexibility'
      ],
      dayInLife: {
        intro: 'A typical day as a UX Designer at Intel balances design work, research, and collaboration with engineering teams.',
        schedule: [
          '9:00 AM - Review design feedback and prepare for meetings',
          '9:30 AM - Team standup with UX colleagues',
          '10:00 AM - User interview for development tool research',
          '11:00 AM - Work on wireframes and prototypes',
          '12:00 PM - Lunch with engineering team',
          '1:00 PM - Design review and critique session',
          '2:30 PM - Collaboration with engineers on implementation',
          '4:00 PM - Update design documentation',
          '5:00 PM - Design system contribution work',
          '5:30 PM - Plan and wrap up'
        ],
        closing: 'UX Design at Intel means creating experiences for the tools that enable engineers to build the world\'s computing, combining design skills with technical understanding.'
      },
      similarRoles: ['Senior UX Designer at Intel', 'Principal UX Designer at Intel', 'UX Researcher at Intel', 'Product Designer at Intel', 'Interaction Designer at Intel']
    },

    'program-manager': {
      title: 'Program Manager',
      slug: 'program-manager',
      industry: 'Technology',
      roleDescription: `Program Managers at Intel orchestrate complex, cross-functional initiatives that deliver processors, platforms, and technologies to market. Working at the intersection of engineering, manufacturing, and business, you\'ll coordinate programs that span multiple years, thousands of engineers, and billions of dollars in investment. Intel\'s program management covers the full product lifecycle: from early architecture definition through design, validation, manufacturing ramp, and product launches. The role requires both technical understanding to work with engineering teams and business acumen to manage schedules, budgets, and executive stakeholders. PMs at Intel navigate long hardware development cycles with numerous dependencies and risks, driving alignment across global teams. With Intel\'s strategic transformation—foundry services, AI products, manufacturing expansion—program managers have opportunities to lead some of the most ambitious initiatives in the semiconductor industry.`,
      responsibilities: [
        'Lead cross-functional programs for processor or platform development',
        'Develop and maintain program plans, schedules, and milestones',
        'Manage program risks and drive mitigation strategies',
        'Coordinate across engineering, manufacturing, and business teams',
        'Track and report program status to executives',
        'Drive decision-making and resolve cross-team conflicts',
        'Manage program budgets and resource allocation',
        'Ensure quality and schedule commitments are met',
        'Facilitate tapeout and manufacturing readiness'
      ],
      growthOpportunities: [
        'Progress from Program Manager to Senior PM, Director, and VP',
        'Lead larger programs with greater strategic impact',
        'Move into engineering management or business leadership',
        'Specialize in specific program domains: silicon, platform, manufacturing',
        'Take on cross-Intel program leadership',
        'Build expertise in hardware development processes',
        'Lead Intel Foundry Services customer programs',
        'Move into general management roles'
      ],
      interviewProcess: [
        { stage: 'Recruiter Screen', description: '30-minute conversation about background and PM experience' },
        { stage: 'Hiring Manager Interview', description: '45-minute discussion of program management approach' },
        { stage: 'Scenario Interview', description: '60-minute interview handling program situations' },
        { stage: 'Cross-functional Interviews', description: 'Conversations with engineering and business stakeholders' },
        { stage: 'Leadership Interview', description: 'Final round with senior program leadership' }
      ],
      technicalQuestions: [
        'How do you approach planning for a multi-year hardware program?',
        'Describe your experience with program risk management.',
        'How do you handle schedule pressure on complex programs?',
        'Explain your approach to cross-team coordination.',
        'How do you manage dependencies in large programs?',
        'Describe your experience with hardware development milestones.',
        'How do you drive decisions when teams disagree?',
        'Explain your approach to executive communication.',
        'How do you handle scope changes in hardware programs?',
        'Describe your experience with tapeout or manufacturing readiness.',
        'How do you balance multiple competing priorities?',
        'Explain your approach to resource management.',
        'How do you track progress across distributed teams?',
        'Describe your experience with program budgets.',
        'How do you handle programs that are behind schedule?',
        'Explain your approach to post-mortem and lessons learned.'
      ],
      behavioralQuestions: [
        'Tell me about a complex program you led successfully.',
        'Describe a time you had to recover a program in trouble.',
        'How have you built relationships across functions?',
        'Tell me about a difficult decision you had to drive.',
        'Describe your experience with executive stakeholders.',
        'How have you handled conflict between teams?',
        'Tell me about a time you managed through ambiguity.',
        'Describe how you prioritize when everything is urgent.',
        'How have you developed or mentored team members?',
        'Tell me about a program failure and what you learned.',
        'Describe your experience with organizational change.',
        'How have you influenced without direct authority?',
        'Tell me about navigating a politically complex situation.',
        'Describe how you communicate bad news to stakeholders.'
      ],
      whatTheyLookFor: [
        'Experience with complex, multi-year programs',
        'Understanding of hardware development processes',
        'Strong stakeholder management and communication',
        'Risk management and problem-solving skills',
        'Cross-functional leadership and influence',
        'Experience with global team coordination',
        'Technical understanding to work with engineering',
        'Business acumen for budget and resource management',
        'PMP certification valued but not required',
        'Semiconductor or hardware industry experience preferred'
      ],
      interviewTips: [
        'Prepare specific examples of programs with clear outcomes',
        'Show understanding of hardware development cycles',
        'Be ready to discuss risk management in detail',
        'Demonstrate stakeholder management experience',
        'Prepare for scenario questions about program challenges',
        'Show experience with large, global programs',
        'Research Intel\'s current programs and initiatives',
        'Demonstrate ability to drive decisions and alignment',
        'Prepare examples of executive communication',
        'Show technical understanding without overstepping',
        'Highlight experience with tapeouts or product launches',
        'Be ready to discuss lessons from program failures',
        'Show adaptability for changing requirements',
        'Prepare questions about Intel\'s PM organization'
      ],
      salary: {
        min: 120000,
        max: 200000,
        average: 160000
      },
      compensation: [
        'Competitive base salary ($120K-$200K based on level)',
        'Annual performance bonus (15-25% of base)',
        'Restricted Stock Units (RSUs)',
        '7% 401(k) match',
        'Employee Stock Purchase Plan',
        'Comprehensive health benefits',
        'Sabbatical program after 7 years',
        'Professional development support',
        'Global mobility opportunities',
        'Executive development programs at senior levels'
      ],
      dayInLife: {
        intro: 'A typical day as a Program Manager at Intel balances coordination, problem-solving, and driving programs forward.',
        schedule: [
          '8:00 AM - Review program status and overnight updates',
          '8:30 AM - Program team standup',
          '9:00 AM - Cross-functional sync on critical path items',
          '10:00 AM - Risk review and mitigation planning',
          '11:00 AM - Engineering leadership meeting',
          '12:00 PM - Lunch',
          '1:00 PM - Stakeholder update preparation',
          '2:00 PM - Executive program review',
          '3:30 PM - 1:1s with team leads',
          '4:30 PM - Address program issues and blockers',
          '5:30 PM - Update plans and prepare for tomorrow'
        ],
        closing: 'Program Management at Intel means driving the programs that deliver processors to billions of devices, coordinating across engineering and business to make technology happen.'
      },
      similarRoles: ['Senior Program Manager at Intel', 'Director of Program Management at Intel', 'Technical Program Manager at Intel', 'Platform Program Manager at Intel', 'Product Development Manager at Intel']
    }